### PR TITLE
Feature 3.7/arangobench by duration

### PR DESCRIPTION
**Pull request by dothebart**
Backport of https://github.com/arangodb/arangodb/pull/12997

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12681/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12684/ choose proper enterprise branch.

**Review by jsteemann — APPROVED** [review]

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12724/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
