### PR TITLE
bug-fix/internal-issue-#565.1

### PR DESCRIPTION
**Pull request by gnusi**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4847/

### CODE REVIEW

**Comment by gnusi** [comment]
related issues:
https://github.com/arangodb/backlog/issues/575
https://github.com/arangodb/backlog/issues/565

**Comment by Dronplane** [comment]
Also related issue https://github.com/arangodb/backlog/issues/593

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4953/

**Comment by Dronplane** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4957/

**Comment by Dronplane** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr/4981/

**Pull request merged**
