### PR TITLE
Documentation: Added notice related to converting JSON files to JSONlines

### PR DESCRIPTION
**Pull request by KVS85**
Added notice related to converting JSON files to JSONlines

### CODE REVIEW

**Comment by KVS85** [comment]
https://docs.arangodb.com/review/documentation/jq-jsonl/Manual/Administration/ImportExport.html

**Comment by dothebart** [comment]
ry) <IT>  may be optimized using

**Comment by KVS85** [comment]
https://docs.arangodb.com/review/documentation/jq-jsonl/Manual/Administration/ImportExport.html

**Comment by sleto-it** [comment]
Hi all, thanks for working on this

@Simran-B I would like to discuss more on having this section in the arangoimp chapter, rather than here on the generic import and expert section - as to me it seems more specific to that tool, and this way we do not split things into different sections. Nor merging for now

**Comment by Simran-B** [comment]
https://docs.arangodb.com/review/documentation/jq-jsonl/Manual/Programs/Arangoimport/ExamplesJson.html

**Pull request merged**
