### PR TITLE
Feature: Add gzip and encryption to import/export

### PR DESCRIPTION
**Pull request by matthewvon**
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/5396/

This is a port from 3.4.

### CODE REVIEW

**Comment by matthewvon** [comment]
includes fix for Windows build: http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/5406/

**Comment by matthewvon** [comment]
again:  http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/5407/

**Comment by matthewvon** [comment]
another Windows change:  http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/5409/

**Comment by matthewvon** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/5425/

This run has Windows not working.  Previous had Mac not working.  Pretty clear it is Jenkins not working.

**Comment by dothebart** [comment]
ack - the windows environment had troubles with the updated openssl - which is fixed now.

**Pull request merged**
