### PR TITLE
attempt to fix thread-local issues with non-trivial constructions

### PR DESCRIPTION
**Pull request by jsteemann**
-### Scope & Purpose

Try to avoid thread locals which do heap allocations on construction
This seems to cause issues at least in some MSVC/Windows environments

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

If this works, please close PR https://github.com/arangodb/arangodb/pull/9251.

### Testing & Verification

This change is already covered by existing tests, such as _nearly all tests_.

VelocyPack test suite also passes for the change without issues.

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4947/

### CODE REVIEW

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4947/

**Comment by mpoeter** [comment]
I am a bit skeptical that the heap allocation itself is the problem... I will try to investigate this in more detail and report back if I find anything (but this is of course independent of this PR).

**Comment by jsteemann** [comment]
@mpoeter : ok, thank you!
It was reported to me that the heap allocation would be the problem, so I tried to defer the allocation to later. I was also surprised that heap allocation before `main` is a problem. I am thus also not very convinced that we have understood the problem yet, however, this patch seems to fix the problems we had.

**Comment by mpoeter** [comment]
@jsteemann I posted my findings here: https://github.com/arangodb/arangodb/pull/9251#issuecomment-506453990

TLD;DR something _very strange_ was going on that cause that crash! But I would most definitely rule out a bug in arangodb or the VCRT.

**Pull request merged**
