### PR TITLE
add latest AQL functions

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

update the list of AQL functions for the frontend

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9061/

### CODE REVIEW

**Comment by KVS85** [comment]
Tests blue except unrelated failures.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9062/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/10793/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
