### PR TITLE
Fix an endless loop in FolloweInfo::persistInAgency.

### PR DESCRIPTION
**Pull request by neunhoef**

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9086/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9092/

**Comment by neunhoef** [comment]
The test run had only the hotbackup failure. Should be OK to merge.

**Comment by KVS85** [comment]
Tests blue except known failure.

**Pull request merged**
