### PR TITLE
BTS-1008: Update react-autocomplete-input to create link to collection with single unique letter in its name

### PR DESCRIPTION
**Pull request by ajurdak**
### Scope & Purpose

If a collections name would be a single letter that doesn't exist in a different collection name as well the collection would not be displayed in the autocomplete input to create a link. After @nikhil-varma fixed the bug in the responsible package ("react-autocomplete-input") and the author merged his PR we were able to update the package to fix the bug.
image

- [x] :hankey: Bugfix

### Checklist

- [x] Manually tested
- [x] :book: CHANGELOG entry made
- [x] Backports
  - [x] Backport for 3.10: #17292 

#### Related Information

- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1008

### CODE REVIEW

**Comment by nikhil-varma** [comment]
I don't see any `package-lock.json` file. I am not sure what is used for building the UI. Can you please check if that's required?

**Comment by ajurdak** [comment]
> I don't see any `package-lock.json` file. I am not sure what is used for building the UI. Can you please check if that's required?

We use yarn to build the UI so package-lock.json ist not needed.

**Review by nikhil-varma — APPROVED** [review]

**Review by adityamukho — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
Unrelated failure in Jenkins.

**Pull request merged**
