### PR TITLE
[3.7] BTS-356 cluster internal errors

### PR DESCRIPTION
**Pull request by kvahed**
### Scope & Purpose

*Fixes BTS-356 fot 3.7*

- [X] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [X] :book: CHANGELOG entry made

#### Backports:

- [X] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [X] The behavior in this PR was *manually tested*
- [X] This change is already covered by existing tests, such as *(please describe tests)*.
- [X] This PR adds tests that were used to verify all changes:
  - [X] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/16707/

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Comment by kvahed** [comment]
image

**Review by neunhoef — COMMENTED** [review]
Changelog missing

**Review by neunhoef — CHANGES_REQUESTED** [review]
This is a backport of https://github.com/arangodb/arangodb/pull/13985/ However, it seems not all changes have made it here. See comments for individual places. Overall, the following are missing in their entirety:

  - a change in `arangod/Sharding/ShardDistributionReporter.cpp` from `sendRequest` to `sendRequestRetry`
  - an absolutely crucial change in `lib/Rest/GeneralResponse.cpp` to make the system correctly translate `TRI_ERROR_CLUSTER_SHARD_LEADER_RESIGNED` to HTTP 421 Misdirected request
  - the integration test in `tests/js/client/shell/shell-document-api-internal-http-return-codes-cluster.js` to check the API behaviour, there is a corresponding failure point in `arangod/Transaction/Methods.cpp` in the `insertLocal` method which is needed for this
  - the behaviour that a connection from the pool can be stale seems not to be implemented in 3.7 yet, therefore the changes in `arangod/Network/Methods.cpp` cannot be applied and corresponding tests in `tests/Network/MethodsTest.cpp` are missing, do we want to backport these, too?

**Review by neunhoef — APPROVED** [review]
LGTM now, I have changed one more forgotten place in `transaction::Methods::anyLocal`, so we need to rerun Jenkins. I will start it.
The question remains if we also have to backport the fixes for stale connections in the pool. I think yes but will talk with Jörg about it.

**Pull request merged**
