### PR TITLE
Feature-3.7/arangosearch-maintenance-rework

### PR DESCRIPTION
**Pull request by gnusi**
backport of https://github.com/arangodb/arangodb/pull/13008

### CODE REVIEW

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13054/

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13057/

**Comment by KVS85** [comment]
Tests blue.

**Review by Dronplane — APPROVED** [review]
LGTM but pipeline analyzer files still present, I guess it is no harm but just redundant for 3.7

**Review by KVS85 — APPROVED** [review]
LGTM.

**Review by joerg84 — APPROVED** [review]

**Comment by joerg84** [comment]
P.S. Would have preferred without the pipeline files, but works for me.

**Pull request merged**
