### PR TITLE
Fix a maintenance bug.

### PR DESCRIPTION
**Pull request by neunhoef**
This is a port of a change in devel.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9411/

**Comment by neunhoef** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux/11154/

**Comment by neunhoef** [comment]
Restart because of Jenkins failure.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
