### PR TITLE
improve clang-format

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Improve linting action.
Relies on https://github.com/arangodb/clang-format-action/pull/2 to be merged and tagged as version 1.0.3.

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by dothebart** [comment]
will this also run over 3rdParty?

**Comment by jsteemann** [comment]
@dothebart : no, it won't. The container at arangodb/clang-format-action@1.0.2 doesn't take 3rdParty into account.

**Review by dothebart — APPROVED** [review]
seems good to me.

**Pull request merged**
