### PR TITLE
[3.7] Bugfix Sorting Gather Executor

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #12777

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12180/

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux/13807/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12213/

**Comment by KVS85** [comment]
Tests blue except unrelated failure.

**Pull request merged**
