### PR TITLE
[3.7] Bug fix/improve replication logging

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #11859

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10443/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10464/

**Comment by KVS85** [comment]
Tests blue except unrelated known failure.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10478/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/12222/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10486/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
