### PR TITLE
Bug fix/fuerte return full status header (#13038)

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This is a backport of https://github.com/arangodb/arangodb/pull/13038.

Fix HTTP/1.1 status response header in fuerte

This change makes fuerte return the full status header, including the numeric status code and the status string in the `http/1.1` header of fuerte responses.

Previously, the return header lacked the numeric status code, so it looked like
```
"http/1.1" : "Ok"
```
Now, with the numeric status code, the response header will look like 
```
"http/1.1" : "200 Ok"
```
This PR also adds a protocol() method for arango client connections in order to check the protocol in use. The possible return values are

- "http" for HTTP/1.1 connections
- "http2" for HTTP/2 connections
- "vst" for VST connections
- "unknown" for everyhting else

This is needed during testing, but can also be used for other purposes.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (e.g. in shell_client)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12768/

### CODE REVIEW

**Review by mpoeter — APPROVED** [review]

**Comment by dothebart** [comment]
should we also have http 1.0 in there?

Else lgtm.

**Review by dothebart — APPROVED** [review]

**Comment by jsteemann** [comment]
> should we also have http 1.0 in there?
> 
> Else lgtm.

I don't understand the connection to http/1.0 here.
While fuerte is used only internally to establish connections to arangod instances (which speak only http/1.1 or http/2, but never http/1.0), the change made in this PR should also work if a backend responds with an http/1.0 response.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13138/

**Comment by dothebart** [comment]
I'd vote for the sake of completeness also to have http/1.0 in there. The code may also be invoked via arangosh, which may connect via a proxy. Hence I think the implementation should have all possibilities available in the field.

**Comment by jsteemann** [comment]
Except that the code in this PR does not care about whether the response is http/1.1 or http/1.0...
It really does not care about the protocol version, nowhere.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13142/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13159/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
