### PR TITLE
Add decription for new ArangoSearch view properties

### PR DESCRIPTION
**Pull request by KVS85**
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/133/

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/135/

**Comment by KVS85** [comment]
http://web01.arangodb.biz/documentation/update-arangosearch-properties-doc/Manual/Views/ArangoSearch/DetailedOverview.html

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/141/
http://web01.arangodb.biz/documentation/update-arangosearch-properties-doc/Manual/Views/ArangoSearch/DetailedOverview.html

**Comment by Simran-B** [comment]
See other review again: https://github.com/arangodb/arangodb/pull/7437#pullrequestreview-178833521

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/143/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/145/

**Pull request merged**
