### PR TITLE
Bug fix/zero mac clang warning to errors

### PR DESCRIPTION
**Pull request by dothebart**
This PR turns warnings into errors for mac compiles.

### CODE REVIEW

**Comment by dothebart** [comment]
Its based on the windows warning branch, thus it derives conversations. 

https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4898/

**Comment by goedderz** [comment]
> Its based on the windows warning branch, thus it derives conversations.

@dothebart  Could you link said branch / PR, so we can view a helpful diff?

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4900/

**Comment by dothebart** [comment]
tests blue!

**Pull request merged**
