### PR TITLE
attempt to properly capitalize header names in VST responses

### PR DESCRIPTION
**Pull request by jsteemann**

### CODE REVIEW

**Comment by ObiWahn** [comment]
Why not a function capitalize outgoing headees, when it is supposed to be exactly the same for http and cat?

**Comment by jsteemann** [comment]
It's not exactly the same.
In the one case, we are writing the result into a string buffer (without copying) and in the other case we don't.

**Comment by dothebart** [comment]
rather sounds like something you want to do as an assert in maintainermode.

**Comment by ObiWahn** [comment]
Shouldn't it be possible to create some string view from the target location (string / vpack buffer). The capitalization would not modify the length do it could modify the string safe place.

**Comment by jsteemann** [comment]
The key of an unordered_map cannot be modified in-place. It's always a const reference. Because changing the may lead to the key having to move into a different bucket in the map.

**Comment by jsteemann** [comment]
@dothebart : what assert are you talking about? I don't understand.

**Comment by ObiWahn** [comment]
That is why I suggested to create a string view of the part of the string
or vpack buffer (target location)

**Comment by dothebart** [comment]
if headers are to be in a specific case (specific enough to fix them automatically) why not not fix them, but fix them in the code instead. Helps grepping in doubt.

**Comment by jsteemann** [comment]
@dothebart : because everybody types headers differently. And if we mix cases, it will all break. That's why we enforce the automatic capitalization. It has worked so far, and it is fine as it is. I think it's not worth giving that up, and having it silently fail in non-maintainer mode when someone (us developers or end users via Foxx) set a header that's not in proper capitalization.

**Comment by jsteemann** [comment]
@dothebart : by the way, the header strings are defined in `lib/Basics/StaticStrings.cpp`, mostly in one place.
Some developers however start adding headers elsewhere in the code without using that facility.
That's how it is, so we have that auto-capitalization as an extra safeguard.

**Pull request merged**
