### PR TITLE
server / client side db._parse added

### PR DESCRIPTION
**Pull request by baslr**

### CODE REVIEW

**Comment by baslr** [comment]
@pluma forgot the client side. can you check this also?

**Comment by fceller** [comment]
@baslr lgtm as well

**Comment by fceller** [comment]
@baslr can you add CHANGELOG entry

**Comment by fceller** [comment]
Also jslint is complaining:

**Comment by pluma** [comment]
One nitpick: I prefer an explicit `global.AQL_PARSE` over adding `AQL_PARSE` to the globals list because it makes it more obvious when reading the code (the globals list is a bit of a hack).

Alternatively the AQL_PARSE could be removed from global and exposed via `internal` as we do with most functions we expose from C++ but want to wrap in JS.

Also also: does AQL_PARSE only accept a string or also bindvars? In the latter case the logic probably doesn't look right in the client.

**Comment by baslr** [comment]
@pluma query only.

**Pull request merged**
