### PR TITLE
Doc - Improve 'Queries without collections' example

### PR DESCRIPTION
**Pull request by 153957**
This seems to have been the original intent of the example.

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @153957,

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by 153957** [comment]
Already signed and submitted ~ 2 years ago, see https://github.com/arangodb/arangodb/pull/3747

**Comment by dothebart** [comment]
meanwhile 
https://github.com/arangodb/docs/blob/master/3.5/aql/examples-queries-no-collections.md
would need to be changed. @Simran-B please use `EXAMPLE_AQL` here so its generated by the server. 

@153957 thanks for spotting!

**Comment by Simran-B** [comment]
Superseded by https://github.com/arangodb/docs/pull/76

**Pull request closed without merging**
