### PR TITLE
Update abseil-cpp and s2geometry

### PR DESCRIPTION
**Pull request by MBkkt**
### Scope & Purpose

Update s2 and abseil.

Abseil have
1. improvements of hashtable, btree, cord perfomance
2. Add AbslStringify overloads to serialize custom types in StrCat/Subsitute/Format/etc
3. Other fixes and improvements

s2 contains only few improvements, mostly from our patch

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Comment by jsteemann** [comment]
@MBkkt : LGTM in general, but it is missing an update of the file `LICENSES-OTHER-COMPONENTS.md`.

**Comment by MBkkt** [comment]
@jsteemann it's update, I don't add new libraries, why is missing?

**Comment by jsteemann** [comment]
> @jsteemann it's update, I don't add new libraries, why is missing?

The version numbers etc. still need to be updated.

**Comment by markuspf** [comment]
any insight why this adds many more lines than it removes?

**Comment by MBkkt** [comment]
@markuspf 

> any insight why this adds many more lines than it removes?

It mostly abseil a lot of new tests, benchmarks.

Most real changes, I wrote

> Abseil have
improvements of hashtable, btree, cord perfomance
Add AbslStringify overloads to serialize custom types in StrCat/Subsitute/Format/etc
Other fixes and improvements

**Review by jsteemann — APPROVED** [review]
LGTM

**Pull request merged**
