### PR TITLE
prefer using absl::flat_hash_map

### PR DESCRIPTION
**Pull request by gnusi**
### Scope & Purpose

Prefer using absl::flat_hash_map<...> instead of std::unordered_map<...> where applicable. It's always faster.
https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [x] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] Backport for 3.9: *(Please link PR)*
- [ ] Backport for 3.8: *(Please link PR)*
- [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by maierlars** [comment]
just wondering if `absl::flat_hash_map` is a drop-in replacement for `std::unordered_map`?

**Comment by markuspf** [comment]
https://abseil.io/docs/cpp/guides/container says explicitly:

```
Unlike some other abstractions that Abseil provides, these containers should not be considered drop-in replacements for their STL counterparts, as there are API and/or contract differences between the two sets of containers. For example, the Abseil containers often do not guarantee pointer stability after insertions or deletions.
```

and I would suggest sufficient caution with these replacements and the assumptions made around them.

**Comment by gnusi** [comment]
@maierlars @maierlars as long as code doesn't rely on pointers stability, it's safe. Are you fine with merging it given Jenkins is already happy?

**Comment by markuspf** [comment]
I don't like this change for (at least) the following reasons:

 * I am not sure this patch addresses a performance problem per-say
 * I cannot possibly know under which assumptions the code that currently is using `std::unordered_map` was written; it might well be that somewhere (implicitly?) pointer stability is assumed. Just saying to be careful is not enough; if you want my approval, I will have to properly look, and that will take time.
 * You are including ``::iresearch_absl::flat_hash_map<T, V, Hash, Eq, Allocator>`` into ArangoDB's `lib/Basics`, where abseil itself is a third-party library (so a third-party library of a third-party library); I would be a slight bit happier if abseil was transparently a 3rd party library in arangodb proper (though, of course, we're now getting ourselves into the valley of unhappiness of multiple copies of abseil in the codebase which can get out of sync. fun all round).

**Comment by gnusi** [comment]
@markuspf 
* `flat_hash_map` is definitely faster and more memory-efficient than `std::unordered_map`.
* Not a single line of code I've changed relies on pointer stability. Happy to wait until you'll take closer look.
* That's already done for `flat_hash_set` and `emilib::HashSet`, so I don't see much difference.

**Comment by markuspf** [comment]
> flat_hash_map is definitely faster and more memory-efficient than std::unordered_map.
    That's already done for flat_hash_set and emilib::HashSet, so I don't see much difference.

Have you *measured* that it matters? My worry is that in a couple of months down the line we get some weird memory corruption bugs and spend multiple developer weeks on fixing them.

> Not a single line of code I've changed relies on pointer stability. Happy to wait until you'll take closer look.
Did you check also all the consequential lines of code?

> That's already done for flat_hash_set and emilib::HashSet, so I don't see much difference.
Just because it is done like this somewhere else, does not mean it is a good idea, or that I have to like it.

I would suggest to not change the use of `std::unordered_map` in code that has not been checked carefully. For the traversal and graph code, the graph team can look at this replacement when the graph refactoring work is picked up again in the next week.

It would be very useful if the hashmap would be imported as a proper 3rd party library by then.

**Comment by gnusi** [comment]
@markuspf ok, so I'm going to revert all graph related parts, then.

**Pull request closed without merging**
