### PR TITLE
[devel] fix state clientlookuptable

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4666/

**Comment by kvahed** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4676/

**Comment by neunhoef** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/6242/

Started again after resolving LOG ids and merging in devel.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4678/

full tests.

**Pull request merged**
