### PR TITLE
upgrade curl to 7.65.3

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Upgrade curl to most recent version 7.65.3

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification

This change is already covered by existing tests, such as *cluster tests with and without ssl*.

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5839/

### CODE REVIEW

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5841/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5846/

Rerun to see whether
```
* Test "shell_server_aql_3"
    [FAILED]  enterprise/tests/js/server/aql/aql-smart-graph-traverser-enterprise-cluster.js

      "testStartUnknownCollection" failed: Error: at assertion #1: assertEqual: (1521) is not equal to (1478)
(Error
    at assertEqual (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:109:19)
    at Object.testStartUnknownCollection (enterprise/tests/js/server/aql/aql-smart-graph-traverser-enterprise-cluster.js:1460:9)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:541:27)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:253:24)
    at enterprise/tests/js/server/aql/aql-smart-graph-traverser-enterprise-cluster.js:3450:9
    at enterprise/tests/js/server/aql/aql-smart-graph-traverser-enterprise-cluster.js:3463:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:337:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52))
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:560:23)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:253:24)
    at enterprise/tests/js/server/aql/aql-smart-graph-traverser-enterprise-cluster.js:3450:9
    at enterprise/tests/js/server/aql/aql-smart-graph-traverser-enterprise-cluster.js:3463:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:337:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52) - test failed

      "totalSetUp" failed: undefined

      "totalTearDown" failed: undefined

   Suites failed: 1 Tests Failed: 3
```
is reproducible.

**Comment by jsteemann** [comment]
Tests failed, because curl is now more picky about HTTP response codes.
Had to fix a few occurrences in smart graph code that returned HTTP 1521 as an error code, which is obviously wrong. Should be fixed now.

Also added enterprise companion PR: https://github.com/arangodb/enterprise/pull/289

https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5864/

**Comment by jsteemann** [comment]
tests blue

**Pull request merged**
