### PR TITLE
Trostpflaster for wrong assertion

### PR DESCRIPTION
**Pull request by markuspf**
This PR removes an assertion that is not correct: If we are a `MultiAqlItemBlockInputRange` one of our dependencies might be `DONE` on a shadow row, while other dependencies don't know yet that they are `DONE`. 

We now assert that we should never enter this inconsistent state and are then asked for data again. Ultimately we should fix the state reporting so that upstreams always know they are `DONE` synchronously for a `MultiAqlItemBlockInputRange`.

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10605/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10609/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10613/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10619/

**Comment by mchacki** [comment]
This PR has been included in
https://github.com/arangodb/arangodb/pull/12018
i will close it as it is obsolete now.

**Pull request closed without merging**
