### PR TITLE
[3.6] agency node delete undefined

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7663/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7674/

**Comment by kvahed** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7675/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
