### PR TITLE
All hail to the SI 

### PR DESCRIPTION
**Pull request by dothebart**
[SI](https://en.wikipedia.org/wiki/International_System_of_Units) that gave us the power to easily write numbers without trailing zeroes to improve readability by choosing the proper unit

### CODE REVIEW

**Comment by ObiWahn** [comment]
Not sure why it is needed but if you want to beautify use `std::literals::chrono`

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5155/

**Comment by dothebart** [comment]
tests green except for overlap in oskar testcase rename.

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5172/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/6956/

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5316/

**Comment by dothebart** [comment]
tests ok except unrelated errors.

**Pull request merged**
