### PR TITLE
increase timeouts, reduce work overhead

### PR DESCRIPTION
**Pull request by dothebart**
This test most probably was only marked timecritical for valgrind. 
Relaxed the timings a bit, un-greylist.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/780/ green in these testruns.

**Comment by jsteemann** [comment]
@dothebart : Please also remove the "timecritical" name part from the test file.

**Comment by dothebart** [comment]
why? it still is. and I don't really see a way to solve this. We may split this file into a non-timecritical and a timecritical part, but thats about it.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7704/

**Comment by dothebart** [comment]
testrun green.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7891/

**Comment by dothebart** [comment]
test green except for unrelated errors.

**Pull request merged**
