### PR TITLE
only anounce coordinator readiness once the agency is convinced we are

### PR DESCRIPTION
**Pull request by dothebart**
it seems that the testing.js cluster readiness checks lean on this condition. 
Tests mustn't start before the coordinator is flagged "ready".

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7445/

**Comment by dothebart** [comment]
Revalidated by running:
``` 
./scripts/unittest 'shell_server' --cluster true --test  shell-database.js --testCase testListDatabases 
```
in loops.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7449/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/9244/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/9257/ blue.

**Pull request merged**
