### PR TITLE
fix cluster-statistics

### PR DESCRIPTION
**Pull request by ObiWahn**
This PR should fix the problem!

We still need to experiment on how to add a test. @jsteemann prefers to have a javascript tests, because we want to see immediately in a PR-run if we break the statistics.
We need to investigate if our permissions-suite is already cluster ready or if we need to change something. Then we need the exact parameters that will be used in osais because we will not be able to test all possible option combinations and need to dedicate to the relevant ones.

I kindly ask @dothebart and @ewoutp to confirm manually that this PR fixes the issue.

### CODE REVIEW

**Comment by ObiWahn** [comment]
Exact command to start in source directory:

arangodb-linux-amd64 --starter.local --all.javascript.startup-options-blacklist='.*' --all.javascript.endpoints-whitelist=arangodb.com --all.javascript.environment-variables-whitelist='^HOSTNAME$' --all.javascript.environment-variables-whitelist='^PATH$' --all.javascript.harden --all.server.harden --server.arangod ./build/bin/arangod --server.js-dir "$(pwd)/js"

**Comment by jsteemann** [comment]
Command doesn't work.
Must be changed to
```
arangodb-linux-amd64 --starter.local --all.javascript.startup-options-blacklist='.*' --all.javascript.endpoints-whitelist=arangodb.com --all.javascript.environment-variables-whitelist='^HOSTNAME$' --all.javascript.environment-variables-whitelist='^PATH$' --all.javascript.harden=true --all.server.harden=true --server.arangod ./build/bin/arangod --server.js-dir "$(pwd)/js"
```
for me to work

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5055/

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5070/

**Comment by jsteemann** [comment]
Permissions tests now fail and need to be adjusted:
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux/6687/EDITION=community,STORAGE_ENGINE=mmfiles,TEST_SUITE=single,limit=linux&&test/artifact/testfailures.txt

```
* Test "permissions_server"
    [FAILED]  tests/js/server/permissions/test-api-transaction-hardened.js

      "testProcessStatistics" failed: at assertion #1: assertTrue: (false) does not evaluate to true
(Error
    at assertTrue (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:72:19)
    at Object.testProcessStatistics (tests/js/server/permissions/test-api-transaction-hardened.js:88:7)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:532:23)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/permissions/test-api-transaction-hardened.js:116:9
    at tests/js/server/permissions/test-api-transaction-hardened.js:118:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at testFunc (eval at runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:794:3), <anonymous>:4:9)
    at Object.runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:797:18)
    at /work/ArangoDB/js/client/modules/@arangodb/testsuites/permissions_server.js:103:32)
    [FAILED]  tests/js/server/permissions/test-foxx-service-access-denied.js

      "testProcessStatistics" failed: at assertion #1: assertEqual: (200) is not equal to (403)
(Error
    at assertEqual (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:109:19)
    at Object.testProcessStatistics (tests/js/server/permissions/test-foxx-service-access-denied.js:114:8)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:532:23)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/permissions/test-foxx-service-access-denied.js:176:9
    at tests/js/server/permissions/test-foxx-service-access-denied.js:178:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at testFunc (eval at runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:794:3), <anonymous>:4:9)
    at Object.runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:797:18)
    at /work/ArangoDB/js/client/modules/@arangodb/testsuites/permissions_server.js:103:32)
```

**Comment by ObiWahn** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5076/

**Comment by ObiWahn** [comment]
> Command doesn't work.
> Must be changed to
> 
> ```
> arangodb-linux-amd64 --starter.local --all.javascript.startup-options-blacklist='.*' --all.javascript.endpoints-whitelist=arangodb.com --all.javascript.environment-variables-whitelist='^HOSTNAME$' --all.javascript.environment-variables-whitelist='^PATH$' --all.javascript.harden=true --all.server.harden=true --server.arangod ./build/bin/arangod --server.js-dir "$(pwd)/js"
> ```
> 
> for me to work.
> 
> However, the patch in this PR fixes the problem for me too.

`arangod` can take the option as `--server.harden` and it does start. This is another bug of the starter. The bug has been confirmed by Max. For some reason the starter does not remove the `all.` in `--all.server.harden`.

**Pull request merged**
