### PR TITLE
simplify stack traces a bit

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Slightly simplify stack traces in case of a crash (a bit less deep stacks)

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *scripts/unittest recovery*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10214/

### CODE REVIEW

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10215/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/10218/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10224/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/1162/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
