### PR TITLE
Bug fix 3.7/make aql fast again 10

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Use cheaper hashing and comparison functions for the AqlValues in the `_valueCount` map.
This is possible because all AqlValues in that map are pointer-based, i.e. types `VPACK_INLINE` will never occur there.
Additionally, keep track of the memory usage of AqlValues in the `_valueCount` map. We do have space there for additional 4 bytes, so we store the memory usage in the map now and thus can save its repeated computation when the AqlItemBlock is destroyed.

Backport of https://github.com/arangodb/arangodb/pull/12249

- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *shell_server_aql*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11135/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11138/

**Comment by jsteemann** [comment]
Tests ok

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11179/

**Comment by KVS85** [comment]
Tests blue.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11184/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
