### PR TITLE
AQL: DATE_UTCTOLOCAL and DATE_LOCALTOUTC detail mode

### PR DESCRIPTION
**Pull request by coronabytes**
### Scope & Purpose

Adds optional detail mode to DATE_UTCTOLOCAL and DATE_LOCALTOUTC
which returns all the relevant info including:

- timezone effect range in utc (daylight saving start / end)
  - null when open intervall  (UTC for example)
- the converted local / utc time
- timezone name abbreviation GMT, CEST CET, EST, EDT, PST, PDT...
- daylight saving active or not (minutes are available - but are considered non authorative)
- offset in seconds to utc
- and the version of tzdata used

this shall conclude all the timezone functionality for now... 

```
DATE_UTCTOLOCAL('2020-01-05', 'Europe/Berlin', true)
DATE_UTCTOLOCAL('2020-07-05', 'Europe/Berlin', true)

{
  "local": "2020-01-05T01:00:00.000",
  "tzdb": "2020f",
  "zoneInfo": {
    "name": "CET",
    "begin": "2019-10-27T01:00:00.000Z",
    "end": "2020-03-29T01:00:00.000Z",
    "save": false,
    "offset": 3600
  }
}

{
  "local": "2020-07-05T02:00:00.000",
  "tzdb": "2020f",
  "zoneInfo": {
    "name": "CEST",
    "begin": "2020-03-29T01:00:00.000Z",
    "end": "2020-10-25T01:00:00.000Z",
    "save": true,
    "offset": 7200
  }
}
```

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

### Testing & Verification

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [x] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

### External contributors / CLA Note 

see #12646

### CODE REVIEW

**Comment by jsteemann** [comment]
@coronabytes : thanks once again for taking the time to add this functionality.

I haven't looked at any code yet because the PR is still in draft state.
However, I already have a suggestion by looking at the PR description, precisely the new function's return values:
```

{
"begin":"2020-10-25T01:00:00.000Z",
"end":"2021-03-28T01:00:00.000Z",
"local":"2021-01-05T01:00:00.000",
"abbrev":"CET",
"save":0,
"offset":3600,
"version":"2020f"
}
```
Just looking at these attribute names it may not be immediately clear to the user what "save" and "offset" mean. Is it possible to use more descriptive names, e.g. "daylightSavingInMinutes", "offsetToUTCInSeconds" or such?
In addition, I would prefer "abbreviation" instead of "abbrev".
Another suggestion to make the meaning more clear would be to split the result into the "local" value and a "zoneInfo" sub-value, i.e.
```
{
  "local":"2021-01-05T01:00:00.000",
  "zoneInfo": {
    "begin":"2020-10-25T01:00:00.000Z",
    "end":"2021-03-28T01:00:00.000Z",
    "abbreviation":"CET",
    "save":0,
    "offset":3600,
    "version":"2020f"
  }
}
```
or even add an optional flag to the existing `DATE_UTCTOLOCAL` so that it either returns just the converted date/time or the converted date/time plus the zoneInfo in one go.
WDYT?

**Comment by coronabytes** [comment]
@jsteemann thanks for the feedback,
I refactored it into a detail switch for DATE_UTCTOLOCAL and DATE_LOCALTOUTC
and renamed the properties to something more descriptive.

I will try the subobject for zoneinfo and then fix the tests

**Review by jsteemann — APPROVED** [review]

**Comment by jsteemann** [comment]
Integration PR to run Jenkins PR tests on: https://github.com/arangodb/arangodb/pull/13464

**Comment by jsteemann** [comment]
Merged via https://github.com/arangodb/arangodb/pull/13464
Thanks!

**Pull request closed without merging**
