### PR TITLE
Actually copy encryption files

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10988/

### CODE REVIEW

**Comment by graetzer** [comment]
blue

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11030/

**Comment by neunhoef** [comment]
If test green, this is good to go.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11031/

**Comment by jsteemann** [comment]
Starting another run due to a test failure in the last run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11038/

**Comment by graetzer** [comment]
blue: http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11044/

**Pull request merged**
