### PR TITLE
Implement memory detection override.

### PR DESCRIPTION
**Pull request by neunhoef**

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9028/

**Comment by neunhoef** [comment]
The test failure is only the known one with resilience_move, which is in devel and will be fixed elsewhere. I think this can be merged.

**Comment by graetzer** [comment]
Why an environment variable and not an option?

**Comment by jsteemann** [comment]
Because currently the default values for amount-of-RAM-based-options such as `--rocksdb.block-cache-size` are set in the constructor of the ApplicationFeatures, when command line options and config file options have not been parsed yet. The value of a startup option is only available after `ApplicationFeature::parseOptions()`.

**Pull request merged**
