### PR TITLE
Bug fix 3.4/issue #10090

### PR DESCRIPTION
**Pull request by iurii-i-popov**
Fixed repeatable seek to the same document
Backport #10164
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8366/

### CODE REVIEW

**Comment by iurii-i-popov** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8367/

**Comment by iurii-i-popov** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8373/

**Comment by iurii-i-popov** [comment]
Tests blue.

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6682/

**Pull request merged**
