### PR TITLE
[3.6] Fix read-only counter adjustments

### PR DESCRIPTION
**Pull request by danielhlarkin**
Port of https://github.com/arangodb/arangodb/pull/12882

Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12386/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/12390/

**Review by jsteemann — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
Tests blue again

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
