### PR TITLE
Better result handling for recovery tests

### PR DESCRIPTION
**Pull request by dothebart**
- add new method jsunity.writeDone() that writes the results to a json file
- use that file writer in all recovery tests
- read that file in the result json in the recovery testrunner
- don't flush the database directories when the test wasn't successfull.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1485/

**Comment by jsteemann** [comment]
Doesn't look right yet, at least all red.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1539/

**Comment by dothebart** [comment]
only nonrelated tests red.

**Pull request merged**
