### PR TITLE
[3.5] Fix constrained sort in the cluster

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #10047 and #10057.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6461/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/6685/
blue.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6771/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
