### PR TITLE
Fix a nullptr access, when a MoveShard is aborted for a dropped

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose
Aborting a move shard job for a already dropped collection causes a nullptr access.

### CODE REVIEW

**Review by kvahed — APPROVED** [review]
LGTM

**Review by neunhoef — COMMENTED** [review]
Should we not, just to be on the safe side, also make
```
  auto myshards = sortedShardList(*snapshot.get(planPath));
```
more robust by checking if the result of `get` is a `nullptr` before dereferencing it?
That is in `Job.cpp`...
What if the collection object is in the agency tree but does not have a `shards` attribute?

**Review by neunhoef — CHANGES_REQUESTED** [review]
CHANGELOG?

**Review by kvahed — COMMENTED** [review]
LGTM

**Review by neunhoef — APPROVED** [review]
LGTM

**Pull request merged**
