### PR TITLE
Update link to "ArangoDB, NodeJS and Docker" in readme

### PR DESCRIPTION
**Pull request by millette**

### CODE REVIEW

**Comment by dothebart** [comment]
hi @millette, good catch! We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

We have not been able to set of an electronic system yet. Can you sign, scan and email it to cla (at) arangodb.com?

Thanks a lot
Willi

**Comment by millette** [comment]
Oh, a CLA, I was just talking about those to a friend. I was just a bit curious about arango and cared enough to fix a 404 link in your docs, but don't ask me to sign a CLA for that. Feel absolutely free to use my PR or fix the link any way you see fit :-)

**Comment by dothebart** [comment]
Yes, I see your point. We've just released 3.0 along with a major overhaul of the documentation, so just found another place to watch using the linkchecker ;-)

**Comment by millette** [comment]
Thank you for understanding :-)

**Pull request closed without merging**
