### PR TITLE
added startup option `--log.escape` for unescaped logging

### PR DESCRIPTION
**Pull request by jsteemann**
This option toggles the escaping of log output. 

  If set to `true` (which is the default value), then the logging will work
  as before, and the following characters in the log output are escaped:

  * the carriage return character (hex 0d)
  * the newline character (hex 0a)
  * the tabstop character (hex 09)
  * any other characters with an ordinal value less than hex 20

  If the option is set to `false`, no characters are escaped. Characters with
  an ordinal value less than hex 20 will not be printed in this mode but will
  be replaced with a space character (hex 20).

  A side effect of turning off the escaping is that it will reduce the CPU 
  overhead for the logging. However, this will only be noticable when logging
  is set to a very verbose level (e.g. debug or trace).

### CODE REVIEW

**Comment by fceller** [comment]
LGTM

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/

**Comment by dothebart** [comment]
@jsteemann  Can't we use a character more obvious that its replacing to be escaped chars? like i.e. $ ?

**Comment by jsteemann** [comment]
The patch is about *not* escaping characters at all. Escaping provides no value, and requires dynamic memory allocation. So not escaping is the preferred way to handle this.

And obviously we do not want to change the old, existing log format, because several people will rely on it.

**Comment by dothebart** [comment]
If I read it correctly, you're replacing special chars by blank - which I sugest to rather pick a char that can more easily be identified.

**Comment by jsteemann** [comment]
Non-printable characters are replaced by a space, which should be fine. The bulk of the non-printable characters are effectively `\t`, `\n` and `\r`. You don't want these to be replaced by another character, because that will render the log messages useless. So replacing them with a space seems to be just right. 
We can replace other non-printable characters with another character if this is important for someone, but I personally this to be an exceptional case.

**Pull request merged**
