### PR TITLE
Fix IResearchViewExecutor to return upstream state, not DONE

### PR DESCRIPTION
**Pull request by markuspf**

### CODE REVIEW

**Comment by markuspf** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10647/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10649/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10651/

**Comment by markuspf** [comment]
> 
> In `bug-fix/bts-109` with this fix.
>

That test is broken. ` ¯\_(ツ)_/¯`

**Comment by mchacki** [comment]
@KVS85 This PR fixes a bug shown by the JS test added in this PR.
There seems to be another issue in BTS-109 branch.
We decided to merge this branch (which is ok on it's own) first.
And then fix the issue in BTS-109 test, (and if applicable other bug(s) triggered by it)

**Comment by markuspf** [comment]
I included the test that was added in `bug-fix/bts-109` to this PR, so the `bug-fix/bts-109` branch is obsolete now.

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10660/

**Comment by markuspf** [comment]
Jenkins is blue.

**Pull request merged**
