### PR TITLE
Additional AQL date functions

### PR DESCRIPTION
**Pull request by CoDEmanX**
DATE_DAYOFYEAR, DATE_ISOWEEK, DATE_LEAPYEAR, DATE_QUARTER, DATE_ADD, DATE_SUBTRACT, DATE_DIFF, DATE_COMPARE and DATE_FORMAT.

Unit tests incomplete and untested. Behavior of some functions might need adjustments. ISO duration cache needs to be cleared on every AQL query to avoid a memory leak.

Please rebuild Aardvark and see TODOs in code.

Not sure what happened to Aardvark's lib.test.js - if it still exists, make sure it knows about the new date functions as well.

You may use my Github user name as contributor name. Some parts contributed by @friday, not sure about him. Inspired by (but not copied from) moment.js and couple stackoverflow.com posts.

### CODE REVIEW

**Comment by CoDEmanX** [comment]
There are some argument type issues:

```js
[FAILED] testDateAddInvalid in 0.009 s: at assertion #23: assertTrue: (undefined) does not evaluate to true

// these are actually accepted, but shouldn't...
DATE_ADD(DATE_NOW(), '', 'year')
DATE_ADD(DATE_NOW(), '1', 'year')
DATE_ADD(DATE_NOW(), null, 'year')
DATE_ADD(DATE_NOW(), false, 'year')
DATE_ADD(DATE_NOW(), [], 'year')
```

**Comment by jsteemann** [comment]
I have merged and will check.

**Comment by jsteemann** [comment]
I have fixed the existing tests. I have a question regarding this one:
```
[ ["1910-01-02", 5, "5"], "1910-01-02T00:00:00.000Z" ]
```
It seems to try to add 5 "5"s to the start date. Is that supposed to work? To which unit should the "5" translate? I couldn't figure out the sense, so I think the call should return `null` and changed the test accordingly.
I also added one or two typeweight checks in the `DATE_CALC` function itself.

**Comment by CoDEmanX** [comment]
A unit "5" should indeed produce an error  / warning. It's supposed to return null. Not sure what I did there, might have happened because of copy/paste.

**Comment by CoDEmanX** [comment]
@friday is okay with being mentioned by his GitHub name BTW.

**Pull request merged**
