### PR TITLE
potential fix for the BTS-57 fix

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Potential fix for the BTS-57 fix.
It should allow concurrent read/write ops in streaming transactions again, at least from the client application perspective. On the server side, the ops will be serialized. And error is return if the operation cannot be started within 30 seconds.
This should fix the original problem reported in BTS-57 and not break downwards-compatibility.

Still needs to be tested with client drivers and confirmed!

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [ ] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [ ] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a *JIRA Ticket number*: https://arangodb.atlassian.net/browse/BTS-57 

### Testing & Verification

This change is already covered by existing tests, such as *shell_client --test transaction*.

We need to perform additional tests using drivers!

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10315/

### CODE REVIEW

**Comment by graetzer** [comment]
No

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/3.devel/job/arangodb-devel-docker-and-drivers-nightly/262/

**Comment by jsteemann** [comment]
@graetzer : can you please be a bit more verbose?
Instead of just commenting "No", please explain why you think there is a problem and what needs changing.

**Comment by joerg84** [comment]
> No

Can you give details? @graetzer

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10326/

**Comment by graetzer** [comment]
if the java tests would work it should trigger this assertion https://github.com/arangodb/arangodb/blob/50152de0f24c5887e5bebc0dd007dd5aab5acfca/arangod/Transaction/Manager.cpp#L473

so the tests are 💩

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10373/

**Comment by jsteemann** [comment]
Obsoleted in favor of upcoming fix by @graetzer

**Pull request closed without merging**
