### PR TITLE
bug fix for agency precondition checks

### PR DESCRIPTION
**Pull request by jsteemann**
now compares objects for real

### CODE REVIEW

**Comment by jsteemann** [comment]
Note that before merging this into devel, we should remove the log message I intentionally added and that will show up when the results of the old precondition check and the new precondition check differ.

**Comment by jsteemann** [comment]
One question that also needs clarification is whether we will ever encounter VelocyPack values of type "Custom" in the agency. If yes, then the new precondition check will fail by throwing an exception. If no, then we can ignore this problem and simply document this requirement somewhere.

**Comment by neunhoef** [comment]
Kaveh and I both have looked at this and it looks good. We hereby bless it.

**Comment by kvahed** [comment]
Code reviwed.

**Comment by jsteemann** [comment]
Ok, thanks!
Let me clean up the branch then.

**Pull request merged**
