### PR TITLE
Bug fix 3.7 router/bts 33

### PR DESCRIPTION
**Pull request by markuspf**
This is a  cherry-pick of #11350 to the `3.7-router` branch.

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9295/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9321/

**Comment by joerg84** [comment]
@markuspf @mchacki Do we need https://github.com/arangodb/arangodb/pull/11350/commits/c6f8b603069030f7bf26aa1181c694a3a069a549 in  here as well?

**Comment by KVS85** [comment]
Tests blue.

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9322/

**Comment by mchacki** [comment]
@joerg84 
`Do we need c6f8b60 in here as well?`

The commit is a performance improvement.
In some cases the results have not been aligned to 1000 lines per batch, but smaller.
On single server this is not too much of in issue.
In cluster the performance difference will show.

It does not fix any wrong behavior, and we are not talking about orders of magnitude in performance differences here.

So *need*: No
*Nice-to-have*: Yes

**Comment by mchacki** [comment]
OK i have just checked:
`c6f8b60` is not save yet, do not wait for it.

**Pull request merged**
