### PR TITLE
Feature 3.5/icu exit code

### PR DESCRIPTION
**Pull request by dothebart**
backport of https://github.com/arangodb/arangodb/pull/12493

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11640/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11656/

**Comment by dothebart** [comment]
unrelated test timeout. 
other tests green.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-windows-packages/1045/

**Review by jsteemann — APPROVED** [review]

**Pull request merged**
