### PR TITLE
Feature/allow access to configured 🔐 in readonly mode

### PR DESCRIPTION
**Pull request by m0ppers**

### CODE REVIEW

**Comment by fceller** [comment]
@m0ppers somthing is wrong: http://c1.triagens-gmbh.zz:8080/view/3.features/job/arangodb-ci/view/change-requests/job/PR-3698/3//artifact/linux-community-maintainer/03-test/singleserver-mmfiles-FAIL/authentication.log

**Comment by neunhoef** [comment]
I have just started a PR jenkins job on this in an attempt to make progress merging this back to devel.

**Comment by neunhoef** [comment]
The failed test is a single server test and I cannot see any error message other than "flow interupted". Is this again a jenkins hoax?

**Comment by fceller** [comment]
"Flow Interrupted" normally means that the test hung for more than 30min

**Comment by fceller** [comment]
We need to debug this:

```
[2017-11-15 23:54:22] Running Mocha Tests: /opt/jenkins/workspace/arangodb-ci_PR-3698-NS2M4T4OJ3DBLK53UORUCWIQQFYPU423FGBBHXZVLZEFXV6ZSFVQ/run.3/js/client/tests/authentication/user-access-right-collection-level-read-spec.js
[2017-11-16 00:23:35] Finished: ABORTED Signal: 15 Time elapsed: 1754.345648765564 - 
```

**Comment by jsteemann** [comment]
Code changes look good to me!

**Pull request merged**
