### PR TITLE
Added EnterpriseGraph Dump & Restore Tests

### PR DESCRIPTION
**Pull request by hkernbach**
### Scope & Purpose

Added Dump & Restore Tests for newly introduced graph type: 
- EnterpriseGraphs

- [x] :hankey: Bugfix (as tests are missing so far)

### Checklist

- [x] Tests
  - [x] **integration tests**
- [ ] :book: CHANGELOG entry made
- [ ] Backports
  - [ ] Backport for 3.10: *(yes required)*

#### Related Information

- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/1011
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-946

### CODE REVIEW

**Comment by hkernbach** [comment]
Unrelated windows failure.. otherwise Jenkins green.

**Comment by hkernbach** [comment]
Jenkins green except unrelated windows failures ...

**Review by naushniki — APPROVED** [review]
LGTM :+1:

**Comment by dothebart** [comment]
please pull in latest and check whether the windows portability issues persist.

**Comment by dothebart** [comment]
last jenkins windows run sufficiently successfull.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Review by mchacki — APPROVED** [review]
LGTM!
Thank you very much for this!

**Pull request merged**
