### PR TITLE
Add option to hide query string in log / WebUI

### PR DESCRIPTION
**Pull request by graetzer**
### Scope & Purpose

Add option to hide query string in log / WebUI

- [ ] :hankey: Bugfix 
- [x] :pizza: New feature 
#### Backports:

- [ ] No backports required
- [x] Backports required for: 3.7, devel

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added **Regression Tests**
  - [ ] Added new C++ **Unit Tests**
  - [ ] Added new **integration tests** (i.e. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)

Additionally:

- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/12226/

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12228/

**Review by KVS85 — CHANGES_REQUESTED** [review]
`.setIntroducedIn` should be added.

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
