### PR TITLE
Backport fix for truncate selectivity

### PR DESCRIPTION
**Pull request by graetzer**
see below

### CODE REVIEW

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5737/

**Comment by danielhlarkin** [comment]
So the bug I fixed can be described by the following operations:
1) Insert batch A.
2) Insert batch B.
3) Truncate.
4) Apply updates.
5) Apply updates.

Step (4) will remove batch A from the buffer and clear the estimator. Step (5) will then find batch B in the buffer and apply it. This is because we only dequeue one batch of insertions and removals at a time, and if the first one is ignored due to truncation, we do not check for further buffered operations to ignore, instead breaking out of the loop early (since both insertions and removals are empty). We instead need to take a maximal prefix of the buffers to ignore or apply all at once.

**Comment by graetzer** [comment]
wait but thats exactly what we do now ? I even added a test for it?

**Comment by danielhlarkin** [comment]
Apologies. I saw the changes I made weren't directly backported, didn't read closely enough, and jumped to a conclusion. This version should indeed be more efficient, and covers the problem just fine.

**Pull request merged**
