### PR TITLE
fix UUID - 3.5

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7511/

**Comment by ObiWahn** [comment]
created rpm package with oskar and created cluster on centos6 server.

**Comment by ObiWahn** [comment]
https://172.16.10.101/job/arangodb-matrix-pr-linux/9300/ -- linux only

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
