### PR TITLE
Feature/aql subquery operations stack materialize executor

### PR DESCRIPTION
**Pull request by hkernbach**
Added here: 
- Applied new API to MaterializeExecutor

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/8795/

**Comment by hkernbach** [comment]
To be safe: http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/8799/

**Comment by hkernbach** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8803/

**Comment by mchacki** [comment]
Failure unrelated

**Pull request merged**
