### PR TITLE
update syncRequest() so that it aborts pending messages on shutdown.

### PR DESCRIPTION
**Pull request by matthewvon**
This PR is to help Jenkins tests that were experiencing hangs on shutdown within syncRequest() due to some Maintenance task.  The exact test and/or core files were not known.  This implies that the "real bug" is not being addressed.  Something in Maintenance and/or Scheduler and/or Communicator is not cleaning up in a timely manner on shutdown in devel (3.5).

- [X ] Bug-Fix for *devel-branch* (i.e. no need for backports?)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/4845/

The enterprise mmfiles test had core file failure.  Appears independent of this code:  wait for db level write lock.

The enterprise rocksdb had a failure which is known to be independent and fixed in subsequent branch.

### CODE REVIEW

**Comment by fceller** [comment]
http://jenkins.arangodb.biz:8080/view/3.devel/job/arangodb-devel-matrix-nightly/82/

**Comment by matthewvon** [comment]
19:03:38 ssh: Could not resolve hostname github.com: Temporary failure in name resolution
19:03:38 fatal: Could not read from remote repository.
19:03:38 
19:03:38 Please make sure you have the correct access rights
19:03:38 and the repository exists.
19:03:38 Failed to checkout community branch

I doubt name resolution of GitHub.com is due to my code.

**Comment by fceller** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4868/

**Comment by fceller** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/6472/

**Pull request merged**
