### PR TITLE
better aql error message

### PR DESCRIPTION
**Pull request by ObiWahn**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3598/

### CODE REVIEW

**Comment by jsteemann** [comment]
Just saw that this change may produce internal errors:
```
2019-03-21T17:59:35.663Z [PASSED] testExclusiveExpectConflict in 2019-03-21T17:59:26.766Z+8.897s
2019-03-21T17:59:51.464Z [PASSED] testExclusiveExpectNoConflict in 2019-03-21T17:59:35.663Z+15.801s
2019-03-21T17:59:51Z [24273] S ERROR JavaScript exception in file '/home/steemann/Arango34NoAsan/js/server/modules/@arangodb/arango-statement.js' at 84,16: ArangoError 4: Expecting type Array or Object (while executing)
2019-03-21T17:59:51Z [24273] S ERROR !  var result = AQL_EXECUTE(this._query, this._bindVars, opts);
2019-03-21T17:59:51Z [24273] S ERROR !               ^
2019-03-21T18:00:02.904Z [PASSED] testExclusiveExpectConflictAQL in 2019-03-21T17:59:51.464Z+11.440s
2019-03-21T18:00:17.097Z [PASSED] testExclusiveExpectNoConflictAQL in 2019-03-21T18:00:02.904Z+14.193s
```
This is because it always assumes `opRes.slice()` is an array (but it may not).

**Comment by jsteemann** [comment]
Please apply the following patch to fix it:
```diff
diff --git a/arangod/Aql/ModificationBlocks.cpp b/arangod/Aql/ModificationBlocks.cpp
index 8c1e0f20e3..e00fe3db94 100644
--- a/arangod/Aql/ModificationBlocks.cpp
+++ b/arangod/Aql/ModificationBlocks.cpp
@@ -352,29 +352,26 @@ void ModificationBlock::handleBabyResult(OperationResult const& opRes,
 
   auto code = first->first;
 
-  auto findMessage = [](OperationResult const& opRes, int errorCode) -> std::string {
-    std::string message;
-    for (auto doc : VPackArrayIterator(opRes.slice())) {
-      try {
-        if (doc.hasKey("errorNum") && doc.get("errorNum").getInt() == errorCode) {
-          if (doc.hasKey("errorMessage")) {
-            message = doc.get("errorMessage").copyString();
-            break;
-          }
+  // check if we can find a specific error message
+  try {
+    if (opRes.slice().isArray()) {
+      for (auto doc : VPackArrayIterator(opRes.slice())) {
+        if (!doc.isObject() || !doc.hasKey("errorNum") || doc.get("errorNum").getInt() != code) {
+          continue;
+        }
+        VPackSlice msg = doc.get("errorMessage");
+        if (msg.isString()) {
+          THROW_ARANGO_EXCEPTION_MESSAGE(code, msg.copyString());
         }
-      } catch (...) {
       }
     }
-    return message;
-  };
-
-  auto message = findMessage(opRes, code);
-  if (message.empty()) {
-    THROW_ARANGO_EXCEPTION(code);
+  } catch (...) {
+    // fall-through to returning the generic error message, which better than
+    // forwarding an internal error here
   }
 
-  Result rv(code, message);
-  THROW_ARANGO_EXCEPTION(rv);
+  // no specific error message found. now respond with a generic error message
+  THROW_ARANGO_EXCEPTION(code);
 }
 
 RemoveBlock::RemoveBlock(ExecutionEngine* engine, RemoveNode const* ep)
```
Please also do the change in the devel PR.

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/4962/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3631/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3655/

**Pull request merged**
