### PR TITLE
Bug fix 3.11/revert better create collection api

### PR DESCRIPTION
**Pull request by mchacki**
### Scope & Purpose

*This PR reverts all my work on Create Collection API to avoid breaking changes.*
**DO NOT MERGE** this PR until we have branched off 3.11 branch. **WE CANNOT HAVE THIS CHANGE IN DEVEL**

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/1248
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Comment by mchacki** [comment]
Update: we are actually able to merge this PR without breaking replication 2.0

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-ANY-components-and-drivers/42/

**Review by goedderz — APPROVED** [review]

**Review by jsteemann — APPROVED** [review]
LGTM

**Comment by mchacki** [comment]
Red matrix-pr error is unrelated to this change.

**Pull request merged**
