### PR TITLE
Documentation/switch example generation to rocksdb

### PR DESCRIPTION
**Pull request by dothebart**
So far the documentation examples would be generated with a server running MM-Files.
This was neccessary due to some examples depending on the mmfiles engine. 
In the near by future we are going to have examples depending on the rocksdb engine - which is a conflict then.

This PR overcomes this by adding a storage engine extension to examples, so they can control which storage engine a server should use when they are generated - append `_mmfiles` or `_rocksdb` as you need it. Subsequently 2 servers are started to achieve this.

The default storage engine for these examples will be switched to rocksdb from now on.

### CODE REVIEW

**Comment by Simran-B** [comment]
```
@startDocuBlock put_api_collection_rotate
...
@EXAMPLE_ARANGOSH_RUN{RestCollectionRotateNoJournal_mmfiles}
```


The docu block name is `put_api_collection_rotate`, which is references in _arangodb/docs_ like `{% docublock put_api_collection_rotate %}`.

The example name `RestCollectionRotateNoJournal_mmfiles` defines the file name (e.g. `3.5/generated/Examples/RestCollectionRotateNoJournal_mmfiles.generated`) and is also used to assign IDs to the `<div>`s in allComments.txt.

Is it possible to have an example without surrounding docublock? If not, then no changes in the docs repository should be necessary.

**Comment by dothebart** [comment]
I only found docublocks that had a significant difference between MMFiles & RocksDB in the HTTP-Api chapters - thus - no - all of them are in that part.

**Comment by Simran-B** [comment]
I would like to post-pone this PR to after the 3.5 release to not break anything now and because there is some work required to test and adjust examples furthers. We might even want examples for both storage engines in a few cases.

**Comment by Simran-B** [comment]
Created a test branch https://github.com/arangodb/arangodb/tree/documentation/testing-example-gen and started arangodb-ANY-examples with options:


| Parameter | Value |
|---|---|
| ARANGODB_BRANCH | documentation/testing-example-gen
| ENTERPRISE_BRANCH | devel
| ARANGODB_DOCS_BRANCH | 3.5
| COMMIT_DOCS | off

but it fails like this:

```
/scripts/buildExamples.fish (line 14): No matches for wildcard 'docs/$ARANGODB_VERSION/aql/*.md'. See `help expand`.
and begin ; rm -rf Documentation/Books/AQL/* ; cp docs/$ARANGODB_VERSION/aql/*.md Documentation/Books/AQL/ ; end
                                              ^
FAILED!
```

Looks like the variable is not set? But why?

**Comment by Simran-B** [comment]
Vadim fixed the problem

**Pull request merged**
