### PR TITLE
Bug fix 3.7/fix http2 stats

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Make h2spec tests work again (mostly)
Backport of https://github.com/arangodb/arangodb/pull/12092

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a *JIRA Ticket number*: https://arangodb.atlassian.net/browse/QA-34

### Testing & Verification

This change is already covered by existing tests, such as *scripts/unittest shell_client --http2* and *h2spec* external tool.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10855/

### CODE REVIEW

**Comment by jsteemann** [comment]
@mpoeter: can't tell yet. @graetzer fixed it. I just verified that the current version works again. I am happy to try the old version and try to gather a backtrace.

**Comment by mpoeter** [comment]
@jsteemann don't bother, it's not that important!

**Comment by jsteemann** [comment]
Tests blue

**Comment by graetzer** [comment]
Calling findStream was not Thread safe, sendResponse is called on any scheduler thread.
Using a mutex would have made the lock free queue pointless

**Pull request merged**
