### PR TITLE
[3.4] Persist and check default language selection

### PR DESCRIPTION
**Pull request by danielhlarkin**

### CODE REVIEW

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2264/

**Comment by danielhlarkin** [comment]
@Simran-B Yes, when using the RocksDB engine or persistent indexes with MMFiles, restarting the server with a different value for `--default-language` will cause indexes over UTF strings to break. As far as I know though, no one has actually encountered this bug, as `--default-language` is a hidden option and not exactly advertised for use.

**Comment by Simran-B** [comment]
@danielhlarkin I see, thanks. Can you add an entry to the CHANGELOG about this? We do have users who set different languages:
- https://github.com/arangodb/arangodb/issues/7111
- https://github.com/arangodb/arangodb/issues/3225
- one more request about Swedish collation, but can't find it anymore

**Comment by dothebart** [comment]
It sounds like that should be an installtime-question, since its basically unchangeable later on? So we should at least have that fixed to i.e. `en_US` with the matching comment in the default config, so that users that intend to change it immediately see the consequences.

**Comment by Simran-B** [comment]
Good point. I guess it's not 100% unchangeable, but you would have to drop and re-create all secondary indexes after changing the language, which can be pretty costly.

Probably not the right time, but could we add support for a per-collection / per-index language setting? Right now it seems to be a global setting, which seems disappointing for everyone who wants to build something multi-lingual in ArangoDB and needs index-accelerated sorting. Does ArangoSearch offer this?

**Comment by danielhlarkin** [comment]
@Simran-B I'll add a CHANGELOG entry.

@dothebart I don't think it's worth the effort to change all the installers at this point, especially since it's likely we'll change the way we handle collation and locales in the future. (@Simran-B We've talked about the multi-lingual support stuff, but there are no concrete plans at the moment.)

**Comment by dothebart** [comment]
@dan https://github.com/arangodb/arangodb/blob/devel/etc/arangodb3/arangod.conf.in

**Comment by danielhlarkin** [comment]
@dothebart I have no idea what that link is suppose to tell me.

**Comment by dothebart** [comment]
Please add the language setting with the mentioned comment there. Since this is what users edit when they don't use the starter.

**Comment by danielhlarkin** [comment]
@dothebart For the time being, since our collation support isn't particularly robust, and it's still a _hidden option_, I don't think it's a good idea to add it to the default config, even commented out, as it encourages users to set it by default. Instead, it should be something we only tell users to set if they are experiencing problems.

**Comment by skitsanos** [comment]
Just got the following on Ubuntu 20.x with
```
2020-10-11T18:54:00Z [716] FATAL [7ef60] {config} specified language 'en_US' does not match previously used language ''
```

Strangely, i can run ArangoDB 3.7.2-1 [linux] 64bit in console, but it dies in own '.service' file...

**Pull request merged**
