### PR TITLE
Cancel connections to known failed servers

### PR DESCRIPTION
**Pull request by graetzer**
### Scope & Purpose

Cancel connections to known failed server

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This PR adds tests that were used to verify all changes: `resilience-synchronous-repl-cluster.js` is no longer greylisted

- [x] Added new **resilience tests** 

http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7387/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/9172/

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7428/

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7434/

**Comment by graetzer** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7437/

**Comment by dothebart** [comment]
Merged the latest stuff in, and tried to reproduce the crash that jenkins detected, it seems to be fixed.

**Comment by KVS85** [comment]
https://172.16.10.101/job/arangodb-matrix-pr-windows/1426/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
