### PR TITLE
potential fix for DEVSUP-492

### PR DESCRIPTION
**Pull request by ObiWahn**
more info

- [ ] port to 3.4
- [ ] port to 3.5
- [x] CHANGELOG
- [x] tests

### CODE REVIEW

**Comment by ObiWahn** [comment]
lets check if we break anything: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7066/

**Comment by ObiWahn** [comment]
[devsup-492.txt](https://github.com/arangodb/arangodb/files/3820097/devsup-492.txt)
here a little test to show the problem

**Comment by jsteemann** [comment]
LGTM, but definitely needs an additional test case. Plus, as it is a behavior change, needs a CHANGELOG entry.
Regarding backporting, please check with support whether this shall be backported to 3.5/3.4.

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7111/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8887/ -- restart liunx job (jenkins failed to execute)

**Comment by lservini** [comment]
LGTM, if possible backport to 3.4

**Pull request merged**
