### PR TITLE
fix reloading "clientId" values from persistence

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix recovery of "clientId" values in Agency when restarting an agent from persistence. 

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] Backports required for: *3.6*

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13333/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13344/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13377/

**Comment by jsteemann** [comment]
Tests blue

**Review by neunhoef — APPROVED** [review]
LGTM

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
