### PR TITLE
Feature/new devel versioning scheme

### PR DESCRIPTION
**Pull request by hkernbach**
- Versioning scheme now follows semantic versioning
- added tests

### CODE REVIEW

**Comment by hkernbach** [comment]
^-- frontend/build/* files does not need to be merged
Documentation I don't know.

**Comment by Simran-B** [comment]
How does the new schema look like? Documentation build scripts need to be checked to ensure nothing breaks.

**Comment by fceller** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/909/

**Comment by fceller** [comment]
@Simran-B the version is now "3.4.0-devel"

**Comment by fceller** [comment]
I will run ./scripts/generateDocumentation.sh

**Comment by Simran-B** [comment]
Couldn't find any issues with the documentation building 👍

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1037/

**Pull request merged**
