### PR TITLE
Bug fix/internal issue 2764

### PR DESCRIPTION
**Pull request by hkernbach**
fixed https://github.com/arangodb/planning/issues/2764

### CODE REVIEW

**Comment by jsteemann** [comment]
@Simran-B : setting the replicationFactor higher than the number of DB servers is possible also via ArangoShell. If we want to disallow this, the server should respond with an error, and the web interface does not need to do anything special here.

**Comment by Simran-B** [comment]
@jsteemann My understanding is that you can set a number higher than the DB servers only if `enforceReplicationFactor` is explicitly turned off, which you can't in the web UI (also see https://github.com/arangodb/planning/issues/3059).

If I set a factor of 5 in the web UI with only 3 DB servers in the cluster, then I get the following toast messages:

- Collection: Collection "test" will be created.
- Error: the number of current dbservers is lower than the requested replicationFactor

If I create a collection with e.g. factor 2, everything goes well. If I then go to the collection settings and change it to 5, Save, I only get:

- Collection: Successfully changed.

Does it accept any number at this point (i.e. change is in fact applied, waiting for more DB servers)? Does it only check the replication factor on initial collection creation if `enforceReplicationFactor` is on?

There is no mention of `replicationFactor` and `enforceReplicationFactor` in the docs for the endpoint to modify collection properties:
https://docs.arangodb.com/3.3/HTTP/Collection/Modifying.html#change-properties-of-a-collection

**Comment by jsteemann** [comment]
It's only enforced on collection creation, not when updating a collection later.

**Comment by jsteemann** [comment]
I don't know if this is intentional or not.
Feel free to open an issue for this if you think it makes sense from the user perspective. But we should not couple it with this issue (6812)

**Pull request merged**
