### PR TITLE
fix windows warnings / compile errors

### PR DESCRIPTION
**Pull request by dothebart**
fix compiler warnings / errors on windows

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4786/

**Comment by mchacki** [comment]
Can you try to include this commit from 3.4?
4982ca6
Fixed the issue there.

**Comment by mchacki** [comment]
Ok just checked the source for above commit is not present in devel, so will not help either.

@fceller and me suspect some misconfiguration now, we did trigger a rerun.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4798/

**Comment by mchacki** [comment]
Ok latest jenkins is green.
Thank you!!!

**Pull request merged**
