### PR TITLE
speed up datetime parsing in AQL

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This PR replaces two `std::regex` instances for AQL date/time matching with hand-written string matchers. This speeds up date/time parsing by about 60-70%.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *scripts/unittest shell_server_aql --test aql-functions-date*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7947/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7951/

**Comment by ObiWahn** [comment]
tests/js/server/aql/aql-functions-date.js fail

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7955/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7956/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7970/

**Comment by jsteemann** [comment]
Tests blue:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7970/

@dothebart @ObiWahn : please review.

**Pull request merged**
