### PR TITLE
3.5 -- DEVSUP-492

### PR DESCRIPTION
**Pull request by ObiWahn**
backport

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7125/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1136/

**Comment by KVS85** [comment]
Tests blue.

**Comment by lservini** [comment]
good, thanks

**Pull request merged**
