### PR TITLE
[3.7] cost estimate spliced subquery no results

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose
3.7 backport of #13715.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/14404/

**Comment by maierlars** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/14412/

**Comment by maierlars** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/14414/

**Review by mchacki — APPROVED** [review]
LGTM

**Pull request merged**
