### PR TITLE
Bugfix of DFS path uniqueness implementation

### PR DESCRIPTION
**Pull request by goedderz**

### CODE REVIEW

**Comment by goedderz** [comment]
Intermediate PR check: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4545/

**Comment by hkernbach** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/6117/

**Comment by goedderz** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4576/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4587/

**Comment by goedderz** [comment]
Jenkins is completely green.

**Comment by goedderz** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4610/

**Comment by goedderz** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4611/

**Comment by goedderz** [comment]
Jenkins is still green.

**Pull request merged**
