### PR TITLE
Revive faster out-of-range comparator for secondary index scans

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Revive faster out-of-range comparator for secondary index scans that do a full collection index scan for index types "hash", "skiplist", "persistent". There is a performance gain of a few percent when running a query on a local collection with 1M entries, e.g. `FOR doc IN collection RETURN doc.value` (where `value` is indexed).

- [ ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *shell_server_aql*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11171/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Comment by graetzer** [comment]
How can the extra method code into the comparator be slower? just inline this check in the header if the inlineing makes it faster ??

**Comment by jsteemann** [comment]
It is not the inlining that is the problem here.
The problem is that the VPackComparator first does the check for the index object id, but this will almost always find that the two compared values have the same object id.
And then the VPackComparator goes on and compares the two index values, to determine which one compares lower/higher. So it calls into VelocyPackHelper::compare eventually.
The check that we now re-added never calls into VelocyPackHelper::compare(). It _only_ compares the index object ids and that's it.
So if outOfRange() is called 10,000 times, the pure comparator-based solution does the index object id check 10,000 times, and then calls VelocyPackHelper::compare() 10,000 times.
The version that we have now only does the index object id check 10,000 times, and saves 10,000 calls to VelocyPackHelper::compare().
That's why it is faster, also in practice when we tested it manually. 
Of course, it will only help if you enumerate the entire index for a collection (e.g. `FOR doc IN collection RETURN doc.value` and `value` is indexed). It will not help with point or range lookups in an index.

**Comment by graetzer** [comment]
lol why did you  not use a clever RocksDBKeyBounds instead of adding another code path to the iterator ??

**Comment by graetzer** [comment]
a clever RocksDBKeyBound would use "<objectId + 1><0x00>" as upper bound

**Comment by jsteemann** [comment]
True, but the whole thing is about reducing the number of calls into VelocyPackHelper::compare.
I don't see how an adjusted bound can help us there if for many keys the objectId is as expected. Then the Comparator will still try to determine the relative order of the 2 keys, which we don't need in the outOfRange() check.
If we could get of the outOfRange() check altogether, that would be great. But I think it was added in the first place because only using `iterate_lower_bound` and `iterate_upper_bound` did not work reliably. At least that is what I remember.
Do you think it is safe to remove the outOfRange() check and rely solely on the `iterate_lower_bound` and `iterate_upper_bound` values? If not, then I don't understand the suggestion.

**Comment by graetzer** [comment]
the first code in the comparator:
```c++
constexpr size_t objectIDLength = RocksDBKey::objectIdSize();

  int r = memcmp(lhs.data(), rhs.data(), objectIDLength);

  if (r != 0) {
    // different object ID
    return r;
  } 
```

**Comment by jsteemann** [comment]
Yes...?
And if that finds the same object id, which it will for a lot of keys, it will call VelocyPackHelper::compare(). And that is exactly what we want to avoid.

**Comment by graetzer** [comment]
I was looking at the lines below that which specifically check for prefixes.

**Comment by jsteemann** [comment]
Here is the Comparator code:
```
 68 int RocksDBVPackComparator::compareIndexValues(rocksdb::Slice const& lhs,
 69                                                rocksdb::Slice const& rhs) const {
 70   constexpr size_t objectIDLength = RocksDBKey::objectIdSize();
 71 
 72   int r = memcmp(lhs.data(), rhs.data(), objectIDLength);
 73 
 74   if (r != 0) {
 75     // different object ID
 76     return r;
 77   }
 78 
 79   if (ADB_UNLIKELY(lhs.size() == objectIDLength || rhs.size() == objectIDLength)) {
 80     if (lhs.size() == rhs.size()) {
 81       return 0;
 82     }
 83     return ((lhs.size() < rhs.size()) ? -1 : 1);
 84   }
 85 
 86   TRI_ASSERT(lhs.size() > sizeof(uint64_t));
 87   TRI_ASSERT(rhs.size() > sizeof(uint64_t));
 88 
 89   VPackSlice const lSlice = VPackSlice(reinterpret_cast<uint8_t const*>(lhs.data()) + sizeof(uint64_t));
 90   VPackSlice const rSlice = VPackSlice(reinterpret_cast<uint8_t const*>(rhs.data()) + sizeof(uint64_t));
 91 
 92   r = ::compareIndexedValues(lSlice, rSlice); 
```
The call in line 92 is expensive, and we want to avoid this when doing a full index scan.
The problem with the Comparator-only approach is that we will scan over a lot of keys with the same prefix. So we won't drop out in line 76 but go on. And for most keys we will not get into the `if` block in line 79, so we will always end up in the VelocyPack comparison in line 92. And that is exactly what the PR avoids, even though it handles it outside the Comparator.
Or am I missing something?

**Comment by graetzer** [comment]
You should land in line 83 no?

**Comment by jsteemann** [comment]
No. The full keys are compared most of the time.

**Comment by jsteemann** [comment]
> a clever RocksDBKeyBound would use "<objectId + 1><0x00>" as upper bound which negates the need for more code in the iterators, because the first memcmp in the comparator would already fail

It _could_ work if we choose a range bound of "<objectId + 1>" or "<objectId - 1>". But the one extra null byte at the end will make ti always bypass the `if` block in line 79.
I am not sure if there are any side effects of using an 8 byte-only range bound, but I can give this a try.

**Comment by graetzer** [comment]
If one of the bounds is just a prefix it will work. We cannot both be right.

**Comment by graetzer** [comment]
The extra byte was a mistake. Lower bounds are inclusive I think

**Comment by graetzer** [comment]
The key advantage here is that rocksdb still uses the comparator because of `iterate_upper_bound`. 
We just have to do an additional check on top, because the transaction iterator does not honour it right now.
So using better bounds should improve performance.

Also your current code does a bswap + comparison; The bswap is not needed.

**Comment by graetzer** [comment]
also seems like iterate_upper_bound might be honoured now by rocksdb: https://github.com/facebook/rocksdb/commit/230bcae7b61c03ded4fd65e9d157c66348440c95

**Comment by graetzer** [comment]
which means we can remove  the outOfRange() check completely for forward iterators

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11253/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
