### PR TITLE
Docs: Check protocol(), throw if not http/1.1, don't filter common headers

### PR DESCRIPTION
**Pull request by Simran-B**
Backport of #13062 

Depends on: #13042

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12980/

http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/701/

**Review by jsteemann — APPROVED** [review]

**Review by dothebart — APPROVED** [review]

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/14503/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/14504/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
