### PR TITLE
Doc - Backport scripts and content changes to 3.3

### PR DESCRIPTION
**Pull request by Simran-B**
Forward port of #7737 

http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/387/

### CODE REVIEW

**Comment by dothebart** [comment]
since we all do this by the incentive of @ObiWahn he should also review this.

**Comment by Simran-B** [comment]
@ObiWahn Oskar has one version of its scripts for all documentation versions and is used for the new jenkins, but the old jenkins uses the scripts which are in this repository. They are possibly different in every version, which is also required to some extent (otherwise we would have to refactor a lot of things). We use the old jenkins to publish documentation, and that will not change in the short term.

---

Compiled successfully in a local build with the `work/build-documentation` folder removed. If it already exists from a previous build (3.4+) then there will be HTML files in the Drivers book which lead to dangling anchor errors:

- /oskar/work/books_html/Drivers/JS/index.html
- /oskar/work/books_html/Drivers/JS/Reference/Collection/SimpleQueries.html 
- /oskar/work/books_html/Drivers/JS/Reference/ViewManipulation.html
- /oskar/work/books_html/Drivers/JS/Reference/Database/ViewAccess.html
- /oskar/work/books_html/Drivers/Java/Reference/View/index.html
- /oskar/work/books_html/Drivers/Java/Reference/View/ArangoSearch.html
- /oskar/work/books_html/Drivers/Java/Reference/View/ViewManipulation.html
- /oskar/work/books_html/Drivers/Java/Reference/Database/ViewAccess.html

I guess the problem is that output folders of unknown books are not removed in the build process (Drivers book was added in 3.4).

**Comment by Simran-B** [comment]
Doesn't that do the opposite of what it should do?

```bash
    # keep or delete files from last build
    if $keep_old; then
        rm -fr "$ARANGO_BUILD_DOC_OUT" || ferr "could not delete books output dir"
        rm -fr "$ARANGO_BUILD_DOC_PRE" || ferr "could not delete ppdir dir"
    fi
```

**Comment by Simran-B** [comment]
@ObiWahn I assume this will fix the dangling anchor errors, because it will delete both output folders by default: https://github.com/arangodb/oskar/pull/92

**Comment by Simran-B** [comment]
Successful on both Jenkins after oskar fix was applied, therefore merging. We can clean up scripts once we got rid of old Jenkins.

**Pull request merged**
