### PR TITLE
BTS-1080: [testing] Bug fix 3.10/recovery detect errors in setup

### PR DESCRIPTION
**Pull request by dothebart**
backport of https://github.com/arangodb/arangodb/pull/17346

### CODE REVIEW

**Review by MBkkt — APPROVED** [review]

**Comment by Dronplane** [comment]
@dothebart  could you please confirm: Would it collect crash dumps for "intentional" crashes during recovery tests in CI? I guess I've saw this several times. But for this PR I don't see any CI runs, so can't confirm this myself.

**Comment by dothebart** [comment]
crashes during the *setup* phase *should not* create a coredump. Crashes during the recovery phase otoh *should*

**Review by jsteemann — APPROVED** [review]
LGTM

**Review by MBkkt — COMMENTED** [review]
I don't have objections but I don't understand most part of PR, so cannot approve

UPD:

lgtm tests:
view-arangosearch*
view-search-alias*

**Comment by dothebart** [comment]
the tests @Dronplane complained about have been disabled for windows, since it was too much fuzzing.

**Pull request merged**
