### PR TITLE
[3.4] Backported TakeoverLeadership action.

### PR DESCRIPTION
**Pull request by maierlars**

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5730/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5734/

**Comment by neunhoef** [comment]
New run, had to adjust one LOG_DEVEL.

**Comment by neunhoef** [comment]
image

**Pull request merged**
