### PR TITLE
allow "stream" attribute on top level

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Allow specifying the "stream" attribute for streaming cursors also on the top level of requests to POST /_api/cursor

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification

This change is already covered by existing tests, such as streaming cursor tests.

This PR adds tests that were used to verify all changes:

- [x] Added new **integration tests** (i.e. in shell_server / shell_server_aql)

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4746/

### CODE REVIEW

**Comment by daoxian** [comment]
What's the purpose to do so?

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4751/

**Comment by jsteemann** [comment]
@daoxian: the purpose is to allow calling the cursor API with both
`{"query":"...", "stream":true}`
as well as
`{"query":"...", "options": {"stream":true}}`
Because we have seen both variants in practice and so far only the latter variant worked.

**Comment by Simran-B** [comment]
@jsteemann What do you mean exactly by "seen both variants in practice"? Does it stem from an inconsistency in the docs?

**Pull request merged**
