### PR TITLE
Fix for  #10897

### PR DESCRIPTION
**Pull request by markuspf**
Ref: #10897 

The problem was caused by `COLLECT var = expr` opening a new variable scope when it was not supposed to.

This PR also adds regression test.

### CODE REVIEW

**Comment by markuspf** [comment]
Note that this PR checks in a newly compiled `grammar` files compiled with bison 3.5.

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8136/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8165/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8174/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8186/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8188/

**Comment by mchacki** [comment]
The Jenkins failure is known and unrelated

**Pull request merged**
