### PR TITLE
Bug fix/cleanup thread exceptions

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Some cleanup and comments of thread exception handling.
Adds missing try...catch to some threads, removes now-superfluous CriticalThread.
The relevant parts of this (adding missing try...catch) have already been backported before.

This PR is a subset of https://github.com/arangodb/arangodb/pull/12972, which I will now close because it got too complex.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12641/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12644/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12648/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12655/

**Comment by jsteemann** [comment]
Tests blue

**Review by neunhoef — APPROVED** [review]
LGTM

**Pull request merged**
