### PR TITLE
[3.3] MMFiles-replication-get-followers-under-lock (backport)

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #7298. See arangodb/release-3.4#140.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-3.3-linux-matrix-nightly/270/
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2090/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2092/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2129/

**Comment by goedderz** [comment]
This probably has to be updated when https://github.com/arangodb/arangodb/pull/7438 is merged.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2224/

**Comment by jsteemann** [comment]
Obsolete now

**Pull request closed without merging**
