### PR TITLE
fix windows build

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

*(Can you describe what functional change your PR is trying to effect?)*

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by ObiWahn** [comment]
I am not sure if this change is responsible but a `p` directory is created as sibling of my build directory during the build phase.

**Comment by fceller** [comment]
please postpone this until 3.5 GA is ready

**Comment by ObiWahn** [comment]
Works for me! I can build on windows again 👍

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4599/

**Comment by mchacki** [comment]
Can you try to include this commit from 3.4?
4982ca6c3d856b74c62a95b61c90f97d3a98be7a
Fixed the issue there.

**Comment by dothebart** [comment]
closing in favour of a completely new branch - diverged to much already.

**Pull request closed without merging**
