### PR TITLE
Enable GCC 9.3.0

### PR DESCRIPTION
**Pull request by KVS85**
oskar PR: https://github.com/arangodb/oskar/pull/241 (must be merged first).

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9548/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/3429/

**Comment by markuspf** [comment]
Just as a random heads-up: BTS-37 (random threading-related failures in Maintenance) was happening with gcc-9.3.0 on my machine, but as stated on that ticket ArangoDB wasn't built using Oskar, so it might have been any old other library that is used)

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
