### PR TITLE
Fix a hanging query shutdown

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11353/

### CODE REVIEW

**Comment by graetzer** [comment]
https://arangodb.atlassian.net/browse/BTS-126

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Java/job/arangodb-ANY-java-driver-matrix/1048/

**Comment by KVS85** [comment]
> http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11353/

Tests blue.

> http://jenkins01.arangodb.biz:8080/view/Java/job/arangodb-ANY-java-driver-matrix/1048/

It seems that this one doesn't work for MMFiles case.

**Comment by jsteemann** [comment]
@KVS85 : test results seem to indicate something doesn't work w.r.t. MMFiles.
But how can one find the actual errors? I download the build artifcat file but it only seems to contain logs from arangod...
So what actually went wrong here?

**Comment by KVS85** [comment]
> @KVS85 : test results seem to indicate something doesn't work w.r.t. MMFiles.
> But how can one find the actual errors? I download the build artifcat file but it only seems to contain logs from arangod...
> So what actually went wrong here?

These tests log activity directly into [console](url=http://jenkins01.arangodb.biz:8080/view/Java/job/arangodb-ANY-java-driver-matrix/1048/ARANGO_EDITION=enterprise,ARANGO_MODE=cluster,ARANGO_STORAGE_ENGINE=mmfiles,DRIVER_HOSTS_ACQUIRE=true,SERVER_NODE=linux&&java&&driver%7C%7Cgce-driver/consoleFull):
```
...
20:28:16 [INFO] Running com.arangodb.StreamTransactionApiTest
20:28:27 [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.73 s <<< FAILURE! - in com.arangodb.StreamTransactionApiTest
20:28:27 [ERROR] streamTransactionFromDifferentCoordinators[1](com.arangodb.StreamTransactionApiTest)  Time elapsed: 10.013 s  <<< ERROR!
20:28:27 org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
20:28:27 	at com.arangodb.StreamTransactionApiTest.streamTransactionFromDifferentCoordinators(StreamTransactionApiTest.java:86)
20:28:27 
...
20:29:19 [ERROR] Errors: 
20:29:19 [ERROR]   StreamTransactionApiTest.streamTransactionFromDifferentCoordinators:86 » TestTimedOut
...
```

**Comment by graetzer** [comment]
thats a new test not in the master version of the driver, does it actually work ?
Test seems to block on begin not any particular operation ?
@rashtao

**Comment by rashtao** [comment]
There was a bug in the test code, fixed here: https://github.com/arangodb/arangodb-java-driver/commit/74933f0ae9463ee7f3bfe44c9f0e6e74deffda06

http://jenkins01.arangodb.biz:8080/view/Java/job/arangodb-ANY-java-driver-matrix/

**Comment by graetzer** [comment]
driver test blue

**Pull request merged**
