### PR TITLE
Bug fix 3.7/internal issue #772

### PR DESCRIPTION
**Pull request by Dronplane**
Backport fixes for:
Community  issue #13238 
Internal issue #772

https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13316/

### CODE REVIEW

**Comment by Dronplane** [comment]
Tests blue except known failures

**Comment by Dronplane** [comment]
Rebuild with spurious wakeup fix https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13321/

**Review by gnusi — APPROVED** [review]

**Comment by KVS85** [comment]
Tests blue except unrelated known failure.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
