### PR TITLE
re-allow VST connections in arangosh

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This was broken temporarily during unreleased 3.7.5 development via https://github.com/arangodb/arangodb/pull/12885.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [ ] No backports required
- [x] Backports required for: 3.6 (will be made in https://github.com/arangodb/arangodb/pull/12886)

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12474/

### CODE REVIEW

**Comment by graetzer** [comment]
is there not a test in oscar running shell_client with vst / http2 ?

**Comment by jsteemann** [comment]
Yes, there are such tests. But they are calling arango.reconnect(...) with an `h2://...` or `vst://...` endpoint, so they bypass the startup parameter validation in arangosh. That's why the tests did not find the problem.
We will need proper tests that actually call arangosh with an `h2://...` or `vst://...` endpoint to see this issue.

**Comment by jsteemann** [comment]
Tests blue

**Review by dothebart — APPROVED** [review]

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12517/

**Comment by jsteemann** [comment]
Tests blue

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
