### PR TITLE
Delete obsolete symlink

### PR DESCRIPTION
**Pull request by markuspf**
### Scope & Purpose

Cleanup

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

### CODE REVIEW

**Review by mchacki — APPROVED** [review]
LGTM
if this compiles it can go out the door :+1:

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by dothebart** [comment]
this can break the build.

**Comment by markuspf** [comment]
It doesn't break on Jenkins? How does it break otherwise?

**Pull request merged**
