### PR TITLE
now escaping the result of a foxx services setup script

### PR DESCRIPTION
**Pull request by hkernbach**
Devel PR for https://github.com/arangodb/arangodb/pull/12737

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/12027/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/12366/

**Comment by hkernbach** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12368/

**Comment by hkernbach** [comment]
image

**Comment by hkernbach** [comment]
image

**Review by mchacki — APPROVED** [review]
LGTM

I think this solves the issue at hand.

**Pull request merged**
