### PR TITLE
Add -fstandalone-debug for Clang Debug builds

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

Add `-fstandalone-debug` for our Clang Debug builds, so we get debug symbols for the STL etc.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Review by hkernbach — CHANGES_REQUESTED** [review]
LGTM, but changelog entry is missing.

**Comment by goedderz** [comment]
> LGTM, but changelog entry is missing.

Do we need one? This does not affect our "normal" builds, just custom ones of developers.

**Comment by goedderz** [comment]
It'd of course be no problem to write one, I just don't think it's necessary, and wouldn't be of interest for users to read. @mchacki WDYT?

**Comment by mchacki** [comment]
ok, i do not think a CHANGELOG entry is relevant here.
This is meant to be user-facing, and there is nothing that this PR changes for our users (we build with gcc on Linux, and Apple has the Flag set anyways)
If at all there should be README_Maintainers entry for this kind of PRs, if the Developers need to take some kind of action, which I do not see in this pr at all.
So I think this PR is all good if it helps us internally and no further file entry is required.

**Review by mchacki — APPROVED** [review]
LGTM

**Pull request merged**
