### PR TITLE
Query helper should support options

### PR DESCRIPTION
**Pull request by pluma**
This adjusts the query helper so instead of this:

```js
db._query(aql`
  FOR i IN 1..1000
  LIMIT 0, 100
  RETURN i
`, { fullCount: true });
```

it's now also possible to do this:

```js
query({ fullCount: true })`
  FOR i IN 1..1000
  LIMIT 0, 100
  RETURN i
`;
```

Previously the query helper couldn't take any arguments (this syntax is still supported):

```js
// no way to pass options here
query`
  FOR i IN 1..1000
  LIMIT 0, 100
  RETURN i
`;
```

### CODE REVIEW

**Comment by pluma** [comment]
I'm marking this as a draft because I'm not sure if this should go in 3.5 or 3.6 and it should be documented in the relevant NewFeatures file before being merged into either.

**Comment by pluma** [comment]
Looks like "ready for review" means "ready to merge". Keep in mind this is explicitly WIP but ready for review.

**Comment by pluma** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4161/

**Comment by pluma** [comment]
Probably need @fceller to decide if this should still go in 3.5 at this point or wait for 3.6.

**Comment by mchacki** [comment]
delayed to after 3.5.0

**Comment by pluma** [comment]
I suggest moving this into 3.6 if it doesn't make the cut for 3.5.0. I don't think a feature should be added in 3.5.1.

**Comment by mchacki** [comment]
Rebased to current devel.
Documentation part moved here:
https://github.com/arangodb/docs/pull/313

**Comment by mchacki** [comment]
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/

**Pull request merged**
