### PR TITLE
feature/arangosearch-s2-3

### PR DESCRIPTION
**Pull request by gnusi**
minor cleanup:
added CHANGELOG entries, adjust default values for geo analyzers

http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12616/

### CODE REVIEW

**Review by Dronplane — APPROVED** [review]
LGTM

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12617/

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12618/

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12619/

**Pull request merged**
