### PR TITLE
Sort followerinfo in maintainermode right

### PR DESCRIPTION
**Pull request by neunhoef**
This is a trivial fix to get the sort order right in maintainer mode for
followerinfo lists.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13292/

**Review by jsteemann — APPROVED** [review]

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13294/

**Comment by jsteemann** [comment]
Now it fails exactly where the modifications were made:
```
* Test "resilience_move"
    [FAILED]  tests/js/server/resilience/move/moving-shards-cluster.js

      "test" failed: server is dead: 
health Check Signal(6)  checkArangoAlive: Marking crashy
health Check Signal(6)  checkArangoAlive: Marking crashy
health Check Signal(6)  checkArangoAlive: Marking crashy

   Suites failed: 1 Tests Failed: 0

--------------------------------------------------------------------------------
Crash analysis of: {"role":"dbserver","port":"12355","endpoint":"tcp://127.0.0.1:12355","rootDir":"/work/tmp/arangosh_heaLOl/resilience_move/dbserver0","url":"http://127.0.0.1:12355","args":{"configuration":"/work/ArangoDB/etc/testing/arangod-dbserver.conf","define":"TOP_DIR=/work/ArangoDB","javascript.app-path":"/work/tmp/arangosh_heaLOl/resilience_move/dbserver0/apps","javascript.copy-installation":false,"http.trusted-origin":"all","temp.path":"/work/tmp/arangosh_heaLOl/resilience_move/dbserver0/tmp","server.storage-engine":"rocksdb","server.endpoint":"tcp://127.0.0.1:12355","database.directory":"/work/tmp/arangosh_heaLOl/resilience_move/dbserver0/data","log.file":"/work/tmp/arangosh_heaLOl/resilience_move/dbserver0/log","javascript.allow-external-process-control":"true","javascript.allow-port-testing":"true","cluster.my-address":"tcp://127.0.0.1:12355","cluster.my-role":"PRIMARY","cluster.agency-endpoint":"tcp://127.0.0.1:12311","javascript.enabled":"false"},"pid":18595,"name":"dbserver - 12355","upAndRunning":true,"id":"PRMR-4f0e33c6-001f-49ab-b93f-9b3bc2596635","stats":{"minorPageFaults":47690,"majorPageFaults":0,"userTime":3.05,"systemTime":1.73,"numberOfThreads":1,"residentSize":0,"residentSizePercent":0,"virtualSize":0,"rchar":114716128,"wchar":171818259,"syscr":33911,"syscw":70733,"read_bytes":16384,"write_bytes":172355584,"cancelled_write_bytes":4096},"message":"\n","exitStatus":{"status":"ABORTED","signal":6}}
(gdb) #0  __restore_sigs (set=set@entry=0x7f3de11fb330)
    at ./arch/x86_64/syscall_arch.h:40
#1  0x00007f3defc5ee1c in raise (sig=sig@entry=6) at src/signal/raise.c:11
#2  0x00007f3defc55098 in abort () at src/exit/abort.c:13
#3  0x00007f3dedfd03c5 in (anonymous namespace)::killProcess (
    signal=signal@entry=6) at /work/ArangoDB/lib/Basics/CrashHandler.cpp:120
#4  0x00007f3dedfd0446 in arangodb::CrashHandler::crash (
    context=context@entry=0x7f3de11fb4f0 "assertion failed in /work/ArangoDB/arangod/Cluster/FollowerInfo.cpp:332: diff.empty()")
    at /work/ArangoDB/lib/Basics/CrashHandler.cpp:436
#5  0x00007f3dedfd0509 in arangodb::CrashHandler::assertionFailure (
    file=file@entry=0x7f3defca2df8 "/work/ArangoDB/arangod/Cluster/FollowerInfo.cpp", line=line@entry=332, 
    context=context@entry=0x7f3defca2dc1 "diff.empty()")
    at /work/ArangoDB/lib/Basics/CrashHandler.cpp:453
#6  0x00007f3deceb6be8 in arangodb::FollowerInfo::updateFailoverCandidates()
    () at /work/ArangoDB/arangod/Cluster/FollowerInfo.cpp:332
#7  0x00007f3dece4bb2a in arangodb::FollowerInfo::allowedToWrite (
```
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/14754/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=(linux&&test)%7C%7Cgce/artifact/testfailures.txt

**Comment by neunhoef** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13305/

**Comment by neunhoef** [comment]
This should be good to go, Jenkins was green. It is a very minor fix, only touching MaintainerMode runs.

**Review by KVS85 — COMMENTED** [review]
LGTM.

**Pull request merged**
