### PR TITLE
disable attempts to create smart satellite graphs/collections

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Disable attempts to create smart satellite graphs/collections, as this combination does not make sense.
Any such attempts will now result in an HTTP 400 ("Bad request") error to be returned.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

Enterprise PR: https://github.com/arangodb/enterprise/pull/538

#### Backports:

- [x] No backports required
- [ ] Backports required for:

### Testing & Verification

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (i.e. in shell_server, shell_client)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11646/

### CODE REVIEW

**Review by hkernbach — APPROVED** [review]

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11652/

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
Building again after #ifdef change:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11655/

**Review by joerg84 — APPROVED** [review]

**Comment by jsteemann** [comment]
Tests blue

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
