### PR TITLE
don't spill the server logs with multiple lines for stacktraces - thi…

### PR DESCRIPTION
**Pull request by dothebart**
…s eases managing of stacktraces.

### CODE REVIEW

**Comment by dothebart** [comment]
@pluma @mpv1989 can you have a look?

**Comment by pluma** [comment]
:-1: from me on this.

Having two sets of functions for this is redundant. The problem right now is that we have no way to log multi-line messages without

a) making them unreadable or
b) barfing all over the log

The latter is especially a problem in the frontend where messages are displayed in reverse order and stacktraces thus become mangled. Additionally it causes obvious problems when exceptions are thrown in two threads at the same time.

However simply condensing multi-line stacktraces into a single log line is effectively unreadable with how log output is currently displayed both in the arangod log and in the frontend. Before we have a nice way to format multi-line entries in both (I doubt I'm the only person to use arangod in interactive mode in development) I can't give a thumbs up on changing how stacks are logged.

FWIW when we do find a way to pretty-print multiline log entries, we should simply replace all occurrences of `errorLines` with `error` (and likewise for the other `*Lines` methods) and alias them.

**Comment by pluma** [comment]
To clarify: I would love to see a change to how we format log events so multi-line log events become a thing. Once we have found a way to format multi-line log events (i.e. single call to `console.error` instead of `console.errorLines`), I'm fine with changing all incidents where we currently rely on `errorLines` for readable output. Stacktraces should not receive special treatment -- they're just the most obvious case of multi-line log events we currently have.

**Comment by dothebart** [comment]
this addresses: https://github.com/arangodb/arangodb/issues/2436

**Comment by dothebart** [comment]
One problem about having two functions is, that this is also used in the frontend, which in term should represent the stacktraces as several lines. 

This is also a massive problem with the windows event log, where its even less obvious which messages are to be combined as one.

**Comment by pluma** [comment]
As I said. If we can find a way to present multi-line events like stacktraces in a meaningful way in aardvark and (ideally) the arangod log, I'll support this change. But in that case I don't see why we wouldn't want to replace `errorLines` and friends completely as they only seem to exist to work around the broken (read: backslash-escaped) representation of line breaks in error events.

**Comment by dothebart** [comment]
meanwhile another PR has been merged which enables JS_LOG to get an array of lines. Whats to be happening with these lines, (whether they will be logged out as single lines or one) should then be decided in the logger itself.

**Comment by pluma** [comment]
@dothebart Link?

**Pull request closed without merging**
