### PR TITLE
Bug-fix/ui-nitpicks

### PR DESCRIPTION
**Pull request by Simran-B**
- Consistently use `LZ4` instead of sometimes `lz4` in the UI
- Enterprise plans -> Enterprise Edition so that is works for on-prem as well and not just AG

### CODE REVIEW

**Review by palashkaria — COMMENTED** [review]
LGTM!

**Comment by Simran-B** [comment]
Improve how the compression and direction gets displayed:
image

Fix the query spotlight categories to to say that edges/documents/system are collections and not show system collections under document collections (bug)
image

**Review by ansoboleva — APPROVED** [review]
LGTM

**Review by palashkaria — APPROVED** [review]
LGTM 🚀

**Pull request merged**
