### PR TITLE
[FE-51] Change help texts in new collection modal

### PR DESCRIPTION
**Pull request by ajurdak**
### Scope & Purpose

- [x] :hankey: Bugfix

### Checklist

- [x] Tests
  - [x] Manually tested

- [x] :book: CHANGELOG entry made

#### Related Information

- [x] Jira ticket: https://arangodb.atlassian.net/browse/FE-51

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by ansoboleva** [comment]
@ajurdak do you have a screenshot of how the new texts look like on the UI? Especially the larger one I suggested. Just to make sure they work well in the pop-up.

**Comment by ajurdak** [comment]
image
image

Here are the screenshots and in my opinion the changed texts work very well.

Jenkins blue except for unrelated errors.

**Review by ansoboleva — APPROVED** [review]
lgtm

**Pull request merged**
