### PR TITLE
fix shrink method in aqlitemblock

### PR DESCRIPTION
**Pull request by hkernbach**
Fixes shrink. 
Same as: https://github.com/arangodb/arangodb/pull/11121

### CODE REVIEW

**Comment by hkernbach** [comment]
Jenkins: http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/8633/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8648/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8661/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
