### PR TITLE
Documentation 2.8/cookbook integration new build script

### PR DESCRIPTION
**Pull request by Simran-B**
Build fails, missing example?

```sh
 - generating MD-Files
[38;5;8mloaded 1 / 121 docu blocks[0m
[31mFailed to locate the docublock 'databaseWaitForSync' for replacing it into the file 'Users\AdministratingArango\README.md'
 have:[0m
Traceback (most recent call last):
  File "../Scripts/generateMdFiles.py", line 578, in <module>
    walk_on_files(inDir, outDir)
  File "../Scripts/generateMdFiles.py", line 401, in walk_on_files
    findStartCode(inFileFull, outFileFull)
  File "../Scripts/generateMdFiles.py", line 423, in findStartCode
    textFile = replaceText(textFile, inFileFull, find)
  File "../Scripts/generateMdFiles.py", line 444, in replaceText
    print >> sys.stderr, WRN_COLOR + dokuBlocks[0].keys() + RESET
TypeError: cannot concatenate 'str' and 'list' objects
GNUmakefile:4: die Regel für Ziel „build-books“ scheiterte
make: *** [build-books] Fehler 1
```

### CODE REVIEW

**Comment by Simran-B** [comment]
Fixed examples problem, but Swagger file apparently not found. Couldn't build under Ubuntu (cd too many args?) and Debian (not finding OpenSSL feature?).

Important note: header.js needs to deal with new folder structure, and old links will become invalid if there are going to be two folders, `Users` and `Cookbook`. Symlink from `cookbook` to `Cookbook` already in place, but the content of `2.8` is the Users manual directly, without subfolder...

**Comment by dothebart** [comment]
@Simran-B I've fixed most of the problems, and disabled the non-working docublock reference check. If you don't know how to fix it (it probably misses some files due to path problems) I'd simply let it disabled, and merge this asap.

**Comment by Simran-B** [comment]
@dothebart There are a couple more things to be done before it can be merged IMO:

- **Check behavior of build script regarding output folder structure**
  For 3.x docs, there are 3 folders for each book + cookbook, but for 2.8, we have the contents of Users in the 2.8 folder, with an additional subfolder for the cookbook on the website. We need to keep this file structure, or make sure old links are redirected properly by the docs server. Could also be handled in the Jenkins jobs that publishes the docs I guess.
- **Adjust header.js version switcher if necessary**
  Might need to fix the logic for 2.8, or possible remove the edge case entirely if we can solve it in the docs server script with redirects.
- **Docs server script** (node-documentation)
  Make sure 2.8 docs are served the way they should, verify that redirects are working and if cookbook vs. Cookbook is handled correctly for 2.8 as well

We can work on this from Feb 6th on when the whitepaper has been released.

**Comment by dothebart** [comment]
- folder structure: we symlink Users/* up, so it shouldn't be a problem. 
 - add symlink for cookbook
 - the version switcher will try to redirect to  `http://3.0.0.3/2.8/index.html` when switching to 3.3 - so, fail here.

**Comment by dothebart** [comment]
- header switching between cookbook and mainbook, and between versions fixed. tested on strato1 - is working as expected.

**Pull request merged**
