### PR TITLE
Do not abuse TRI_ERROR_REQUEST_CANCELED in Cluster code

### PR DESCRIPTION
**Pull request by markuspf**
Introduce a special error code to signal that updating the plan on
creating a collection had a failed precondition, and maybe the
surrounding code should try again.

In particular stop abusing a pre-existing error code that has no
relation to this context.

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10476/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10479/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10506/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10549/

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
