### PR TITLE
Bug fix 3.4/little weekend fix

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7368/

**Comment by jsteemann** [comment]
@obiwahn: Wrong branch names used in Jenkins build... Please restart with correct branches

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7391/

**Comment by KVS85** [comment]
ports:

 - [ ] 3.3 -- https://github.com/arangodb/arangodb/pull/10525
 - [ ] 3.4 -- https://github.com/arangodb/arangodb/pull/10526
 - [x] 3.5 -- https://github.com/arangodb/arangodb/pull/10527
 - [x] devel -- https://github.com/arangodb/arangodb/pull/10518

**Comment by jsteemann** [comment]
Tests blue except one test failure on Windows, which looks totally unrelated.

**Comment by KVS85** [comment]
> Tests blue except one test failure on Windows, which looks totally unrelated.

`ssl_server` had false positive. Status of collection for RocksDB makes no sense.

**Pull request merged**
