### PR TITLE
Port reboot tracker catching failed and removed servers to 3.5.

### PR DESCRIPTION
**Pull request by neunhoef**

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10451/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10467/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10473/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10474/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
