### PR TITLE
Doc - macOS - Remove Graphical App, improve CLI install steps

### PR DESCRIPTION
**Pull request by Simran-B**
According to @hkernbach, we don't develop or built the so called _Graphical App_ anymore. We should thus remove it from the docs.

We might wanna describe how to install the DMG package ("double-click to mount ... drag xxx onto Application folder"?) and also update it in the snippets for the download website:

https://github.com/arangodb/oskar/blob/master/snippets/3.4/macosx.html.in

> For a standard server setup, download the Server package and
    install it using the **package manager**.

Is there even a package manager on macOS? Don't you mount, then drag'n'drop to install in case of the DMG package?

Preview:
- http://web01.arangodb.biz/documentation/install-cli-macos/Manual/Installation/MacOSX.html

### CODE REVIEW

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/305/

**Comment by sleto-it** [comment]
Putting again in wip, to take the opportunity to fix a few other things, listed below:

- "The ArangoDB Starter is not included in v3.4.0. This issue will be fixed in a later 3.4.x version.", this one can be removed now from this page - this should be fixed as far as I know

**Comment by Simran-B** [comment]
@sleto-it So was it included in (a possibly re-released) v3.4.0 or not? Was it in the 3.3.x packages? Or should we simply remove that sentence because it only affects the initial .0 release?

**Comment by sleto-it** [comment]
simran, nope, it was included in a 3.4 hotfix as far as I know, we should find out which one. @KVS85 could know
No, in 3.3 is not there, so we should document as known issue in 3.3 imho

**Pull request merged**
