### PR TITLE
Ignore not-yet created databases on other coordinators

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Ignore not-yet created databases on other coordinators when querying the list of currently running or slow AQL queries.
This prevents a "database not found" error to be potentially returned in a multi-coordinator setup when the list of slow queries is accessed/cleared directly after a new database has been created.

Multi-coordinator support for the current/slow query list access is added in 3.6.10 only, so this issue was not yet in any released version.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13133/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13406/

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
