### PR TITLE
fix snowball invocation and dependencies

### PR DESCRIPTION
**Pull request by dothebart**
This fixes the dependency chain so the snowball executeable is built before its invoked

### CODE REVIEW

**Comment by gnusi** [comment]
@dothebart please check with @Dronplane

**Comment by gnusi** [comment]
@dothebart what is the purpose of this PR?

**Comment by Dronplane** [comment]
Let me check devel build...

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4890/

**Comment by dothebart** [comment]
tests green except unrelated errors.

**Pull request merged**
