### PR TITLE
Bug fix 3.7/fix endpoints status reporting 2

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose
re-sync testsuite with devel, partial backport of https://github.com/arangodb/arangodb/pull/13113 broke this.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12946/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12947/

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
