### PR TITLE
Enabled modification nodes in spliced subqueries again

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

Enable AQL optimization rule `splice-subqueries` when modification nodes are present.

- [X] Strictly *new functionality*
- [X] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests.

### CODE REVIEW

**Comment by goedderz** [comment]
Currently, `aql-modify-cluster.js` and `aql-modify-subqueries.js` fail.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7331/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7332/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7343/

**Comment by mchacki** [comment]
Jenkins again after merge with devel:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7353/

**Pull request merged**
