### PR TITLE
Try to fix compile with gcc-11.3

### PR DESCRIPTION
**Pull request by MBkkt**
### Scope & Purpose

consteval has bugs like false positive

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1383/

**Review by Dronplane — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
This branch doesn't compile for me with g++-11.3.
```
In file included from /home/jan/Arango310NoAsan/client-tools/Export/arangoexport.cpp:48:
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h: In instantiation of ‘arangodb::ClientFeature::ClientFeature(Server&, bool, size_t, double, double) [with Server = arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >; size_t = long unsigned int]’:
/usr/include/c++/11/bits/unique_ptr.h:962:30:   required from ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = arangodb::ClientFeature; _Args = {arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >&, bool}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<arangodb::ClientFeature, std::default_delete<arangodb::ClientFeature> >]’
/home/jan/Arango310NoAsan/client-tools/Export/arangoexport.cpp:88:49:   required from here
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:67:65:   in ‘constexpr’ expansion of ‘arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >::contains<arangodb::ShellConsoleFeature>()’
/home/jan/Arango310NoAsan/lib/ApplicationFeatures/ApplicationServer.h:387:42:   in ‘constexpr’ expansion of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::contains<arangodb::ShellConsoleFeature>()’
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:70:23:   in ‘constexpr’ expansion of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::kTypes.frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::find(arangodb::ctti<arangodb::ShellConsoleFeature>())’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:127:21:   in ‘constexpr’ expansion of ‘frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::find_impl<const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >&>((*(const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >*)this), (* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:160:27:   in ‘constexpr’ expansion of ‘(& self)->frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::lookup((* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:183:23:   in ‘constexpr’ expansion of ‘frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::lookup_impl<const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >&>((*(const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >*)this), (* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:179:43:   in ‘constexpr’ expansion of ‘self.frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::tables_.frozen::bits::pmh_tables<32, frozen::elsa<frozen::basic_string<char> > >::lookup<frozen::basic_string<char> >((* & key))’
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:67:5:   in ‘constexpr’ expansion of ‘frozen::bits::seed_or_index()’
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:67:5: error: modification of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::kTypes’ is not a constant expression
   67 |     if constexpr (Server::template contains<ShellConsoleFeature>()) {
      |     ^~
In file included from /home/jan/Arango310NoAsan/client-tools/Utils/ArangoClient.h:26,
                 from /home/jan/Arango310NoAsan/client-tools/Export/arangoexport.h:27,
                 from /home/jan/Arango310NoAsan/client-tools/Export/arangoexport.cpp:24:
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h: In instantiation of ‘static constexpr size_t arangodb::TypeList<T>::id() [with U = arangodb::ShellConsoleFeature; T = {arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature}; size_t = long unsigned int]’:
/home/jan/Arango310NoAsan/lib/ApplicationFeatures/ApplicationServer.h:381:36:   required from ‘static constexpr size_t arangodb::application_features::ApplicationServerT<Features>::id() [with T = arangodb::ShellConsoleFeature; Features = arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>; size_t = long unsigned int]’
/home/jan/Arango310NoAsan/lib/ApplicationFeatures/ApplicationServer.h:394:60:   required from ‘static constexpr bool arangodb::application_features::ApplicationServerT<Features>::isCreatedAfter() [with Feature = arangodb::HttpEndpointProvider; OtherFeatures = {arangodb::ShellConsoleFeature}; Features = arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>]’
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:69:73:   required from ‘arangodb::ClientFeature::ClientFeature(Server&, bool, size_t, double, double) [with Server = arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >; size_t = long unsigned int]’
/usr/include/c++/11/bits/unique_ptr.h:962:30:   required from ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = arangodb::ClientFeature; _Args = {arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >&, bool}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<arangodb::ClientFeature, std::default_delete<arangodb::ClientFeature> >]’
/home/jan/Arango310NoAsan/client-tools/Export/arangoexport.cpp:88:49:   required from here
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:75:30: error: non-constant condition for static assertion
   75 |     static_assert(contains<U>(), "Type not found");
      |                   ~~~~~~~~~~~^~
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:75:30:   in ‘constexpr’ expansion of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::contains<arangodb::ShellConsoleFeature>()’
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:70:23:   in ‘constexpr’ expansion of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::kTypes.frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::find(arangodb::ctti<arangodb::ShellConsoleFeature>())’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:127:21:   in ‘constexpr’ expansion of ‘frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::find_impl<const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >&>((*(const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >*)this), (* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:160:27:   in ‘constexpr’ expansion of ‘(& self)->frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::lookup((* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:183:23:   in ‘constexpr’ expansion of ‘frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::lookup_impl<const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >&>((*(const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >*)this), (* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:179:43:   in ‘constexpr’ expansion of ‘self.frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::tables_.frozen::bits::pmh_tables<32, frozen::elsa<frozen::basic_string<char> > >::lookup<frozen::basic_string<char> >((* & key))’
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:75:30:   in ‘constexpr’ expansion of ‘frozen::bits::seed_or_index()’
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:75:30: error: modification of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::kTypes’ is not a constant expression
In file included from /home/jan/Arango310NoAsan/client-tools/Export/arangoexport.cpp:48:
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h: In instantiation of ‘arangodb::ClientFeature::ClientFeature(Server&, bool, size_t, double, double) [with Server = arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >; size_t = long unsigned int]’:
/usr/include/c++/11/bits/unique_ptr.h:962:30:   required from ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = arangodb::ClientFeature; _Args = {arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >&, bool}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<arangodb::ClientFeature, std::default_delete<arangodb::ClientFeature> >]’
/home/jan/Arango310NoAsan/client-tools/Export/arangoexport.cpp:88:49:   required from here
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:69:73: error: non-constant condition for static assertion
   68 |       static_assert(Server::template isCreatedAfter<HttpEndpointProvider,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   69 |                                                     ShellConsoleFeature>());
      |                                                     ~~~~~~~~~~~~~~~~~~~~^~
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:69:73:   in ‘constexpr’ expansion of ‘arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >::isCreatedAfter<arangodb::HttpEndpointProvider, arangodb::ShellConsoleFeature>()’
/home/jan/Arango310NoAsan/lib/ApplicationFeatures/ApplicationServer.h:394:60:   in ‘constexpr’ expansion of ‘arangodb::application_features::ApplicationServerT<arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature> >::id<arangodb::ShellConsoleFeature>()’
/home/jan/Arango310NoAsan/lib/ApplicationFeatures/ApplicationServer.h:381:36:   in ‘constexpr’ expansion of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::id<arangodb::ShellConsoleFeature>()’
/home/jan/Arango310NoAsan/lib/Basics/TypeList.h:76:23:   in ‘constexpr’ expansion of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, arangodb::application_features::BasicFeaturePhaseClient, arangodb::TempFeature, arangodb::ExportFeature>::kTypes.frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::find(arangodb::ctti<arangodb::ShellConsoleFeature>())’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:127:21:   in ‘constexpr’ expansion of ‘frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::find_impl<const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >&>((*(const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >*)this), (* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:160:27:   in ‘constexpr’ expansion of ‘(& self)->frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::lookup((* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:183:23:   in ‘constexpr’ expansion of ‘frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::lookup_impl<const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >&>((*(const frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >*)this), (* & key))’
/home/jan/Arango310NoAsan/3rdParty/iresearch/external/frozen/include/frozen/unordered_map.h:179:43:   in ‘constexpr’ expansion of ‘self.frozen::unordered_map<frozen::basic_string<char>, long unsigned int, 15, frozen::elsa<frozen::basic_string<char> >, std::equal_to<frozen::basic_string<char> > >::tables_.frozen::bits::pmh_tables<32, frozen::elsa<frozen::basic_string<char> > >::lookup<frozen::basic_string<char> >((* & key))’
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:69:73:   in ‘constexpr’ expansion of ‘frozen::bits::seed_or_index()’
/home/jan/Arango310NoAsan/client-tools/Shell/ClientFeature.h:69:73: error: modification of ‘arangodb::TypeList<arangodb::application_features::CommunicationFeaturePhase, arangodb::application_features::GreetingsFeaturePhase, arangodb::VersionFeature, arangodb::HttpEndpointProvider, arangodb::ConfigFeature, arangodb::FileSystemFeature, arangodb::LoggerFeature, arangodb::RandomFeature, arangodb::ShellColorsFeature, arangodb::ShutdownFeature, arangodb::SslFeature, arangodb::EncryptionFeature, ara
```

**Review by jsteemann — CHANGES_REQUESTED** [review]
Does not work for me :crying_cat_face:

**Pull request closed without merging**
