### PR TITLE
Bug in behavior of ignoreRevs=false

### PR DESCRIPTION
**Pull request by neunhoef**
### Scope & Purpose

There is a small bug in the implementation of our API. If one updates
(or replaces) a single document and gives the key only in the URL
but not in the body of the document, and also adds the option 
`ignoreRevs=false` and specifies the `_rev` in the body, then this
rev is silently rewritten to 0 due to a bug.

This PR fixes this bug. Also see #13232.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [x] Backports required for: 3.7, 3.6

### Testing & Verification

*(Please pick either of the following options)*

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13688/

**Review by fceller — APPROVED** [review]

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13702/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13709/

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
