### PR TITLE
[3.4] back port of agency call back cleanup

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5711/

**Comment by kvahed** [comment]
image

**Comment by neunhoef** [comment]
Unfortunately, the API is published, so we cannot leave out the changed entries, please revert.

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5819/

**Pull request merged**
