### PR TITLE
Forbid subqueries in PRUNE in additional cases

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

Subqueries cannot work in PRUNE and should be forbidden (see #10232/#10231/#10266). However, one case of subqueries was missing in the grammar.

- [X] :hankey: Bugfix 
- [x] :book: CHANGELOG entry made
- [X] :muscle: The behavior in this PR was *manually tested*
- [X] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [X] Backport for *3.7*: https://github.com/arangodb/arangodb/pull/12586
- [X] Backport for *3.6*: https://github.com/arangodb/arangodb/pull/12587
- [X] Backport for *3.5*: https://github.com/arangodb/arangodb/pull/12588

#### Related Information

- [X] GitHub issue: #12372

### Testing & Verification

- [X] This PR adds tests that were used to verify all changes:
- [X] Added **Regression Tests**

### Documentation

- [x] Added a *Changelog Entry*

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11680/

**Review by mchacki — CHANGES_REQUESTED** [review]
In general LGTM.

However I think we are required to commit the generated grammar files, otherwise the non-maintainer version will not contain this bug-fix.

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11714/

**Comment by goedderz** [comment]
image

**Review by mchacki — APPROVED** [review]
LGTM!

**Review by jsteemann — APPROVED** [review]

**Pull request merged**
