### PR TITLE
Measure time a request takes to get executed by the scheduler

### PR DESCRIPTION
**Pull request by goedderz**

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4815/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4895/

**Comment by goedderz** [comment]
Jenkins looks fine.

**Comment by markuspf** [comment]
Oh, and when you say "jenkins looks fine" you mean the test failure is known not to be related to this change?

**Comment by goedderz** [comment]
> Where will this measurement show up?
If you increase the loglevel of `Logger::REQUESTS` to at least `TRACE`, they show up in the logs for every HTTP or Vst Request.
> Is this measuring the time between a request being queued and being executed?
Exactly, so we can see e.g. when we're waiting a long time on the scheduler's queue.
> Oh, and when you say "jenkins looks fine" you mean the test failure is known not to be related to this change?
Yes, those two are shutdown failures.

**Pull request merged**
