### PR TITLE
[3.5] agency fixes for node delete from devel

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7667/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7826/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7832/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
