### PR TITLE
[3.4] Note that ArangoSearch views cannot be used as edge collections in traversals

### PR DESCRIPTION
**Pull request by goedderz**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2957/

### CODE REVIEW

**Comment by sleto-it** [comment]
Hi,

Thanks for this PR. A few comments:

- @Simran-B should we also consider (in addition to the changes made already in this PR) a new "Limitations" page as subpage of https://docs.arangodb.com/3.4/Manual/Views/ArangoSearch/? I believe it might be useful to list all the limitations of ArangoSearch in a single page. If you agree and this is not handled in this PR, please could you create an issue in planning?

- should we quickly enhance this PR adding a "warning" box (in the text Tobias wrote)?

Thanks,

**Comment by Simran-B** [comment]
Counter question: Do people expect Views to act like edge collections? For me that seems a bit far fetched. Thus I wonder how much we need to emphasize that you can't treat them like edge collections.

**Comment by mchacki** [comment]
Ok shall i merge or not?
It seems someone has used a View as an EdgeCollection in the Traversal, so i think we need to at least write it down.

**Comment by Simran-B** [comment]
Feel free to merge it. If we change our mind and want to emphasize is more then we can add hint boxes in another PR. For now, it is more important to have this statement in the docs rather than not.

**Pull request merged**
