### PR TITLE
Bug fix/test shell skiplist rm performance

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7430/

**Comment by ObiWahn** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7438/

**Comment by jsteemann** [comment]
IMHO the only valid "fix" for this test is to remove it entirely.
It tests deletion performance for the skiplist index, but the performance is influenced by the overall load on the system. If we run it in our test environment, **anything** can happen at the same time, including other tests going wild, the disk being maxed out etc.
If we don't run this test in full isolation, the performance will be unpredictable.
Let's remove it.

**Comment by ObiWahn** [comment]
https://github.com/arangodb/planning/issues/4682

**Pull request merged**
