### PR TITLE
add multiple coordinator support

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

This adds the ability to pass multiple coordinators into arangojs tests.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

https://github.com/arangodb/arangojs/issues/699

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue: https://github.com/arangodb/arangojs/issues/699
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This is an addition to the testing framework

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12916/

**Review by pluma — APPROVED** [review]
lgtm, but keep in mind that if `arangod.url` is not in the same IP format as the agency returns, arangojs may accidentally add duplicates when it fetches the list of coordinators from the first server.

**Comment by dothebart** [comment]
tests blue.

**Comment by dothebart** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12953/

**Pull request merged**
