### PR TITLE
change "parameters" to "bindVars"

### PR DESCRIPTION
**Pull request by baslr**
===>>>> DO **NOT** MERGE! <<<< ===

match v8 and rest calls response

### CODE REVIEW

**Comment by fceller** [comment]
@baslr to be backward compatible can you add both parameters and bindVars?

**Comment by fceller** [comment]
Is there a documentation update?

**Comment by baslr** [comment]
its possible. This function is not documented at all.

**Comment by fceller** [comment]
Then just mark `parameters` as deprecated in the source code.

**Comment by fceller** [comment]
LGTM

**Pull request merged**
