### PR TITLE
[3.7] Bug fix/fix agency comm result swallowing errors

### PR DESCRIPTION
**Pull request by goedderz**
Conservative backport of #11892, with smaller and less intrusive changes.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10556/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10569/

**Comment by jsteemann** [comment]
Yet another PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10574/

**Comment by jsteemann** [comment]
And another one:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10575/

**Comment by KVS85** [comment]
All PRs failed in Windows part with 2 problems:
- catch suite stucked at
```
[----------] 14 tests from AsyncAgencyCommTest
[ RUN      ] AsyncAgencyCommTest.send_with_failover
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
2020-06-19T12:25:48Z [8076] ERROR {agencycomm} Error transforming result: Expecting item
...
```
- ArangoDB wasn't able to start in active_failover suite

**Comment by goedderz** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10579/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
