### PR TITLE
(K_)SHORTEST PATHS: Display correct directions in explainer/profiler

### PR DESCRIPTION
**Pull request by markuspf**
This is a reincarnation of #9049. Lets make sure Jenkins is happy this time.

### CODE REVIEW

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4586/

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux/6153/

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux/6203/

**Comment by mchacki** [comment]
Ok jenkins failures unrelated, known, one already fixed by other PR.

**Pull request merged**
