### PR TITLE
Active Failover upgrade guide, missing maintenance API docs

### PR DESCRIPTION
**Pull request by graetzer**
Internal Ref:

- https://github.com/arangodb/planning/issues/2427

### CODE REVIEW

**Comment by jsteemann** [comment]
Need this PR for devel as well once approved by @sleto-it

**Comment by jsteemann** [comment]
@sleto-it: looks ok from my point of view. can we merge this?

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/98/

**Comment by graetzer** [comment]
@sleto-it build is green, can we merge this ?

**Comment by sleto-it** [comment]
Almost there @graetzer . I will

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/102/

**Pull request merged**
