### PR TITLE
Bug fix 3.4/fix internal issue 4451

### PR DESCRIPTION
**Pull request by hkernbach**
Same as: https://github.com/arangodb/arangodb/pull/10538

### CODE REVIEW

**Comment by hkernbach** [comment]
Jenkins: http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7381/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7406/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7510/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7561/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
