### PR TITLE
tests modification limits

### PR DESCRIPTION
**Pull request by ObiWahn**
add test only

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8047/

**Comment by ObiWahn** [comment]
@mchacki , @markuspf I have added you because team-gordo has rewritten the modification code and you have probably the best overview of what needs to be done.

**Comment by markuspf** [comment]
I'd like to nominate @graetzer as using `{optimizer: {rules: ["-parallelize-gather"]}}` as options for the queries makes the failures go away. Thanks to @mchacki for suggesting to try that one first.

**Comment by jsteemann** [comment]
The `parallelize-gather` rule should only have an effect on UPDATE/REPLACE/REMOVE, but not on INSERT. And for UPDATE/REPLACE/REMOVE queries with a LIMIT, I expected the parallelize-gather rule to not fire...

**Comment by markuspf** [comment]
The `INSERT` test in this PR does not fail for me, only `REMOVE` and `UPDATE` 

For `UPDATE` (and `REMOVE` as well)
```
[::1]:8530@_system> db._explain(`FOR doc IN ${cn1} FILTER doc.valueMod < 10 UPDATE doc WITH { modified : true } IN ${cn1} LIMIT ${modify_docs} RETURN 0`, {}, {optimizer: {rules: [""]}});
Query String (136 chars, cacheable: false):
 FOR doc IN UnitTestsClusterLimit FILTER doc.valueMod < 10 UPDATE doc WITH { modified : true } IN 
 UnitTestsClusterLimit LIMIT 50 RETURN 0

Execution plan:
 Id   NodeType                  Site  Est.   Comment
  1   SingletonNode             DBS      1   * ROOT
  5   CalculationNode           DBS      1     - LET #5 = { "modified" : true }   /* json expression */   /* const assignment */
  2   EnumerateCollectionNode   DBS   1000     - FOR doc IN UnitTestsClusterLimit   /* full collection scan, projections: `_key`, `valueMod`, 5 shard(s) */   FILTER (doc.`valueMod` < 10)   /* early pruning */
  6   UpdateNode                DBS   1000       - UPDATE doc WITH #5 IN UnitTestsClusterLimit 
 12   RemoteNode                COOR  1000       - REMOTE
 13   GatherNode                COOR  1000       - GATHER   /* parallel */
  7   LimitNode                 COOR    50       - LIMIT 0, 50
  8   CalculationNode           COOR    50       - LET #7 = 0   /* json expression */   /* const assignment */
  9   ReturnNode                COOR    50       - RETURN #7

Indexes used:
 By   Name      Type      Collection              Unique   Sparse   Selectivity   Fields       Ranges
  6   primary   primary   UnitTestsClusterLimit   true     false       100.00 %   [ `_key` ]   doc

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-data-modification-out-variables
  3   patch-update-statements
  4   distribute-in-cluster
  5   scatter-in-cluster
  6   distribute-filtercalc-to-cluster
  7   remove-unnecessary-remote-scatter
  8   undistribute-remove-after-enum-coll
  9   reduce-extraction-to-projection
 10   move-filters-into-enumerate
 11   parallelize-gather

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
 exclusive                false
 overwrite                false
 ignoreRevs               true
```

**Comment by ObiWahn** [comment]
@mchacki has this been fixed in a different PR?

**Comment by mchacki** [comment]
@ObiWahn we have this in the Subquery Optimization branch, which is not merged back yet.
I will review this test and include it into the branch.

**Pull request closed without merging**
