### PR TITLE
Put the write into the IoContext.

### PR DESCRIPTION
**Pull request by maierlars**
Follow up to https://github.com/arangodb/arangodb/pull/10474

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7337/

**Comment by graetzer** [comment]
This is gonna make things slow

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7349/

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7352/

**Comment by neunhoef** [comment]
The problem is that we have correctness problems with SSL and VST and many concurrent requests. The code as it currently is is broken with SSL. In view of the feature freeze and the start of QA testing, let's merge this now and do more performance investigations next week.

**Pull request merged**
