### PR TITLE
FE-386 | Fix cross render issue with collection Info and Content tab switching

### PR DESCRIPTION
**Pull request by nikhil-varma**
Backport for #20176

### CODE REVIEW

**Review by palashkaria — APPROVED** [review]
LGTM

**Review by shd8 — APPROVED** [review]
LGTM

**Review by palashkaria — APPROVED** [review]
LGTM!

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-ANY-jslint/31254/

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
