### PR TITLE
Index the result array for streaming cursor

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

This PR changes (for VelocyPack based protocols) the `result` field of cursors with `stream: true` from an unindexed to an indexed array. This is already the case for non-streaming cursors. The Java driver (as of v6.9.0) accesses those entries with linear runtime each, resulting in degraded performance as reported in #13476. The Java driver will be fixed in an upcoming version, too: https://github.com/arangodb/arangodb-java-driver/commit/5c8324aa5d62f5e468e8b0e2dd0fe8c60e243172

- [X] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [X] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [X] GitHub issue / Jira ticket number: #13476
- [ ] Design document: 
Related fix in the Java driver: https://github.com/arangodb/arangodb-java-driver/commit/5c8324aa5d62f5e468e8b0e2dd0fe8c60e243172

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### CODE REVIEW

**Comment by jsteemann** [comment]
I am generally happy with the change in this PR, but I think we should fix the Java driver as well, so that it does a linear scan over the result.

**Comment by goedderz** [comment]
> I am generally happy with the change in this PR, but I think we should fix the Java driver as well, so that it does a linear scan over the result.

Yes, @rashtao is already looking into whether this is feasible.

**Comment by rashtao** [comment]
Java driver fixed: https://github.com/arangodb/arangodb-java-driver/commit/5c8324aa5d62f5e468e8b0e2dd0fe8c60e243172

**Comment by goedderz** [comment]
Closing in favor of the following distinct(!) PRs:

* https://github.com/arangodb/arangodb/pull/13620 (for devel) and
* https://github.com/arangodb/arangodb/pull/13621 (for 3.7).

**Pull request closed without merging**
