### PR TITLE
BTS-766 | Docs: Add DocuBlock for PUT /_api/collection/<coll>/compact

### PR DESCRIPTION
**Pull request by Simran-B**
### Scope & Purpose

Add missing description for endpoint.

Interesting find: it only requires read access for both database and collection to trigger the compaction. Is that intentional?

### Checklist

- [x] :books: documentation written
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

- [x] Docs PR: https://github.com/arangodb/docs/pull/894
- [x] GitHub issue / Jira ticket: BTS-766

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Review by dothebart — APPROVED** [review]

**Comment by ansoboleva** [comment]
@Simran-B was it verified by jenkins?

**Comment by Simran-B** [comment]
Yes, all verified (and 3.10 examples committed to https://github.com/arangodb/docs/pull/894 but we will to redo that before merge)
✔️ 3.10 https://jenkins.arangodb.biz:3456/view/Documentation/job/arangodb-ANY-examples/1607/
✔️  3.9 https://jenkins.arangodb.biz:3456/view/Documentation/job/arangodb-ANY-examples/1634/
✔️ 3.8 https://jenkins.arangodb.biz:3456/view/Documentation/job/arangodb-ANY-examples/1634/

**Review by ansoboleva — APPROVED** [review]
reviewed

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
