### PR TITLE
Bug fix 3.7/oasis 409

### PR DESCRIPTION
**Pull request by Dronplane**
Backport for OASIS-409 fix 

https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13458/

Enterprise PR:https://github.com/arangodb/enterprise/pull/632

### CODE REVIEW

**Comment by Dronplane** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13538/

**Comment by Dronplane** [comment]
Tests blue

**Comment by Dronplane** [comment]
With arangosearch cluster recovery tests: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13542/

**Comment by Dronplane** [comment]
Also blue

**Comment by Dronplane** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13681/

**Comment by Dronplane** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13685/

**Comment by KVS85** [comment]
Tests blue except unrelated known failure.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
