### PR TITLE
[DOC-59] Bug fix/js api forward ttl cursor option

### PR DESCRIPTION
**Pull request by Simran-B**
### Scope & Purpose

Forward the `ttl` cursor option for AQL queries in the JavaScript API from the `db._query()` and `db._createStatement()` methods to the server.

Tested in arangosh:
```
c = db._query("FOR i IN 1..2000 RETURN i", { }, { ttl: 0.00001 }); for (let i=0; i<2000; i++) { c.next(); }

JavaScript exception in file '/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arangosh.js' at 93,7: ArangoError 1600: cursor not found
!      throw error;
!      ^
stacktrace: ArangoError: cursor not found
    at Object.exports.checkRequestResult (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arangosh.js:91:21)
    at ArangoQueryCursor.next (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arango-query-cursor.js:222:16)
    at <shell command>:1:85
```

arangod --console does not show the same behavior. I'm not sure if my code is incorrectly forwarding the option or if no timeout occurs simply because running inside the server fetches the cursor so quickly that the timeout doesn't occur.

- [x] :hankey: Bugfix

### Checklist

- [x] Tests
  - [x] **Regression tests**
  - [ ] C++ **Unit tests**
  - [x] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [x] Backports ?
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/DOC-59
- [ ] Design document:

### CODE REVIEW

**Comment by jsteemann** [comment]
> arangod --console does not show the same behavior. I'm not sure if my code is incorrectly forwarding the option or if no timeout occurs simply because running inside the server fetches the cursor so quickly that the timeout doesn't occur.

This is because when running stuff in the server's console, it doesn't create a cursor at all. The entire query result is returned the calling function at once, without a cursor.

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by Simran-B** [comment]
> The entire query result is returned to the calling function at once

Is that the reason why `batchSize` isn't handled in the server module but is in the client module? Seems like we shouldn't add code for `ttl` if there isn't even a cursor?

There do appear to be cursors for the `stream: true` case guessing by the name (`ArangoQueryStreamCursor`) - or is it misleading?

**Comment by jsteemann** [comment]
> > The entire query result is returned to the calling function at once
> 
> Is that the reason why `batchSize` isn't handled in the server module but is in the client module? Seems like we shouldn't add code for `ttl` if there isn't even a cursor?

For the client (arangosh) side, we should definitely add the ttl code, because it was previously missing and is useful to have.
For non-streaming queries on the server side, the ttl will be ignored. For streaming queries, it will likely be used, so it is useful to add ttl code on the server side as well.

> There do appear to be cursors for the `stream: true` case guessing by the name (`ArangoQueryStreamCursor`) - or is it misleading?

Yes, for streaming cursors, the ttl is likely useful on the server side as well, so let's add the ttl code on the server side as well!

**Comment by Simran-B** [comment]
Removed the server module changes and created https://arangodb.atlassian.net/browse/BTS-1297 about the `cursor is busy` error in case of a streaming cursor expiring due to TTL. Turned some tests into client-side tests.

**Comment by Simran-B** [comment]
arangodb-matrix-pr-linux.x86-64 for community cluster was red, but the new tests passed:

```
2023-04-05T10:54:34.495Z [============] localArangosh: Trying tests/js/client/shell/shell-query.js ... 

2023-04-05T10:54:34.499Z [------------] 2 tests from QuerySuite (setUpAll: 0ms)
2023-04-05T10:54:34.499Z [ RUN        ] testQueryOptionsTtlError
2023-04-05T10:54:34.503Z [     PASSED ] testQueryOptionsTtlError (setUp: 0ms, test: 4ms, tearDown: 0ms)
2023-04-05T10:54:34.503Z [ RUN        ] testQueryOptionsObjectTtlError
2023-04-05T10:54:34.505Z [     PASSED ] testQueryOptionsObjectTtlError (setUp: 0ms, test: 2ms, tearDown: 0ms)
2023-04-05T10:54:34.505Z [------------] 2 tests from QuerySuite ran (tearDownAll: 0ms)
2023-04-05T10:54:34.505Z [   PASSED   ] 2 tests.
2023-04-05T10:54:34.505Z [============] Ran: 2 tests (2 passed, 0 failed) (6ms total)
```

```
2023-04-05T10:55:21.649Z [============] localArangosh: Trying tests/js/client/shell/shell-statement.js ... 

...

2023-04-05T10:55:21.678Z [ RUN        ] testConstructWithOptions
2023-04-05T10:55:21.678Z [     PASSED ] testConstructWithOptions (setUp: 0ms, test: 0ms, tearDown: 0ms)
2023-04-05T10:55:21.678Z [ RUN        ] testExecuteOptionsTtlError
2023-04-05T10:55:21.682Z [     PASSED ] testExecuteOptionsTtlError (setUp: 0ms, test: 4ms, tearDown: 0ms)
2023-04-05T10:55:21.682Z [------------] 6 tests from StatementStreamSuite ran (tearDownAll: 0ms)
2023-04-05T10:55:21.682Z [   PASSED   ] 6 tests.
2023-04-05T10:55:21.683Z [============] Ran: 10 tests (10 passed, 0 failed) (19ms total)
```

arangodb-matrix-pr-linux.aarch64 community cluster failed, apparently because github.com could not be resolved.
Enterprise cluster had some unrelated test failures, but the new tests were completed successfully like above.

arangodb-matrix-pr-windows community cluster also had some unrelated test failures, but the new tests were completed successfully like above.

**Pull request merged**
