### PR TITLE
[3.7] Persist count changes from recovery to avoid lost updates 

### PR DESCRIPTION
**Pull request by danielhlarkin**
Port of https://github.com/arangodb/arangodb/pull/12864 with some additional fixes for revision trees

### CODE REVIEW

**Comment by danielhlarkin** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12342/

**Comment by KVS85** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12350/

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/12364/

**Review by jsteemann — APPROVED** [review]

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
