### PR TITLE
Doc - Add RocksDB IOPS program options 

### PR DESCRIPTION
**Pull request by Simran-B**
Introduced in #8492, but missing in option dump

### CODE REVIEW

**Comment by Simran-B** [comment]
@matthewvon Should we also mention these options elsewhere, e.g. Troubleshooting?

**Comment by matthewvon** [comment]
Troubleshooting:  Yes.  I am not familiar with that portion of the documentation.  Want to point there?

**Comment by matthewvon** [comment]
Same low IOPS impacts import via api commands.  Our arangoimport command line has been fixed for the problem.  Thinking there might need to be a "warnings for cheap VMs" section.

**Comment by Simran-B** [comment]
Could use some love:
https://docs.arangodb.com/3.4/Manual/Troubleshooting/

Would be great to turn this chapter into a proper guide for users. Related planning issue which I also updated: https://github.com/arangodb/planning/issues/3599

**Comment by Simran-B** [comment]
Merging for now so that we can publish v3.4.5 docs with these options included

**Pull request merged**
