### PR TITLE
Bug fix/cleanup register planning

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Clean up the AQL register planning code a bit, and simplify APIs a bit.

- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *scripts/unittest shell_server_aql, scripts/unittest catch*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9164/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9167/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9168/

**Comment by mpoeter** [comment]
Just out of curiosity - why do you sort the RegisterId vectors? I did not see anything that relies on the order (though I could have easily missed that).

**Comment by jsteemann** [comment]
You are right, nothing reies on the order of the registers in the vector.
However, I am sorting them so when we walk over them we will be accessing registers in ascending order. Often, when a register is accessed its underlying data is accessed as well. If we don't access registers in random order but in ascending order, we may benefit from cache prefetching, at least in theory. Though I doubt this will have a great effect in reality.

**Comment by jsteemann** [comment]
Obsoleted by https://github.com/arangodb/arangodb/pull/11385

**Pull request closed without merging**
