### PR TITLE
Bug fix 3.7/bts 169

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix BTS-169: Cost estimation for LIMIT nodes was wrong
https://arangodb.atlassian.net/browse/BTS-169
Backport of https://github.com/arangodb/arangodb/pull/12491

This is a cosmetic change, but should not have any effect on execution plans other than fixing the number of estimated items.

- [x] :hankey: Bugfix 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [ ] No backports required
- [x] Backports required for: 3.7

#### Related Information

- [x] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-169

### Testing & Verification

- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added **Regression Tests**
  - [ ] Added new C++ **Unit Tests**
  - [x] Added new **integration tests** 
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11582/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11629/

**Review by gnusi — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11631/

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
