### PR TITLE
unttled supervision maintenance

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7874/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8405/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8414/

**Comment by jsteemann** [comment]
Jenkins run failed with compile errors:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8414/

```
/work/ArangoDB/arangod/Agency/Supervision.cpp:317:124: error: invalid operands of types 'const char [110]' and 'const char*' to binary 'operator+'
  317 |         << "Supervision maintenace key in agency is not a string. This should never happen and will prevent hot backups. " + e.what();
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~
      |            |                                                                                                                       |
      |            const char [110]                                                                                                        const char*
/work/ArangoDB/arangod/Agency/Supervision.cpp: In member function 'virtual void arangodb::consensus::Supervision::run()':
/work/ArangoDB/arangod/Agency/Supervision.cpp:927:134: error: invalid operands of types 'const char [110]' and 'const char*' to binary 'operator+'
  927 |                   << "Supervision maintenace key in agency is not a string. This should never happen and will prevent hot backups. " + e.what();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~
      |                      |                                                                                                                       |
      |                      const char [110]                                                                                                        const char*
```

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8580/

**Comment by kvahed** [comment]
image

**Pull request merged**
