### PR TITLE
remove define that slows down Windows debug builds

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Remove a define that slows down Windows debug builds considerably.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behaviour change can only be verified via automatic tests

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4598/

### CODE REVIEW

**Comment by Dronplane** [comment]
BTW: the other hot point in Debug binary  on windows is inside "debug iterators". This behavior is controlled by _ITERATOR_DEBUG_LEVEL macro. Default value for debug build is 2  (Enables Debug iterators).
The complex part is that this setting should be changed across whole solution, including V8 binaries, which are not using defines from CMake (where we could add to CMAKE_CXX_FLAGS_DEBUG value -D_ITERATOR_DEBUG_LEVEL=1 )

**Comment by jsteemann** [comment]
@Dronplane : ok, good point.
It sounds like "fixing" the debug iterators requires a bit more work, so let's address this in a separate PR. Feel free to open one if you have a solution in mind already.
In the meantime, we can still review and merge this PR here to get its benefits.

**Comment by jsteemann** [comment]
Tests completely blue.

**Comment by dothebart** [comment]
@Dronplane I tried to only disable that, however, one needs to modify V8 so it also does that, else it doesn't work (breaks on linking)

**Pull request merged**
