### PR TITLE
MAFA - make AQL fast again

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This PR aims to improve the performance of some internal AQL operations, by pulling off a few dirty hacks.
This is work in progress.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *shell_server_aql*.

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10202/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10230/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10236/

**Comment by markuspf** [comment]
This looks like multiple pull-requests to me; it makes chages to (at least)

 * velocypack (which technically is a third party library, shouldn't these changes happen there?)
 * `AqlValue`
 * `AqlItemRows`
 * The implementation of ExecutionBlocks
 * Modification executors
 * Expressions
 * Functions

and it is not clear to me whether they are connected, and if they actually *need* to be in one PR which subsequently touches 45 files.

I also do not understand most of the microoptimisations, or don't get the justification for them, not to speak of whether there are changes to what the code does. With so many changes going on in this PR, it is really hard to review (or say anything about its ok-ness).

There is also no evidence that this PR achieves what it claims to do; does it make AQL execution faster? If so by how much? How was it measured?

**Comment by jsteemann** [comment]
velocypack library changes need to go into the velocypack repository _as well_, but they also need to go to arangodb/arangodb, as the two repos are not connected automatically by some magic.

Justification:
I found a lot of code that is very happy about memory allocations and otherwise redundant operations.
Normally this is not a good thing in code parts that are supposed to run very often (like AqlValue.*, AqlItem*, Modification*). So I fixed it.

A bit of the changes is covered by our performance tests, which I ran:
http://172.16.10.101:8080/view/Performance/job/arangodb-simple-performance--result-15days/

Many of the changes are not covered by these tests (e.g. the changes to Modification*). But I strongly doubt that saving memory allocations will make things worse.

I am happy to split this into smaller PRs if that's easier to grasp.

**Comment by jsteemann** [comment]
Closed in favor of smaller PRs

**Pull request closed without merging**
