### PR TITLE
remove wrong assertion that can ruin agency startup in maintainer mode

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Remove an invalid assertion that sporadically triggered at agency startup in maintenance mode only.
The assertion has been removed in 3.7 and devel for a while already.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12106/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue except unrelated timeout.

**Review by kvahed — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13742/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
