### PR TITLE
removeFollower orbits

### PR DESCRIPTION
**Pull request by neunhoef**
This addresses a problem with removeFollower jobs. Under certain
circumstances, these jobs are constantly created and immediately
aborted again.

The situation, in which this can happen, is the following:

In this case, the Plan as four servers ["A", "B", "C", "D"], of which
`"D"` is FAILED, Current has ["A", "B", "D"], that is, the FAILED server
is still officially "in sync".

Therefore, apparentRF is 4, actualRF is 3 and inSyncRF counts as 3,
too. Thus the removeFollower job is scheduled. When it runs, it notices
that one of the in-sync followers is actually FAILED and aborts. And
so the cycle restarts. This is easy to fix, we count only non-FAILED
followers for inSyncRF.

Furthermore, in such situations it can currently happen that all
dbservers are eventually configured as followers. This PR limits
the additional servers to 2 more than the replicationFactor.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13487/

**Review by kvahed — APPROVED** [review]
LGTM

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13488/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13571/
new run with completed tests.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13577/
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13578/
one without a clang11 compilation fix and one with it.

**Review by kvahed — APPROVED** [review]
LGTM

**Pull request merged**
