### PR TITLE
[3.7] hot backup agency locks client

### PR DESCRIPTION
**Pull request by kvahed**
Solves OASIS-252

### CODE REVIEW

**Comment by kvahed** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10891/

**Comment by KVS85** [comment]
@kvahed please fix `AsyncAgencyCommTest` (http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-mac-onlycatch/8482/EDITION=community,limit=mac/artifact/testfailures.txt).

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10929/

**Comment by kvahed** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10935/

**Comment by kvahed** [comment]
image

**Comment by kvahed** [comment]
> @kvahed please fix `AsyncAgencyCommTest` (http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-mac-onlycatch/8482/EDITION=community,limit=mac/artifact/testfailures.txt).

done

**Pull request merged**
