### PR TITLE
added load-balancing support for several query-related APIs

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Add proper load-balancing support to the "list current queries" and "list slow queries" APIs.

This is a backport of PR https://github.com/arangodb/arangodb/pull/10997, which was merged into 3.7 and devel about 10 months ago.

---

In addition, added support for fetching the list of currently running and slow AQL queries from all databases at once, by adding an `all` parameter to the following query APIs:

* `require("@arangodb/aql/queries").current({ all: true })`: will return the currently running queries from all databases, not just the currently selected database.
* HTTP GET `/_api/query/current?all=true`: same, but for the HTTP REST API.
* `require("@arangodb/aql/queries").slow({ all: true })`: will return the slow query history from all databases, not just the currently selected database.
* HTTP GET `/_api/query/slow?all=true`: same, but for the HTTP REST API.
* `require("@arangodb/aql/queries").clearSlow({ all: true })`: will clear the slow query history for all databases, not just the currently selected database.
* HTTP DELETE `/_api/query/slow?all=true`: same, but for the HTTP REST API.

Using the `all` parameter is only allowed when making the call inside the `_system` database and with superuser privileges.

This is a backport of https://github.com/arangodb/arangodb/pull/13087/

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *shell_client, shell_server*.
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (e.g. load_balancing, shell_client, server_permissions)

Link to Jenkins PR run: 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12867/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Review by fceller — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12876/

**Comment by KVS85** [comment]
Tests blue except unrelated failure.

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
