### PR TITLE
[3.6] Fix AQL cost estimate for spliced subqueries

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #13119

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12930/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12938/

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13062/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13068/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
