### PR TITLE
UI: Add Drivers & Integrations column + fix links for 3.4

### PR DESCRIPTION
**Pull request by maxkernbach**
new UI support tab:

image

### CODE REVIEW

**Comment by Simran-B** [comment]
Would need to be something like:
- if version contains "devel" (e.g. 3.5.0.devel) --> devel
- else (e.g. 3.3.14) --> major.minor

Can this be done in the grunt script for the web UI?

**Comment by sleto-it** [comment]
@maxkernbach @hkernbach - just wondering if we can progress this more taking into account @jsteemann 's comment - so we can then merge

**Comment by Simran-B** [comment]
@maxkernbach LGTM, tested with devel branch

**Comment by sleto-it** [comment]
okay - seems we are all set now. I am removing that "ongoing discussion" label

**Pull request merged**
