### PR TITLE
[3.4] Fix Buffer methods

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?) 

**devel version**: https://github.com/arangodb/arangodb/pull/9070

#### Related Information

- This issue was reported via the ArangoDB community slack

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [x] Added **Regression Tests** (Only for bug-fixes) 

~~http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4579/~~

http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4584/

### Documentation

- [x] Added a *Changelog Entry*

### CODE REVIEW

**Comment by pluma** [comment]
New build because the old one uncovered a test failure. See devel version of this PR for details.

**Comment by mchacki** [comment]
Jenkins expired before i could check:
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4670/

**Comment by pluma** [comment]
@mchacki I've recreated the build: http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4741/

**Comment by pluma** [comment]
Closed in favor of a new backport pending #9229.

**Pull request closed without merging**
