### PR TITLE
[3.5] Added precondition to ensure that server is still as seen before.

### PR DESCRIPTION
**Pull request by maierlars**

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7271/

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7275/

**Comment by neunhoef** [comment]
This is good to go.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
