### PR TITLE
Bug fix 3.4/restore feature perms

### PR DESCRIPTION
**Pull request by hkernbach**
Similar to, same purpose: https://github.com/arangodb/arangodb/pull/10603

**This PR relies on**: https://github.com/arangodb/arangodb/pull/10539/
**and needs to be merged first.** 

After the merge of # 10539, we need to start a Jenkins run for this PR.

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7516/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7517/

**Comment by hkernbach** [comment]
Jenkins green except for windows build.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7844/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-mac-onlycatch/5729/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
