### PR TITLE
Make v8 optional on startup

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/351/

### CODE REVIEW

**Comment by jsteemann** [comment]
Junge!

**Comment by jsteemann** [comment]
A few suggestions:
* let's rename the option from `--javascript.disable` to `--javascript.enabled`. That way the option name is more in line with other options. We also need to change the default value to `true` then of course. I think we can then use the `_enabled` and `isEnabled()` functionality of ApplicationFeature then to test if V8 is disabled or not.
* can we skip the initialization of the V8 platform completely in case JS is turned off? There is the V8PlatformFeature in lib/ApplicationFeatures, and it should not be started as well then. 
* some features, such as the debug console will not work without JS. So when starting with JS turned off but console mode requested, we should make the start fail with a descriptive error message. There may be more such features (don't know yet)
* in Query.cpp, before enterContext() is called, we should not only have an assertion, but test properly if JS is enabled or not. If disabled, we can throw an exception with a descriptive error message.
* let's change our local scripts, such as `startLocalCluster.sh` and such, to disable JavaScript when an agency instance is started. That way, we will have a few installations and tests using the option already.

**Comment by graetzer** [comment]
- Did I not turn off `V8PlatformFeature` correctly? https://github.com/arangodb/arangodb/pull/5220/files#diff-99cb04ae84f6dbcbcdfea0f81c9322eeR181
- If you use --console or --javascript.scripts etc, there is already an error. 
- Coordinator should work too technically, I added an error for the DBServer

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/359/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/362/

**Pull request merged**
