### PR TITLE
Propagate commit errors to AQL

### PR DESCRIPTION
**Pull request by m0ppers**

### CODE REVIEW

**Comment by m0ppers** [comment]
not happy with throwing. there is quite some cleanup in the catch stuff so I did it this way...there is also a commit() for explain()...not sure if we need to add it there as well.

**Comment by jsteemann** [comment]
It looks all good.
We should add some tests that explicitly trigger an error on commit. I will try to add them now.

**Comment by jsteemann** [comment]
Added failure tests for commit errors.

**Comment by m0ppers** [comment]
hmmm...just had a look at the code....doing a unittest seems hard it seems or do you think it is sensible at this point?

**Pull request merged**
