### PR TITLE
Clarification: installation via `kubectl` works for default namespace…

### PR DESCRIPTION
**Pull request by jgerken**
…, only.

Preferred solution for other namespaces is to use Helm (https://github.com/arangodb/kube-arangodb/issues/223#issuecomment-421364461).

### CODE REVIEW

**Comment by Simran-B** [comment]
Thanks a lot for your contribution to ArangoDB!

Would you mind adding a description of how to adapt the manifest file?

For legal reasons we need you to fill out and sign our Contributor License Agreement (CLA) to accept a contribution like yours. We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by jgerken** [comment]
I did not know about `kustomize` yet, I'll have a look and add an example.

**Comment by jgerken** [comment]
I have added a description what needs to be adapted. I failed to use `kustomize`. In the manifest for `ArangoLocalStorage` some objects use `namespace: kube-system` which must not be overridden. The namespace replacement command of `kustomize` changes all namespaces. I could figure out a way to change the namespace only if the previous values was `default` - of course I could have bound patches to specific objects but that would be very fragile. Renaming, deleting or adding objects would break the customisation. Therefore, I settled for using `sed` which makes it straight forward to do the replacement. Currently, `sed` is only be required for `arango-storage.yaml` and for the other `kustomize` could be used. For consistency I decided to use the same approach for all files.

I have no idea how one would do that under a normal Windows developer machine. I stopped using Windows 10 years ago. I have heard that it is possible nowadays to have a Linux shell under Windows 10. If someone knows how to do this on Windows, feel free to add it. Otherwise the Windows developers have to use a text editor.

@Simran-B regarding the CLA, I have read it but I need to talk to our HR department next week if I need their approval to sign it.

**Comment by Simran-B** [comment]
Yeah, there is Windows Subsystem for Linux (WSL):
https://docs.microsoft.com/en-us/windows/wsl/install-win10

The requirements seem to be a 64-bit system, 2+ GB RAM and Windows 10 Build >= 1803. In the beta phase it was limited to Windows Pro Edition and higher, but that doesn't seem to be the case anymore.

There is also the Git Bash shell which has `sed`:

image

Cygwin apparently as well:

image

PowerShell is the more modern Windows shell and scripting language. It doesn't have a sed command, but you can do something similar by the look of things:

- https://blogs.msdn.microsoft.com/zainnab/2007/07/08/grep-and-sed-with-powershell/
- http://blogs.catapultsystems.com/cfuller/archive/2014/09/26/using-sed-and-grep-in-powershell/

No pressure regarding the CLA!

**Comment by Simran-B** [comment]
https://github.com/arangodb/docs/pull/112

**Pull request closed without merging**
