### PR TITLE
adjust formula for automatic memory usage limit

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Slightly adjusted the formula for automatic memory usage limits, based on available RAM.

Values for the following RAM sizes have been adjusted by more useful:

    Available memory:            0      (0MiB)  Limit:            0   unlimited, %mem:  n/a
    Available memory:    134217728    (128MiB)  Limit:     33554432     (32MiB), %mem: 25.0
    Available memory:    268435456    (256MiB)  Limit:     67108864     (64MiB), %mem: 25.0

The values for very low memory systems were not sensible with the previous formula (they were set to unbounded), so this PR adjusts them.
This does not need to be backported, because in 3.7 and before the memory usage is unlimited by default.

Docs PR: https://github.com/arangodb/docs/pull/624

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [x] Docs PR: https://github.com/arangodb/docs/pull/624

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14079/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14081/

**Review by hkernbach — APPROVED** [review]

**Review by Simran-B — APPROVED** [review]
The test failure seems unrelated (Hot Backup)

**Comment by jsteemann** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/14140/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14182/

**Pull request merged**
