### PR TITLE
Less dropped followers

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This PR contains several improvements for cluster transactions and collection locking, which are somewhat related.
Included are the backports of the following devel-fixes:

* https://github.com/arangodb/arangodb/pull/12654
* https://github.com/arangodb/arangodb/pull/13136
* https://github.com/arangodb/arangodb/pull/12985

Detailed description of the changes:

**Less dropping of followers I**:

Enable larger follower transactions, by enabling intermediate commits on followers, too.
If a transaction is intermediate-committed on a follower but aborted on a leader, the follower will respond with a new error code `TRI_ERROR_CLUSTER_FOLLOWER_TRANSACTION_COMMIT_PERFORMED` (mapped to HTTP 409 Conflict), which the leader can use to drop the follower.

The PR also allows to lazily start a follower transaction on a follower from multiple leaders.
This can happen if we have 3 (or more) database servers and 2 shards, so that
- db server 1 is the leader for shard A
- db server 2 is the leader for shard B
- db server 3 is the follower for both shards A and B

In this case db server 1 may try to lazily start a follower transaction on db server 3 for shard A, and db server 2 may try to do the same for shard B. It is important that both operations succeed, because otherwise one of the calls would just drop db server 3 as a follower.
It is also important to note that each leader may only send information about "their" shards to the follower (i.e. either shard A or shard B), but may not send the entire list of shards used in the transaction. This happens at least for multi-collection AQL write queries that lazily start follower transactions for a write operation on a given shard.
The previous behavior for this case was that the follower responded with "transaction in use" when the second leader tried to lazily start the follower transaction, and that the follower was dropped.
With this PR, no followers should be dropped in this situation.

The PR adds a new test suite in file `tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js` to test the changes. Some of the tests are only executed if there are at least 3 DB servers, so the PR also changes the number of DB servers for some of the tests to 3 (from previously 2).

This is a backport of https://github.com/arangodb/arangodb/pull/12654

**Less dropping of followers II**:

In addition, this PR backports the change in https://github.com/arangodb/arangodb/pull/13136, which also reduces the likelyhood of dropping followers.

**Instrumentation for collection locking**:

This PR also adds metrics for collection locks:
- `arangodb_collection_lock_timeouts_exclusive`: Number of lock timeouts when trying to acquire collection exclusive locks 
- `arangodb_collection_lock_timeouts_write`: Number of lock timeouts when trying to acquire collection write locks 
- `arangodb_collection_lock_acquisition_micros`: Total amount of collection lock acquisition time [μs]
- `arangodb_collection_lock_acquisition_time`: Total collection lock acquisition time histogram [s]

And it reduces lock timeout on followers to 15 seconds.
Rationale: we should not have any locking conflicts on followers, generally. Any shard locking should be performed on leaders first, which will then, eventually replicate changes to followers. replication to followers is only done once the locks have been acquired on the leader(s). 

The latter two things are a backport of https://github.com/arangodb/arangodb/pull/12985

Docs PR: https://github.com/arangodb/docs/pull/575

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (e.g. in shell_client)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12985/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12988/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12999/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13009/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13027/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13034/

**Review by fceller — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13401/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/14852/

**Comment by KVS85** [comment]
Tests blue except unrelated failure.

**Pull request merged**
