### PR TITLE
Edge Replace: _to and _from are required

### PR DESCRIPTION
**Pull request by baslr**
rm Note: The attributes _from and _to of an edge are immutable

### CODE REVIEW

**Comment by dothebart** [comment]
I'd rather write: Including *_from* and *_to* is mandatory.

**Comment by dothebart** [comment]
We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

We have not been able to set of an electronic system yet. Can you sign, scan and email it to cla (at) arangodb.com?

;-)

**Comment by baslr** [comment]
You've Got Mail ;)

**Comment by dothebart** [comment]
mille gracie.

**Pull request merged**
