### PR TITLE
bugfix for https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fixes a crash described in https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029

- [ ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a GitHub Issue reported by a Community User: https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [x] Added new **integration tests** (i.e. in shell_server / shell_server_aql)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8130/

### CODE REVIEW

**Comment by iurii-i-popov** [comment]
@jsteemann I added the same fix for an index node optimization with a test.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8153/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8155/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8164/

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
