### PR TITLE
Added "Community integrations" section to Drivers docs

### PR DESCRIPTION
**Pull request by jaredpetersen**
Added a new "Community integrations" section to the Drivers docs. Included an entry in the section for [Kafka Connect ArangoDB](https://github.com/jaredpetersen/kafka-connect-arangodb), a [Kafka Connector](https://docs.confluent.io/current/connect/managing/index.html) that sinks data from Apache Kafka into ArangoDB.

I signed the Contributor License Agreement and sent it in via email.

### CODE REVIEW

**Comment by jaredpetersen** [comment]
@Simran-B Can you take a look at this and let me know what you think? Thanks for your help on this - I really appreciate it 😄

**Comment by Simran-B** [comment]
Hey Jared,
sorry for the delay. I'm currently busy and couldn't find someone in the team who tried the connector out. If we advertise it in the officials docs then we should have at least tested it once IMHO.
One question: it is not related to datacenter to datacenter synchronization right?

**Comment by jaredpetersen** [comment]
@Simran-B No worries! I figured you were busy.

I totally understand the need to vet the connector. When someone is able to try the connector out, there's a doc [here](https://github.com/jaredpetersen/kafka-connect-arangodb/tree/master/docs/development) that shows how it all works by running you through starting up a local Kafka cluster with ArangoDB using Docker Compose.

It's not related to datacenter to datacenter synchronization. As far as I know, ArangoDB already has mechanisms to take care of that. This connector "sinks" data into ArangoDB from other non-ArangoDB sources, whatever those might be. Eventually I'd like to get the connector to read from the ArangoDB Write Ahead Log and write records into Kafka so that other applications can get streaming data from the database [but I don't see a way to do so yet](https://stackoverflow.com/q/54426598/7583677).

**Comment by Simran-B** [comment]
We are moving the documentation to a separate repository. It is currently private, but will be made public soon. Closing the PR here, tracking this issue further in https://github.com/arangodb/docs/issues/11

**Pull request closed without merging**
