### PR TITLE
BTS-933: SmartSearch error handling 

### PR DESCRIPTION
**Pull request by hkernbach**
Backport of: https://github.com/arangodb/arangodb/pull/16721
EE Companion: https://github.com/arangodb/enterprise/pull/999

### CODE REVIEW

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by hkernbach** [comment]
Jenkins green except unrelated windows failure AGAIN

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by hkernbach** [comment]
Jenkins green except unrelated windows failure

**Comment by KVS85** [comment]
Only unrelated known failure on Windows.

**Pull request merged**
