### PR TITLE
Improved observability

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Forward port of the changes introduced in 3.6 via https://github.com/arangodb/arangodb/pull/13035.
The forward port is smaller than the referenced 3.6 PR because several metrics added by that PR already existed in devel.
This PR just adds the new things that were originally added by that 3.6 PR.
In addition, this PR also cleans up some code in the SupervisedScheduler.

**Metrics**:
* Added new scheduler metrics:
  * `arangodb_scheduler_jobs_done`: Total number of scheduler queue jobs done
  * `arangodb_scheduler_jobs_submitted`: Total number of jobs submitted to the scheduler queue
  * `arangodb_scheduler_jobs_dequeued`: Total number of jobs dequeued from the scheduler queue
  * `arangodb_scheduler_num_working_threads`: Number of currently working scheduler threads
* Added new metric `arangodb_replication_cluster_inventory_requests` to track the number of requests received for cluster inventories. The cluster inventory API is called at the beginning of a dump process or by arangosync.

**Availability API**:
Added startup option `--server.unavailability-queue-fill-grade`. This option   has a consequence for the `/_admin/server/availability` API only, which is often called by load-balancers and other availability probing systems. 

The `/_admin/server/availability` API will now return HTTP 200 if the fill grade of the scheduler's queue is below the configured value, or HTTP 503 if the fill grade is above it. This can be used to flag a server as unavailable in case it is already highly loaded.

The default value for this option is `0.75`, i.e. 75%. This is a change compared to previous versions of ArangoDB, where the default value was `1` (i.e. 100%).

To prevent sending more traffic to an already overloaded server, it can be sensible to reduce the default value to even `0.5`.
This would mean that instances with a queue longer than 50% of their maximum queue capacity would return HTTP 503 instead of HTTP 200 when their availability API is probed. 

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] 3.6: https://github.com/arangodb/arangodb/pull/13035,3.7: https://github.com/arangodb/arangodb/pull/13037

#### Related Information

- [x] Docs PR: https://github.com/arangodb/docs/pull/580

### Testing & Verification

- [x] The behavior in this PR was *manually tested*

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12753/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12755/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12756/

**Comment by jsteemann** [comment]
Tests blue

**Review by neunhoef — APPROVED** [review]
LGTM

**Pull request merged**
