### PR TITLE
[3.6] Also throw if result is not ok()

### PR DESCRIPTION
**Pull request by markuspf**
Backport of #11663

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10037/

**Comment by mchacki** [comment]
I added the DO_NOT_ERGE_ label as there is a compile issue in this PR. This has been fixed in Original.

Please remove as soon as cherry-pick is done.

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10041/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
