### PR TITLE
Bug fix/replace create collection safety ttl with supervision

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

No longer to use the agency's TTL as a safety measure against coordinator crashes when creating collections, but use the supervision instead.

- [X] Bug-Fix for *devel-branch*
- [X] Bug-Fix for a *3.6*: https://github.com/arangodb/arangodb/pull/10728
- [X] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [ ] The behavior change can be verified via automatic tests

#### Related Information

Related to https://github.com/arangodb/release-3.6/issues/42.

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [ ] Added new **resilience tests**

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7728/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7735/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7787/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7788/ blue

**Comment by goedderz** [comment]
Screenshot_20191220_161518

**Comment by maierlars** [comment]
image
A valid Jenkins Certificate **has to** include the timestamp and the branch name!

**Comment by goedderz** [comment]
Screenshot_20191220_174530

**Comment by goedderz** [comment]
This is buggy anyway without https://github.com/arangodb/arangodb/pull/10756.

**Pull request merged**
