### PR TITLE
Ensure failoverCandidates have no servers not in Plan, first amendment.

### PR DESCRIPTION
**Pull request by neunhoef**
Followup fix in FollowerInfo::remove.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12208/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12214/

**Comment by KVS85** [comment]
Tests blue.

**Comment by KVS85** [comment]
Should be addressed in 3.6 branch only.

**Pull request closed without merging**
