### PR TITLE
[CINFRA-492] Add suite shell_client_transaction

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

Added test suite `shell_client_transaction` to the CI matrix. Was added (and some files moved there) in https://github.com/arangodb/arangodb/pull/16414/files#diff-c7ccb564e3e90efc9e6dd3d9e620cb037a3f7eada565c9615564303a9026e292.

- [X] :hankey: Bugfix

### CODE REVIEW

**Comment by dothebart** [comment]
do you think arangosh accessing it via different means of communications can make a difference?

**Comment by goedderz** [comment]
> do you think arangosh accessing it via different means of communications can make a difference?

The tests were previously part of `shell_client`, so I used the same settings. I don't know the tests in detail, so I'd rather be on the safe side unless someone checks and assures otherwise.

**Comment by dothebart** [comment]
from what I see in the linked PR this will allways be a clustered setup? Then in general it doesn't make sense to run it in single server since the load estimates will be wrong and destabilize everything.

**Comment by dothebart** [comment]
ok, maybe the linked commit isn't the only change there.

**Review by maierlars — APPROVED** [review]

**Review by dothebart — APPROVED** [review]

**Comment by goedderz** [comment]
Jenkins failure is unrelated.

**Pull request merged**
