### PR TITLE
[3.6] - Add rocksdb.exclusive-write tests

### PR DESCRIPTION
**Pull request by maxkernbach**
Added tests for **enabled/disabled `rocksdb.exclusive-writes`: single/cluster**

**TODO**: Fix asserts for `exclusive-collections-off` tests

**Tests successful for `rocksdb.exclusive-writelock=true`: single server + cluster**

* Test "server_permissions"
    [SUCCESS] tests/js/client/server_permissions/exclusive-collections-on-noncluster-rocksdb.js

 * Overall state: Success

* Test "server_permissions"
    [SUCCESS] tests/js/client/server_permissions/exclusive-collections-on-rocksdb.js

 * Overall state: Success

**Test fails for `rocksdb.exclusive-writelock=false`: single server**

```
* Test "server_permissions"
    [FAILED]  tests/js/client/server_permissions/exclusive-collections-off-noncluster-rocksdb.js

      "testExclusiveExpectConflictWithoutOption" failed: ArangoError: timeout waiting to lock key Operation timed out: Timeout waiting to lock key
    at Proxy.ArangoDatabase._executeTransaction (/home/max/Git/arangodb/js/client/modules/@arangodb/arango-database.js:1181:11)
    at Object.testExclusiveExpectConflictWithoutOption (tests/js/client/server_permissions/exclusive-collections-off-noncluster-rocksdb.js:104:10)
    at Object.run (/home/max/Git/arangodb/js/common/modules/jsunity/jsunity.js:551:27)
    at Object.Run [as run] (/home/max/Git/arangodb/js/common/modules/jsunity.js:275:24)
    at tests/js/client/server_permissions/exclusive-collections-off-noncluster-rocksdb.js:140:9
    at tests/js/client/server_permissions/exclusive-collections-off-noncluster-rocksdb.js:143:3
    at RunTest (/home/max/Git/arangodb/js/common/modules/jsunity.js:389:12)
    at testFunc (eval at runInLocalArangosh (/home/max/Git/arangodb/js/client/modules/@arangodb/test-utils.js:881:3), <anonymous>:4:9)
    at Object.runInLocalArangosh (/home/max/Git/arangodb/js/client/modules/@arangodb/test-utils.js:884:18)
    at /home/max/Git/arangodb/js/client/modules/@arangodb/testsuites/server_permissions.js:103:32 - test failed


 * Overall state: Fail
   Suites failed: 1 Tests Failed: 1
```

**Test fails for `rocksdb.exclusive-writelock=false`: cluster**

```* Test "server_permissions"
    [FAILED]  tests/js/client/server_permissions/exclusive-collections-off-rocksdb.js

      "testExclusiveExpectConflictWithoutOption" failed: ArangoError: precondition failed
    at Proxy.ArangoDatabase._executeTransaction (/home/max/Git/arangodb/js/client/modules/@arangodb/arango-database.js:1181:11)
    at Object.testExclusiveExpectConflictWithoutOption (tests/js/client/server_permissions/exclusive-collections-off-rocksdb.js:104:10)
    at Object.run (/home/max/Git/arangodb/js/common/modules/jsunity/jsunity.js:551:27)
    at Object.Run [as run] (/home/max/Git/arangodb/js/common/modules/jsunity.js:275:24)
    at tests/js/client/server_permissions/exclusive-collections-off-rocksdb.js:140:9
    at tests/js/client/server_permissions/exclusive-collections-off-rocksdb.js:143:3
    at RunTest (/home/max/Git/arangodb/js/common/modules/jsunity.js:389:12)
    at testFunc (eval at runInLocalArangosh (/home/max/Git/arangodb/js/client/modules/@arangodb/test-utils.js:881:3), <anonymous>:4:9)
    at Object.runInLocalArangosh (/home/max/Git/arangodb/js/client/modules/@arangodb/test-utils.js:884:18)
    at /home/max/Git/arangodb/js/client/modules/@arangodb/testsuites/server_permissions.js:103:32 - test failed

 * Overall state: Fail
   Suites failed: 1 Tests Failed: 1```

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7753/

**Comment by hkernbach** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/7759/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7768/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
