### PR TITLE
Fix disabling of optimizer rules.

### PR DESCRIPTION
**Pull request by danielhlarkin**
Backport of https://github.com/arangodb/arangodb/pull/10717

Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7727/

### CODE REVIEW

**Comment by KVS85** [comment]
Tests blue.

**Comment by joerg84** [comment]
@danielhlarkin thanks for fixing this! Just curious: we have a test where we actually try to disable an unknown rule?

**Comment by danielhlarkin** [comment]
@joerg84 We currently do not have any integration tests at all for this startup parameter, just manual ones. (I've verified that on attempting to disable an unknown rule, you get a warning message on startup, as expected.) This is due to the way our testing system is set up. It would require designing a whole new suite in testing.js with different behavior than our current system. I would guess that's too much effort for 3.6 at least, but could be done at a later date if we really want to.

**Comment by jsteemann** [comment]
I will add these tests. @danielhlarkin @joerg84

**Comment by joerg84** [comment]
Thanks @jan

Am Di., 17. Dez. 2019 um 15:04 Uhr schrieb Jan <notifications@github.com>:

**Comment by jan** [comment]
@joerg84 No problem at all. If you need anything, just let me know!

**Pull request merged**
