### PR TITLE
Use static variable names in Foxx generator

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This prevents complications with generated names shadowing existing variable names.

- [x] :hankey: Bugfix (requires CHANGELOG entry)

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

### CODE REVIEW

**Review by ajurdak — APPROVED** [review]
LGTM.

**Comment by pluma** [comment]
@fceller @joerg84 Can we get this merged into devel for 3.10? This addresses the problem with the Foxx generator creating invalid JavaScript when collections have names that conflict with pre-existing variable names.

**Comment by pluma** [comment]
jenkins is green: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/19809/

**Review by fceller — APPROVED** [review]
LGTM

**Comment by pluma** [comment]
will merge when jenkins is green again

**Comment by pluma** [comment]
jenkins is green

**Pull request merged**
