### PR TITLE
Doc - Known Issues - new links

### PR DESCRIPTION
**Pull request by sleto-it**
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/237/

### CODE REVIEW

**Comment by sleto-it** [comment]
seems this page has multiple links in the same line, so the build is failing
https://github.com/arangodb/arangodb/blob/documentation-3.3/known-issues-imp/Documentation/Books/Manual/Graphs/README.md

can be easily fixed but unsure if there are others (and/or why the build didn't fail before)

**Comment by Simran-B** [comment]
I bet there are a bunch more such errors until we finalize https://github.com/arangodb/arangodb/pull/7737 and forward-port it from 3.2 to 3.3...

Old Jenkins may not be affected (the additional checks which make new Jenkins fail should not be in the 3.3 build script).

**Comment by sleto-it** [comment]
understood - I merge

**Comment by Simran-B** [comment]
PATCH_DOCUMENTATION job on old Jenkins worked:
https://docs.arangodb.com/3.3/Manual/ReleaseNotes/KnownIssues33.html

**Pull request merged**
