### PR TITLE
Fixed ordering of includes in varusage finder. 

### PR DESCRIPTION
**Pull request by mchacki**
Seemingly apple clang gets confused sometimes with this and generates invalid code

This commit does not change any documented behavior.
We only managed to reproduce it on a release package of MacOs.
It does not show up on any development version.

### CODE REVIEW

**Comment by mchacki** [comment]
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9974/

**Comment by joerg84** [comment]
That shouldn't make a difference, or.... Thanks for finding...

**Comment by mchacki** [comment]
Jenkins after devel update:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9975/

**Comment by KVS85** [comment]
Tests blue.

**Comment by mchacki** [comment]
@joerg84 i was under the impression too.
I was expecting that the initializer list would just create the Object as expected.

However:
If I explicitly name the Object to be created the compiler (clang) was not able to compile this viel, because the Type was not defined.
Seemingly gcc was able to compile everything fine.

So my guess is that clang trailed down an unexpected path.

**Pull request merged**
