### PR TITLE
Bug fix 3.5/little weekend fix

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7367/

**Comment by KVS85** [comment]
ports:

 - [ ] 3.3 -- https://github.com/arangodb/arangodb/pull/10525
 - [ ] 3.5 -- https://github.com/arangodb/arangodb/pull/10527
 - [ ] devel -- https://github.com/arangodb/arangodb/pull/10518

**Comment by jsteemann** [comment]
Test failure because of duplicate log ids..?!

**Comment by jsteemann** [comment]
@obiwahn: Wrong branch names used in Jenkins build... Please restart with correct branches

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7390/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
