### PR TITLE
Switch to thread-local RandomDevice instances.

### PR DESCRIPTION
**Pull request by mpoeter**
In some situations the mutex around the single shared RandomDevice can become a bottleneck. I therefore suggest to use thread-local instances that are lazily initialized upon first usage.

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3011/

**Comment by jsteemann** [comment]
@mpoeter : compilation failed on MacOS with
```
/Users/jenkins/c22-mac.test/oskar/work/ArangoDB/lib/Random/RandomGenerator.cpp:444:61: error: type of thread-local variable has non-trivial destruction
thread_local std::unique_ptr<RandomDevice> RandomGenerator::_device(nullptr);
                                                            ^
/Users/jenkins/c22-mac.test/oskar/work/ArangoDB/lib/Random/RandomGenerator.cpp:444:61: note: use 'thread_local' to allow this
1 error generated.
```

**Comment by mpoeter** [comment]
Huh... which compiler do you use your for MacOS builds? thread-local objects with non-trivial destructors are part of C++11...

**Comment by jsteemann** [comment]
```
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- The C compiler identification is AppleClang 10.0.0.10001145
```
The mode is `-std=c++14`.

**Comment by jsteemann** [comment]
@mpoeter : I think this is caused by `lib/Basics/operating-system.h`:
```
#if __llvm__ == 1
#define thread_local __thread
#endif
```
IIRC this snippet was there already even before we switched to C++11. It is probably useless nowadays.

**Comment by mpoeter** [comment]
Ah, that also explains the message `note: use 'thread_local' to allow this`. Yes, this can probably be removed by now! Will to that tomorrow.

**Comment by jsteemann** [comment]
Ok, thanks!

**Comment by mpoeter** [comment]
Unfortunately I could not reproduce the error with a local clang build. I've removed the `thread_local` macros for LLVM and Windows as all major compilers should support it by now. Hope this fixes the MacOS build. 🤞

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3028/

**Pull request merged**
