### PR TITLE
Bug fix 3.6/arangobench

### PR DESCRIPTION
**Pull request by dothebart**
backport of https://github.com/arangodb/arangodb/pull/13132 and sync features / tests

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12951/

**Comment by dothebart** [comment]
tests blue.

**Comment by KVS85** [comment]
> tests blue.

Except known failure.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-matrix/18/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
