### PR TITLE
Updates jquery and handlbars

### PR DESCRIPTION
**Pull request by OKNoah**
WIP, not sure how to test 😅

### CODE REVIEW

**Comment by hkernbach** [comment]
Thank you very much for your try, but we're currently in the process of updating swagger to latest 3.9.0 version. This version no longer uses those libraries.

**Comment by hkernbach** [comment]
See: https://github.com/arangodb/arangodb/pull/4285

**Comment by OKNoah** [comment]
@hkernbach :) cool, sorry for the extra ticket

**Comment by mchacki** [comment]
Closing this as it is already covered by https://github.com/arangodb/arangodb/pull/4285 thank you for your effort it is highly appreciated.

**Pull request closed without merging**
