### PR TITLE
Deprecate rocksdb.max-write-buffer-number startup option

### PR DESCRIPTION
**Pull request by Simran-B**
### Scope & Purpose

Mark the startup option `rocksdb.max-write-buffer-number` as deprecated in v3.4.8 and v3.5.0 because it does nothing. It is hardcoded to number of column families (7) + 2 = 9.

_matthew_:
> Set too low it causes rocksdb to regularly block all writes. Yes, it could be set higher ... but can also lead to block writes. Currently the value is fixed at "number of column families" plus two. This setting was heavily tested. And shown to be aligned with five years of research on Google's leveldb upon which rocksdb is based.

- [ ] Backport to 3.4 and 3.5

#### Related Information

*(Please reference tickets / specification etc )*

- [x] There is a *JIRA Ticket number* (In case a customer was affected / involved):  https://arangodb.atlassian.net/browse/ES-371

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage - while technically a code change, it should affect nothing but the documentation (and `arangod --help` output)

### CODE REVIEW

**Comment by Simran-B** [comment]
Code change verified to be working, arangod.json (for backport):

```json
  "rocksdb.max-write-buffer-number" : {
    "category" : "option",
    "default" : 2,
    "deprecatedIn" : [
      "v3.4.8",
      "v3.5.0"
    ],
    "description" : "maximum number of write buffers that build up in memory. This option is ignored! There is a hardcoded maximum of number of column families + 2 (currently 9) write buffers based on performance research",
    "dynamic" : false,
    "enterpriseOnly" : false,
    "hidden" : false,
    "introducedIn" : null,
    "obsolete" : false,
    "requiresValue" : true,
    "section" : "rocksdb",
    "type" : "uint64"
  },
```

**Comment by Simran-B** [comment]
@jsteemann says that we should think about making this option actually work instead of deprecating it.

**Comment by matthewvon** [comment]
"make it work" then means the minimum should be number of column families plus two, and user could increase above that.  Going lower creates performance bottleneck on write buffer flush.

**Comment by Simran-B** [comment]
Okay, but I think the value the user passes should be the total max, and ignored if it's below column families plus two (with a log warning). The current default seems to be the offset of plus two? That's kinda confusing, especially because the true max is 9 by default.

Will leave this PR pending until further notice.

**Comment by matthewvon** [comment]
"true max" is 2:  https://github.com/arangodb/arangodb/blob/devel/3rdParty/rocksdb/6.2/include/rocksdb/advanced_options.h#L167 ... I am the person that raised it to 9 ... 7 column families plus 2.

**Comment by jsteemann** [comment]
Let's just honor the user's setting for this option *if* it is explicitly set by the user.
And if it's not explicitly set, then we should apply our default (which currently is 7+2).
Objections?

**Comment by matthewvon** [comment]
Yes.  I object to allowing less than 9.  The user is not going to understand the performance impact.  They are likely thinking "this will decrease my memory footprint".  Then we end up having to debug their environment when server suddenly has periodic stalls which can lead to cluster replication sync issues and other nasty items.

**Comment by jsteemann** [comment]
I think the above PRs of mine obsolete this issue. @Simran-B

**Comment by Simran-B** [comment]
Removed the deprecation part, reworded the description to:

> maximum number of write buffers that build up in memory (default: number of column families + 2 = 9 write buffers). You can increase the amount only

**Pull request merged**
