### PR TITLE
Feature/sha512 aql cpp

### PR DESCRIPTION
**Pull request by hkernbach**

### CODE REVIEW

**Comment by jsteemann** [comment]
@hkernbach : can you add the function to the AQL documentation? Thanks!

**Comment by hkernbach** [comment]
@jsteemann added docu. See https://github.com/arangodb/arangodb/pull/4181/commits/6be8d1a3fb2c59f37d2ec3498f78416b454a4eee

**Comment by aterry1** [comment]
K

**Comment by baslr** [comment]
test doesnt cover c++ and js.

**Pull request merged**
