### PR TITLE
[3.5] Background Get Ids

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose
Obtain new unique IDs via a background thread. There are now to batches available and as soon as one batch is used a background thread is started to obtain more ids. This allows the current thread to continue almost immediately.

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5833/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6350/

**Comment by neunhoef** [comment]
Let's wait for another jenkins run, I have merged 3.5 in again.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6463/

**Comment by KVS85** [comment]
Tests blue except unrelated `timeout in cluster operation` failure that led to JS module execution timeout for ArangoSearch test.

**Pull request merged**
