### PR TITLE
Remove obsolete code

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This PR tries to achieve several things at the same time:
* remove a few dead stores, found by scan-build
* remove unused variables, found by scan-build
* use move semantics for SharedAqlItemPtrs in a few more places
* remove some older legacy compatibility code that was only there to support incoming calls from older versions (3.5, 3.6) - 3.7 API compatibility should not have changed by this PR
* remove some obsolete that was not in use after some refactorings

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *shell_server_aql, agency, gtest*.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12871/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12874/

**Comment by jsteemann** [comment]
Tests blue

**Review by fceller — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12932/

**Pull request merged**
