### PR TITLE
generate procdump on forcefull shutdown regardless whether we previously

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

generate procdump on forcefull shutdown regardless whether we previously had a procdump running or its disabled

- [x] :fire: test infrastructural fix

#### Backports:

- [x] Backport for 3.9: *(Please link PR)*
- [x] Backport for 3.8: *(Please link PR)*
- [x] Backport for 3.7: *(Please link PR)*

### CODE REVIEW

**Review by Dronplane — APPROVED** [review]
LGTM

**Review by mpoeter — APPROVED** [review]

**Comment by dothebart** [comment]
Oskar timeout on windows, rest green.

**Comment by Dronplane** [comment]
Just curious - shouldn't  we get a crash dump in that case? Or Oscar timeouts are handled differently?

**Comment by dothebart** [comment]
I don't think oskar has anything like that. https://github.com/arangodb/oskar/blob/master/helper.psm1 would be the place to search.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
