### PR TITLE
Output CPU context and image base in signal handler (if available).

### PR DESCRIPTION
**Pull request by mpoeter**
### Scope & Purpose

Some error reports like #12683 or #12597 would greatly benefit from additional information. In particular for SIGSEGV crashes the full CPU context and image base can provide a lot of information, even if no debug symbols are available.

- [ ] :hankey: Bugfix 
- [x] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required

Though it might make sense to have this in older versions as well (up to you).

After loading the according executable into [IDA Pro Free](https://www.hex-rays.com/products/ida/support/download_freeware/) and rebasing the image to the according base address from the process, we can check the instruction pointer (RIP) and the addresses from any callstacks. This is how I analyzed the issue in #12597.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11917/

**Comment by jsteemann** [comment]
@mpoeter: Thanks for this PR!
I had started a similar change to show the executables base address, though I didn't have time to finish it yet.
It is not based on `dladdr`. but on `getauxval(AT_PHDR)`.
I am pretty sure both variants will work fine when compiling the executables with glibc.
However, our release packages are built statically and are linked to libmusl, and unfortunately it has a lot less to offer here.
So I will pull this PR now and check whatever it will do to a libmusl-based build.
This will take a bit of time, but I will make sure it will be pursued!

**Comment by jsteemann** [comment]
@mpoeter : just built the branch into a release build, statically linked against libmusl, started the executable and sent it a SIGSEGV signal.
Here is the log output:
```
2020-09-23T11:38:38Z [90550] FATAL [a7902] {crash} ArangoDB 3.8.0-devel enterprise [linux], thread 0 caught unexpected signal 11 (SIGSEGV) accessing address 0x000003e800016259: signal handler invoked\nCPU context:\n  rip: 0x00007f057e34136b rsp: 0x00007ffe9d9bb188\n  efl: 0x0000000000000246 rbp: 0x0000000000000080\n  rsi: 0x0000000000000080 rdi: 0x00007ffe9d9bb264\n  rax: 0xfffffffffffffffc rbx: 0x00007f057ac88c80\n  rcx: 0x00007f057e34136b rdx: 0x0000000000000002\n  r8:  0x0000000000000000 r9:  0x0000000000000000\n  r10: 0x00007ffe9d9bb1e0 r11: 0x0000000000000246\n  r12: 0x00000000000000ca r13: 0x00007ffe9d9bb264\n  r14: 0x0000000000000080 r15: 0x00007ffe9d9bbb70\nimage base address: 0x0000000000000000
2020-09-23T11:38:38Z [90550] INFO [308c3] {crash} frame 1 [0x00007f057c94ac9f] (anonymous namespace)::crashHandlerSignalHandler(int, siginfo_t*, void*) (+0x000000000000003f)
2020-09-23T11:38:38Z [90550] INFO [308c3] {crash} frame 2 [0x00007f057e338e7c] sigprocmask (+0x0000000000000021)
2020-09-23T11:38:38Z [90550] INFO [ded81] {crash} available physical memory: 41722023936, rss usage: 304959488, vsz usage: 1206083584, threads: 46
```
While I have no reason to question the register output, the image base address is reported as `0x0`. I think this is expected when statically linking with libmusl.

**Comment by mpoeter** [comment]
@jsteemann I am more than happy if you have an alternative to `dladdr`! On Windows I would simply use `GetModuleHandle(NULL)` to get the base address of the executable, but for Linux `dladdr` was basically the only thing I could find after a lot of googling (except for parsing the content from `/proc/self/maps`).

**Comment by mpoeter** [comment]
@jsteemann I like the `getauxval(AT_PHDR)` approach much more (not only because it should work independent of glibc). One minor gotcha was that it does not return the base address directly, but the the address of the program header, which is located after the ELF header. So to get the actual base address we have to subtract the size of the ELF header. I have changed the code accordingly and hope this works correctly with libmusl now.

**Comment by jsteemann** [comment]
@mpoeter : Thanks! I think I will abandon my own changes then in favor of your PR.
I will also use your PR as a basis for incorporating a few minimal changes of mine that may be still relevant.
Just to manage expectations: I think I can do this and also test it with libmusl only next week, so please expect a slight delay here.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12102/

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
Backport for 3.7: https://github.com/arangodb/arangodb/pull/12767

**Pull request merged**
