### PR TITLE
Feature/upgrade v8 7.1.302.28

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2977/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2989/

**Comment by ObiWahn** [comment]
diff --git a/lib/ApplicationFeatures/V8PlatformFeature.cpp b/lib/ApplicationFeatures/V8PlatformFeature.cpp
index be00b7448a..f48ee843e1 100644
--- a/lib/ApplicationFeatures/V8PlatformFeature.cpp
+++ b/lib/ApplicationFeatures/V8PlatformFeature.cpp
@@ -188,15 +188,15 @@ void V8PlatformFeature::unprepare() {
 v8::Isolate* V8PlatformFeature::createIsolate() {
   v8::Isolate::CreateParams createParams;
   createParams.array_buffer_allocator = _allocator.get();
-  createParams.oom_error_callback = oomCallback;
-  createParams.fatal_error_callback = fatalCallback;
+/// TODO  createParams.oom_error_callback = oomCallback;
+///   createParams.fatal_error_callback = fatalCallback;

Is something missing here?

**Comment by ObiWahn** [comment]
diff --git a/lib/Basics/FileUtils.cpp b/lib/Basics/FileUtils.cpp
index bf9bcfb395..9938f5fdc6 100644
--- a/lib/Basics/FileUtils.cpp
+++ b/lib/Basics/FileUtils.cpp
@@ -324,9 +324,9 @@ bool copyDirectoryRecursive(std::string const& source, std::string const& target
   std::string rcs;
   std::string flt = source + "\\*";
 
-  UnicodeString f(flt.c_str());
+  icu::UnicodeString f(flt.c_str());
 
-  handle = _wfindfirst(f.getTerminatedBuffer(), &oneItem);
+  handle = _wfindfirst((wchar_t*)f.getTerminatedBuffer(), &oneItem);
 
   if (handle == -1) {
     error = "directory " + source + " not found";
@@ -335,7 +335,7 @@ bool copyDirectoryRecursive(std::string const& source, std::string const& target
 
   do {
     rcs.clear();
-    UnicodeString d((wchar_t*)oneItem.name, static_cast<int32_t>(wcslen(oneItem.name)));
+    icu::UnicodeString d((wchar_t*)oneItem.name, static_cast<int32_t>(wcslen(oneItem.name)));
     d.toUTF8String<std::string>(rcs);
     fn = (char*)rcs.c_str();
 #else
@@ -418,8 +418,8 @@ std::vector<std::string> listFiles(std::string const& directory) {
   std::string rcs;
 
   std::string filter = directory + "\\*";
-  UnicodeString f(filter.c_str());
-  handle = _wfindfirst(f.getTerminatedBuffer(), &oneItem);
+  icu::UnicodeString f(filter.c_str());
+  handle = _wfindfirst((wchar_t*)f.getTerminatedBuffer(), &oneItem);

c style cast

**Comment by ObiWahn** [comment]
diff --git a/lib/V8/v8-conv.cpp b/lib/V8/v8-conv.cpp
index 1aebf2496f..6871747c31 100644
--- a/lib/V8/v8-conv.cpp
+++ b/lib/V8/v8-conv.cpp
 /// @brief converts an V8 object to a boolean
-bool TRI_ObjectToBoolean(v8::Handle<v8::Value> const value) {
+bool TRI_ObjectToBoolean(v8::Isolate* isolate, v8::Handle<v8::Value> const value) {
   if (value->IsBoolean()) {
-    return value->ToBoolean()->Value();
+    return value->IsTrue();
   }
 
really?

**Comment by ObiWahn** [comment]
```
+++ b/lib/V8/v8-globals.h
+#define TRI_IGETC isolate->GetCurrentContext()
+
+#define TRI_GET_INT32(VAL) VAL->Int32Value(TRI_IGETC).FromMaybe(0)
+
+#define TRI_GET_UINT32(VAL) VAL->Uint32Value(TRI_IGETC).FromMaybe(0)
+
+#define TRI_GET_DOUBLE(VAL) VAL->NumberValue(TRI_IGETC).FromMaybe(0.0)
+
+#define TRI_GET_STRING(VAL) \
+  VAL->ToString(TRI_IGETC).FromMaybe(v8::Local<v8::String>())
+
+#define TRI_GET_OBJECT(VAL) \
+  VAL->ToObject(TRI_IGETC).FromMaybe(v8::Local<v8::Object>())
+
+#define TRI_OBJECT_HAS_PROPERTY(OBJECT, PROPERTYSTRING) \
+  OBJECT->Has(TRI_IGETC, TRI_V8_ASCII_STRING(isolate, PROPERTYSTRING)).FromMaybe(false)
+
+#define TRI_OBJECT_HAS_V8_PROPERTY(OBJECT, PROPERTYSTRING) \
+  OBJECT->Has(TRI_IGETC, PROPERTYSTRING).FromMaybe(false)
+
+#define TRI_OBJECT_HAS_OWN_V8_PROPERTY(OBJECT, PROPERTYSTRING) \
+  OBJECT->HasOwnProperty(TRI_IGETC, PROPERTYSTRING).FromMaybe(false)
+
+#define TRI_OBJECT_HAS_OWN_PROPERTY(OBJECT, PROPERTYSTRING)                       \
+  OBJECT->HasOwnProperty(TRI_IGETC, TRI_V8_ASCII_STRING(isolate, PROPERTYSTRING)) \
+      .FromMaybe(false)
+
+#define TRI_OBJECT_GET_PROPERTY(OBJECT, PROPERTYSTRING)                \
+  OBJECT->Get(TRI_IGETC, TRI_V8_ASCII_STRING(isolate, PROPERTYSTRING)) \
+      .FromMaybe(v8::Local<v8::Value>())
+
+#define TRI_OBJECT_GET_V8_PROPERTY(OBJECT, PROPERTY) \
+  OBJECT->Get(TRI_IGETC, PROPERTY).FromMaybe(v8::Local<v8::Value>())
+
+#define TRI_OBJECT_DELETE_PROPERTY(OBJECT, PROPERTYSTRING) \
+  OBJECT->Delete(TRI_IGETC, TRI_V8_ASCII_STRING(isolate, PROPERTYSTRING)).FromMaybe(false)
+
+#define TRI_OBJECT_DELETE_V8_PROPERTY(OBJECT, PROPERTY) \
+  OBJECT->Delete(TRI_IGETC, PROPERTY).FromMaybe(false)
+
+#define TRI_OBJECT_TO_V8_STRING(OBJECT) \
+  OBJECT->ToString(TRI_IGETC).FromMaybe(v8::Local<v8::String>())
+
+#define TRI_TO_OBJECT(VAL) \
+  VAL->ToObject(TRI_IGETC).FromMaybe(v8::Local<v8::Object>())
+
```

I do not like the new macros. I think passing something like `isolate->getCurrentContext()` into a function is not too bad and makes much more obvious what is going on.

**Comment by ObiWahn** [comment]
```
js/client/authentication/user-access-right-task-update-view-arangosearch-spec.js
js/client/authentication/user-access-right-task-update-view-arangosearch-spec_1.js
js/client/authentication/user-access-right-task-update-view-arangosearch-spec_2.js
```
Is this work in progress?

**Comment by danielhlarkin** [comment]
> Some functionality is missing and I do not like the marcos.

@ObiWahn Which macros in particular?

**Comment by dothebart** [comment]
> > Some functionality is missing and I do not like the marcos.
> 
> @ObiWahn Which macros in particular?

he is talking about the new macros in `lib/V8/v8-globals.h` that keep object property access a one-liner. The new V8 api has even more neccity for boiler plate code for simple things, that I decided to throw more macros at it.

**Comment by danielhlarkin** [comment]
Ah, I see. The way I was looking through the diffs, they didn't appear as new code for some reason. I would also be somewhat against introducing new macros when we can avoid it. We already have enough to be confused about without hiding what's happening.

**Comment by dothebart** [comment]
Blue: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4307/

**Pull request merged**
