### PR TITLE
Try to make cluster tests tsan run more useful

### PR DESCRIPTION
**Pull request by MBkkt**
### Scope & Purpose

* Suppress very popular and easy to reproduce replication2 lock order inversions
  These errors make all report unreadable because they spam it
* Fix 3 simple data races
* Remove already unnecessary suppressions

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.11: *(Please link PR)*
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM for the code changes.
I can't comment on the replication2 suppressions.

**Review by Dronplane — APPROVED** [review]
LGTM

**Review by apetenchea — COMMENTED** [review]
I have to check if the replication2 suppression are false positives or real warnings.

**Review by markuspf — APPROVED** [review]

**Review by apetenchea — APPROVED** [review]
I have looked at the replication2 lock-order-inversion warning and I believe it to be a false-positive. I'm 90% sure about this and will double-check at a later time with another colleague.
I think it's fine to suppress it.

**Comment by MBkkt** [comment]
Tests are blue, except other cluster tsan issues

**Pull request merged**
