### PR TITLE
Fix potential undefined behavior

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix potential undefined behavior when iterating over connected nodes in an execution plan and calling callbacks for each of the nodes: if the callbacks modified the list of connected nodes of the current that they were called from, this could lead to potentially undefined behavior due to iterator invalidation. The issue occurred when using a debug STL via `_GLIBCXX_DEBUG`.

I verified that the issue (debug STL assertion failure when running the cluster AQL tests) goes away with this PR.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] Backports required for: *3.7*: https://github.com/arangodb/arangodb/pull/13521, *3.6*: https://github.com/arangodb/arangodb/pull/13522

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
  - [x] Added new **integration tests** (shell_server_aql, but only with debug STL)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [x] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13911/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13922/

**Review by goedderz — APPROVED** [review]
LGTM, though this makes me wonder under which circumstances it makes sense to change dependencies of the current node, and just continue the walk to the old dependencies. It might indicate a bug in the walker where this happens.

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
> LGTM, though this makes me wonder under which circumstances it makes sense to change dependencies of the current node, and just continue the walk to the old dependencies. It might indicate a bug in the walker where this happens.

I think we first need clarification about how many optimizer rules this actually affects. I can run a test today to find this out.

**Pull request merged**
