### PR TITLE
Fix _admin/cluster/removeServer error message

### PR DESCRIPTION
**Pull request by Simran-B**
### Scope & Purpose

Code checks for HTTP `POST` method, but error message says only `DELETE` would be accepted.
This PR corrects the error message.

- [x] Bug-Fix for *devel* **(should it be backported to 3.4?)**
- [ ] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [ ] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [ ] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [ ] The behavior change can only be verified via automatic tests

#### Related Information

- [ ] There is a GitHub Issue reported by a Community User: 
- [ ] There is an internal planning ticket: 
- [ ] There is a *JIRA Ticket number* (In case a customer was affected / involved): 
- [ ] There is a design document: 

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

### Documentation

- [ ] Added a *Changelog Entry* **(should this change be added?)**
- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *http API* 
- [ ] Added *Swagger examples* for the http API

### CODE REVIEW

**Comment by Simran-B** [comment]
The error messages are inconsistent in their wording, e.g.
- only XXX requests allowed <> only the XXX method is allowed
- only to coordinators <> only coordinators can serve this request

Should that also be addressed?

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5606/

**Comment by Simran-B** [comment]
Changed "only XXX method is allowed" to "only XXX requests are allowed" to be more consistent.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7588/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1559/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
