### PR TITLE
[3.5] hotbackup path normalisation and list documentation updates

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6562/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/388/

**Comment by KVS85** [comment]
> http://jenkins.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/388/

Examples blue. exit code was wrong due to bad job execution script. Fixed in job.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
