### PR TITLE
de gray - test-shell-foxx-paths

### PR DESCRIPTION
**Pull request by ObiWahn**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7414/ -- good - unreated test red
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/9200/ -- failed hot_backup

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7431/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7439/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/9227/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/9233/

**Comment by ObiWahn** [comment]
https://github.com/arangodb/planning/issues/4682

**Comment by jsteemann** [comment]
Started a fresh test run:
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7505/

**Comment by ObiWahn** [comment]
from catch.log of above test
```
3680 [----------] 5 tests from MaintenanceFeatureTestThreaded
3681 [ RUN      ] MaintenanceFeatureTestThreaded.populate_action_queue_and_validate
3682 2019-12-02T14:11:30Z [75370] FATAL could not broadcast the condition: Invalid argument
3683 Mon Dec 02 2019 15:11:45 GMT+0100 (Central European Standard Time) Finished: ABORTED Signal: 6 Time elapsed: 44.422698974609375 - 
3684 No testresult file found at: /Users/jenkins/vm12-mac/oskar/work/tmp/arangosh_WfqNtD/gtest/testResults.json
3685 not cleaning up as some tests weren't successful:
3686 ["/Users/jenkins/vm12-mac/oskar/work/tmp/arangosh_WfqNtD/gtest_dummy"] false - false - false

```

**Pull request merged**
