### PR TITLE
make V8 gyp issue testTrackFileAccess, flush our Oskar cache

### PR DESCRIPTION
**Pull request by dothebart**
this pr fixes the `FileTracker : error FTK1011: could not create the new file tracking log file` we are seeing in conjunction with clcache by making gyp set `TrackFileAccess` in the gyp generated msbuild-files too.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/595/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6575/

http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/597/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6576/

http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/598/

**Comment by jsteemann** [comment]
@KVS85 : what's the status of this PR? Do we want to merge it now?

**Comment by jsteemann** [comment]
@kvs85: is this PR still needed or shall we close it?

**Pull request closed without merging**
