### PR TITLE
added lost gharial tests

### PR DESCRIPTION
**Pull request by hkernbach**
added lost gharial tests from 3.2 branch to 3.3

### CODE REVIEW

**Comment by hkernbach** [comment]
also fixing this: 
https://github.com/arangodb/arangodb/pull/6153

**Comment by hkernbach** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/647/

**Comment by jsteemann** [comment]
Tests failed:
```
* Test "shell_server"
    [FAILED]  js/common/tests/shell/general-graph-creation-cluster-spec.js

      "General graph creation with startup options adding collections later replication factor should be 2 for vertex collection" failed: AssertionError: expected 1 to equal 2
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:319:46)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options adding collections later replication factor should be 2 for edge collection" failed: AssertionError: expected 1 to equal 2
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:324:46)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options adding collections later replication factor should be 2 for orphan collection" failed: AssertionError: expected 1 to equal 2
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:329:46)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options adding collections later number of shards should be 3 for vertex collection" failed: AssertionError: expected 1 to equal 3
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:338:43)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options adding collections later number of shards should be 3 for edge collection" failed: AssertionError: expected 1 to equal 3
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:343:43)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options adding collections later number of shards should be 3 for orphan collection" failed: AssertionError: expected 1 to equal 3
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:348:43)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options modify edge definition replication factor should be 2 for vertex collection" failed: AssertionError: expected 1 to equal 2
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:368:46)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)

      "General graph creation with startup options modify edge definition number of shards should be 3 for vertex collection" failed: AssertionError: expected 1 to equal 3
    at Context.<anonymous> (js/common/tests/shell/general-graph-creation-cluster-spec.js:377:43)
    at Function.global.DEFINE_MODULE.exports.nextTick [as immediately] (js/common/bootstrap/modules/process.js:30:5)
   Suites failed: 1 Tests Failed: 8
```

**Comment by hkernbach** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/666/

**Comment by hkernbach** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/672/

**Comment by hkernbach** [comment]
@jsteemann jenkins is green.

**Pull request merged**
