### PR TITLE
enable rocksdb data-block hash-index

### PR DESCRIPTION
**Pull request by ObiWahn**
The VPackIndex does not use the optimization because arrays can compare
as equal even if they are not exactly equal. The default comparator in
rocksdb (BytewiseComparatorImpl), that we use in all other places, uses
the additional hash index automatically.

Please note that for legal reasons we require you to sign the 
[Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Comment by graetzer** [comment]
and whats the relation the `kHashSearch` thing we use on edge indexes ?

**Comment by danielhlarkin** [comment]
Changes look fine on a code level, but I agree with Simon that I'd like to see some basic comparison of memory usage and performance. Shouldn't need anything too in-depth, but a couple different (random) usage patterns?

@graetzer It's unclear to me what the relation is. It sounds roughly like they're for the same thing. (An index for the block-based tables?) But this is definitely a new feature of some sort, and Facebook claims it helps speed up point lookups and seek by something like 21%. https://github.com/facebook/rocksdb/blob/5f63a89b3504d981a811fb784c8da6a9732bd71d/docs/_posts/2018-08-23-data-block-hash-index.markdown

I'm cautiously optimistic, but want to see that it actually helps (or at least doesn't hurt) before we commit to it.

**Comment by jsteemann** [comment]
I agree, we definitely want to see if and how much using the extra hash index will help or hurt performance before we merge this back.

**Comment by graetzer** [comment]
@danielhlarkin I know I read the blog too. I think we need to understand this better. AFAIK the kHashSearch essentially turns the edge CF into a prefix database, where the total order of keys with different prefixes (i.e. edges in our case) is not guaranteed. 
I still need to do a deepdive into the code to understand this new index.

**Pull request closed without merging**
