### PR TITLE
fix default collection property cache enabled

### PR DESCRIPTION
**Pull request by kvahed**
### Scope & Purpose

*fix default collection property cache enabled*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [x] Backport for 3.9: *https://github.com/arangodb/arangodb/pull/16288*
  - [x] Backport for 3.8: *https://github.com/arangodb/arangodb/pull/16289*
  - [x] Backport for 3.7: *https://github.com/arangodb/arangodb/pull/16290*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM!

**Review by jsteemann — APPROVED** [review]
LGTM!

**Review by ansoboleva — APPROVED** [review]
lgtm

**Comment by ansoboleva** [comment]
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/2002/ - executed successfully. The PR can be merged now.

**Pull request merged**
