### PR TITLE
issue 400.1: implement an asynchronous task execution pool (thread pool) in IResearchFeature

### PR DESCRIPTION
**Pull request by vasiliy-arangodb**

### CODE REVIEW

**Comment by vasiliy-arangodb** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/153/

**Comment by graetzer** [comment]
This would be the third (or even fourth) thread-pool running in every arangod instance, I do not think we should include this PR. Can you explain why this thread-pool is better / different than the existing Scheduler ?
Currently there is an effort to replace the existing scheduler with something not based on `boost::asio::io_context`to increase throughput, can you work with @neunhoef to include features you might need ?

**Comment by vasiliy-arangodb** [comment]
@graetzer this is an effort to convert the thread pool per-ArangoSearch View instance (using std::thread) into one common thread pool for all of ArangoSearch (using arangodb::Thread) so as to reduce the amount of threads running in especially a cluster environment. Currently due to sharding this thread counts has been seen to exceed 100 threads in tests

**Comment by neunhoef** [comment]
I have not looked at this in detail so far. The problem is that the word "thread pool" covers a wide range of things. There are a lot of different use cases for a thread pool and I have my doubts that one implementation will be enough for all places in ArangoDB. So what we need to do is to come up with the properties/features this particular thread pool has to have and see if we already have something that fits somewhere in ArangoDB. Is performance critical here? Are there many small tasks or rather less but long running ones? Is there some kind of priority scheme needed? Is the number of threads dynamic or static?

**Comment by vasiliy-arangodb** [comment]
@neunhoef ArangoSearch views require 'commit' to be called every so often to satisfy the 'eventually-consistent' requirement
the current implementation of ArangoSearch had a thread-pool in each view instance to run a 'commit' job at configurable intervals
this has proved to create too many threads in the 'cluster' scenario (over 100 threads seen in JavaScript tests)
therefore it was decided to consolidate all the ArangoSearch View thread pools into a single thread pool accessible via the IResearchFeature

> So what we need to do is to come up with the properties/features this particular thread pool has to have
> Is performance critical here?
depends on how 'eventually-consistent'
> Are there many small tasks or rather less but long running ones?
long-running recurring tasks
> Is there some kind of priority scheme needed?
all tasks are treated equal
> Is the number of threads dynamic or static?
static based on std::thread::hardware_concurrency

**Comment by vasiliy-arangodb** [comment]
replaced with https://github.com/arangodb/arangodb/pull/5761

**Pull request closed without merging**
