### PR TITLE
Forbid indexes on _id

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Disallow indexing _id, when it is used as a sub-attribute, e.g.
`db.collection.ensureIndex({ type: "hash", fields: ["foo._id"] });`

This PR also makes `IndexFactory::instantiate(...)` return the index by value, and not fill an in/out variable.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification

Extra integration tests have been added.

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4959/

### Documentation

- [x] Added a *Changelog Entry* 
- [x] Added entry to *Release Notes* : https://github.com/arangodb/docs/pull/90

### CODE REVIEW

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4970/

**Comment by dothebart** [comment]
hm, wasn't one of our design decisions not to use exceptions for program control-flow anymore? Imho this PR goes into the opposite direction?

**Comment by jsteemann** [comment]
What part of the code are you referring to exactly? I don't see a problem with the changes.

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4972/

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4983/

**Pull request merged**
