### PR TITLE
avoid usage of potentially unsafe slices() method

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

calling slices() on the `response` member in arangodb::network::Response is potentially unsafe if there are no prior checks, as `response` can be a nullptr.

This is in response to a test failure observed in http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13716/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=(linux&&test)%7C%7Cgce/

Backport of https://github.com/arangodb/arangodb/pull/12760

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [ ] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required
- [ ] Backports required for: 

### Testing & Verification

- [x] This change is already covered by existing tests, such as *all networking tests*

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12097/

### CODE REVIEW

**Comment by graetzer** [comment]
this is really a waste of everones time. if `res.error == fuerte::Error::NoError` then `res.response != nullptr`

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12297/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/12300/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/12302/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/12306/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13907/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
