### PR TITLE
Python script to generate docs for program options (WIP)

### PR DESCRIPTION
**Pull request by Simran-B**

### CODE REVIEW

**Comment by Simran-B** [comment]
@dothebart I committed a change to the .sh and the .js scripts to make it work in Cygwin.

Furthermore enabled pretty printing for --dump-options, to play nice together with version control.

Integration of the processing script is pending, but it is already capable of printing an HTML table for arangobench to stdout. Need to discuss the format with Santo.

**Comment by dothebart** [comment]
in general I would prefer to print markdown, since thats then better debuggeable. 
I also would prefer a bullet point list over a table - you also need to test how this renders to epub & pdf

**Comment by Simran-B** [comment]
This is impossible to render to Markdown because of its limitations in regards to tables. HTML is valid Markdown however. Need to check if we need some CSS classes in addition to use the Gitbook theme.

It looks cleaner as a table IMO and follows the example of [MySQL](https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html) and [Neo4j](https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/). If you want a list instead, please convince Santo first.

**Comment by Simran-B** [comment]
generateMdFiles.py can now generate the docublocks in-memory. The checks for a full build fail however, because it tries to find the files for the program options blocks, which do not exist.

@dothebart Can you adjust the build script to ignore them? (not the whole Markdown file the docublocks are used in however)

```
Not all blocks were found on both sides:
Documentation      |     Programcode:
program_options_arangosh
Documentation:
./Manual/Administration/Arangosh/Configuration.md:@startDocuBlock program_options_arangosh
```
Usage of docublock for testing:

```diff
diff --git a/Documentation/Books/Manual/Administration/Arangosh/Configuration.md b/Documentation/Books/Manual/Administration/Arangosh/Configuration.md
index b2acb47..0fd6392 100644
--- a/Documentation/Books/Manual/Administration/Arangosh/Configuration.md
+++ b/Documentation/Books/Manual/Administration/Arangosh/Configuration.md
@@ -1,6 +1,8 @@
 ArangoDB Shell Configuration
 ============================

+@startDocuBlock program_options_arangosh
+
 _arangosh_ will look for a user-defined startup script named *.arangosh.rc* in the
 user's home directory on startup. The home directory will likely be `/home/<username>/`
 on Unix/Linux, and is determined on Windows by peeking into the environment variables
```
The actual integration of `@startDocuBlock` for the program options should happen in the administration refactor PR, not here.

Rendered result with some tweaks to the CSS:

image

**Comment by Simran-B** [comment]
Merged into https://github.com/arangodb/arangodb/pull/4907

**Pull request closed without merging**
