### PR TITLE
Bugfix Sorting Gather Executor

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose

In case of a softlimit 0 do not update a empty dependency. This triggered an assertion in maintainer mode.

It seems that the behavior in production code was correct, just suboptimal. So a CHANGELOG entry seems unnecessary.

- [x] :hankey: Bugfix 
- [ ] :book: CHANGELOG entry made
- [X] :muscle: The behavior in this PR was *manually tested*
- [X] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] Backports required for: **3.7**

### Testing & Verification

- [x] This change is already covered by existing tests, such as `tests/js/server/aql/aql-optimizer-rule-views-sorted-indexes.js`.
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added **Regression Tests**

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12118/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12149/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12162/

**Comment by goedderz** [comment]
Jenkins is blue.

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12171/

**Review by mchacki — APPROVED** [review]
LGTM

**Pull request merged**
