### PR TITLE
KShortestPathsExecutor must reset its KShortestPathFinder, including all caches.

### PR DESCRIPTION
**Pull request by markuspf**
Make sure the KShortestPathsExecutor resets the KShortestPathFinder correctly, including all caches.

Unfortunately there is no easy way to reproduce failure, so no regression test.

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9108/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9116/

**Comment by markuspf** [comment]
Jenkins blue

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9120/

**Comment by markuspf** [comment]
I added code for `ShortestPathFinder` as well.

*Note* that this PR now fixes *two separate issues*:
 * Resetting the finder when the executor is reconstructed in place
 * clearing the finder's caches when starting a new search

**Comment by KVS85** [comment]
Tests blue!

**Pull request merged**
