### PR TITLE
Bug fix 3.5/single edge definition editing

### PR DESCRIPTION
**Pull request by hkernbach**
Same as: https://github.com/arangodb/arangodb/pull/10690

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7680/

**Comment by hkernbach** [comment]
Jenkins green.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7827/

**Comment by KVS85** [comment]
Tests blue except known macOS failure (due to time-critical test):
```
* Test "catch"
    [FAILED]  basics

      "test" failed: exit code was 1

    [FAILED]  IResearchFeatureTest

      "test" failed: /Users/jenkins/vm07-mac/oskar/work/ArangoDB/tests/IResearch/IResearchFeature-test.cpp:1227
Value of: (true == deallocated1)
  Actual: false
Expected: true

   Suites failed: 2 Tests Failed: 2
```

http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-mac-onlycatch/5711/EDITION=community,limit=mac/

**Pull request merged**
