### PR TITLE
make collection counts get in sync on replication

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix collection counts on replication and getting-in-sync.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (i.e. in shell_client)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12410/

### CODE REVIEW

**Comment by danielhlarkin** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12411/

**Review by danielhlarkin — APPROVED** [review]

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux-nonmaintainercompile/11674/

**Comment by danielhlarkin** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12412/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12417/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-windows/6053/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12427/

**Review by danielhlarkin — APPROVED** [review]

**Comment by jsteemann** [comment]
Tests blue

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
