### PR TITLE
Add `taocpp::json` 3rd-party library. (MIT license)

### PR DESCRIPTION
**Pull request by ObiWahn**
Add library that we want to use for schema validation.

- [x] add to CHANGELOG
- [x] remove `src` if json tests build on all platforms (rebase)

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/10362/

**Comment by dothebart** [comment]
pls add a section to `3rdparty/README_maintainers.md` - curl can probably be removed in the same pass

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8605/

**Comment by ObiWahn** [comment]
> pls add a section to `3rdparty/README_maintainers.md` - curl can probably be removed in the same pass

- This PR has nothing to do with curl.
- This is a plain checkout of the library (docs / test / examples removed). There is nothing to add to the readme.

**Comment by dothebart** [comment]
There is. You just stated what to add.

**Comment by ObiWahn** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/8623/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8624/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8625/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8625/

**Comment by ObiWahn** [comment]
super seeded by (included in): https://github.com/arangodb/arangodb/pull/11191

**Pull request closed without merging**
