### PR TITLE
remove 404-ed callbacks from agency

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5708/

**Comment by neunhoef** [comment]
Unfortunately, the API is published, so we cannot leave out the changed entries, please revert.

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5817/

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5825/

**Pull request merged**
