### PR TITLE
more effective test for parallel traversals

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

As we can't check query execution plans for traversal parallelization, this now adds a failure point that is only triggered during parallel execution. That way the tests have an unambiguous way to tell if traversal parallelism was applied or not.

Community part of https://github.com/arangodb/enterprise/pull/604

Backport of https://github.com/arangodb/arangodb/pull/13220

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

#### Related Information

- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/604

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13215

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue except known, unrelated issue

**Review by mchacki — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
Tests blue except unrelated failure in test (which was fixed in separate commit).

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13234/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
