### PR TITLE
fixed ui behaviour when replacing a foxx app

### PR DESCRIPTION
**Pull request by hkernbach**
Same as: https://github.com/arangodb/arangodb/pull/9719

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6277/

**Comment by pluma** [comment]
@KVS85 that method was removed in my PR which was merged into this one, so I'm guessing I missed one of the references, which still needs updating. @hkernbach can you look into this?

**Comment by hkernbach** [comment]
@pluma I'm on it. Currently building 3.5 ..

**Comment by pluma** [comment]
@hkernbach also make sure to check whether this issue already exists in #9719.

**Comment by hkernbach** [comment]
Yep, will be an issue there as well.

**Pull request merged**
