### PR TITLE
Add support for nested aql queries in JS

### PR DESCRIPTION
**Pull request by pluma**
This is a port of https://github.com/arangodb/arangojs/pull/568 for ArangoDB.

The goal is to get this into 3.4.1 and 3.5.0.

/cc @mchacki FYI

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1261/

**Comment by jsteemann** [comment]
@pluma: Is there a PR for 3.4 as well?

**Comment by pluma** [comment]
The PR was created before 3.4 was detached so no.

I don't have VPN and I'm on vacation, so I can't see what jenkins has to say.

**Comment by jsteemann** [comment]
Created a PR for 3.4:
https://github.com/arangodb/arangodb/pull/6612

**Pull request merged**
