### PR TITLE
Scheduler Queue Allocations

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose

Reduced the number of allocations by creating a templated queue entry. Previously `queue` called `make_unique` on a `WorkItem` which had a `unique_function` member. In most cases, this `unique_function` allocated memory to store the lambda object. Now we manually store the lambda itself in the WorkItem and use a virtual call to invoke it. (This virtual call was previously hidden in `unique_function::operator()`).

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [x] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

*(Please pick either of the following options)*

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *all*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13091/

**Review by jsteemann — APPROVED** [review]
LGTM, but I expect merge conflicts with https://github.com/arangodb/arangodb/pull/13108.

**Comment by maierlars** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13096/

**Comment by maierlars** [comment]
image

**Pull request merged**
