### PR TITLE
Bug fix 3.3/little weekend fix

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7369/

**Comment by jsteemann** [comment]
@obiwahn: Wrong branch names used in Jenkins build... Please restart with correct branches

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7392/

**Comment by jsteemann** [comment]
IMHO this is ready to merge, although the Mac tests showed compile errors. But they seem to be totally unrelated and are probably caused by an incompatible compiler used for 3.3.

**Comment by KVS85** [comment]
ports:

 - [x] 3.4 -- https://github.com/arangodb/arangodb/pull/10526
 - [x] 3.5 -- https://github.com/arangodb/arangodb/pull/10527
 - [x] devel -- https://github.com/arangodb/arangodb/pull/10518

**Pull request closed without merging**
