### PR TITLE
Fix race bug in gtest.

### PR DESCRIPTION
**Pull request by neunhoef**
A local AgencyCallback object does not need an AgencyComm instance.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11302/

**Comment by neunhoef** [comment]
This has a green test, pending review, it is good to go.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11307/

**Comment by jsteemann** [comment]
Tests blue except clcache failure on Windows

**Comment by neunhoef** [comment]
I think this is good to go.

**Pull request merged**
