### PR TITLE
Atomic query killing

### PR DESCRIPTION
**Pull request by graetzer**
Make cleanup and killing exclusive operations

### CODE REVIEW

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10812/

**Comment by graetzer** [comment]
https://172.16.10.101/job/arangodb-matrix-pr/10881/

**Comment by graetzer** [comment]
https://172.16.10.101/job/arangodb-matrix-pr/10888/

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10921/

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10923/

**Comment by jsteemann** [comment]
Still has one test failure:
```
* Test "shell_client_3"
    [FAILED]  tests/js/client/shell/shell-transaction.js

      "testAbortWriteTransactionAQL" failed: Error: at assertion #3: assertTrue: (false) does not evaluate to true
(Error
    at assertTrue (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:71:19)
    at Object.testAbortWriteTransactionAQL (tests/js/client/shell/shell-transaction.js:755:9)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:549:27)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:276:24)
    at tests/js/client/shell/shell-transaction.js:4337:9
    at tests/js/client/shell/shell-transaction.js:4348:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:390:12)
    at testFunc (eval at runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:881:3), <anonymous>:4:9)
    at runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:885:18)
    at Object.performTests (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:233:21))
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:569:23)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:276:24)
    at tests/js/client/shell/shell-transaction.js:4337:9
    at tests/js/client/shell/shell-transaction.js:4348:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:390:12)
    at testFunc (eval at runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:881:3), <anonymous>:4:9)
    at runInLocalArangosh (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:885:18)
    at Object.performTests (/work/ArangoDB/js/client/modules/@arangodb/test-utils.js:233:21)
    at Object.shellClient [as shell_client] (/work/ArangoDB/js/client/modules/@arangodb/testsuites/aql.js:60:13)
    at iterateTests (/work/ArangoDB/js/client/modules/@arangodb/testing.js:506:36) - test failed

   Suites failed: 1 Tests Failed: 1

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10936/

**Comment by jsteemann** [comment]
Another crash, also in `load_balancing` tests:
``` 
Tue Jul 07 2020 19:35:30 GMT+0200 (Central European Summer Time) arangosh: Running JSUnity test from file '/home/jsteemann/ArangoNoAsan/tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js'
2020-07-07T17:35:30.040Z [------------] 3 tests from QueriesSuite (setUpAll: 0ms)
2020-07-07T17:35:30.040Z [ RUN        ] testCurrentQueriesCoordinator
2020-07-07T17:35:30Z [234280] C WARNING [25cc4] {general} killing AQL query 2199025265634 'RETURN SLEEP(100000)'
2020-07-07T17:35:30Z [234280] C WARNING [11928] {general} caught exception in RestCursorHandler: AQL: query killed (while executing)
2020-07-07T17:35:30.554Z [     PASSED ] testCurrentQueriesCoordinator (setUp: 0ms, test: 514ms, tearDown: 0ms)
2020-07-07T17:35:30.555Z [ RUN        ] testCurrentQueriesDBServer
2020-07-07T17:35:31Z [234280] C WARNING [25cc4] {general} killing AQL query 2199025265650 'FOR i IN 1..10000000 INSERT {} INTO UnitTestsCollection'
2020-07-07T17:35:31Z [234280] C WARNING [33cfb] {aql} engine snippet '2010099' is still in use
2020-07-07T17:35:31Z [234280] C FATAL [a7902] {crash} ArangoDB 3.8.0-devel enterprise [linux], thread 5 [SchedWorker] caught unexpected signal 6 (SIGABRT): assertion failed in /home/jsteemann/ArangoNoAsan/arangod/Aql/AqlItemBlock.cpp:1108: _refCount > 0
2020-07-07T17:35:31Z [234280] C WARNING [11928] {general} caught exception in RestCursorHandler: AQL: query killed (while executing)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 1 [0x0000562068d8c273] arangodb::CrashHandler::assertionFailure(char const*, int, char const*) (+0x00000000000000e3)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 2 [0x0000562067842384] arangodb::aql::AqlItemBlock::decrRefCount() const (+0x0000000000000034)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 3 [0x00005620678b60d3] void arangodb::aql::ExecutionBlockImpl<arangodb::aql::IdExecutor<arangodb::aql::ConstFetcher> >::injectConstantBlock<arangodb::aql::IdExecutor<arangodb::aql::ConstFetcher>, void>(arangodb::aql::SharedAqlItemBlockPtr, arangodb::aql::SkipResult) (+0x0000000000000113)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 4 [0x0000562067caf022] arangodb::aql::DistributeClientBlock::execute(arangodb::aql::AqlCallStack, arangodb::aql::ExecutionState) (+0x0000000000000132)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 5 [0x0000562067c87ebb] arangodb::aql::BlocksWithClientsImpl<arangodb::aql::DistributeExecutor>::executeWithoutTraceForClient(arangodb::aql::AqlCallStack, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (+0x000000000000058b)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 6 [0x0000562067c8888a] non-virtual thunk to arangodb::aql::BlocksWithClientsImpl<arangodb::aql::DistributeExecutor>::executeForClient(arangodb::aql::AqlCallStack, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (+0x000000000000021a)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 7 [0x0000562067a0cfd1] arangodb::aql::ExecutionEngine::executeForClient(arangodb::aql::AqlCallStack const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (+0x00000000000002c1)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 8 [0x00005620677f672d] arangodb::aql::RestAqlHandler::handleUseQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arangodb::velocypack::Slice) (+0x0000000000000b0d)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 9 [0x00005620677f807e] arangodb::aql::RestAqlHandler::useQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (+0x000000000000035e)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 10 [0x00005620677fdad9] arangodb::aql::RestAqlHandler::execute() (+0x0000000000000c29)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 11 [0x00005620673a9f1e] arangodb::rest::RestHandler::executeEngine(bool) (+0x000000000000010e)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 12 [0x00005620673aaf6a] arangodb::rest::RestHandler::runHandlerStateMachine() (+0x000000000000048a)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 13 [0x00005620677497af] fu2::abi_400::detail::type_erasure::invocation_table::function_trait<void ()>::internal_invoker<fu2::abi_400::detail::type_erasure::box<false, arangodb::rest::CommTask::handleRequestSync(std::shared_ptr<arangodb::rest::RestHandler>)::{lambda()#1}, std::allocator<{lambda()#1}> >, false>::invoke(fu2::abi_400::detail::type_erasure::data_accessor*, unsigned long) (+0x000000000000010f)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 14 [0x000056206753b3b0] arangodb::SupervisedScheduler::runWorker() (+0x00000000000001c0)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 15 [0x0000562068db5040] arangodb::Thread::runMe() (+0x0000000000000030)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 16 [0x0000562068db5153] arangodb::Thread::startThread(void*) (+0x0000000000000083)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 17 [0x0000562068e87d1a] ThreadStarter(void*) (+0x000000000000003a)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 18 [0x00007fbb5ac08609] start_thread (+0x00000000000000d9)
2020-07-07T17:35:31Z [234280] C INFO [308c3] {crash} frame 19 [0x00007fbb5a410103] clone (+0x0000000000000043)
2020-07-07T17:35:31Z [234280] C INFO [ded81] {crash} available physical memory: 41722015744, rss usage: 160681984, vsz usage: 942448640, threads: 38
2020-07-07T17:35:31Z [234279] P ERROR [abcdf] {communication} communication error: 'Connection reset by peer'
2020-07-07T17:35:31.599Z [     PASSED ] testCurrentQueriesDBServer (setUp: 0ms, test: 1044ms, tearDown: 0ms)
2020-07-07T17:35:31.599Z [ RUN        ] testSlowQueries
2020-07-07T17:35:42Z [234281] C WARNING [8bcee] {queries} slow query: 'RETURN SLEEP(11)', bind vars: {}, took: 11.010505 s
2020-07-07T17:35:42.625Z [   FAILED   ] testSlowQueries (setUp: 0ms, test: 11026ms, tearDown: 0ms)
Error: at assertion #1: assertEqual: (200) is not equal to (500)
(Error
    at assertEqual (/home/jsteemann/ArangoNoAsan/js/common/modules/jsunity/jsunity.js:108:19)
    at Object.testSlowQueries (/home/jsteemann/ArangoNoAsan/tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js:230:7)
```

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10989/

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10998/

**Comment by jsteemann** [comment]
Yes!

**Pull request merged**
