### PR TITLE
Fix BTS-33

### PR DESCRIPTION
**Pull request by markuspf**
If a `SubqueryStartExecutor` encountered shadow rows, it did sometimes not write remaining data rows leading to incomplete query results. See also internal bug BTS-33.

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9207/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9208/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9209/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9291/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9294/

**Comment by mchacki** [comment]
New Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9305/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9330/

**Comment by mchacki** [comment]
Jenkins:

http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9396/

finally all blue.
Thanks all for the joint effort!

**Pull request merged**
