### PR TITLE
backoff windows - replication requires to many tcp connections

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

release pressure on the windows CI: replication factor 1 is enough.

- [x] :hankey: Bugfix revert for windows CI stability

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/

**Comment by fceller** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/14256/

**Comment by fceller** [comment]
@dothebart the PR is complete blue

**Review by fceller — APPROVED** [review]
LGTM

**Review by jsteemann — APPROVED** [review]

**Pull request merged**
