### PR TITLE
Ensure hotbackup agency lock is released under all circumstances.

### PR DESCRIPTION
**Pull request by neunhoef**
We have some reports that sometimes the hotbackup agency lock can be left behind. This was happening in https://arangodb.atlassian.net/browse/OASIS-252 and in other tickets. This PR addresses this problem although we never fully understood how this problem actually arises. In this PR, scope guards are used to ensure proper cleanup of the agency lock.

### CODE REVIEW

**Comment by neunhoef** [comment]
This needs some more backports from the `devel` version.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10950/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10955/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
