### PR TITLE
Bug in behaviour of ignoreRevs=false

### PR DESCRIPTION
**Pull request by neunhoef**
There is a small bug in the implementation of our API. If one updates
(or replaces) a single document and gives the key only in the URL
but not in the body of the document, and also adds the option
ignoreRevs=false and specifies the _rev in the body, then this
rev is silently rewritten to 0 due to a bug.

This PR fixes this bug. Also see #13232.

### Scope & Purpose

*(Please describe the changes in this PR for reviewers)*

- [*] :hankey: Bugfix 

#### Backports:

- [ ] No backports required
- [*] Backports required for: 3.6, 3.7

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [*] This PR adds tests that were used to verify all changes:
  - [*] Added **Regression Tests**

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13703/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13704/

**Review by fceller — APPROVED** [review]
LGTM

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
