### PR TITLE
[SEARCH-379] Pass transaction for optimization to supportIndexCondition

### PR DESCRIPTION
**Pull request by gnusi**
### Scope & Purpose

Pass transaction for optimization to `Index::supportIndexCondition`, `Index::specializeCondition`.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by Dronplane — APPROVED** [review]
LGTM

**Comment by Dronplane** [comment]
But we need a test for the issue. Just in case.

**Comment by gnusi** [comment]
@Dronplane will address is a separate PR

**Review by MBkkt — APPROVED** [review]

**Review by jsteemann — APPROVED** [review]
LGTM!

**Review by mchacki — APPROVED** [review]
The change is okay.

However for the next time please add that this is a bugfix on existing code, but not a new feature change. I had hard time to figure out that the change proposed here fixes a side effect that is not even Part of the files in this PR.

Also please add some information on "WHY" the transaction is now passed into those messages, makes it much easier for a reviewer to understand what is going on.

I am missing a test for the actual issue. I am only approving this as @gnusi promised to add this test in a follow up PR.

**Pull request merged**
