### PR TITLE
Bug fix 3.7/re add ability udf emmit error

### PR DESCRIPTION
**Pull request by dothebart**
forward port of https://github.com/arangodb/arangodb/pull/11995

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10697/

**Comment by dothebart** [comment]
all blue.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10721/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
