### PR TITLE
clean up usage costs

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Split Index::UsageCosts into FilterCosts and SortCosts

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behaviour change can only be verified via automatic tests

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/262

### Testing & Verification

This change is already covered by existing tests, such as *all AQL tests which pick indexes*.

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4824/

### CODE REVIEW

**Comment by danielhlarkin** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4850/

**Comment by danielhlarkin** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/4876/

**Comment by fceller** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/6476/

**Comment by fceller** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4879/

**Comment by danielhlarkin** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4886/

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4960/

**Pull request merged**
