### PR TITLE
attempt to fix unstable test

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Attempt to fix the following unstable integration test:
```
=== server_parameters ===
* Test "server_parameters" [FAILED]  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js

      "testUpdateEdgeDisbled" failed: Error: at assertion #5003: {
  "writesExecuted" : 0, "writesIgnored" : 0, "scannedFull" : 0, "scannedIndex" : 5000, "cursorsCreated" : 1, "cursorsRearmed" : 4999, "cacheHits" : 1147, "cacheMisses" : 3853, "filtered" : 0, "httpRequests" : 0, "executionTime" : 0.02600592700036941, "peakMemoryUsage" : 98304 }: (1147) is not equal to (0)
(Error
    at assertEqual (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:108:19)
    at runCheck (tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js:64:7)
    at Object.testUpdateEdgeDisbled (tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js:151:7)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:552:27)
```

Test-only bugfix. Intentionally no CHANGELOG entry written for it.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [x] Backport for 3.10: https://github.com/arangodb/arangodb/pull/17931
  - [ ] Backport for 3.9: -
  - [ ] Backport for 3.8: -

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by MBkkt — CHANGES_REQUESTED** [review]
It looks like waitForMetrics() needs after every query here.

For an example

```js
    testUpdateEdgeEnabled: function() {
      db._query(`FOR i IN 0..${n - 1} INSERT {_from: CONCAT('v/test', i), _to: CONCAT('v/test', (i % 25))} INTO ${cn}`);
      waitForMetrics();

      const oldValue = getMetric("rocksdb_cache_auto_refill_loaded_total");
      db._query(`FOR doc IN ${cn} UPDATE doc WITH {value: doc.value + 1} INTO ${cn}`);
      const newValue = getMetric("rocksdb_cache_auto_refill_loaded_total");
      assertTrue(newValue - oldValue >= 2 * n, { oldValue, newValue });
      waitForMetrics();
      runCheck(true);
    }
```

looks incorrect, probably should be

```js
    testUpdateEdgeEnabled: function() {
      db._query(`FOR i IN 0..${n - 1} INSERT {_from: CONCAT('v/test', i), _to: CONCAT('v/test', (i % 25))} INTO ${cn}`);
      waitForMetrics();
      const oldValue = getMetric("rocksdb_cache_auto_refill_loaded_total");

      db._query(`FOR doc IN ${cn} UPDATE doc WITH {value: doc.value + 1} INTO ${cn}`);
      waitForMetrics();
      const newValue = getMetric("rocksdb_cache_auto_refill_loaded_total");

      assertTrue(newValue - oldValue >= 2 * n, { oldValue, newValue });
      runCheck(true);
    }
```

**Comment by jsteemann** [comment]
> It looks like waitForMetrics() needs after every query here.
> 
> For an example
> 
> ```js
>     testUpdateEdgeEnabled: function() {
>       db._query(`FOR i IN 0..${n - 1} INSERT {_from: CONCAT('v/test', i), _to: CONCAT('v/test', (i % 25))} INTO ${cn}`);
>       waitForMetrics();
> 
>       const oldValue = getMetric("rocksdb_cache_auto_refill_loaded_total");
>       db._query(`FOR doc IN ${cn} UPDATE doc WITH {value: doc.value + 1} INTO ${cn}`);
>       const newValue = getMetric("rocksdb_cache_auto_refill_loaded_total");
>       assertTrue(newValue - oldValue >= 2 * n, { oldValue, newValue });
>       waitForMetrics();
>       runCheck(true);
>     }
> ```
> 
> looks incorrect, probably should be
> 
> ```js
>     testUpdateEdgeEnabled: function() {
>       db._query(`FOR i IN 0..${n - 1} INSERT {_from: CONCAT('v/test', i), _to: CONCAT('v/test', (i % 25))} INTO ${cn}`);
>       waitForMetrics();
>       const oldValue = getMetric("rocksdb_cache_auto_refill_loaded_total");
> 
>       db._query(`FOR doc IN ${cn} UPDATE doc WITH {value: doc.value + 1} INTO ${cn}`);
>       waitForMetrics();
>       const newValue = getMetric("rocksdb_cache_auto_refill_loaded_total");
> 
>       assertTrue(newValue - oldValue >= 2 * n, { oldValue, newValue });
>       runCheck(true);
>     }
> ```

I don't get the example here. In the original code you used as an example, there **is** already a `waitForMetrics()` call after the UPDATE query. It does not follow the `db._query()` directly, but follows the `getMetric()` call, however, it is there already.

**Comment by MBkkt** [comment]
> it is there already
@jsteemann 
Yes, my claim it's is strange to call waitForMetrics after call get metrics

**Comment by jsteemann** [comment]
> > it is there already
> 
> @jsteemann
> 
> Yes, my claim it's is strange to call waitForMetrics after call get metrics

Despite the function names, the two shouldn't depend on each other, so their order should not matter.

**Comment by MBkkt** [comment]
> Despite the function names, the two shouldn't depend on each other, so their order should not matter.

Ok but maybe it will be more clear?
Anyway is true for all tests with same issue?

Btw I still don't understand why do you need call waitForMetrics before first get metrics, and don't need for second

**Comment by jsteemann** [comment]
> > Despite the function names, the two shouldn't depend on each other, so their order should not matter.
> 
> Ok but maybe it will be more clear? Anyway is true for all tests with same issue?
> 
> Btw I still don't understand why do you need call waitForMetrics before first get metrics, and don't need for second

I will add some comments to the tests now...

**Review by MBkkt — APPROVED** [review]
To remove request changes, still don't understand honestly

**Review by MBkkt — COMMENTED** [review]
Ok. I'm understand now, thanks!

**Pull request merged**
