### PR TITLE
3.11 backport for BTS-1340

### PR DESCRIPTION
**Pull request by cpjulia**
### Scope & Purpose

Backport for https://github.com/arangodb/arangodb/pull/18854.
Fixed telemetrics api making shell hang when logging into it and leaving it too quickly so the telemetrics API doesn't have time to send the data to the warehouse. The thread could be hanging on SSL_connect() until the connection timeout if the socket is blocking, so the socket was made non-blocking for the thread to leave SSL_connect() after the connection is interrupted when leaving the shell.

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM

**Review by apetenchea — APPROVED** [review]
LGTM

**Review by Dronplane — CHANGES_REQUESTED** [review]
Please see me comments to the original PR. There are some suspicious places.

**Review by Dronplane — APPROVED** [review]
LGTM

**Review by jsteemann — COMMENTED** [review]
LGTM

**Pull request merged**
