### PR TITLE
Update ChangeRootPassword.md

### PR DESCRIPTION
**Pull request by RobertShaw1**
Please note that for legal reasons we require you to sign the 
[Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Comment by RobertShaw1** [comment]
After submitting the pull request, I realize the documentation is probably intentionally generic to accommodate multiple OS's.  However, I feel there should be some information in the docs about how to stop/start/restart the server and the likely location of the arangod.conf file.

I was able to install arangodb with no problems.  The next day I went to go log into the Web GUI and for some reason, the authentication did not work.  After some google searching, I learned that many new users are having this same issue.  Makes me think there's a bug which I'm sure has been reported and is in the process of being corrected.  But in the meantime, I think a quick update to the docs to help folks _Change the Root password_ would help those running into this failed auth issue.

**Comment by dothebart** [comment]
Heh, I just found out some places were we log instructions that would only work with linux, so this PR has good company ;-) Maybe creating a page that lists all possibilities and referencing that would be a good thing to do.

**Comment by sleto-it** [comment]
Thanks for your PR and feedback

I agree on the importance of having a page with info per OS on how to stop, start, restart the server

There is a PR work in progress with info on how to start and stop the server. That page has info per operating system. So we can just link this page, and leave "stop" and "restart" generic here (that was the idea)

Regarding file typically located at `/usr/local/etc/arangodb3/arangod.conf` , this is not true in all cases (even on linux) as if the starter is in use, the conf file is in the starter data dir

PR https://github.com/arangodb/arangodb/pull/5830 (work in progress)

**Comment by RobertShaw1** [comment]
Thanks for the responses, gents!  I'll close this PR.

**Pull request closed without merging**
