### PR TITLE
Issue #8941

### PR DESCRIPTION
**Pull request by RudySchockaert-EngieIT**
### Scope & Purpose

This PR fixes the bug where the "Users" menu does not function when running arangodb behind a reverse proxy and the 'basePath' is not empty. (e.g. https://myserver/basepath/_db/_system/_admin/aardvark/index.html)

- [ ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [ ] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [ ] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [ ] The behaviour change can only be verified via automatic tests

#### Related Information

Issue #8941

- [x] There is a GitHub Issue reported by a Community User: 
- [ ] There is an internal planning ticket: 
- [ ] There is a *JIRA Ticket number* (In case a customer was affected / involved): 
- [ ] There is a design document: 

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by hkernbach** [comment]
Thanks for the PR. Needs further investigations.

**Comment by joerg84** [comment]
@hkernbach is there an update here or can we close?

**Comment by hkernbach** [comment]
@joerg84 This still needs to be verified and tested
=> Setup reverse proxy + ArangoDB & test.

**Comment by jsteemann** [comment]
@RudySchockaert-EngieIT : thanks for the PR! Apparently it took a little while for us to get this in, but the change is now in our devel branch, and expected to be released with ArangoDB 3.7.

**Pull request merged**
