### PR TITLE
make graphs transaction-aware

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Make graphs in general-graph transaction aware

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/302

- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [ ] Added new **integration tests** (i.e. in shell_client, shell-graph-transaction.js)

https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5945/

### CODE REVIEW

**Comment by jsteemann** [comment]
We probably need to add additional tests for smart graphs here as well.

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5952/

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5958/

**Comment by Simran-B** [comment]
@jsteemann This fixes the following known issue, correct?

> Stream Transactions currently do not support the graph operations that are initiated via the general-graph JavaScript module or via the REST API at /_api/gharial. Right now these operations will act as if no stream transaction is present. Stream transaction support for these operations will be added later.

**Comment by Simran-B** [comment]
Using a single server:

```js
> sg._create("sg1", [], [], {replicationFactor:2, numberOfShards: 3, smartGraphAttribute: "foo"});
{[SmartGraph]
}

> sg._listObjects();
[
  {
    "_key" : "sg1",
    "_id" : "_graphs/sg1",
    "_rev" : "_ZMH8leq---",
    "numberOfShards" : 3,
    "replicationFactor" : 2,
    "minReplicationFactor" : 1,
    "isSmart" : false,
    "edgeDefinitions" : [ ],
    "orphanCollections" : [ ]
  }
]
```

It creates a general-graph (non-smart).

Using `./scripts/startLocalCluster.sh -d 3 -b 1300` on c9, I get a coordinator crash when adding a vertex collection?!

> sg._create("sg1", [], [], {replicationFactor:2, numberOfShards: 3, smartGraphAttribute: "foo"});
> sg._graph("sg1")._addVertexCollection("orphan1");

JavaScript exception in file '/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 2001: Connection reset by peer
!      throw error;
!      ^
stacktrace: ArangoError: Connection reset by peer
    at Object.exports.checkRequestResult (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arangosh.js:97:21)
    at SmartGraph.CommonGraph._addVertexCollection (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/general-graph.js:106:34)
    at <shell command>:1:18

`/home/simran/oskar/work/ArangoDB/core-27015-1567169242` on c9

**Comment by KVS85** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5996/

**Comment by jsteemann** [comment]
@KVS85 : the above failures are completely unrelated to this PR.
The tests fails if there are a different number of views present in the system than the tests expect.
Nothing in this PR has anything to do with that.

The test assumptions for the failing view tests are not safe, by the way. Because they don't take into account that there may be some other views present in the system, which the tests didn't set up.
So if any other test leaves a view around, these tests will all fail.

**Comment by dothebart** [comment]
@jsteemann testing.js will make a test fail that doesn't clean up views after itself afaik - one of the first things @kvs85 implemented.

**Comment by jsteemann** [comment]
@dothebart : yes, sure. but what is the relation to this PR?

**Comment by dothebart** [comment]
its `shell-view-arangosearch.js` itself that probably doesn't shutdown & delete a view properly.

**Pull request merged**
