### PR TITLE
introduce AqlItemBlock::_nrEffectiveItems

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Introduce `_nrEffectiveItems` for AqlItemBlock, which keeps track of the maximum modified (i.e. written-to) row number in the AqlItemBlock.
It is updated on every write, and read back when mass operations, such as cleanup or copying, or executed for all rows of the block. The idea is that such operations can be saved for rows that are known to be empty anyway.

This is a minimal backport of https://github.com/arangodb/arangodb/pull/12473, omitting all the renamings done in that PR.

- [ ] :hankey: Bugfix 
- [x] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required
- [ ] Backports required for

### Testing & Verification

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [x] This change is already covered by existing tests, such as *shell_server_aql*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11543/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Review by graetzer — APPROVED** [review]

**Comment by graetzer** [comment]
I think you could rename it to maxModifiedIndex

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11623/

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
