### PR TITLE
fix a crash in FieldIterator::next()

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

FieldIterator::next() unconditionally subtracts a value of 2 from the end of its `_stack` member, which can make the operation point before the beginning of the `_stack` storage of `_stack` has less than 2 members.
There is a follow-up check to check if the subtracted value is at least a big as `_stack.begin()`, but this may be too late.

Using a debug STL build (`_GLIBCXX_DEBUG`) already crashes when subtracting 2 from the container's end:
```
2021-02-10T01:28:38.955Z [============] runInArangod: Trying tests/js/server/aql/aql-arangosearch-count-optimization.js ...
/usr/include/c++/10/debug/safe_iterator.h:924:
In function:
    __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<arangodb::iresearch::FieldIterator::Level*,
    std::__cxx1998::vector<arangodb::iresearch::FieldIterator::Level,
    std::allocator<arangodb::iresearch::FieldIterator::Level> > >,
    std::__debug::vector<arangodb::iresearch::FieldIterator::Level>,
    std::random_access_iterator_tag>::_Self __gnu_debug::operator-(const
    _Self&,
    __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<arangodb::iresearch::FieldIterator::Level*,
    std::__cxx1998::vector<arangodb::iresearch::FieldIterator::Level,
    std::allocator<arangodb::iresearch::FieldIterator::Level> > >,
    std::__debug::vector<arangodb::iresearch::FieldIterator::Level>,
    std::random_access_iterator_tag>::difference_type)

Error: attempt to retreat a past-the-end iterator 2 steps, which falls
outside its valid range.

Objects involved in the operation:
    iterator @ 0x0x7f09585f93e0 {
      type = __gnu_cxx::__normal_iterator<arangodb::iresearch::FieldIterator::Level*, std::__cxx1998::vector<arangodb::iresearch::FieldIterator::Level, std::allocator<arangodb::iresearch::FieldIterator::Level> > > (mutable iterator);
      state = past-the-end;
      references sequence with type 'std::__debug::vector<arangodb::iresearch::FieldIterator::Level, std::allocator<arangodb::iresearch::FieldIterator::Level> >' @ 0x0x7f09585f9850
    }
```

I have never seen this cause any issues without a debug STL build, but this could be just luck and is not necessarily portable.

Note: 3.7 does not seem to be affected by this issue. At least there is no subtraction of `2` in IResearchDocument there.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *shell_server_aql*.
- [x] I ensured this code runs with ASan / TSan or other static verification tools (`_GLIBCXX_DEBUG`)

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13915/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13919/

**Comment by jsteemann** [comment]
Waiting for alternative bugfix from @gnusi / @Dronplane

**Comment by jsteemann** [comment]
I added this PR to enable `_GLIBCXX_DEBUG` when building with gcc in maintainer mode:
https://github.com/arangodb/arangodb/pull/13550

That PR can only be merged once this issue here is fixed.

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13996/

**Pull request merged**
