### PR TITLE
fixed gauge assignment operatorsd

### PR DESCRIPTION
**Pull request by kvahed**
### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [X] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [X] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [X] Backports required for: *3.7*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [X] This change is a trivial rework / code cleanup without any test coverage.
- [X] The behavior in this PR was *manually tested*
- [X] This change is already covered by existing tests, such as *Guage*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/12815/

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Review by neunhoef — APPROVED** [review]
LGTM

**Review by neunhoef — APPROVED** [review]
LGTM.

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/12797/

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by neunhoef** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/13040/

**Comment by danielhlarkin** [comment]
After some discussion with @mpoeter we think we should use a parameterized memory order with a default of sequential consistency. That preserves existing behavior, but would allow us to relax it where it makes sense, and more closely mimic the default `std::atomic` interfaces. @kvahed Would you mind if I make these changes directly in this branch to move things along?

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by neunhoef** [comment]
The `std::memory_order_seq_cst` is now the default. Since `operator+=` and friends cannot take an additional parameter, currently it is not possible to specify the order. However, we can always introduce `fetch_add` and the like if this is needed. But this can be done later.

**Comment by neunhoef** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/13083/

**Comment by mpoeter** [comment]
> we can always introduce `fetch_add` and the like if this is needed. But this can be done later.

That would be my suggestion as well, as I prefer to specify the memory order explicitly.

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/13265/

**Comment by kvahed** [comment]
image

**Pull request closed without merging**
