### PR TITLE
Feature 3.6/improved observability

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This PR improves observability in the following ways:

* Add database, shard name and error information to several shard-related log messages.
* Display shard names of a collection in the web interface when in the details view of the collection.
* Added HTTP requests metrics for tracking the number of superuser and normal user requests separately:
  - `arangodb_http_request_statistics_superuser_requests`: Total number of HTTP requests executed by superuser/JWT
  - `arangodb_http_request_statistics_user_requests`: Total number of HTTP requests executed by clients

This PR also contains all commits from https://github.com/arangodb/arangodb/pull/12751, which will make no difference when this gets merged into 3.6.

- [ ] :hankey: Bugfix 
- [x] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x]:muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12086/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12087/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12090/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12094/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12111/

**Comment by jsteemann** [comment]
Tests blue

**Review by dothebart — APPROVED** [review]

**Comment by dothebart** [comment]
can we have something similar for the shutdown code so we know database/collection of the lock we fail to acquire (if)?

**Comment by KVS85** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12143/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12157/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12158/

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12165/

**Review by KVS85 — APPROVED** [review]

**Comment by KVS85** [comment]
Tests (expectedly) blue.

**Pull request merged**
