### PR TITLE
Specialize scheduler pointer to allow devirtualization of method calls

### PR DESCRIPTION
**Pull request by goedderz**

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4816/

**Comment by maierlars** [comment]
This might be a optimization for now, but the idea was to have multiple implementations of the scheduler for different work loads.

**Comment by graetzer** [comment]
is this actually a measureable optimization?

**Comment by goedderz** [comment]
@maierlars As I understood it, the used scheduler will be fixed per lane, so this will still be possible either way. @graetzer yes, specifically this way: https://github.com/arangodb/arangodb/pull/9224/files?file-filters%5B%5D=.cpp&owned-by%5B%5D=#diff-c51b8ac1a0cdb9e4a2ac2b8cd64076af

This is obviously a micro optimization, and will not have much impact. But it's a really minor change, too, and the scheduler's performance affects a lot of things, so I decided to do it.

**Comment by goedderz** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4894/

**Comment by goedderz** [comment]
Jenkins looks fine.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4915/

**Pull request merged**
