### PR TITLE
Sort shard name lists numerically.

### PR DESCRIPTION
**Pull request by neunhoef**

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8315/

**Comment by jsteemann** [comment]
ClusterInfo.cpp, lines 974 - 983 should also use that new function!

**Comment by neunhoef** [comment]
Right, good catch!

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8316/ new run after latest change.

**Pull request merged**
