### PR TITLE
[3.6] Add kill-check during early pruning

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #13151. Includes #13183.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13046/

**Review by jsteemann — APPROVED** [review]

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13067/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13122/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13129/

**Comment by jsteemann** [comment]
Tests blue

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
