### PR TITLE
Feature/aql subquery execute remote node api flag

### PR DESCRIPTION
**Pull request by goedderz**
Add a flag to the RemoteNode whether to either use the execute or getSome/skipSome API.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8720/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8722/

**Comment by goedderz** [comment]
> LGTM, I assume this will be removed again when we're done with the Umbau?

Not quite. We need it for rolling upgrades from 3.6 to 3.7 and can remove it in 3.8.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8727/

**Comment by mchacki** [comment]
The jenkins errors here have been fixed in base branch.

**Pull request merged**
