### PR TITLE
[3.5] Bug fix/fix undeterministic traversal test

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #10688

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7684/

**Comment by goedderz** [comment]
Jenkins is blue.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7828/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
