### PR TITLE
fix BTS-57

### PR DESCRIPTION
**Pull request by graetzer**
Unclear if good idea, this no longer really prevents for multiple writing AQL queries on the same transaction. 

http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10042/

### CODE REVIEW

**Comment by graetzer** [comment]
close ticket when done: https://arangodb.atlassian.net/browse/BTS-57

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10148/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/10150/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/10151/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/10154/

**Pull request merged**
