### PR TITLE
Improve Cluster udfs

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11429/

https://arangodb.atlassian.net/browse/BTS-159

### CODE REVIEW

**Comment by joerg84** [comment]
@graetzer I believe we need backports of this as well or?

**Comment by graetzer** [comment]
I don’t know, essentially UDFs do not work in the cluster since > 1 year, seems almost like an unused feature to me

**Comment by markuspf** [comment]
It is at least used by the people who submitted the bug report.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11442/

**Pull request merged**
