### PR TITLE
added updateDeps

### PR DESCRIPTION
**Pull request by sarasfox**
Added updateDeps to foxx-manager cli for use with salt. please give good look over this.

### CODE REVIEW

**Comment by pluma** [comment]
Thanks!

**Comment by pluma** [comment]
This actually seems to duplicate the `set-dependencies` command except the URL it uses doesn't seem to exist.

**Comment by sarasfox** [comment]
That if I can use it from foxx-manger CLI as recall the collect that held
config and collect were different and foxx- manger had no way to setup the
mount point for a dependence. For salt this requirement.

**Comment by pluma** [comment]
Yeah, that's what the set-dependencies command does.

**Pull request merged**
