### PR TITLE
Doc - New Driver Book

### PR DESCRIPTION
**Pull request by sleto-it**
- Adds new Driver book
- Implement sync mechanism with external repos

### CODE REVIEW

**Comment by sleto-it** [comment]
@Simran-B FYI, low priority, but we can still do some work here. I will work on the toc (so that the pages can be copied from the external repos) and you can work on the other structure details (the link in the horizontal bar, the search, etc) - try to compile. Thanks

**Comment by Simran-B** [comment]
@sleto-it This will require some redesigning I guess, because we can't really fit any more elements in mobile layouts. Perhaps this is the opportunity to scrap the old hackish header and replace it with something more extensible (based on React)?

**Comment by sleto-it** [comment]
thanks @Simran-B 

about that https://github.com/arangodb/arangodb/pull/4825/commits/ae6b1e1e08562ef874d15d924261659489c7e710 : you will need to open pr in the respective repo, otherwise next time I will pull from them we will lose your changes

i think you can use the PRs that are open already, and push there

thanks,

**Comment by Simran-B** [comment]
@sleto-it My bad, reverted the changes to non-local files and pushed them in the external repo PRs.

**Pull request merged**
