### PR TITLE
Fixing heartbeat agency update.

### PR DESCRIPTION
**Pull request by maierlars**
The heartbeat thread updates the agency endpoint once per second but did not put the leader in front, instead it put them in lexicographic order. Thus in case the leader is not the first server, each server in the cluster forgets every second which server was the actual leader and asked the first named follower, just to be redirected immediately.

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7148/

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7151/

**Comment by neunhoef** [comment]
This can and should be merged for 3.4.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7834/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1809/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
