### PR TITLE
Bug fix 3.7/fix spin locks

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Add missing rollback of state changes when an attempt-based write operation on a spin lock fails.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *all*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10993/

### CODE REVIEW

**Comment by jsteemann** [comment]
Not ready to merge yet: I had added an assertion, but this does not work in the arangodbtests unit tests context.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11003/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11006/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
