### PR TITLE
Cleanup of EnumerateList produceRows

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

Minor cleanup in the EnumerateList executor. Make the code more readable, and send consistent upstream calls; previously, in some hard to describe circumstances, a softLimit was introduced.

- [X] :hankey: Bugfix 
- [X] :hammer: Refactoring 
- [X] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [X] No backports required

### Testing & Verification

- [X] This change is a trivial rework / code cleanup without any test coverage.
- [X] This change is already covered by existing tests, such as **shell_server_aql**.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12173/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12184/

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12187/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12193/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12223/

**Comment by goedderz** [comment]
image

**Comment by mchacki** [comment]
Recent jenkins still blue:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13194/

**Pull request merged**
