### PR TITLE
Bug fix 3.6/internal issue #748

### PR DESCRIPTION
**Pull request by Dronplane**
Fixes wrong iteration over sorted values returned by stored column reader

https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11473/

### CODE REVIEW

**Comment by Dronplane** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11480/

**Comment by Dronplane** [comment]
Tests blue except known V8 crash

**Comment by KVS85** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/13150/

**Comment by KVS85** [comment]
> https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/13150/

Tests were blue.

**Pull request merged**
