### PR TITLE
3.5 Bug-Fix and Refactoring work on resetDeadJobs 

### PR DESCRIPTION
**Pull request by markuspf**
Backport of #10800

### CODE REVIEW

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7925/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8089/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8095/

**Comment by KVS85** [comment]
Tests blue except known unrelated failures.

**Pull request merged**
