### PR TITLE
[3.6] Fixed AR-113 and added regression tests

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #13196.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13259/

**Comment by goedderz** [comment]
image

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/13414/

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
