### PR TITLE
Ungreylist shell-compaction-seq-mmfiles-noncluster-timecritical

### PR DESCRIPTION
**Pull request by markuspf**
This test has passed running through the night on my machine. Jenkins run for verification here https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7526/

### CODE REVIEW

**Comment by markuspf** [comment]
Jenkins run to validate mergeability: 
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7563/

**Comment by markuspf** [comment]
This is a bit confusing, do you want me to remove the `-timecritical-` bit as well?

**Comment by KVS85** [comment]
> This is a bit confusing, do you want me to remove the `-timecritical-` bit as well?

Yes.

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7570/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7691/

**Comment by markuspf** [comment]
Jenkins is blue

**Comment by markuspf** [comment]
Jenkins blue

**Pull request merged**
