### PR TITLE
Fix end condition (hasMore) for EnumerateViewNode.

### PR DESCRIPTION
**Pull request by danielhlarkin**
Should address https://github.com/arangodb/release-3.4/issues/134.

### CODE REVIEW

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2109/

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2133/

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2141/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2142/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2196/

**Comment by gnusi** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2236/

**Pull request merged**
