### PR TITLE
Added tests for dual LDAP feature (3.7)

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Backport of https://github.com/arangodb/arangodb/pull/14248
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/691

This will add the three test scenarios:

* two active ldap servers
* first ldap server active, second ldap server not reachable
* second ldap server not reachable, second ldap server active

The fourth scenario, only one ldap, is tested by the existing tests.
 
This requires a PR for oskar (https://github.com/arangodb/oskar/pull/319) which starts two LDAP servers as docker containers.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required.

#### Related Information

- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/691

### Testing & Verification

- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests**

### CODE REVIEW

**Review by fceller — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-matrix/40/

**Comment by KVS85** [comment]
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-matrix/2186/

**Comment by KVS85** [comment]
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-matrix/2194/

**Pull request merged**
