### PR TITLE
Fix Arangosh windows instability

### PR DESCRIPTION
**Pull request by graetzer**
### Scope & Purpose

Try to fix an issue on window

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)

### Testing & Verification

This change is already covered by existing tests, such as *(please describe tests)*.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5148/

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/295/

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5207/
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/325/

**Comment by graetzer** [comment]
Retry because enterprise fails
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/328/

**Comment by KVS85** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5240/
https://jenkins01.arangodb.biz/job/arangodb-ANY-windows-matrix/329/

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/332/

**Pull request merged**
