### PR TITLE
Feature/swagger 3.25.1

### PR DESCRIPTION
**Pull request by Simran-B**
### Scope & Purpose

- Update Swagger to v3.25.1 to fix security vulnerability.
- Disable validator to avoid the _INVALID_ schema badge.
- Restore docExpansion behavior for Swagger Foxx (but use "list" mode for server API docs): #11579

image

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [ ] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [ ] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a GitHub Issue reported by a Community User: https://github.com/arangodb/arangodb/issues/11525

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

Manually tested Swagger UI in Web UI with and without server authentication, RESTful API as well as Foxx documentation router. 

### Documentation

- [x] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)

### CODE REVIEW

**Comment by dothebart** [comment]
@pluma we decided to switch the behaviour. 
You only have the section titles, and click on them to expand to have less scrolling from the beginning. 
Does this work for you?

**Comment by pluma** [comment]
@dothebart In that case the review still fails because the instructions need to be updated accordingly.

However while I understand how this change makes sense for the ArangoDB HTTP API docs, it doesn't make much sense for the majority of Foxx services out there because unless users explicitly tag their endpoints and have lots of them, they're all grouped under a single tag called "default" and I think this harms UX.

Users may not be aware they have to click on the "default" section and think the feature or their service is broken, especially given that this worked differently before. And even if they figure it out, they'll now have to perform an extra click every time they want to access any of the routes, which during development can add up quite a bit.

Ultimately this is a UX issue with swagger-ui itself, but I think we should find a solution that doesn't negatively impact Foxx users.

My ideal solution would be to only enable this feature when there are less than N routes (say, N=10) and only if there is more than one section. That's probably not possible given how swagger-ui works.

So the alternative would be to pass an extra query string argument where we link the HTTP API docs and set `docExpansion` based on that. That would mean the HTTP API docs (which are probably much larger than the vast majority of user provided services would be) is always collapsed but Foxx services continue to be expanded as before. This should be fairly trivial to implement in aardvark.

**Comment by dothebart** [comment]
ok, didn't know that this html snippet was used for the foxx things and for the arangodb API. Maybe simply having two files is easier?

**Comment by pluma** [comment]
Having two files that only differ by one line seems overkill to me. Changing the URL aardvark uses to embed the HTTP API docs (e.g. adding something like `?collapsed` and just adding something like `docExpansion: new URL(location).searchParams.has("collapsed") ? "none" : "list"` seems easier and more maintainable, no?

**Comment by pluma** [comment]
Also, can we please think of Foxx before merging things like #10833? If Foxx is no longer considered an important feature, I'm okay with that and would just like to be informed of this change in direction. If it is considered important, please take it seriously when considering the impact of these kinds of changes.

**Comment by dothebart** [comment]
Hi, 
sorry neither of us knew that this would also change the foxx ui behaviour, thanks for pointing out. 
Can you create a PR to fixx this for the foxx UI?

**Comment by pluma** [comment]
I've added a PR that fixes this issue. As it was introduced in a previous PR that has already been merged, I'm approving this PR.

**Comment by Simran-B** [comment]
Thanks Alan, this was indeed not intentional

**Comment by Simran-B** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/9934/
Alan's modifications (#11579) require a rebuild of Aardvark before it works. Verified in a local build that everything is working as expected after that.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10020/

http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/628/

**Comment by KVS85** [comment]
Tests are blue except unrelated known failure in `hot_backup`.

**Pull request merged**
