### PR TITLE
Added "startupTime", "computationTime" and "storageTime" to Pregel result statistics

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Added "startupTime", "computationTime" and "storageTime" to Pregel result statistics.
This makes the more detailed timings available as part of the Pregel job result, so it can be better understood how long the individual parts of a run took.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] Backports required for: *3.7*

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13301/

### CODE REVIEW

**Review by fceller — APPROVED** [review]
LGTM

**Review by mchacki — APPROVED** [review]
LGTM

**Review by mchacki — CHANGES_REQUESTED** [review]
Wait a second.
Sorry, can we add tests?
We do not need to have exact matching of numbers (that is off obviously)
But we should assert that attribute is available only if we do store, and always > 0.0 if it is available.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13307/

**Comment by jsteemann** [comment]
Tests blue

**Review by mchacki — APPROVED** [review]
LGTM, thanks for adding the test :+1:

**Pull request merged**
