### PR TITLE
[3.7] Fix SORT in subqueries when crossing block boundaries

### PR DESCRIPTION
**Pull request by goedderz**
Backport of https://github.com/arangodb/arangodb/pull/12752

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12179/

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12209/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
