### PR TITLE
Doc - Backport scripts and content changes to 3.2

### PR DESCRIPTION
**Pull request by Simran-B**
Shall eventually fix the build issues in the new Jenkins.

Backport of https://github.com/arangodb/arangodb/pull/5209 and other changes.

Tested locally with success using oskar with a [build script fix](https://github.com/arangodb/oskar/pull/64) and `./scripts/buildDocumentation --books "Manual AQL HTTP Cookbook"` - do we need to handle the non-existence of the Drivers book <= 3.3 in the build_documentation script?

### CODE REVIEW

**Comment by Simran-B** [comment]
Drivers book needs to be excluded (does not exist <= 3.3):

```
============================== Build Book - Drivers ==============================
book source:       /oskar/work/ArangoDB/Documentation/Books/Drivers
preprocessing dir: /oskar/work/books_pp/Drivers
output dir:        /oskar/work/books_html/Drivers
-------------------------- Source Checks - Book Drivers --------------------------
+ bs 01 checking for bad code sections in Drivers
grep: /oskar/work/ArangoDB/Documentation/Books/Drivers: No such file or directory
+ bs 02 checking for headers that won't proper display on github in Drivers
grep: /oskar/work/ArangoDB/Documentation/Books/Drivers: No such file or directory
+ bs 03 checking for unused image files Drivers
find: '/oskar/work/ArangoDB/Documentation/Books/Drivers': No such file or directory
--------------------------- Preprocess - Book Drivers ----------------------------
 - copy directory structure
/oskar/containers/documentation.docker/build_documentation: line 189: cd: /oskar/work/ArangoDB/Documentation/Books/Drivers: No such file or directory

Error: could not enter book source dir: /oskar/work/ArangoDB/Documentation/Books/Drivers
```

@ObiWahn How can/should this be done?

**Comment by ObiWahn** [comment]
You could use the `--books` flag if you just want to create a subset of `ALLBOOKS`  as shown here: https://github.com/arangodb/oskar/blob/master/scripts/buildDocumentation#L17

**Comment by Simran-B** [comment]
@ObiWahn For manual building yes, but how to automate this for new Jenkins?

Should be hard-code something like `if version >= 3.4 then buildBook(Drivers)`?
The same script is used to build 3.3, 3.4 etc., unlike in old Jenkins, which uses a versioned build script.

One could also skip books if there is no source folder for them, but I worry that it could camouflage other errors (e.g. all files of all books missing because of some error).

**Comment by ObiWahn** [comment]
@Simran-B yes some check if the version is lower than 3.3 is probably the best what could be done. The information should not be on part of different branches anymore, but it still needs some place where it will be encoded. I think that `oskar` is the right place because it is the tool, that knows how to build ArangoDB. As the documentation is part of the database I think the information should be encoded in the same place.

**Comment by Simran-B** [comment]
Documentation build finally succeeded with this oskar patch: https://github.com/arangodb/oskar/pull/87

I hope this will be easy to forward port to 3.3 to fix it for new jenkins as well.

**Comment by sleto-it** [comment]
@Simran-B for 3.3 we can use this branch and PR hopefully - or if needed close that and reopen a new one (in that I did several changes to fix links etc): https://github.com/arangodb/arangodb/pull/8249

**Comment by Simran-B** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/373/

**Pull request merged**
