### PR TITLE
re-add functions lost in merchcident of cd74fb3501276ae1efd4e40b5e48d8448021c4f3

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

this was here, and removed. We need it for the tests in the nightlies.

- [x] :hankey: Bugfix

### CODE REVIEW

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by dothebart** [comment]
https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.x86-64/3515/ nightly run

**Comment by dothebart** [comment]
https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.x86-64/3523/

**Comment by dothebart** [comment]
https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.x86-64/3528/ nightly run green.

**Pull request merged**
