### PR TITLE
Bug fix 3.5/restore feature perms

### PR DESCRIPTION
**Pull request by hkernbach**
# Pull Request Guidelines

Fixed permissions for dump/restore.

### Scope & Purpose

- [x] Bug-Fix for *devel-branch* (already merged)
- [x] Bug-Fix for a *released version* (this PR)
- [X] The behavior change can be verified via automatic tests.

#### Related Information
- [x] There is a GitHub PR: https://github.com/arangodb/arangodb/pull/10540

### Testing & Verification

This change is already covered by existing tests, such as *(dump restore suite)*.

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7504/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7515/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7518/

**Comment by hkernbach** [comment]
Jenkins green except for windows build.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7819/

**Pull request merged**
