### PR TITLE
Feature 3.7/more resource tracking

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Improved tracking of query memory usage for traversals, hashed collect and distinct collect and sort.
This is a forward-port of https://github.com/arangodb/arangodb/pull/13110.

Enterprise PR: https://github.com/arangodb/enterprise/pull/595
 
- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

#### Related Information

- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/595

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *shell_server_aql*.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12921/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12969/

**Comment by jsteemann** [comment]
Tests blue

**Review by danielhlarkin — APPROVED** [review]

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13227/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
