### PR TITLE
Agency restart fixes for mini chaos

### PR DESCRIPTION
**Pull request by neunhoef**
This ports the fixes for the minu chaos agency restarts from 3.7
to devel.

Background:

Before the fix there is a time when a compaction snapshot is received
from the leader, such that if the agent crashes at the wrong time, it
can not longer restart, since there is a mismatch between the latest
compaction snapshot and the rest of the log entries.

This PR fixes this problem by altering the restart procedure and erasing
the complete local Raft log when this is detected at restart. The
thinking behind is that if this happens, all we have from the Raft log
is anyway seriously outdated.

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [*] :hankey: Bugfix (requires CHANGELOG entry)

#### Backports:

- [*] Backports required for: 3.6

### Testing & Verification

*(Please pick either of the following options)*

- [*] The behavior in this PR was *manually tested*
- [*] This fixes mini chaos tests, which sometimes expose the problem

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13424/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13686/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13687/

**Review by kvahed — APPROVED** [review]
LGTM

**Pull request merged**
