### PR TITLE
upgrade boost to 1.71.0

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
https://172.16.10.101/job/arangodb-matrix-pr-linux/8512/

**Comment by jsteemann** [comment]
Ok, so we are going more than 50 versions back?
```diff
diff --git a/3rdParty/boost/CMakeLists.txt b/3rdParty/boost/CMakeLists.txt
index 6d5399043f..2f3ec0e667 100644
--- a/3rdParty/boost/CMakeLists.txt
+++ b/3rdParty/boost/CMakeLists.txt
@@ -1,7 +1,7 @@
 project(boost)
 
 #the boost version must also be adjusted in the top-level CMakeLists.txt file
-set(boost_version "1.17.0")
+set(boost_version "1.69.0")
 set(BOOST_VERSION ${boost_version} PARENT_SCOPE)
 set(boost_src "${CMAKE_CURRENT_SOURCE_DIR}/${boost_version}")
 
```

**Comment by jsteemann** [comment]
Can you also please fix the directory name from `3rdParty/boost/1.17.0` to the correct version number?
It is kind of obvious that the version number is wrong, so I am wondering why I am supposed to review it in this state :thinking:

**Comment by ObiWahn** [comment]
> 1.17.0
https://www.boost.org/users/history/version_1_17_0.html

**Comment by ObiWahn** [comment]
> It is kind of obvious that the version number is wrong, so I am wondering why I am supposed to review it in this state thinking

Because 2 people did not notice.

**Comment by ObiWahn** [comment]
Clean up the version mess in a new PR

**Comment by ObiWahn** [comment]
https://github.com/arangodb/arangodb/pull/10299

**Pull request closed without merging**
