### PR TITLE
Deal with lost documents found in chaos testing.

### PR DESCRIPTION
**Pull request by neunhoef**
This PR addresses problems found in chaos testing. The scenario was quite
complicated, but involved two different issues:

 -  AQL queries were not promptly cleaned up after a coordinator restart
    or failure. This could prevent DropCollection operations from
    happening, thereby clogging up a Maintenance worker, if only few
    cores were available. This in turn could delay other Maintenance
    actions in unrelated collections.

 -  Delayed Maintenance actions for a shard could trigger an old and no
    longer valid DropCollection action to happen after a controlled
    leader change on the new leader.

The first issue is addressed in this PR by using the RebootTracker for
AQL queries and coordinator failures.

The second issue is addressed by serializing all Maintenance actions
for each shard and only planning the next one once the previous one
has been finished.

This will be backported to 3.5, 3.6 and 3.7.

GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-181

Design document: https://github.com/arangodb/documents/blob/master/DesignDocuments/03_IN_PROGRESS/MaintenanceActionSerialization.md

Testing is a problem. We have no good test harness to test a coordinator
failure or reboot and quick query cleanup. This was tested manually by
doing:

c = db._create("c");
for (i = 0; i < 300; ++i) { c.insert({Hallo:i}); };
db._query(`FOR x IN c LIMIT 20 RETURN {x, y:SLEEP(1)}`).toArray()
  restart coordinator quickly
db.c.drop();       // should finish after 20s or so when the above
                   // query snippt finishes its run

The new shard locking in the MaintenanceFeature has some newly added
unit tests.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11756/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11758/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11759/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11841/

**Review by goedderz — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
Tests blue except known and unrelated failures in Go driver API check.

**Pull request merged**
