### PR TITLE
add a new for pregel "parallelism" attribute

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Contains tests from https://github.com/arangodb/arangodb/pull/15164

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] Backport for 3.9: https://github.com/arangodb/arangodb/pull/15165

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (shell_client, shell_server)

### CODE REVIEW

**Review by markuspf — APPROVED** [review]
LGTM

(technically this change is backwards incompatible, but I don't really think this is an issue)

**Review by markuspf — CHANGES_REQUESTED** [review]
Why does this not remove the `parallelism` response?

**Comment by jsteemann** [comment]
> Why does this not remove the `parallelism` response?

Why should it from the `parallelism` response?

**Comment by jsteemann** [comment]
Merging this PR now. The PR only adds a new test, so it should be fine. 
Other .cpp code changes from the 3.8 PR https://github.com/arangodb/arangodb/pull/15164 are not necessary to port to devel, because they were already fixed in devel by some prior work.

**Pull request merged**
