### PR TITLE
[3.4] Forbid ambiguous casts to and from ResultT

### PR DESCRIPTION
**Pull request by goedderz**

### CODE REVIEW

**Comment by ObiWahn** [comment]
Maybe people will wonder when the cast to bool does not work, but the compiler will show the error. For the non-`ResultT<bool>` the implicit cast makes the result usage nicer :+1:

**Comment by goedderz** [comment]
Thanks @ObiWahn. I'm wondering if there are more cases where we should forbid the implicit casts.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3008/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3058/

**Comment by goedderz** [comment]
All green.

**Pull request merged**
