### PR TITLE
invoke the java and js driver tests from testing.js

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
waiting for @rashtao to fix cleanup of the tests; aside of that its working now.

**Comment by rashtao** [comment]
@dothebart The database is now cleaned up after execution of Java tests (since https://github.com/arangodb/arangodb-java-driver/commit/a781254996e4ec3d1b40b2e9b9a97e7d32fcdb08).

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11910/

**Review by rashtao — APPROVED** [review]
LGTM

**Review by pluma — APPROVED** [review]

**Pull request merged**
