### PR TITLE
Feature/internal 3306

### PR DESCRIPTION
**Pull request by jsteemann**
Implementation of most things mentioned in https://github.com/arangodb/planning/issues/3306

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2428/

**Comment by jsteemann** [comment]
I don't think we should have "internal" options. IMHO the distinction between hidden-by-default and visible-by-default options is already enough.
Apart from that, we also have "obsolete" options, which are kept around only to keep older startup commands working. "obsolete" options will not affect program behavior otherwise, and we do not want to advertise them, so I think these should always be hidden and never exported, not even by `--dump-options`.
I am not sure if anything else needs to be done for this PR, or if you are happy with merging it. Please let me know.
Please also note that I marked all options that are added by enterprise features as enterprise options now. This was missing in previous versions. Now all options related to LDAP, encryption and one option regarding SSL are additionally marked as enterprise-only.

**Comment by Simran-B** [comment]
- No internal options: fine with me
- Obsolete options: yes, they should always be hidden indeed. Are they currently exported by `--dump-options`? If yes, can you change it to either not dump them (preferred), or add another attribute that indicates this (`obsolete: true`)?
- LDAP etc.: hm, didn't notice that they were `enterpriseOnly: false`. Great that it is fixed! We should backport this to 3.3 to fix the docs there as well.
- I haven't tested it yet, but feel free to merge the PR. I will do the doc generation scripts in a separate PR.

**Comment by jsteemann** [comment]
We are not showing obsolete options in `--dump-options` at the moment. Should this ever change, each option has an attribute "obsolete" already, which can then be used to filter out unwanted options from the results. Currently it will always contain "false".

Re hidden and non-hidden options: The decision which options are hidden and which aren't is partly arbitrary. The sheer amount of available options just requires that we only show the most important options by default. I think this is the most valid explanation, but I am not sure if that explanation needs to go into the documentation or not.
If you want to do something different depending on whether an option is hidden or not, `--dump-options` already provides a "hidden" attribute for each option.

Re the enterprise options: I can add the missing enterprise flags in 3.4 now. 3.3 doesn't have the enterprise/non-enterprise distinction at all.

**Comment by jsteemann** [comment]
We are not showing obsolete options in `--dump-options` at the moment. Should this ever change, each option has an attribute "obsolete" already, which can then be used to filter out unwanted options from the results. Currently it will always contain "false".

Re hidden and non-hidden options: The decision which options are hidden and which aren't is partly arbitrary. The sheer amount of available options just requires that we only show the most important options by default. I think this is the most valid explanation, but I am not sure if that explanation needs to go into the documentation or not.
If you want to do something different depending on whether an option is hidden or not, `--dump-options` already provides a "hidden" attribute for each option.

Re the enterprise options: I can add the missing enterprise flags in 3.4 now. 3.3 doesn't have the enterprise/non-enterprise distinction at all.

**Comment by jsteemann** [comment]
We are not showing obsolete options in `--dump-options` at the moment. Should this ever change, each option has an attribute "obsolete" already, which can then be used to filter out unwanted options from the results. Currently it will always contain "false".

Re hidden and non-hidden options: The decision which options are hidden and which aren't is partly arbitrary. The sheer amount of available options just requires that we only show the most important options by default. I think this is the most valid explanation, but I am not sure if that explanation needs to go into the documentation or not.
If you want to do something different depending on whether an option is hidden or not, `--dump-options` already provides a "hidden" attribute for each option.

Re the enterprise options: I can add the missing enterprise flags in 3.4 now. 3.3 doesn't have the enterprise/non-enterprise distinction at all.

**Comment by Simran-B** [comment]
@sleto-it I think we should not display whether an option is flagged as hidden in the docs, because its purpose is to not flood the shell if you run `--help`. WDYT?

**Pull request merged**
