### PR TITLE
Feature/react webpack testing

### PR DESCRIPTION
**Pull request by hkernbach**
Old PR: https://github.com/arangodb/arangodb/pull/8712
This one will fix tests. 

We need to create a new (ruby) suite. Suite is now called: `http_webif`. 
This will run on a nightly base, not in every PR. 

New oskar suite changes, see here:
- https://github.com/arangodb/oskar/pull/194

New blacklist PR's here:
- 3.3: https://github.com/arangodb/arangodb/pull/10305
- 3.4: https://github.com/arangodb/arangodb/pull/10306
- 3.5: https://github.com/arangodb/arangodb/pull/10307

Latest Devel PR:
- http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/6850/

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/6830/

**Comment by hkernbach** [comment]
@KVS85 please check if everything is setup properly. 

Latest PR jenkins run: http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/6850/

**Comment by hkernbach** [comment]
@KVS85 jenkins blue (in case the result is removed by tomorrow)

**Comment by KVS85** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7464/

**Comment by KVS85** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/

**Comment by KVS85** [comment]
Tests blue. Other bugs related to reducing UI-related minimal size and replication tab problem for Active-Failover and Master/Slave modes are subject to other PRs.

**Pull request merged**
