### PR TITLE
backported additional AQL query metrics to 3.6

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Added new metrics for tracking AQL queries and slow queries:
* `arangodb_aql_query_time`: histogram with AQL query times distribution.
* `arangodb_aql_slow_query_time`: histogram with AQL slow query times distribution.

These metrics already existed in devel for a while. This PR just backports them.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12852/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12861/

**Review by fceller — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12879/

**Comment by Simran-B** [comment]
3.6 docs don't have a list of all metrics, so no change needed on that front (unless we want to add a full list for 3.6?)

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
@Simran-B : probably we should copy over the list of metrics page from 3.7 or 3.8 to 3.6, and then just remove the ones which are not present in 3.6. WDYT?

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
