### PR TITLE
arangosearch Views: Add primarySortCache and primaryKeyCache options to DocuBlocks

### PR DESCRIPTION
**Pull request by Simran-B**
See https://github.com/arangodb/docs/pull/1191 (to be merged for v3.9.6)

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM

**Review by nerpaula — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
@Simran-B please add Jenkins and/or examples generation check links.

**Comment by Simran-B** [comment]
https://jenkins.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/2640/

**Pull request merged**
