### PR TITLE
Fixed illegal optimizer rule on multiple consecutive SORTs

### PR DESCRIPTION
**Pull request by hkernbach**
Backport of: https://github.com/arangodb/arangodb/pull/16718
Please see all notes there.

### CODE REVIEW

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by hkernbach** [comment]
Jenkins green except unrelated windows failure ...

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by KVS85** [comment]
Only unrelated known failures on Windows in Jenkins.

**Pull request merged**
