### PR TITLE
[3.9] Disable COMDAT folding.

### PR DESCRIPTION
**Pull request by mpoeter**
### Scope & Purpose

Disable COMDAT folding (aka Identical Code Folding) on Windows, because it can break a program that depends on unique addresses for functions or read-only data members (which apparently we do).
No CHANGELOG entry since this is not user facing and does not affect a released version.

- [x] :hankey: Bugfix

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by Dronplane** [comment]
MSDN says `By default, /OPT:ICF is enabled by the linker unless /OPT:NOICF or /DEBUG is specified. To override this default and prevent COMDATs from being folded in the program, specify /OPT:NOICF.` here https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations?view=msvc-160
So I suggest instead of simply removing `/OPT:ICF` add `/OPT:NOICF`

**Comment by jsteemann** [comment]
> MSDN says `By default, /OPT:ICF is enabled by the linker unless /OPT:NOICF or /DEBUG is specified. To override this default and prevent COMDATs from being folded in the program, specify /OPT:NOICF.` here [docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations?view=msvc-160](https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations?view=msvc-160) So I suggest instead of simply removing `/OPT:ICF` add `/OPT:NOICF`

According to @mpoeter the explicit _enabling_ of ICF reduced program size greatly, so it seems to have been opt-in rather than opt-out. I am not sure however it that statement referred to a debug build or a release build.

**Comment by Dronplane** [comment]
For debug builds ICF is diabled (to make stack traces more readable). For non debug builds ICF is implicitly enabled.

**Comment by mpoeter** [comment]
@Dronplane The `/DEBUG` linker option enables creation of debugging information for the executable. So this is not only for debug builds, but also release builds, since we want to have debug symbols for our release as well. But you are right that it would be better to disable it explicitly, and I also add a comment explaining the reasons for it.

**Pull request merged**
