### PR TITLE
Feature 3.7/ldap better error handling

### PR DESCRIPTION
**Pull request by fceller**
Two parts:

- improved log messages and adjusted log level.
- in case of false for referrals and restart use LDAP_OFF; refactored duplicate code

### CODE REVIEW

**Comment by fceller** [comment]
This has an enterprise branch as well

**Comment by fceller** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11833/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11943/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/5651/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/5653

**Review by dothebart — APPROVED** [review]

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11969/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
