### PR TITLE
[PREGEL]replaced "PageRank" by "pagerank" everywhere in the API

### PR DESCRIPTION
**Pull request by romanatarango**
### Scope & Purpose

Replaced "PageRank" by "pagerank" in the internal and the API of Pregel. 

Now when the PageRank algorithm is run, `... GET /_api/control_pregel/{id}` returns 
```
{
...
	"algorithm": "pagerank",
...
}
```
instead of 
```
{
...
	"algorithm": "PageRank",
...
}
```
- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-971
- [ ] Design document:

### CODE REVIEW

**Comment by joerg84** [comment]
Thanks for the cleanup! I suppose this is a backwards incompatible change?

**Comment by jwierzbo** [comment]
@romanatarango is the rest of possible values consistent with the documentation (https://www.arangodb.com/docs/devel/http/pregel.html)?

**Comment by romanatarango** [comment]
> Thanks for the cleanup! I suppose this is a backwards incompatible change?

It is.

**Comment by romanatarango** [comment]
> @romanatarango is the rest of possible values consistent with the documentation (https://www.arangodb.com/docs/devel/http/pregel.html)?

Thay are all like "PageRank" except "slpa".

**Comment by jwierzbo** [comment]
> > @romanatarango is the rest of possible values consistent with the documentation (https://www.arangodb.com/docs/devel/http/pregel.html)?
> 
> Thay are all like "PageRank" except "slpa".

Could you change the rest of them as well, to line it up with the documentation? :)

**Comment by romanatarango** [comment]
> > > @romanatarango is the rest of possible values consistent with the documentation (https://www.arangodb.com/docs/devel/http/pregel.html)?
> > 
> > 
> > Thay are all like "PageRank" except "slpa".
> 
> Could you change the rest of them as well, to line it up with the documentation? :)

Here (last commit) you are :-). For "WCC"/"wcc" this is still inconsistent: on https://www.arangodb.com/docs/devel/http/pregel.html, we have "WCC" in example answers, on https://www.arangodb.com/docs/devel/graphs-pregel-algorithms.html, the parameter is "wcc", so our logic implies that the answer should be "wcc" as well. @joerg84 FYI

**Review by jwierzbo — APPROVED** [review]

**Comment by markuspf** [comment]
I quite dislike this change, because it's a breaking change that accomplishes very little; I am ready to merge it; I would like to think more carefully about API for pregel in the future, though.

**Pull request merged**
