### PR TITLE
Remove fetchRow, fetchAllRows, fetchShadowRow and fetchShadowRowInternal

### PR DESCRIPTION
**Pull request by markuspf**
Deleted code is good code: This deletes the old (and now unused) fetcher API in AQL execution.

Reviewers please let me know if there's more stuff that can be removed, though we should merge this one here and then make some new pull requests for more cleanup.

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10543/

**Comment by markuspf** [comment]
Note that this PR will be extended to remove some more "old API" code, as well as tests that aren't useful anymore.

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10599/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10621/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10622/

**Pull request merged**
