### PR TITLE
fix make directory windows error handling (#13157)

### PR DESCRIPTION
**Pull request by dothebart**
backport of https://github.com/arangodb/arangodb/pull/13157

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13070/

**Review by jsteemann — APPROVED** [review]

**Review by KVS85 — APPROVED** [review]
LGTM.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
