### PR TITLE
Improve windows installer

### PR DESCRIPTION
**Pull request by dothebart**
- set the reasonable exit code in the windows service if its exiting,
   so we can retrieve it later on
 - improve exit code descriptions
 - properly handle exitcodes in the windows installer so we can give
   better error messages when something goes wrong
 - unify the detection of 'this user' vs. 'all users' installs

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/490/

**Comment by Simran-B** [comment]
Could you have a look at this too? https://github.com/arangodb/planning/issues/2480

**Comment by dothebart** [comment]
I did, it should now decide in a clearer manner when its a user install and a system wide install, and thus not do this anymore

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/663/

**Pull request merged**
