### PR TITLE
fix and extend cluster metrics

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This PR provides 3 metrics-related changes:

* Added cluster metrics `arangodb_load_plan_accum_runtime_msec` and `arangodb_load_current_accum_runtime_msec` to track the total time spent in `loadPlan()` and `loadCurrent()` operations.
* Fixed wrong reporting of failures in all maintenace failure counter metrics (`arangodb_maintenance_action_failure_counter`). Previously, each successful maintenance operation was reported as a failure, so the failure counters actually were counters for the number of successful maintenance actions.
* Adjusted the scale of the `arangodb_maintenance_action_queue_time_msec` to cover a more useful range.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11034/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11056/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11064/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/12772/
http://172.16.10.101:8080/job/arangodb-matrix-pr-mac-onlycatch/8646/
http://172.16.10.101:8080/job/arangodb-matrix-pr-windows/4842/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
