### PR TITLE
removes the man target from default maintainer build

### PR DESCRIPTION
**Pull request by ObiWahn**
Do not modify manpages during maintainer mode build.

### CODE REVIEW

**Comment by ObiWahn** [comment]
Should be merged once the release script calls the manpage build manually.

**Comment by ObiWahn** [comment]
@neunhoef @dothebart can we merge this?

**Comment by dothebart** [comment]
Installation/release.sh ~line 349 needs to invoke this target.

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/656/

**Pull request merged**
