### PR TITLE
Try to fix corruption error

### PR DESCRIPTION
**Pull request by graetzer**
### Scope & Purpose

Simplify code in background indexing

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behaviour change can only be verified via automatic tests

#### Related Information

- [x] There is an internal planning ticket: https://github.com/arangodb/release-3.5/issues/101

### Testing & Verification

*(Please pick either of the following options)*

This PR adds tests that were used to verify all changes:

- [x] Added new **integration tests** (i.e. in shell_server / shell_server_aql)

http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6430/

### CODE REVIEW

**Comment by fceller** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4860/

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6462/

**Comment by fceller** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4868/

**Comment by markuspf** [comment]
This is really hard to review for me, the only thing I can do is apply the patch and see whether the problem persists (which it looks like it does not).

I would be good if (at least in future), commits were a bit more clear cut and had a commit message, and there was a description of what was the problem and how it is fixed.

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6479/

**Comment by graetzer** [comment]
lets see what they say regarding the corruption error: https://github.com/facebook/rocksdb/issues/5455

**Comment by markuspf** [comment]
Does this mean that the `NO DATA LEFT` is not really an error, but a wrong message?

**Comment by danielhlarkin** [comment]
@markuspf We think it might be a wrong message for the RocksDB API to return, and that it should just indicate there is more data to read. If that's the case, then we would need to retry the read if we are in one of the initial (non-locked) catchup passes. If we are in the final (locked) catchup pass, we could safely ignore a retry message here since the subsequent writes must have happened in a different collection.

**Comment by danielhlarkin** [comment]
Oh, just noticed they actually responded. Then yes, we need to do what I posted above. @graetzer Do you want to adjust this PR with the RocksDB patch and the retry code?

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4921/

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4928/

**Comment by graetzer** [comment]
lgtm

**Pull request merged**
