### PR TITLE
Suppress startup warning about no user table.

### PR DESCRIPTION
**Pull request by danielhlarkin**

### CODE REVIEW

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/1568/

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/1579/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/1593/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1600/

**Pull request merged**
