### PR TITLE
Always try to join threads in tests

### PR DESCRIPTION
**Pull request by MBkkt**
### Scope & Purpose

*(Please describe the changes in this PR for reviewers, motivation, rationale - **mandatory**)*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by markuspf — CHANGES_REQUESTED** [review]
Can you describe the problem you are solving?

Can this be done with less duplication?

**Review by dothebart — APPROVED** [review]

**Comment by MBkkt** [comment]
@markuspf 

> Can you describe the problem you are solving?

Check slack message

> Can this be done with less duplication?

Yes but I'm not interested.
Also we don't have std::jthread in libc++

**Comment by markuspf** [comment]
> @markuspf
> 
> > Can you describe the problem you are solving?
> 
> Check slack message
> 

Its not useful for this discussion to go across media; I also do not know (or understand) what you mean.

> > Can this be done with less duplication?
> 
> Yes but I'm not interested. Also we don't have std::jthread in libc++

I am not sure what I understand what you mean by "I am not interested"?

You asked for a review, I tried reviewing the code and I do not know what the problem is you're solving (and I do not understand how), but I see that there is a lot of code duplication. 

I think that duplication should be avoided.

In particular I am opposed to merging this into the Replication2 code base as is.

**Comment by MBkkt** [comment]
@markuspf 

> I am not sure what I understand what you mean by "I am not interested"?

It's mean I'm not interested to beatiful fix replication2/etc **test** code.
It means authors of this code wrote it buggy: not-always join threads and I fix **only** this.

If you want avoid duplication **you** can create special wrapper, struct for create threads in test.

**Comment by MBkkt** [comment]
@markuspf 

> In particular I am opposed to merging this into the Replication2 code base as is.

But I am opposed to have bugs in code.

I agreed duplication not good but it already was (see for-loops for join threads).
Why it should be fixed by me?

**Comment by MBkkt** [comment]
@markuspf 

> I also do not know (or understand) what you mean.

If we have exception or early return already created threads in vector will be destroyed.

And in that case will be called std::terminate, because we skip to call join or detach

**Comment by mpoeter** [comment]
> I agreed duplication not good but it already was (see for-loops for join threads). Why it should be fixed by me?
> 
> Your comment about duplication should be NIT in my opinion.

Code duplication is a code smell, especially if it occurs more than twice (like here). Yes, this is "just" test code, but test code should have the same quality standards as production code.

In general code that we check code should be cleaner than the code we checked out! So you should try to reduce the existing code duplication instead of adding yet more. Why you? Because you are already touching that code!

**Comment by MBkkt** [comment]
But I doesn't have a time to add new files and check everything builds locally or fix it and rerun jenkins few times.
If this fix with a little more duplication then was is worse than have bugs, ok, closed

**Comment by markuspf** [comment]
Reopening;

The problem you spotted (that exceptions could be thrown while joining the threads created in a test) is an actual problem. That is a good spot!

I did not understand previously that you were trying to fix *this* problem, and it would have been beneficial if you had described it right away in the PR description, so that I can read it and review the PR with that in mind.

Then I spotted a lot of duplicated lines being introduced; that always looks odd to me, so I asked whether this fix can be done without so much duplication. This was also a genuine question: I did not understand the problem, *or* the solution yet, so I could not in a review tell whether it could be done (within reasonable time).

I was trying to help getting this PR merged by providing a review, that is all.

I will now try to make a suggestion how to improve this code.

**Comment by markuspf** [comment]
I think this is now superseded by #16918 and I will close it again. Thanks for everyone for the contributions.

**Pull request closed without merging**
