### PR TITLE
Do not check isEnabled

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5986/

### CODE REVIEW

**Comment by jsteemann** [comment]
There is a competing PR by @gnusi:
https://github.com/arangodb/arangodb/pull/8989

I don't know which approach is the correct one. We have to discuss with him.

**Comment by graetzer** [comment]
its not competing it won't cause merge conflicts

**Comment by jsteemann** [comment]
I see that `start()` and `beginShutdown()` are called only for enabled features, so yes, it starts to make sense to me now.
Was there any real-life bug related to this PR?

**Comment by graetzer** [comment]
no

**Comment by jsteemann** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4459/

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6043/

**Pull request merged**
