### PR TITLE
defer creation of ArangoSearch threadpool

### PR DESCRIPTION
**Pull request by jsteemann**
moved threadpool creation from IResearchFeature constructor into
method IReseachFeature::initializeAsync(). This prevents the
threadpool from being created when the IResearchFeature object is
created.
In arangod, the feature object is created at the very start, before
it is clear if we actually need the IResearchFeature on the server.
In case we are an agency node, we will not need the IResearchFeature
at all, so we will disable it at some point during the startup
sequence. This however makes more sense if the feature hasn't yet
started a threadpool.

IResearchFeature::initializeAsync isn't private because it needs to
be called from the unit tests to properly initialize the async tests
for the IResearchFeature

Please note that for legal reasons we require you to sign the 
[Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/317/

**Comment by vasiliy-arangodb** [comment]
The IResearchFeature should not be instantiated on the agency at all, since there is no need for the Agency to know about IResearch
The patch proposed in this pull-request requires that the developer not forget to call extra methods or the IResearchFeature instance will be in an invalid state. This approach makes the code more fragile.

**Comment by jsteemann** [comment]
@vasiliy-arangodb : Well, all features are instanciated in arangod.cpp, as it has been the case since 3.0.
At the beginning, it is not known which role a server instance will have (e.g. agency, coordinator, db server, single server). This is determined at runtime, by some of the features. And it is controlled by options which the features provide. In order to provide their options, features need to be instanciated first.
Later loading and thus instanciating of features is not possible, because features have dependencies and order requriements. These dependencies cannot be met later on if features are instanciated dynamically.
So we won't change it that features have to be instanciated first. However, features should do as little as possible in their constructor, and defer all their real work to `prepare`. This PR honors this. The thread pool is created via `prepare` now, and there is no need to call an extra function. This is required only for testing. However, if you don't like that, please create a class that derives from IResearchFeature that creates the thread pool again in the ctor, and use that for testing only.

**Comment by vasiliy-arangodb** [comment]
@jsteemann @mchacki in #iresearch mentioned that prepare() is not called for features not found in the dependency tree of the current ArangoDB process
therefore it is sufficient to only move the ArangoDB Thread startup call from the constructor into prepare()
the changes would be limited to IResearchFeature.cpp and would not require API changes or implicit function call requirements

**Comment by vasiliy-arangodb** [comment]
I think calling prepare() in tests would be more in line with the existing ArangoDB architecture, e.g.
diff --git a/arangod/IResearch/IResearchFeature.cpp b/arangod/IResearch/IResearchFeature.cpp
index fa723264cc..2914542819 100644
--- a/arangod/IResearch/IResearchFeature.cpp
+++ b/arangod/IResearch/IResearchFeature.cpp
@@ -395,6 +395,7 @@ class IResearchFeature::Async {
 
   void emplace(std::shared_ptr<ResourceMutex> const& mutex, Fn &&fn); // add an asynchronous task
   void notify() const; // notify all tasks
+  void start();
 
  private:
   struct Pending {
@@ -587,10 +588,6 @@ IResearchFeature::Async::Async(): _terminate(false) {
     thread._terminate = &_terminate;
   }
 
-  // start threads
-  for (auto& thread: _pool) {
-    thread.start(&_join);
-  }
 }
 
 IResearchFeature::Async::~Async() {
@@ -601,8 +598,10 @@ IResearchFeature::Async::~Async() {
 
   // join with all threads in pool
   for (auto& thread: _pool) {
-    while(thread.isRunning()) {
-      _join.wait();
+    if (thread.hasStarted()) {
+      while(thread.isRunning()) {
+        _join.wait();
+      }
     }
   }
 }
@@ -631,6 +630,13 @@ void IResearchFeature::Async::notify() const {
   }
 }
 
+void IResearchFeature::Async::start() {
+  // start threads
+  for (auto& thread: _pool) {
+    thread.start(&_join);
+  }
+}
+
 IResearchFeature::IResearchFeature(arangodb::application_features::ApplicationServer* server)
   : ApplicationFeature(server, IResearchFeature::name()),
     _async(std::make_unique<Async>()),
@@ -698,6 +704,9 @@ void IResearchFeature::prepare() {
   registerTransactionDataSourceRegistrationCallback();
 
   registerRecoveryHelper();
+
+  // start the async task thread pool
+  _async->start();
 }
 
 void IResearchFeature::start() {
diff --git a/tests/IResearch/IResearchFeature-test.cpp b/tests/IResearch/IResearchFeature-test.cpp
index 5ac292b49a..2bf064c741 100644
--- a/tests/IResearch/IResearchFeature-test.cpp
+++ b/tests/IResearch/IResearchFeature-test.cpp
@@ -35,6 +35,7 @@
 #include "IResearch/Containers.h"
 #include "IResearch/IResearchFeature.h"
 #include "Rest/Version.h"
+#include "RestServer/ViewTypesFeature.h"
 #include "StorageEngine/EngineSelectorFeature.h"
 
 // -----------------------------------------------------------------------------
@@ -125,6 +126,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     bool deallocated = false;
     std::condition_variable cond;
     std::mutex mutex;
@@ -143,6 +146,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(nullptr);
     bool deallocated = false;
     std::condition_variable cond;
@@ -162,6 +167,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(&server);
     std::condition_variable cond;
     std::mutex mutex;
@@ -176,6 +183,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     bool deallocated = false;
     std::condition_variable cond;
     std::mutex mutex;
@@ -197,6 +206,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(&server);
     bool deallocated = false;
     std::condition_variable cond;
@@ -216,6 +227,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(&server);
     bool deallocated = false;
     std::condition_variable cond;
@@ -248,6 +261,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(&server);
     bool deallocated = false;
     bool execVal = true;
@@ -278,6 +293,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(&server);
     bool deallocated = false;
     bool execVal = false;
@@ -313,6 +330,8 @@ SECTION("test_async") {
 
     {
       arangodb::iresearch::IResearchFeature feature(&server);
+      server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+      feature.prepare(); // start thread pool
     }
   }
 
@@ -327,6 +346,8 @@ SECTION("test_async") {
 
     {
       arangodb::iresearch::IResearchFeature feature(&server);
+      server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+      feature.prepare(); // start thread pool
       std::shared_ptr<bool> flag(&deallocated, [](bool* ptr)->void { *ptr = true; });
 
       feature.async(resourceMutex, [&cond, &mutex, flag](size_t& timeoutMsec, bool)->bool { SCOPED_LOCK(mutex); cond.notify_all(); timeoutMsec = 100; return true; });
@@ -340,6 +361,8 @@ SECTION("test_async") {
   {
     arangodb::application_features::ApplicationServer server(nullptr, nullptr);
     arangodb::iresearch::IResearchFeature feature(&server);
+    server.addFeature(new arangodb::ViewTypesFeature(&server)); // required for IResearchFeature::prepare()
+    feature.prepare(); // start thread pool
     auto resourceMutex = std::make_shared<arangodb::iresearch::ResourceMutex>(&server);
     bool deallocated0 = false;
     bool deallocated1 = false;

**Comment by jsteemann** [comment]
Can't figure out any meaning from the above comment apart from "prepare is more in line".
So I will change my PR to only use prepare and remove the extra method.

**Comment by vasiliy-arangodb** [comment]
with the aforementioned diff the TRI_ASSERT are no longer required since the '_async' instance is guaranteed to exist and jobs may be scheduled at any time (they simply will not run)

**Comment by jsteemann** [comment]
Implemented @vasiliy-arangodb 's changes and merge with devel.

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/327/

**Pull request merged**
