### PR TITLE
[3.10] [AQL] Add ALL_SHORTEST_PATHS feature

### PR DESCRIPTION
**Pull request by aMahanna**
Scope & Purpose
Add feature to compute ALL_SHORTEST_PATHS between two given vertices.

* Design Doc PR: https://github.com/arangodb/documents/pull/114
* Documentation PR: https://github.com/arangodb/docs/pull/1071
* Jira: https://arangodb.atlassian.net/browse/APM-531

 Devel PR: https://github.com/arangodb/arangodb/pull/16407

### CODE REVIEW

**Review by markuspf — APPROVED** [review]
LGTM

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by Sacramentix** [comment]
Good job, I can't wait to be able to use this awesome feature ❤️.

**Comment by aMahanna** [comment]
(afaik the build failure in https://jenkins01.arangodb.biz/job/arangodb-matrix-pr/22828/ is unrelated)

**Pull request merged**
