### PR TITLE
Set internal state to DONE when upstream is DONE

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

- [X] Bug-Fix for *devel-branch*

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7338/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7344/

**Comment by goedderz** [comment]
Jenkins is blue.

**Comment by mchacki** [comment]
Jenkins again after merge with devel:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7354/

**Pull request merged**
