### PR TITLE
issue #3741: attempt to fix terminal color output in Windows

### PR DESCRIPTION
**Pull request by jsteemann**
Attempt to fix issue #3741

### CODE REVIEW

**Comment by jsteemann** [comment]
Please do not merge yet. Still needs manual testing!

**Comment by Simran-B** [comment]
Works on Windows 7 SP1 (no colors, no garbage) and Windows 10 latest (colors, no garbage).
I assume that it works on an older Window 10 one or the other way, too.

**Comment by jsteemann** [comment]
Ok, let's merge it eventually then!

**Comment by Simran-B** [comment]
@jsteemann Found a problem with an older Windows 10 version:

The build fails because `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is not defined.

VS14 2015
Win 10 Pro 1703, build 15063.483

Potential fix:

```diff
diff --git a/lib/ApplicationFeatures/ShellColorsFeature.cpp b/lib/ApplicationFeatures/ShellColorsFeature.cpp
index 89545e2..0172953 100644
--- a/lib/ApplicationFeatures/ShellColorsFeature.cpp
+++ b/lib/ApplicationFeatures/ShellColorsFeature.cpp
@@ -24,6 +24,9 @@

 #ifdef _WIN32
 #include "Basics/win-utils.h"
+#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
+#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
+#endif
 #endif

 using namespace arangodb;
```

**Comment by jsteemann** [comment]
Does this enable the colors too?

**Comment by jsteemann** [comment]
Will you open a PR for this, or do you want me to do it?

**Comment by Simran-B** [comment]
Live and in colors:

image

I'm going to do the PRs. Any code style change wishes, or can I push it as-is?

**Comment by jsteemann** [comment]
It's all fine then. Just go ahead with the PRs as you like.

**Comment by Simran-B** [comment]
Updated 3.2 and 3.3 PRs, created new PR for devel.

**Pull request merged**
