### PR TITLE
[devel] - Add rocksdb.exclusive-write tests

### PR DESCRIPTION
**Pull request by hkernbach**
Port of https://github.com/arangodb/arangodb/pull/10729 for devel.

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7755/

**Comment by hkernbach** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/7757/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/7769/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
