### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sesam**
fix broken link

### CODE REVIEW

**Comment by Simran-B** [comment]
Thanks a lot for informing us about this broken link!

We would like to accept your patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by sesam** [comment]
Hi. I signed online via the Facebook projects page. Are both needed?

**Comment by janavolkova9** [comment]
The redirect has been added. Thanks

**Comment by sesam** [comment]
Excellent.

About the CLA signing process - there seems to be some discrepancy between what's documented on your webpages and how it works in practice.

**Comment by sesam** [comment]
Sorry, it seems I got confused. When trying to create the PR, I got an initial warning and was blocked from creating the PR.
I saw two options, sign online (which eventually linked to something very alike https://code.facebook.com/cla but with very broken CSS) or downloading the PDF.
After reloading the online sign page it became readable enough that I could click on Single individual.
After that, I retried creating the link fix PR, and this time I was allowed.
This led me to think that I had passed the "CLA sign" check.
But probably that was something else?

**Comment by dothebart** [comment]
hm, the facebook code probably is about rocksdb which we build upon - We also send patches there - but its not directly arangodb - If there was somewhere to head wrong to that it would be good to know ;)

**Comment by Simran-B** [comment]
@sesam To quickly explain the situation: Some open source projects allow you to sign a CLA online, which is apparently sufficient in the US and maybe other countries as well. However, in Germany it is not. As a former German company, we still need physically signed CLAs, but a scanned/faxed version of it is also okay. We might be able to accept digital agreements in the future.

**Pull request closed without merging**
