### PR TITLE
[3.7] Fix AQL cost estimate for spliced subqueries

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #13119

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12929/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12939/

**Review by mchacki — APPROVED** [review]
LGTM

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13061/

**Pull request merged**
