### PR TITLE
[3.9] Replace ansi-html with ansi-html-community

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This is a backport of #15654 for 3.9. For upgrade compatibility reasons it includes an alias module re-exporting ansi-html-community as ansi-html.

- [x] :hammer: Refactoring/simplification

### Checklist

- [x] :book: CHANGELOG entry made

#### Related Information

- [x] Jira ticket: BTS-730

### CODE REVIEW

**Review by kvahed — APPROVED** [review]
LGTM

**Comment by pluma** [comment]
FYI I've manually tested the module alias.

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by pluma** [comment]
jenkins passed, the github PR status integration is just broken again

**Review by ajurdak — APPROVED** [review]
LGTM.

**Pull request merged**
