### PR TITLE
Feature/FE-46 view UI usability improvements

### PR DESCRIPTION
**Pull request by emmanueletukudo**
### Scope & Purpose

This PR is for UI improvement on the View UI pages as well as adding tooltips to options where necessary. The affected pages are mostly the `Info` and `Consolidation Policy` pages.

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by adityamukho — COMMENTED** [review]
Some files in this PR are the same as one of the previous approved PRs. Better to wait until that is merged so that this PR is greatly simplified.

**Review by ajurdak — APPROVED** [review]
LGTM.

**Review by adityamukho — APPROVED** [review]
Conflict needs to be resolved (trivial). Otherwise LGTM.

**Review by ajurdak — APPROVED** [review]
LGTM.

**Pull request merged**
