### PR TITLE
:pizza: fix #17673 extended `DATE_*` with optional timezone paramaters

### LINKED ISSUE #17673: [Feature Request] `DATE_ADD()` with optional timezone
At the moment it takes some conversions to securly add a day to a date that is not UTC. This query shows what I mean:

```AQL
RETURN {
    a: DATE_LOCALTOUTC(DATE_ADD(DATE_TIMESTAMP(DATE_UTCTOLOCAL(1561932000000, 'Europe/Berlin')),200,'d'), 'Europe/Berlin'),
    b: DATE_ADD(1561932000000,200,'d')
}
```

This returns 2 different values due to day light saving is changing the timezone offset:

```AQL
[
  {
    "a": "2020-01-16T23:00:00.000Z",
    "b": "2020-01-16T22:00:00.000Z"
  }
]
```

It would be great to just do this:

```AQL
RETURN {
    a: DATE_ADD(1561932000000,200,'d','Europe/Berlin'),
    b: DATE_ADD(1561932000000,200,'d')
}
```

and get

```AQL
[
  {
    "a": "2020-01-16T23:00:00.000Z", // or "2020-01-17T00:00:00.000+01:00"
    "b": "2020-01-16T22:00:00.000Z"
  }
]
```

### PR DESCRIPTION
**Pull request by konsultaner**
#####  :pizza: New feature
One might have to compute date operations in certain timezones. For example if you want to add a day to the 26th of March 2023. The UTC timezone has no daylight savings. So you would add 24 hours, but in the timezone `Europe/Berlin` you would gain an extra hour. To only add 23 hours you need to convert the time to local, compute and convert it back to utc.

Example:

```
2023-03-25T23:00:00.000Z == 2023-03-26T00:00:00.000+01:00

add one day in UTC

2023-03-25T23:00:00.000Z + 1 day == 2023-03-26T23:00:00.000Z

add one day in 'Europe/Berlin'

2023-03-25T23:00:00.000Z + 1 day == 2023-03-26T22:00:00.000Z
2023-03-26T22:00:00.000Z == 2023-03-27T00:00:00.000+02:00
```

### Checklist

| Function | timezoned | js-test|
|-|-|-|
|[DATE_DAYOFWEEK()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_dayofweek)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_YEAR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_year)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_MONTH()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_month)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_DAY()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_day)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_HOUR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_hour)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_MINUTE()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_minute)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_SECOND()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_second)|no need|no need|
|[DATE_MILLISECOND()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_millisecond)|no need|no need|
|[DATE_DAYOFYEAR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_dayofyear)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_ISOWEEK()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_isoweek)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|DATE_ISOWEEKYEAR()|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_LEAPYEAR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_leapyear)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_QUARTER()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_quarter)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_DAYS_IN_MONTH()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_days_in_month)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_TRUNC()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_trunc)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_ROUND()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_round)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_FORMAT()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_format)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_ADD()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_add)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_SUBTRACT()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_subtract)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_DIFF()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_diff)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
|[DATE_COMPARE()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_compare)|<ul><li>[x] </li></ul>|<ul><li>[x] </li></ul>|
 
- [x] :book: CHANGELOG entry made
- [x] :books: https://github.com/arangodb/docs/pull/1290
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

- [x] GitHub issue / Jira ticket: #17673

### CODE REVIEW

**Comment by dothebart** [comment]
Hi, 
please make sure to obey the formatting rules. This `.git/hooks/pre-commit` Pre-Commit hook can force you to:
```

#!/usr/bin/env bash
# Configure this hook by running the following:
#    1. cd arangodb
#    2. cp .githooks/pre-commit .git/hooks/pre-commit
#    3. git config core.hooksPath .git/hooks
# pre-requisite: Linux-based system || macOS-based system
# pre-requisite: Docker
# pre-requisite: Bash 4
# pre-requisite: Git 2.9+

adb_path="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/../.." &> /dev/null && pwd )"

echo "ArangoDB directory: $adb_path"
pushd "$adb_path" > /dev/null

changed_files_filename=".clang-format-$$.changed.tmp"
# clean up after ourselves
trap "rm -f $changed_files_filename" EXIT
trap "rm -f $changed_files_filename; exit" SIGINT SIGTERM SIGHUP

# collect a list of file names of all modified files in $changed_files_filename
git diff --cached --diff-filter=ACMRT --name-only -- arangod/ lib/ client-tools/ tests/ | grep -e '\.ipp$' -e '\.tpp$' -e '\.cpp$' -e '\.hpp$' -e '\.cc$' -e '\.c$' -e '\.h$' > "$changed_files_filename"

if [ -s "$changed_files_filename" ]; then
  # hand over a list of changed files from the local filesystem into a Docker container that contains a fixed
  # version of clang-format and some small shell wrapper to iterate over the list of files
  docker run --rm -u "$(id -u):$(id -g)" --mount type=bind,source="$adb_path",target=/usr/src/arangodb arangodb/clang-format:1.2 "validate" "$changed_files_filename"
fi
status=$?

popd > /dev/null

exit $status
```

**Comment by konsultaner** [comment]
@jsteemann @dothebart @mpoeter
Next step would be to implement `DATE_DIFF` with timezones.

The current signature is:

```c++
add({"DATE_DIFF", ".,.,.|.", flags, &functions::DateDiff});
```

which would change to 

```c++
add({"DATE_DIFF", ".,.,.|.,.,.", flags, &functions::DateDiff});
```

There are several options to update the signature to:

- [x] dateA, dateB, unit, asFloat
- [x] dateA, dateB, unit, timezonaForAAndB
- [x] dateA, dateB, unit, timezonaForAAndB, asFloat
- [ ] dateA, dateB, unit, asFloat, timezonaForAAndB
- [x] dateA, dateB, unit, timezonaA, timezonaB, asFloat
- [ ] dateA, dateB, unit, asFloat, timezonaA, timezonaB

I could implement all but think, that only the checked once should be chosen.

**Comment by konsultaner** [comment]
Writing more tests raised a question:

Should a timezoned input erstimate a timezone (or set a time offset) and use it even if no timezone was passed as last parameter? I see an issue in daylight savings. 

```AQL
RETURN DATE_ROUND("2023-03-26T00:55:55.555+01:00", 1, 'day')
// 2023-03-25T23:00:00.000Z

// would have the same result as

RETURN DATE_ROUND("2023-03-25T23:55:55.555Z", 1, 'day', 'Europe/Berlin')
// 2023-03-25T23:00:00.000Z
```

but 

```AQL
RETURN DATE_ADD("2023-03-26T00:00:00.000+01:00", 1, 'day')
// 2023-03-26T23:00:00.000Z

// would NOT have the same result as

RETURN DATE_ADD("2023-03-25T23:00:00.000Z", 1, 'day', 'Europe/Berlin')
// 2023-03-26T22:00:00.000Z
```

**Comment by markuspf** [comment]
I have successfully rebased the changes on current devel and started a CI job to validate the changes don't break any tests (I use a branch on this repository for this)

One slight irritation is the fact that the document toolchain was changed so someone will have to port the documentation changes. I carefully asked the documentation team for help.

**Comment by Simran-B** [comment]
Ported docs PR: https://github.com/arangodb/docs-hugo/pull/396

**Comment by jsteemann** [comment]
@konsultaner : thanks for the contribution! Changes finally merged into devel/3.12.

**Comment by konsultaner** [comment]
Thank you!😇

**Pull request closed without merging**
