### PR TITLE
Feature/translate translate function now in c++

### PR DESCRIPTION
**Pull request by hkernbach**

### CODE REVIEW

**Comment by baslr** [comment]
Does the js implementation has tests?

**Comment by hkernbach** [comment]
@baslr yes.

**Comment by jsteemann** [comment]
Please fix the failing AQL tests.

**Comment by baslr** [comment]
https://github.com/arangodb/arangodb/blob/devel/js/server/tests/aql/aql-functions.js#L1604
the test doesnt cover the c++ and js implementation.

**Pull request merged**
