### PR TITLE
Documentation corrections

### PR DESCRIPTION
**Pull request by CoDEmanX**
- ~~**new AQL functions**: `DATE_DAYOFYEAR`, `DATE_ISOWEEK`, `DATE_LEAPYEAR`, `DATE_CALC`~~. *(will make that a separate pull request when it's ready)*
- misspellings (removed apparently superfluous "wo", gatter > gather in context of clusters etc.)
- arangob test-case list in manpages
- case of words, like Http > HTTP
- whitespace
- edits in favor of American English over British English (was mixed, possibly missed a few; maybe consider to rename server script initialise.js too)

### CODE REVIEW

**Comment by pluma** [comment]
I'm in favour of AE in the source code (variables, filenames, etc) but apathetic about the English variant used in documentation as far as it's consistent. We should probably have a style guide for that.

**Comment by dothebart** [comment]
Can we have all those small corrections in a separate pull request?
Its easier to just pass them through and improves the sight on the real changes.

**Comment by CoDEmanX** [comment]
Github is a bit tricky, pull requests update automatically - I did not tell it to make the AQL DATE additions part of it. What I do now is developing my DATE additions further in another branch of my fork, and have my devel branch contain these doc changes only for now (so PR will only contain these changes). I tried to split the large doc commit into two smaller commits, one for files that had whitespace changes only, and one for the typos. Hope it's in an acceptable state for you.

**Comment by pluma** [comment]
Yeah, you should create a separate branch for each PR if you want to isolate changes. GitHub PRs are per-branch not per-commit.

**Comment by CoDEmanX** [comment]
Fixed typos in changelog too. Will do another PR for initialise > initialize (in comments, actual code and files). Found some other typical typos, that may occur in couple for files:

```
accout
alignement
apropriate
atomcially
Authorisation
autorization
behaviour
cancelation
captial
colelction
comparion
comparsion
critieria
deleteable
dialogue
Docummentation
entitiy
finalisation
hierchical
inialise
initalised
initialisation
initialise
instanciation
occured
openend
optimised
optimiser
prefered
preferrably
prileges
propertly
Randonmess
respectivly
seldomly
seperately
seperator
signalling
specifc
Specifiying
spurios
stastical
synchronisation
utilties
```

**Comment by jsteemann** [comment]
Thanks very much!

**Pull request merged**
