### PR TITLE
why?

### PR DESCRIPTION
**Pull request by jsteemann**
intentionally context-free

https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7624/

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1598/

**Comment by jsteemann** [comment]
Non-Windows-Tests blue

**Comment by jsteemann** [comment]
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7640/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7673/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
