### PR TITLE
Documentation/add example anchors

### PR DESCRIPTION
**Pull request by dothebart**
the (not yet final) effects can be viewed at:  http://192.168.173.88/devel2/HTTP/UserManagement/#RestGrantDatabase_container 

when hovering the documentation-div; the v^ will also un/fold the examples to be discussed whether this is what we want.

### CODE REVIEW

**Comment by Simran-B** [comment]
A way to show/hide the result is a good idea IMO. Currently, you can only show, but no more hide a possibly long result. Not sure how to design and style this yet.

Some random ideas:

- Remove prefixes like `shell>` and rather indicate in what context the example is supposed to be run as caption somewhere above the example
- Button to copy example to clipboard?
- Use separate boxes for example code and result block, possibly with captions?
- Give each example a meaningful caption to describe what it does?

**Comment by Simran-B** [comment]
@dothebart does the script check if there are collisions in IDs (duplicate anchors)? It's possible that a single page contains two headlines with the same slug (we had plenty of this before we removed the **Example** and **Examples** headlines), which may not be obvious because of DocuBlocks.

**Comment by dothebart** [comment]
no, didn't add a check for this yet, but was already thinking about that. 
In this case you will only get duplicate anchors if you have the same example used twice in a file - which means that the anchor would essentially bring you to the same content. 

I think show/hide should be in one row with the chain, and maybe also hide/unhide the show/hide link so that essentially only one link is there.

**Comment by dothebart** [comment]
I've now changed the ^V to become 'hide' similar to the show. @sleto-it have a look ;-)

**Comment by Simran-B** [comment]
To reduce confusion if one hides the result, I propose the following:

```
 ______________________       ______________________
|                      |     |                      |
| Example code box     | ==> | Example code box     |
|______________________|     |______________________|
                             
[ Show result body]          [ Hide result body]
                              ______________________
                             |                      |
                             | Result box           |
                             |______________________|

```

The Show/Hide button can be one DOM element which changes text, but keeps its position, so that it act more like a toggle. If the user has expanded the result and scrolled to the end, there will be no button anymore which would lead to an unpleasant jump of content if used. It is sufficient to show the result box if the button is clicked (you can also click the code box currently).

**Pull request merged**
