### PR TITLE
add mips64 support

### PR DESCRIPTION
**Pull request by loongson-gz**
### Scope & Purpose
add mips64 support

### Testing & Verification
tested on loongson 3A3000

### CODE REVIEW

**Comment by dothebart** [comment]
Hi, 
please note that we require an Apache style CLA to be signed: https://www.arangodb.com/community/

A note about this PR: 
While this (most probably) adds the ability to compile ArangoDB on MIPS, this doesn't add any functional waranties. Since we neither have hardware nor developer time to CI-Assure the proper functioning on this target, more work may be required to make this usefull on a longson / mips system.

Also ArangoDB 3.3 is pretty late in its release cycle, usually we only accept PRs to the `devel` branch. 

Put that aside, LGTM.

**Comment by joerg84** [comment]
@loongson-gz Thanks for your contribution! Would it be possible to port this to our devel branch if possible? Also happy to hear more about your use-case here!

**Comment by loongson-gz** [comment]
> @loongson-gz Thanks for your contribution! Would it be possible to port this to our devel branch if possible? Also happy to hear more about your use-case here!

yeah, I will port to devel branch. about use-case do you some suggest ? thank you very much！

**Comment by KVS85** [comment]
@loongson-gz unfortunately, we have to close this PR due to the fact that such change can be integrated into devel only at the moment and only then backported to previous branched.

In addition, 3.3 branch will have EOL very soon: https://www.arangodb.com/eol-notice/

**Pull request closed without merging**
