### PR TITLE
Replace xmldom with @xmldom/xmldom

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This replaces xmldom with @xmldom/xmldom as xmldom is no longer maintained.

This is an internal, undocumented dependency and the replacement is a fully API-compatible fork.

The dependency is only used as part of the exports testsuite.

- [x] :hammer: Refactoring/simplification

### Checklist

- [x] :book: CHANGELOG entry made
- [x] Backports
  - [x] Backport for 3.9: https://github.com/arangodb/arangodb/pull/15660

#### Related Information

- [x] Jira ticket: BTS-730

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by Zyqsempai** [comment]
@KVS85 Let's push this one as well

**Review by ajurdak — APPROVED** [review]
LGTM.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
