### PR TITLE
Bug fix/optional docs collapse

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This PR restores the collapsing behavior for Foxx API docs while retaining the new behavior for the ArangoDB HTTP API docs.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [ ] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [ ] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [ ] The behavior change can be verified via automatic tests

#### Related Information

This fixes a regression introduced in #10833 as described in #11530.

- [ ] There is a GitHub Issue reported by a Community User: 
- [ ] There is an internal planning ticket: 
- [ ] There is a *JIRA Ticket number* (In case a customer was affected / involved): 
- [ ] There is a design document: 

### Testing & Verification

This change is already covered by existing tests, such as *see _3rdParty/README_maintainers.md*.

### Documentation

- [x] Added a *Changelog Entry*

### CODE REVIEW

**Comment by pluma** [comment]
@Simran-B This PR probably needs to be backported to all versions affected by the changes in #10833.

**Comment by pluma** [comment]
I've requested changes in the backports of #11530 as this would avoid the hassle of having to backport this change to every ArangoDB version rather than just devel (in which the collapse behavior has already been changed via a prior PR, necessitating this change).

**Comment by hkernbach** [comment]
@dothebart yes, please remove those autogenrated files.

**Comment by pluma** [comment]
I've removed the generated files.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9851/

**Comment by dothebart** [comment]
only unrelated errors.

**Pull request merged**
