### PR TITLE
Fix windows path handling not to slip into UNC lookup (#10073)

### PR DESCRIPTION
**Pull request by dothebart**
Backport of https://github.com/arangodb/arangodb/pull/10073

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/

**Comment by KVS85** [comment]
Built 3.5 based on the branch, but still see `\\` access:


```

+----------------------+----------------+--------+--------------+---------------------------------+--------------------+----------------------------------+--------------+--------------------+------------------------------------+------------------+------------------+------------------+--------+---------+-----------------------+
|    "Time of Day"     | "Process Name" | "PID"  | "Operation"  |             "Path"              |      "Result"      |             "Detail"             |              |                    |                                    |                  |                  |                  |        |         |                       |
+----------------------+----------------+--------+--------------+---------------------------------+--------------------+----------------------------------+--------------+--------------------+------------------------------------+------------------+------------------+------------------+--------+---------+-----------------------+
| "7:22:27.9099354 AM" | "arangosh.exe" | "2264" | "CreateFile" | "\\etc\arangodb3\arangosh.conf" | "BAD NETWORK PATH" | "Desired Access: Read Attributes |  Synchronize |  Disposition: Open |  Options: Synchronous IO Non-Alert |  Open For Backup |  Attributes: n/a |  ShareMode: Read |  Write |  Delete |  AllocationSize: n/a" |
+----------------------+----------------+--------+--------------+---------------------------------+--------------------+----------------------------------+--------------+--------------------+------------------------------------+------------------+------------------+------------------+--------+---------+-----------------------+
```

**Comment by dothebart** [comment]
can you reproduce it with devel as well? or is it fixed there?

**Comment by KVS85** [comment]
> can you reproduce it with devel as well? or is it fixed there?

image

Yes, in devel also.

`time ./arangosh.exe --version` is 2.342s against `time ./arangosh.exe --version -c none` with 0.031s.

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6572/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
