### PR TITLE
pm-124

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This is the 3.6 backport of https://github.com/arangodb/arangodb/pull/11289.

``` 
* Changed behavior for creating new collections in OneShard databases
  (i.e. databases with "sharding" attribute set to "single"):

  Previously it was allowed to override "distributeShardsLike" and "numberOfShards"
  for each new collection. The default values were "_graphs" and 1 and were not
  modified if the user did not alter them, but it was still possible to alter them.
  This is now (silenly) ignored. Any attempt to set any value for
  "distributeShardsLike" or "numberOfShards" for new collections in a OneShard
  database will silently be ignored. The collection will automatically be sharded
  like the sharding prototype and will have a single shard.

  The behavior has been adjusted to match the behavior when creating collections
  in a cluster started with `--cluster.force-one-shard true` option. Here any user-
  supplied values for "distributeShardsLike" or "numberOfShards" were always ignored.

  Now the behavior is identical for OneShard databases and databases in cluster
  started with `--cluster.force-one-shard true`.

  The web interface now also hides the "Distribute shards like" settings in this
  case, and makes the "Number of shards" input box read-only.
``` 
- [x] Bug-Fix for *released version*
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a *JIRA Ticket number*: https://arangodb.atlassian.net/browse/PM-124 

### Testing & Verification

This change is already covered by existing tests, such as *scripts/unittest shell_server shell_client --test shell-one-shard --cluster true*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9101/

### CODE REVIEW

**Comment by KVS85** [comment]
Tests blue.

**Comment by jsteemann** [comment]
@ifcologne : what "messaging to the user" do you mean? Please provide more details.

**Comment by ifcologne** [comment]
Instead of silently ignoring changes we can add a note in the WebUI that "In OneShard databases you can not change this setting on a collection level" and disable the field. The API could return a warning that the alleged distributeShardsLIke change will not affect OneShard databases and will be sharded alike.

**Comment by jsteemann** [comment]
No, our APIs can't return warnings.

**Comment by jsteemann** [comment]
Apart from that we are *not* silenly ignoring changes in the web UI, but we make the "number of shards" field read-only and hide the "distribute shards like" field. Nothing is ignored when using the web UI.
Stuff will be ignored when creating a collection via the API, but our API can either return success or failure, but no warnings.

**Pull request merged**
