### PR TITLE
Fix loop.

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

This fixes the following problem:

If a coordinator wants to roll back a create database operation and the database has - for whatever reason - already been removed from the agency, then the corresponding retry loop runs endlessly, always running into 412 precondition failed. This endless loop is broken by the changes in this PR.

Forward port of https://github.com/arangodb/arangodb/pull/13166
Backport of https://github.com/arangodb/arangodb/pull/13174

TODO: still needs an automated test.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] Backports required for: 3.6 (https://github.com/arangodb/arangodb/pull/13166)

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13107/

### CODE REVIEW

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13253/

**Comment by KVS85** [comment]
Tests blue except unrelated known unreliable test.

**Comment by fceller** [comment]
We will have a tests in a second PR

**Comment by fceller** [comment]
@neunhoef please review merge

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13433/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
