### PR TITLE
[3.7] Try to improve error message extraction

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #12324

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11666/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/11673/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11741/

**Comment by goedderz** [comment]
image

**Review by neunhoef — APPROVED** [review]
LGTM

**Pull request merged**
