### PR TITLE
Remove mocha, chalk

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This PR removes mocha and chalk. These are internal (undocumented) dependencies that cause unnecessary noise during audits and are no longer used as of 3.8 (see #14501, #14505).

- [x] :hankey: Bugfix

### Checklist

- [x] :book: CHANGELOG entry made
- [x] Backports
  - [x] Backport for 3.9: *(Please link PR)*

#### Related Information

- [x] GitHub issue / Jira ticket: ES-1015

### CODE REVIEW

**Review by dothebart — APPROVED** [review]

**Review by ajurdak — APPROVED** [review]
LGTM.

**Comment by pluma** [comment]
Build failure is unrelated. Restarted jenkins.

**Comment by pluma** [comment]
jenkins is green

**Comment by pluma** [comment]
Rerunning jenkins after merge.

**Pull request merged**
