### PR TITLE
Documentation/dc2dc improvements

### PR DESCRIPTION
**Pull request by sleto-it**
This PR is a first attempt to improve DC2DC documentation

Until now there was a single long page wich was describing several aspects/topics related DC2DC, including:

- an introduction to DC2DC  
- details about deployment
- administration details 
- monitoring details 
- security details 
- troubleshooting details 

This PR splits the different topics into different specific sections, and includes them in several chapters that are "standard", or mostly "expected" by readers, e.g. "Administration", "Monitoring", "Security", "Troubleshooting"

When some of these chapters were not existing, e.g. "Monitoring" and "Security" they have been created - as they will be useful in general in the future to aggregate more info related to those topics (not specific to DC2DC). Creation of these chapters was indeed already planned

The DC2DC "Introduction" part has currently been inserted into the "Scalability" chapter. However, this chapther will need to be improved in a future in a way that it includes an overview of all the solutions available to scale ArangoDB:

- master/replica-slave replication
- master/slave with automatic failover
- cluster
- DC2DC (cluster replication) - already included 

Improving this "Scalability" chapter is behind the scope of this PR - and can be done at a second stage 

The PRs aims at keeping / preserving existing external links 

Opportunity has been taken to refactor the subsections of the "Deployment" chapter  (only in the summary file), so that now it is more easy:

- Single instance
- Cluster
- Multiple Datacenters

This is just a first step of many needed to improve the doc

Planning issues ref:

- https://github.com/arangodb/planning/issues/1499
- https://github.com/arangodb/planning/issues/1515
- https://github.com/arangodb/planning/issues/1498

After review / approval this PR should be backported to 3.3. A simple cherry-pick should be enough

Suggested to compile and see the changes locally

Next step after merging:

- integrate additional recent changes (issue ref: https://github.com/arangodb/planning/issues/1607)

Thanks,

### CODE REVIEW

**Comment by neunhoef** [comment]
I am happy to see improvements in the DC2DC documentation, many thanks for that. We need to sort out one problem, though: So far, the master copy of the documentation (which we maintain with code changes) has been in the `arangodb/arangosync` repository. The decision to have a single page was taken to make it easier to copy over a new version from the `arangosync` repo to the main `ArangoDB` repo. This is now considerably more difficult. So either, we have to decide that the main source of truth of the documentation lies in the `arangodb/arangodb` repository, which is bad in my opinion, since ArangoDB and `arangosync` can have different release cycles. Or alternatively, we have to leave the main source in the `arangosync` repository and find a way to copy over changes conveniently. I would like to avoid a situation in which one has to edit documentation in two places, with the same change potentially happening at different times. How can we sort this out?

**Comment by sleto-it** [comment]
Thanks for your comment. Having one single page makes it surely easier to copy
the file from `arangosync` to the main ArangoDB repo. However. in my opinion from 
the other side, having one single page moved from one repo to another does not
help much in terms of integration with the official manual, where there are
different sections and chapters and where there is the need to add links to other
sections 

In general, I agree on importance of avoiding to maintain duplicate text and edit the doc
in two places. I am open to this, though, if necessary to have an official doc in a very
good shape

I believe automatically copying the files from `arangosync`  to the `arangodb` repo will
add more complexity to an already complex system - and might not solve 100% the
concern that doc is not "integrated" with other sections 

Can you detail more your concern about different release cycles? Few thoughts
on this topic:

- At any time the ArangoDB doc can be built and the content will appear online as
soon as the doc build process has completed. This is unrelated to ArangoDB server
release. The documentation build can be triggered in a self-service way by anyone
in the Team (there is a specific procedure, it takes a few seconds to start the build)

So if something has changed in arangosync (or the starter), one may still release
arangosync (or the starter), and at the same time make a PR for the official doc.
Then merge the PR (or ask someone else to merge it), and then trigger a doc build.
This will result in a synchronization or alignment  between doc and the new 
arangosync (or starter) version

Opening documentaiton issues, in planning, can also be a possisble solution to have
doc changes implemented - provided that what has to be changed or is new is well
described in the planning issue. Obiously, since someone else will need to take the
issue and work on it, it can pass some time before the doc reflects the suggested
changes, but will, eventually, as we work and close documentation issues. For emergency
changes, PR + PR merge + "Doc Build" will remain the faster (and self-service) approach,
though

Open to any other approaches that provide a good/better compromise between the need
of having good doc for user, prospects and customers, and the developers needs

**Comment by sleto-it** [comment]
Discussed during a call last week. Cluster team would prefer to "split" the doc into their repo and then have an automatic system that copies the files from their repo to the doc

@ewoutp , @neunhoef should I merge this PR and then as soon as you have split the readme file under your docs/tutorial folder we talk with Willi to set up the sync system?

Or what do you suggest. I need to include into the doc some changes that are in this branch, and are not specific to DC2DC, e.g. changes into the deployment chapther, and other new chapters

If we cannot merge this, then I will create a new PR with those other changes and no change to DC2DC

Thanks,

**Comment by sleto-it** [comment]
I think merging this in develop can be the easier solution. Then as soon as you have split the doc in your repo (I can work to send PR if you are too busy), we talk with Willi, and we set up process to replace some specific files

**Comment by ewoutp** [comment]
I'm fine with merging the structure into devel now (and we copy it back into arangosync repo from there) as long as we end up with a set of files in arangosync that are master and an automatic copy produce towards here.

**Comment by sleto-it** [comment]
cool, thanks. willi and me will work on the "automatic" replication of the master files into the doc branch asap.

**Pull request merged**
