### PR TITLE
Bug fix 3.3/add aql check document

### PR DESCRIPTION
**Pull request by jsteemann**

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2606/

**Comment by sleto-it** [comment]
thanks! feel also to add some documentation for the function CHECK_DOCUMENT? or can be done by @Simran-B later if we do not want to delay this PR (in this case pls just open a issue in planning for him)

many thanks,

**Comment by Simran-B** [comment]
It's [purely internal for debugging](https://github.com/arangodb/arangodb/pull/7842#issuecomment-449564166). Not sure what it actually does though.

If you want to document it, then it should go here: https://docs.arangodb.com/3.4/AQL/Functions/Miscellaneous.html#internal-functions

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2637/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2656/

**Pull request merged**
