### PR TITLE
Check authentication for cluster APIs

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1673/

### CODE REVIEW

**Comment by jsteemann** [comment]
@neunhoef: can we merge this?

**Comment by graetzer** [comment]
we need to adjust the permissions required for move shard and shard distribution

**Comment by jsteemann** [comment]
@neunhoef @graetzer: can we merge this?

**Comment by graetzer** [comment]
I think this is ready now

**Comment by jsteemann** [comment]
@neunhoef : click click?

**Pull request closed without merging**
