### PR TITLE
try to stabilize a flaky foxx test

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Try to stabilize a flaky foxx test.
Ideally, this could fix https://arangodb.atlassian.net/browse/BTS-268
The problem seems to have been a race a coordinator startup between databases appearing in Current and the JavaScript code that runs on coordinators at startup.

On initial start, the coordinator created the system database by writing an entry in the agency's Plan. It did not wait for the system database to appear in Current. So it happily went on executing the JavaScript startup code for coordinators, which iterates over all databases and registers an in-memory value for each.
In case all DB servers now created the system database in Current quickly enough, this was not a problem, and everything went fine.
However, in case not all DB servers created the system database in Current quickly enough, the code on the coordinator could already read the list of available databases and would get an empty array, due to the system database not being ready in Current yet.
Now we wait on coordinator startup for at least one database to appear. No change needs to be done on DB servers, and especially we cannot block there on startup, as the DB servers are responsible for creating the databases in Current themselves, so it is important that each DB server starts up and executes the maintenance to create missing databases.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

#### Related Information

- [x] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-268

### Testing & Verification

- [x] This change is already covered by existing tests, such as *shell_server*.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13854/

### CODE REVIEW

**Review by dothebart — APPROVED** [review]

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13861/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14017/

**Comment by jsteemann** [comment]
Tests blue

**Review by dothebart — APPROVED** [review]

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
