### PR TITLE
Docs: Sync external repos 2018-09-26

### PR DESCRIPTION
**Pull request by Simran-B**
Ran fetchRefs.sh, fixed a [broken link and code example](https://github.com/arangodb/arangojs/pull/570) and added new pages to two SUMMARY.md files.

### CODE REVIEW

**Comment by Simran-B** [comment]
`fetchRefs.sh` prepends a "do not edit" text to all files, even images! See #6477

**Comment by Simran-B** [comment]
- The "do not edit" note is only added to Markdown files now.
- Synced ArangoJS changes from 2018-09-13.
- Successful docu build using an oskaresque container on c21
- There is an unintentional section separator in the Drivers book navigation, between the two listed integrations. This is caused by the `# ...` special comment for the [fetchRefs script](There is an uninhttps://github.com/arangodb/arangodb/blob/devel/Documentation/Scripts/fetchRefs.sh#L11). It's unfortunate that Gitbook uses the hash symbol for comments in SUMMARY.md, whereas it stands for a headline in Markdown generally. Removing the spaces between the hash symbol and the text breaks one of your checks, and spaces in front of it will make the script not find it anymore (regex is `^#`). A backward compatible fix would be to add spaces in front of it, and change the regex to: `^ *#` (will this also help for Markdown rendering on Github, i.e. display it as normal text instead of as headline?)

**Comment by Simran-B** [comment]
If an updated docker image is required for a PR (like here), what is the process to update it? Can I push it to the registry and will it be automatically pulled onto the new jenkins?

**Comment by Simran-B** [comment]
Jenkins broken (errors because of "read-only file system"?), but the documentation build itself succeeded.

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/92/

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/94/

**Pull request merged**
