### PR TITLE
[3.4] Background Get Ids

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose
Obtain new unique IDs via a background thread. There are now to batches available and as soon as one batch is used a background thread is started to obtain more ids. This allows the current thread to continue almost immediately.

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5832/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6351/

**Comment by neunhoef** [comment]
We wait for another jenkins run after I merged 3.4 in again.

**Comment by neunhoef** [comment]
This can be merged, there was a Windows test failure, but Frank says that this has other reasons.

**Pull request merged**
