### PR TITLE
bug-fix 3.4 single-edge-definition-editing 

### PR DESCRIPTION
**Pull request by hkernbach**
Same as: https://github.com/arangodb/arangodb/pull/10690

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/job/arangodb-matrix-pr-linux/9467/

**Comment by maxkernbach** [comment]
Tests green

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7854/

**Comment by KVS85** [comment]
Tests blue except unrelated Windows known failure (http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1831/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=windows&&test/artifact/testfailures.log):
```
* Test "active_failover"
    [FAILED]  tests\js\client\active-failover\readonly.js

      "testLeaderAfterFailover" failed: at assertion #181: assertEqual: (4) is not equal to (3)
(Error
    at assertEqual (c:\vm03-windows\oskar\work\ArangoDB\js\common\modules\jsunity\jsunity.js:103:19)
    at Object.tearDown (c:\vm03-windows\oskar\work\ArangoDB\tests\js\client\active-failover\readonly.js:319:7)
    at c:\vm03-windows\oskar\work\ArangoDB\js\common\modules\jsunity\jsunity.js:470:16
    at Object.run (c:\vm03-windows\oskar\work\ArangoDB\js\common\modules\jsunity\jsunity.js:530:15)
    at Object.Run [as run] (c:\vm03-windows\oskar\work\ArangoDB\js\common\modules\jsunity.js:193:24)
    at c:\vm03-windows\oskar\work\ArangoDB\tests\js\client\active-failover\readonly.js:476:9
    at c:\vm03-windows\oskar\work\ArangoDB\tests\js\client\active-failover\readonly.js:479:3
    at RunTest (c:\vm03-windows\oskar\work\ArangoDB\js\common\modules\jsunity.js:273:12)
    at c:\vm03-windows\oskar\work\ArangoDB\js\common\modules\@arangodb\testrunner.js:47:13
    at arrayEach (c:\vm03-windows\oskar\work\ArangoDB\js\node\node_modules\lodash\lodash.js:537:11))

      "totalSetUp" failed: undefined

      "totalTearDown" failed: undefined



   Suites failed: 1 Tests Failed: 3
```

**Pull request merged**
