### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by CoDEmanX**
Actually, Gitbook's markdown parser isn't standard-compliant - or broken in other words.
`<i>text with * in it</i>` should circumvent the problem. If not, a backslash in front of the asterisk should finally fix it, or `&ast;` / `&#42;`.

Cursor and batch size descriptions fit way better to sequential access chapter, and the link to the collection methods is more prominent in the parent chapter.

### CODE REVIEW

**Comment by CoDEmanX** [comment]
Added another commit:
Delete readme.txt on how to generate user manual, because it's incomplete and redundant (README_maintainers.md contains essentially the same info). Also corrected some typos.

There's something missing in README, line 25:
>   AQL Query Example  AQL Query Example

and further down there's
>   Microservice Example  Microservice Example

I can offer a Windows documentation building readme:
https://gist.github.com/CoDEmanX/548cf017e313bd4bc0dd

Not sure how to incorporate it. Would fit in README_maintainers.md, but then there should also be updated instructions for Linux / OSX. Perhaps split the maintainers readme into multiple files?

**Comment by CoDEmanX** [comment]
Added documentation for Arangob, updated its man page.

BTW: The --delay parameter in the blog post misses its value, should be `--delay true`:
https://www.arangodb.com/2012/10/gain-factor-of-5-using-batch-updates/

**Comment by CoDEmanX** [comment]
The 2nd paragraph here is incomplete?
https://docs.arangodb.com/Replication/index.html#replication-configuration

**Comment by dothebart** [comment]
Thanks a lot.

**Comment by jsteemann** [comment]
@CoDEmanX : It turned out that simply adding the `true` to the blog post in Wordpress did not work. It completely killed all the formatting. Wordpress as usual...

I have therefore added a comment to the blog post that explains the parameter is missing. Thanks!

**Comment by dothebart** [comment]
Regarding the readme, I've split it up into two commits to: 
[the cookbook windows article](https://github.com/arangodb/Cookbook/commit/5f939ac95297ca61f76bfafab6bacd939223e026) when compiling windows, and the relevant parts into [README_maintainers](https://github.com/arangodb/arangodb/commit/8f098d9fa4417a13c999d76da14eae69636a3297).
A while back [I've added a portable (to windows) way to generate the examples](https://github.com/arangodb/arangodb/6eb1976b18ec0e28ea5db0a0c2a17bfb0afe3a92) (where I encountered the symlink problem you mention...), 
[now also mentioned in README_maintainers](https://github.com/arangodb/arangodb/commit/a0fe908ae111e5e75df544819d0c9bdccdd25698)

Thats why I scratched the 'nag arangodb team if make barfs' paragraph ;-)

Please note that corrections to included modules may get overwritten if modules are updated (i.e. the yaml module) Eventually you may want to propose that patch upstream therefore ;-)

**Comment by dothebart** [comment]
btw, another thing I failed to finalise is to get the boost tests working on windows. The readme
https://github.com/arangodb/Cookbook/blob/master/recipes/CompilingUnderWindows.md contains the steps up to the point I gave up on "can't mix static and dynamic linking" Maybe you know howto do it? ;-)

**Comment by CoDEmanX** [comment]
@Jan: huh, maybe if you edit it directly in the database? Should stop Wordpress from "re-processing" formatting. But a note is fine.

@dothebart: Thanks!
The link to the portable way to gen examples is broken?!

>  Eventually you may want to propose that patch upstream therefore ;-)

Hm, which file is that exactly? Or did you mean that theoretically?

No clue about how to fix the boost tests :(

**Pull request merged**
