### PR TITLE
Code in file has semi colon in the wrong place, causing a bug

### PR DESCRIPTION
**Pull request by odeds**
It took me sometime to figure out why my foxx upgrade is failing, can save some time for the next person who copy paste :)

### CODE REVIEW

**Comment by Simran-B** [comment]
Good catch!

We would like to accept your patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by Simran-B** [comment]
@odeds Sorry to bother you, but we really need a signed CLA for this to merge it

**Comment by odeds** [comment]
@Simran-B I don't have a printer/scanner at home, i will try to do this next week :)
it's fine by me if you want to fix it yourself and close this pull request.

**Comment by Simran-B** [comment]
No problem, thanks for pointing it out!

**Pull request closed without merging**
