### PR TITLE
better AQL error messages

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
This needs to be added (if ok) to the aql-line-wise branch that I debug parallel to this PR.

**Comment by ObiWahn** [comment]
added missing `break`

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3597/

**Comment by jsteemann** [comment]
Please see https://github.com/arangodb/arangodb/pull/8505#pullrequestreview-217411329

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/4963/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3633/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3646/

**Pull request merged**
