### PR TITLE
[3.4] Bug fix/smart bfs stack size

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #10577.

The enterprise part is in https://github.com/arangodb/enterprise/pull/372.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7658/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7669/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7852/

**Comment by KVS85** [comment]
Tests blue except unrelated known failure (Linux cluster, Enterprise with RocksDB):
```
* Test "shell_server_2"
    [FAILED]  tests/js/server/shell/shell-skiplist-correctness.js

      "testFillIndexFailure" failed: at assertion #4: assertEqual: (1) is not equal to (2)
(Error
    at assertEqual (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:103:19)
    at Object.testFillIndexFailure (tests/js/server/shell/shell-skiplist-correctness.js:329:7)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:526:23)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:193:24)
    at tests/js/server/shell/shell-skiplist-correctness.js:338:9
    at tests/js/server/shell/shell-skiplist-correctness.js:341:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:273:12)
    at eval (eval at callback (/work/ArangoDB/js/actions/_admin/app.js:82:18), <anonymous>:2:52)
    at eval (eval at callback (/work/ArangoDB/js/actions/_admin/app.js:82:18), <anonymous>:2:135)
    at Function.callback (/work/ArangoDB/js/actions/_admin/app.js:82:18))

      "totalSetUp" failed: undefined

      "totalTearDown" failed: undefined

   Suites failed: 1 Tests Failed: 3
```

**Pull request merged**
