### PR TITLE
query errors 1501,1502,1510,1511 now result in http 400

### PR DESCRIPTION
**Pull request by baslr**
(empty,parse error,variable name invalid,variable redeclared) result in http 400

today I noticed that my query
```
let a = {_key :123}
UPSERT {_key: a._key} INSERT a IN test
```
resulted in http 500 with `syntax error ...` Also empty queries and
variable redeclaration `let a = 4 let a = 4 return a` result in 500.
Finally found the root cause.

### CODE REVIEW

**Comment by baslr** [comment]
the test for the cursor query could be wrong:
https://travis-ci.org/arangodb/arangodb/builds/97748030#L9208
https://travis-ci.org/arangodb/arangodb/builds/97903140#L9451

I compiled b39a02b69180abe6caab79117d7485dda16943ff 
```
architecture: 64bit
build-date: 2015-12-20 01:58:02
configure:  './configure' '--with-openssl-inc=/opt/local/include/' '--with-openssl-lib=/opt/local/lib/' '--host=x86_64-apple-darwin15.2.0' '--target=x86_64-apple-darwin15.2.0' 'host_alias=x86_64-apple-darwin15.2.0' 'target_alias=x86_64-apple-darwin15.2.0'
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
libev-version: 4.11
maintainer-mode: false
openssl-version: OpenSSL 1.0.2e 3 Dec 2015
repository-version: remotes/origin/ClustUp1-41-gb39a02b69180abe6caab79117d7485dda16943ff-dirty
server-version: 2.7.0-devel
sizeof int: 4
sizeof void*: 8
tcmalloc: false
v8-version: 4.3.61
```

```
POST  /_db/_system/_api/cursor
{
  "query": "FOR u IN @cn FILTER u.name = @name LIMIT 2 RETURN u.n",
  "bindVars": {
    "cn": "users",
    "name": "peter"
  },
  "count": false,
  "options": {
    "fullCount": false
  }
}
# res
500
{ server: 'arangodb',
  connection: 'keep-alive',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '161' }
{
  "error": true,
  "errorMessage": "syntax error, unexpected assignment near '= @name LIMIT 2 RETURN u.n' at position 1:28 (while parsing)",
  "code": 500,
  "errorNum": 1501
}
```

**Comment by baslr** [comment]
Interesting: ArangoDB v2.5.7 returns http 4 on 1501/1502

**Comment by fceller** [comment]
Hi @baslr we would like to use the Apache Contributor License in order to stay Apache 2 licensed. Would it be possible for you to send us a signed copy as PDF? See https://www.arangodb.com/documents/cla.pdf

**Comment by fceller** [comment]
@baslr if you need any additional information, you can contact as: hackers (at) arangodb.com

Thanks a lot for your contributions.

**Comment by jsteemann** [comment]
The response code HTTP 400 is the correct return code for the cases you mentioned.
Due to some internal refactoring some HTTP status codes changed in 2.8, which was unintended.

I was told we did not receive a signed CLA from you yet, so I unfortunately could not merge your PR into devel and 2.8. So I rolled my own fix which also handles a lot of other status codes that always resulted in an `HTTP 500` being returned while other return codes actually make more sense.

**Pull request closed without merging**
