### PR TITLE
Add query execution time and query id to audit log query messages.

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Log query runtime and query id in audit log query messages.
This is a backport of the functionality in https://github.com/arangodb/arangodb/pull/13260, but without any of the refactoring.

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/611

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

#### Related Information

- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/611

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13304/

### CODE REVIEW

**Review by fceller — APPROVED** [review]
LGTM

**Review by fceller — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
Tests blue

**Comment by KVS85** [comment]
feature-3.6/audit-query-logging-improvements

**Comment by KVS85** [comment]
Tests blue except known failure in time-dependent unreliable test.

**Pull request merged**
