### PR TITLE
Ungreylist shell-query-stream-timecritical-spec

### PR DESCRIPTION
**Pull request by markuspf**
I ran this test overnight on current devel and it still passed. I will run a Jenkins now to see whether it passes there, too.

### CODE REVIEW

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7525/

**Comment by markuspf** [comment]
See also https://github.com/arangodb/planning/issues/4682

**Comment by markuspf** [comment]
A recent jenkins run to validate mergeability:

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7562/

**Comment by markuspf** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7569/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7692/

**Comment by jsteemann** [comment]
@markuspf : mmh, I don't see any change to the test code in this PR. How will this work more reliably now than before?

**Comment by markuspf** [comment]
I think the short answer is: it doesn't, but I cannot get it to fail, and I also don't have a good idea how to fix it if I did:

The test uses `SLEEP` in a query to test slow query detection and handling. It uses a default delay of `5` seconds for slow queries.

Of course it can happen that a test run is so slow that even queries that do not sleep (or sleep for a very short time) are still marked "slow";

It strikes me that we then have a big problem with the test setup, and I cannot think of a good solution to "calibrate" where to put a slow-query sleep threshold.

If there's another reliability problem, I'd be happy to fix it if someone managed to reproduce it.

**Comment by dothebart** [comment]
IMHO the `-timecritical` has to stay in place. `grey` was added to all `-timecritical` without taking this into account.

**Comment by jsteemann** [comment]
Closing as obsolete

**Pull request closed without merging**
