### PR TITLE
Bug fix/planning issue 514 replication api

### PR DESCRIPTION
**Pull request by ObiWahn**
https://github.com/arangodb/planning/issues/514

### CODE REVIEW

**Comment by graetzer** [comment]
This pull requests does not address `logger-first-tick`, `logger-tick-ranges`

**Comment by ObiWahn** [comment]
https://github.com/arangodb/arangodb/blob/a14ad78d3e6b9b26a902f01312a946d5a00c768d/Documentation/DocuBlocks/Rest/Replication/JSF_get_api_replication_dump.md Line 28 Updates the doc accordingly. There was no request to change the behavior.

**Comment by jsteemann** [comment]
@simon @ObiWahn : should we document/fix these APIs too?

**Comment by graetzer** [comment]
@ObiWahn I don't get it, why is `/_api/replication/dump` relevant here.
I am also fairly certain rocksdb supports the `chunkSize`: https://github.com/arangodb/arangodb/blob/devel/arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp#L2417

**Comment by graetzer** [comment]
I implemented the missing REST handlers and fixed the `dump` docs

**Comment by ObiWahn** [comment]
That is nice but seems unrelated to the request opened by @neunhoef. Was there a failing test or something else that uses the "missing" routes?

**Comment by graetzer** [comment]
To quote @neunhoef 
> Some calls are not implemented for RocksDB, this should be reflected in the manual.

I just implemented the missing ones, no the manual is correct again ;-)

**Pull request merged**
