### PR TITLE
Admin cookie authentication

### PR DESCRIPTION
**Pull request by pluma**
**NOTE: This is a work in progress. Do not merge yet.**

This PR implements cookie-based login/logout and sessions in Aardvark.

# TODO

* [x] Implement baseline login/logout logic using Foxx sessions with cookies.
* [x] Refactor frontend logic to only make the initial API requests when authenticated.
* [x] Prettier login form. (@hkernbach?)
* [x] Don't apply `disableAuthentication` to aardvark (C++?)
* [x] Implement session cookie auth (with `arango-sid-$dbName`) in API (C++).
* [x] Expose `disableAuthentication` status to JS (C++).
* [x] If `disableAuthentication` is active, `whoAmI` should return `false` as user.
* [x] Make `_api/collection` behave correctly when using cookie auth (@fceller)

### CODE REVIEW

**Comment by pluma** [comment]
Pinging @fceller @mchacki 

My work here is done, I think.

**Comment by razvanphp** [comment]
+1

Please consider different username/passwords for different databases and an easy way to switch. In the current implementation, browser caches the Basic Auth and some databases are just hidden. To complicate things even more, some Foxx apps might have different credentials, so web "Try me!" should still work.

**Comment by pluma** [comment]
@razvanphp with this PR you'll be able to logout and switch to any databases available to the same user. I guess user switching would be a nice feature, but this'll at least make it easier.

Once the C++ logic is implemented, this could land in the next release.

**Comment by pluma** [comment]
This would fix #1262.

**Comment by razvanphp** [comment]
We still get the Basic Auth password popup sometimes, with the name "db/_system". Even if I put the correct password, he then redirects me to the new login page. Is this intended? Bug?

**Comment by pluma** [comment]
Interesting. Can you isolate reproducible steps? I'm guessing it's caused by the logged-in web admin's polling, which hits the API, which will still fall back to Basic Auth if the cookie has been cleared or is expired. There's no obvious solution to fix that AFAICT.

**Comment by razvanphp** [comment]
Yes, I think it happens when the session expires, I just get it now all the time when I refresh and not login into the new form. I still have the cookies at this time, but even if I delete them, it behaves the same.

The requests that seem to triggers this:
`http://server:8529/_db/_system/_api/collection?_=1434385045202` -> 401 Unauthorized

here I get the basic auth popup (I can get rid of it only if I click cancel)... and then another request appears:

`http://server:8529/_db/_system/_admin/aardvark/whoAmI?_=1434385271417`

That responds 200 with body `{"user":null}`

**Comment by pluma** [comment]
@razvanphp Can you clarify: you're getting the basic auth popup when you refresh and it happens *before* the login form is shown? That would be a bug in the frontend (a regression, in fact).

OTOH it's expected behaviour that you don't get a cookie if you log in via basic auth. The cookie-based login is controlled by the admin frontend, the basic auth login by the API. Setting a cookie after basic auth would affect the entire API (which otherwise aims to be stateless). You shouldn't see basic auth dialogs in the frontend, however, unless you make API requests after the session expires. There doesn't seem to be a way to intercept 401 popups generated from AJAX requests, but that's a browser issue.

**Comment by razvanphp** [comment]
Yes, it happens BEFORE the login form is shown. In fact, it does not appeat until I close the basic auth popup.

As I said, it's the collections API call that is causing this, maybe it's triggered too soon, before the whoAmI call.

**Comment by pluma** [comment]
Yes, that's not supposed to happen. I'm investigating what caused the regression and how we can avoid it.

**Comment by pluma** [comment]
Okay, I've tracked it down to this commit: 5cf30c71a59a52965f322fe16054324bd333d2fb

Seems like the client.js in aardvark is a generated file. I'll see whether changing the original source impacts arangosh. Otherwise this should be trivial to fix.

**Comment by pluma** [comment]
@razvanphp I've fixed it in devel. The logic now behaves correctly in both the browser (lazy init) and arangosh (eager init).

**Pull request merged**
