### PR TITLE
[3.5] Missing post failure on readlock in SynchronizeShard & RebootTracker

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by neunhoef** [comment]
This is still WIP and should be finished for 3.5.4 next week.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7835/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7837/

**Comment by KVS85** [comment]
Tests red.

`tests/js/server/resilience/move/moving-shards-cluster.js` of `resilience_move` fails (reproducibly) with the following errors:
```
* Test "resilience_move"
    [FAILED]  tests/js/server/resilience/move/moving-shards-cluster.js

      "testShrinkNoReplication_nodata" failed: at assertion #4: assertTrue: (false) does not evaluate to true
(Error
    at assertTrue (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:72:19)
    at Object.testShrinkNoReplication (tests/js/server/resilience/move/moving-shards-cluster.js:633:7)
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:532:23)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52))

      "testMoveShardFromFollower_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeader_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeaderNoReplication_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromFollowerRepl3_1_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromRepl3_2_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeaderRepl_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeaderToFollower_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testResignLeadership_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutFollower_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutLeader_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutMultipleCollections_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOut3Replicas_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutMultipleShards_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutNoReplication_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMaintenanceMode_nodata" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:922:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testSetup_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testShrinkNoReplication_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromFollower_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeader_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeaderNoReplication_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromFollowerRepl3_1_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromRepl3_2_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeaderRepl_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMoveShardFromLeaderToFollower_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testResignLeadership_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutFollower_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutLeader_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutMultipleCollections_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOut3Replicas_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutMultipleShards_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testCleanOutNoReplication_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "testMaintenanceMode_data" failed: ArangoError 1487: the number of current dbservers is lower than the requested replicationFactor - ArangoError: the number of current dbservers is lower than the requested replicationFactor
    at createSomeCollections (tests/js/server/resilience/move/moving-shards-cluster.js:503:23)
    at Object.setUp (tests/js/server/resilience/move/moving-shards-cluster.js:589:7)
    at /work/ArangoDB/js/common/modules/jsunity/jsunity.js:476:16
    at Object.run (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:529:15)
    at Object.Run [as run] (/work/ArangoDB/js/common/modules/jsunity.js:195:24)
    at tests/js/server/resilience/move/moving-shards-cluster.js:928:9
    at tests/js/server/resilience/move/moving-shards-cluster.js:936:3
    at RunTest (/work/ArangoDB/js/common/modules/jsunity.js:275:12)
    at source (eval at <anonymous> (unknown source), <anonymous>:4:52)

      "totalSetUp" failed: undefined

      "totalTearDown" failed: undefined

   Suites failed: 1 Tests Failed: 35
```

Test logs, server logs: [arangosh_LhdOhH.zip](https://github.com/arangodb/arangodb/files/4002681/arangosh_LhdOhH.zip)

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7851/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
