### PR TITLE
[3.7] fix default collection property cache enabled

### PR DESCRIPTION
**Pull request by kvahed**
[### Scope & Purpose

*fix default collection property cache enabled*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [X] :book: Documentation 

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document: 

](https://github.com/arangodb/arangodb/pull/16289)

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM!

**Review by ansoboleva — APPROVED** [review]
lgtm

**Comment by ansoboleva** [comment]
because of the changed docublock, this PR requires example generation: https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/1997/

**Comment by ansoboleva** [comment]
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/2002/ - executed successfully, changes are committed to the docs repo. This PR can be merged now.

**Comment by KVS85** [comment]
Can't be merged into 3.7.18 because it's finalized and 3.7 is EoL.

**Pull request closed without merging**
