### PR TITLE
Docs: Fix query option optimizer.rules in DocuBlock

### PR DESCRIPTION
**Pull request by Simran-B**
`"optimizer": { "rules": [ ... ] }` is expected, not `"optimizer.rules": [ ... ]`

Also fixes semantic errors (equivalent paths) and duplicate operation IDs.
And updates doc URL in Web UI.

### CODE REVIEW

**Comment by Simran-B** [comment]
```diff
-                "optimizer.rules": {
-                    "description": "an array of to-be-included or to-be-excluded optimizer rules\ncan be put into this attribute, telling the optimizer to include or exclude\nspecific rules. To disable a rule, prefix its name with a `-`, to enable a rule, prefix it\nwith a `+`. There is also a pseudo-rule `all`, which will match all optimizer rules.\n\n",
+                "optimizer": {
+                    "$ref": "#/definitions/explain_options_optimizer"
+                }
+            },
+            "type": "object",
+            "x-filename": "/home/simran/oskar/work/ArangoDB/Documentation/DocuBlocks/Rest/AQL/post_api_explain.md"
+        },
+        "explain_options_optimizer": {
+            "description": "Options related to the query optimizer.\n\n",
+            "properties": {
+                "rules": {
+                    "description": "A list of to-be-included or to-be-excluded optimizer rules can be put into this\nattribute, telling the optimizer to include or exclude specific rules. To disable\na rule, prefix its name with a `-`, to enable a rule, prefix it with a `+`. There is\nalso a pseudo-rule `all`, which matches all optimizer rules. `-all` disables all rules.\n\n",
                     "format": "string",
                     "items": {
                         "type": "string"
```

@dothebart does `items` implicitly mean array (of strings)?

**Comment by dothebart** [comment]
it may be invalid. please consult the swagger editor to detect potential invalid openapi definitions.

**Comment by Simran-B** [comment]
There are a few semantic errors, but all unrelated. LGTM:

image

image

**Comment by Simran-B** [comment]
There are overlapping routes (equivalent paths), making Swagger editor complain (semantic error). 

Some of the path parameters are named inconsistently.

`{document-handle}` is actually a document ID, so `{collection-name}/{document-key}` (with the slash **not** URL encoded as `%2F`!), so this can be used to disambiguate some of the routes. Note that some error messages need to be adjusted as well to not say something about `document-handle` anymore.

Note that there are 3 PUT routes. Reading multiple docs requires the query param `?onlyget=true`. Can this be hardcoded into the path to disambiguate the route or does Swagger not allow this? We might not be allowed to document it as `@RESTQUERYPARAM` in addition.

```
Current:

PUT     /_api/document/{collection-name}     get documents (multiple), GET does not support body
POST    /_api/document/{collection-name}     create new documents (multiple)
PATCH   /_api/document/{collection}          update documents (multiple)
PUT     /_api/document/{collection}          replace documents (multiple)
DELETE  /_api/document/{collection}          delete documents (multiple)

HEAD    /_api/document/{document-handle}     get document header fields (single)
GET     /_api/document/{document-handle}     get document (single)
POST    /_api/document/{collection}          create document (single)
PATCH   /_api/document/{document-handle}     update document (single)
PUT     /_api/document/{document-handle}     replace document (single)
DELETE  /_api/document/{document-handle}     delete document (single)

Suggestion:

PUT     /_api/document/{collection}?onlyget=true  get documents (multiple), GET does not support body
POST    /_api/document/{collection}#multiple      create new documents (multiple)
PATCH   /_api/document/{collection}               update documents (multiple)
PUT     /_api/document/{collection}               replace documents (multiple)
DELETE  /_api/document/{collection}               delete documents (multiple)

HEAD    /_api/document/{collection}/{key}         get document header fields (single)
GET     /_api/document/{collection}/{key}         get document (single)
POST    /_api/document/{collection}               create document (single)
PATCH   /_api/document/{collection}/{key}         update document (single)
PUT     /_api/document/{collection}/{key}         replace document (single)
DELETE  /_api/document/{collection}/{key}         delete document (single)
```

**Comment by Simran-B** [comment]
```
Semantic error at paths./_api/document/{collection}?onlyget=true
Query strings in paths are not allowed.
```

Changed:

```diff
-PUT     /_api/document/{collection}?onlyget=true
+PUT     /_api/document/{collection}#get

-PUT     /_api/gharial/{graph}/edge/{definition}
+PUT     /_api/gharial/{graph}/edge/{definition}#definition

-DELETE  /_api/gharial/{graph}/edge/{definition}
+DELETE  /_api/gharial/{graph}/edge/{definition}#definition
```

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/483/

**Comment by Simran-B** [comment]
TODO: remove subtype boolean from boolean type properties

**Comment by Simran-B** [comment]
Test run / preview for latest change:
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/487/

**Comment by Simran-B** [comment]
Example generation succeeded and I checked the Swagger JSON in the online editor - no more semantic errors!
https://github.com/arangodb/docs/pull/261

**Pull request merged**
