### PR TITLE
Do not audit log replication writes by default [BTS_826]

### PR DESCRIPTION
**Pull request by neunhoef**
We found that replication document writes are audit logged on the DEBUG
log level of the topic "audit-document". Seemingly accidentally the
default log level for this topic is currently DEBUG. This leads to
extreme delays for shards trying to get in sync, since there there is
an audit log call for every single document being replicated. Since
a synchronously written audit log can delay writing a document by up
to a factor of 1000 and since the document write has already been audit
logged on the leader, we propose to set the default log level for
"audit-document" to INFO, which was probably intended in the first
place.

Similarly, the default log level for "audit-authentication" is also
DEBUG. This leads that non-authentication events for low priority things
like credentials missing for internal UI requests and /_open/auth are
currently audit logged by default. Again, we propose to change the 
default log level for "audit-authentication" to INFO, which was probably
intended in the first place.

### Scope & Purpose

*(Please describe the changes in this PR for reviewers, motivation, rationale - **mandatory**)*

- [*] :hankey: Bugfix
- [*] :fire: Performance improvement

### Checklist

- [*] :book: CHANGELOG entry made
- [*] Backports
  - [*] This is the backport for 3.9. Original: https://github.com/arangodb/arangodb/pull/15924

### CODE REVIEW

**Comment by neunhoef** [comment]
This is awaiting release-owners decisions, therefore the DO_NOT_MERGE label.

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by neunhoef** [comment]
Decision by silence to backport.

**Review by kvahed — APPROVED** [review]
LGTM

**Pull request merged**
