### PR TITLE
Update iresearch

### PR DESCRIPTION
**Pull request by gnusi**
### Scope & Purpose

IResearch library upgrade

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by Dronplane — APPROVED** [review]
LGTM

**Comment by dothebart** [comment]
I strictly vote against trying git submodules once more. 
We have wasted hours of developer time waiting for their checkouts and getting their checkouts working after switching branches etc. On disk representation grew in size last time we tried by a lot. We should not repeat this mistake.

**Comment by goedderz** [comment]
While I wasn't involved in the previous try, I'm actually looking forward to using git submodules for our 3rdParty libs. That will make the repository smaller and cleaner, and make it less work to push changes to 3rdParty repos. And it seems to work cleanly in several other projects I've used or am using, so I'd be surprised if there was a fundamental issue with it.

**Comment by gnusi** [comment]
For now unfortunately not `git submodule` nor cmake `fetchContent` don't work reliably with our CI. We'll adjust oskar and give another try later on. This PR is nailed down to regular iresearch update from upstream.

**Pull request merged**
