### PR TITLE
use the primary index when full-scanning a collection

### PR DESCRIPTION
**Pull request by jsteemann**
and not peeking into any of the documents. this is preferrable to using
  the documents column family because in RocksDB keys and values are stored
  together, and the values in the documents column family can be much bigger
  than the values in the index column family.

  this optimization is only pulled off if the documents are not used later
  on

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3674/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3686/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4076/

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4087/

**Comment by graetzer** [comment]
stupid question: Did you measure how much the a performance improves ?

**Pull request merged**
