### PR TITLE
Check authentication for cluster APIs

### PR DESCRIPTION
**Pull request by graetzer**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4093/

### CODE REVIEW

**Comment by jsteemann** [comment]
Got some test failures, which may be completely unrelated.
Therefore re-running tests:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2876/

**Comment by jsteemann** [comment]
I saw the PR contains some adjustments for the web interface (restriction to `_system` database), which is good.
Do we also need to restrict some of the operations to admin users in the web interface?

**Comment by jsteemann** [comment]
Talked to @mchacki : needs some UI adjustments before merging.
Can be done soon.

**Comment by Darkheir** [comment]
I think that limiting the "Rebalance shards" button to only the `_system` database makes it impossible to rebalance the shards of the others databases.

In my case the `_system` db has no collections so the button is not displayed and in my others databases the button don't appear so we can't rebalance shards ...

**Pull request merged**
