### PR TITLE
Make the reboot tracker catch failed coordinators, too.

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Make the reboot tracker catch failed coordinators, too.
Previously the reboot tracker was invoked only when a DB server failed or was restarted, and when a coordinator was restarted.
Now it will also act if a coordinator just fails (without restart).

- [x] :hankey: Bugfix 
- [x] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] Backports required for: 3.5 (https://github.com/arangodb/arangodb/pull/12636), 3.6 (https://github.com/arangodb/arangodb/pull/12606), 3.7

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11877/

### CODE REVIEW

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11878/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11883/

**Comment by jsteemann** [comment]
Tests blue

**Review by KVS85 — APPROVED** [review]

**Pull request merged**
