### PR TITLE
fix idle timeouts for VST and HTTP/2

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

The effective idle timeout was almost always bumped up to the full 300 seconds (i.e. this->WriteTimeout) instead of the configured value of `--http.keep-alive-timeout`.
This was supposed to be fixed for 3.7.3 already, but apparently did not work properly.

We should add additional tests by drivers (e.g. Java) to cover this case.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12476/

### CODE REVIEW

**Comment by graetzer** [comment]
so what is this doing tests/js/client/server_parameters/test-idle-timeouts.js ?

**Review by graetzer — COMMENTED** [review]
why are the existing tests not covering this

**Comment by jsteemann** [comment]
`server_parameters` tests are only running with http+tcp, not with vst or http/2.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12495/

**Comment by jsteemann** [comment]
Obsolete at the moment. Will be reopened once a solution has been approved for devel.

**Pull request closed without merging**
