### PR TITLE
Feature/split libarangoserver

### PR DESCRIPTION
**Pull request by goedderz**
Split `libarangoserver` into multiple smaller libraries. This is motivated for once by https://github.com/arangodb/arangodb/pull/9596 running into https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1248?view=vs-2019: That is, the static data & code section of Windows binaries may not exceed 2GB, even for 64bit binaries. We might run into this sooner or later anyway.

Plus having multiple small libraries, as opposed to one huge monolithic library, is cleaner, and we can hope for much faster link times when only few object files were changed.

Based on https://github.com/arangodb/arangodb/pull/9666 and should be merged after it.

There is still more we could do, but for now it seems like a noticeable improvement.

### CODE REVIEW

**Comment by goedderz** [comment]
An intermediate PR run: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5740/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5867/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5901/

**Comment by goedderz** [comment]
Current dependency tree of the split arangoserver library. Reported by `cmake --graphviz=...`, I removed other libraries (i.e. everything that isn't split off arangoserver), and did a transitive reduction of the graph with `tred` to make it easier to look at.

split-arangoserver

**Comment by goedderz** [comment]
Current dependency tree of the split arangoserver library. Reported by `cmake --graphviz=...`, I removed other libraries (i.e. everything that isn't split off arangoserver), and did a transitive reduction of the graph with `tred` to make it easier to look at.

split-arangoserver

**Comment by dothebart** [comment]
Nice! I don't understand, why the V8 isn't more wide spread - since there are wrappers for the most functionalities in place?

**Comment by goedderz** [comment]
I find that dubious, too. But even when moving them manually at the far end of the list of linked libraries, the linker doesn't complain. So at least by trying it out, it doesn't seem I missed anything (at least for these libs, I've surely missed something somewhere :wink: ).

**Comment by goedderz** [comment]
Updated graph:
split-arangoserver

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5911/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5912/

**Comment by goedderz** [comment]
One failure left on linux/community edition, retry:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5918/

**Comment by goedderz** [comment]
Some Jenkins hiccups before, new try:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5922/

**Comment by goedderz** [comment]
Release builds work fine:
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-windows-packages/327/
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-linux-packages/305/
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-mac-packages/321/

**Pull request merged**
