### PR TITLE
tell users they must not use arangosh to invoke these (#13013)

### PR DESCRIPTION
**Pull request by dothebart**
backport of https://github.com/arangodb/arangodb/pull/13013

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13098/

**Comment by dothebart** [comment]
blue except 1 mac and 1 linux test failing to checkout the source

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13169/

**Comment by KVS85** [comment]
Tests blue.

**Review by jsteemann — APPROVED** [review]

**Pull request merged**
