### PR TITLE
remove old, potentially unsafe ScopeGuard implementation

### PR DESCRIPTION
**Pull request by jsteemann**
use TRI_DEFER instead so there are less variants

Motivation for this PR: remove a ScopeGuard implementation that was effectively used in just a few places, and replace it with the much more frequently used TRI_DEFER mechanism.

### CODE REVIEW

**Comment by danielhlarkin** [comment]
@jsteemann I definitely understand wanting one mechanism for deferred/scoped execution. I'm on board with removing `ScopeGuard` and keeping `TRI_DEFER` given that `TRI_DEFER` is more widely used and offers exception-safety.

I am, however, wondering about the trade-offs between the two current mechanisms, partially to foster a discussion regarding whether we want to keep `TRI_DEFER` indefinitely or potentially replace it at some point.

It looks like `TRI_DEFER` includes:
 * PRO exception safety
 * PRO some file/line numbering facility (which probably helps with debugging)
 * UNCLEAR automatic lambda-wrapping
 * CON macro magic
 * CON release-only semantics
 * CON seems API is only guaranteed to work with a single statement

It looks like `ScopeGuard` includes:
 * PRO acquire-release semantics
 * UNCLEAR no lambda-wrapping, explicit API
 * CON no exception safety
 * CON no file/line numbering

The biggest question, I think, is whether the automatic lambda-wrapping is a good thing or a bad thing. On the one hand, it is convenient, and reduces some boilerplate. On the other hand, it potentially removes control from the user, and could hide additional surprises.

Personally I lean towards non-macro solutions whenever possible. It seems the main benefit that `TRI_DEFER` provides over using the underlying class is the file/line numbering. I wonder to what extent this actually helps debugging?

Additionally, it seems we could potentially use a couple variants of this pattern. One simply a `DeferredExcecution`, with release-only semantics. The other a `ResourceGuard` solution, with acquire-release semantics. They could share an underlying implementation, no doubt. There's no reason that we couldn't use this also as a basis for our various locker classes as well.

**Comment by jsteemann** [comment]
I simply wanted to reduce the variants that are in use, *now*.
As it was, `ScopeGuard` did not provide any additional value compared to `TRI_DEFER`. And it was neither efficient nor safe.

I hope we will eventually extend `TRI_DEFER` with some proper mechanism so most of the concerns you mentioned will be addressed. But I would like to do it in a separate step, to PRs keep manageable and move quickly.

**Comment by danielhlarkin** [comment]
@jsteemann Agreed. I wanted to put those thoughts out there for the record.

**Comment by jsteemann** [comment]
Yes, and I totally agree this will be a good thing to do and to extend it in the future.

**Comment by jsteemann** [comment]
@danielhlarkin : thanks!

**Pull request merged**
