### PR TITLE
fixed version of arangosh result evaluation refactoring - properly count objects

### PR DESCRIPTION
**Pull request by dothebart**
## Scope & Purpose
This refactors the `testing.js` result evaluation into an own library, and adds more result evaluators plus the possibility to only invoke result evaluators with old testreport-json files.

- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification
This is a refactoring.
### Documentation
 - [x] described the functionality in README_maintainers.md

### CODE REVIEW

**Comment by jsteemann** [comment]
@dothebart : please start a Jenkins PR run

**Comment by dothebart** [comment]
forgot to post: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6427/ - only unrelated issues.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8127/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6439/

**Pull request merged**
