### PR TITLE
do not kill thread in case of exception

### PR DESCRIPTION
**Pull request by fceller**
In case of SSL connection not catching the exception during shutdown can cause a hanger.

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13289/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13311

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13312/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13313/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13337/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13340/

**Comment by KVS85** [comment]
Test blue except known false positive failure.

**Pull request merged**
