### PR TITLE
Improve performance and memory efficiency of agency restart

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Make agency restart from persistence more efficient in terms of performance and memory usage, by skipping over irrelevant log entries in the `log` collection, and using slightly more efficient code.

This is a minimal backport of the changes in https://github.com/arangodb/arangodb/pull/13199

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [x] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *agency, mini chaos*.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13154/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Review by neunhoef — APPROVED** [review]
LGTM

**Review by fceller — APPROVED** [review]

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13243/

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
