### PR TITLE
fixed api views within the ui

### PR DESCRIPTION
**Pull request by hkernbach**

### CODE REVIEW

**Comment by mpv1989** [comment]
After I added a `link` to the properties with:
```
 "links": {
    "test-collection": {}
}
```
I got the following result.
```
  "links": {
    "test-collection": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": false,
      "trackListPositions": false,
      "storeValues": "none",
      "id": "819547",
      "type": "arangosearch",
      "view": "hD10209C4EF61/819364"
    }
  }
```
Since the fields `id`, `type`, `view` are not documented in the [HTTP REST API documentation](https://docs.arangodb.com/devel/HTTP/Views/ArangoSearch.html), I assume they are internal fields and should not be printed in the webUI.

**Comment by mpv1989** [comment]
We have an inconsistent behavior between collection links and field links.
Collection links are displayed with default values. The properties of field links are only displayed when they vary from the defaults.

**Example**

sending
```
  "links": {
    "test-collection": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "value": {
          "includeAllFields": false
        }
      },
      "includeAllFields": false,
      "trackListPositions": false,
      "storeValues": "none",
      "id": "819547",
      "type": "arangosearch",
      "view": "hD10209C4EF61/819364"
    }
  }
```
removes `includeAllFields` from field link `value`
```
  "links": {
    "test-collection": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "value": {}
      },
      "includeAllFields": false,
      "trackListPositions": false,
      "storeValues": "none",
      "id": "819547",
      "type": "arangosearch",
      "view": "hD10209C4EF61/819364"
    }
  }
```

**Comment by mpv1989** [comment]
In view `queries` when I open the AQL keyword/function search, I can not find the keyword `VIEW`.

Steps to reproduce this:
1. Go to view `queries`
2. Click on the magic wand or press `ctrl`+`space`
3. type "VIEW"

I expect the same functionality as when I search for the keyword `GRAPH`

**Comment by hkernbach** [comment]
> do we mean it serious that you can change the properties of a arangosearch view only in a Json editor. So I have to read the HTTP REST API documentation to work with the webUI?

Currently, I assume yes.

> Since the fields id, type, view are not documented in the HTTP REST API documentation, I assume they are internal fields and should not be printed in the webUI.

Then we need some mechanism to get exactly that info. If we do this manually, someday it will be broken. 

> We have an inconsistent behavior between collection links and field links.
Collection links are displayed with default values. The properties of field links are only displayed when they vary from the defaults.

Needs to be adjusted, but not in this PR. 

> I expect the same functionality as when I search for the keyword GRAPH

Added.

**Pull request merged**
