### PR TITLE
[BTS-714] Fix various TSan issues. 

### PR DESCRIPTION
**Pull request by mpoeter**
### Scope & Purpose

This PR fixes various issues found during 3.9 release testing. I also found most of them independently during local testing and fixed them in #15514 for devel, so this is basically a backport of that PR.

- [x] :hankey: Bugfix 

#### Backports:

- [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

- [x] Jira ticket number: https://arangodb.atlassian.net/browse/BTS-714

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests
- [x] I ensured this code runs with TSan

### CODE REVIEW

**Comment by mpoeter** [comment]
https://jenkins.arangodb.biz:3456/job/arangodb-ANY-linux-san.x86-64/953/

**Review by Dronplane — CHANGES_REQUESTED** [review]
Let's not suppress IResearch* part. It really doesn't look like false positives.  We need this to be fixed eventually. Also suppressing by only file/class  name will disable not only the issue we already know about (like BTS-685) but potentially make us blind for all new issues in the same files/classes.

**Comment by mpoeter** [comment]
https://jenkins.arangodb.biz:3456/job/arangodb-ANY-linux-san.x86-64/956/

**Review by MBkkt — APPROVED** [review]
LGTM

**Comment by MBkkt** [comment]
You forgot rebase or merge origin/3.9 in your branch
https://github.com/arangodb/arangodb/blob/3.9/tsan_arangodb_suppressions.txt

**Review by Dronplane — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/963/

**Pull request merged**
