### PR TITLE
ES-1006 Documentation/fix admin server tls documentation 3.7

### PR DESCRIPTION
**Pull request by kapahimansi123**
### Scope & Purpose

- Corrected documentation for admin server to reflect that the end point is protected.

#### Backports:

changes not needed before 3.7

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Review by dothebart — APPROVED** [review]
Nice! Thanks!

**Comment by ansoboleva** [comment]
@kapahimansi123 
1. As per https://arangodb.atlassian.net/browse/ES-1006 ticket, the documentation for the GET /_admin/server/mode incorrectly states that it does not require authentication. Why is not fixed in this PR?
2. For the GET /_admin/server/tls call (which you've actually changed here), not superuser rights, but authentication is required. "The corresponding POST request is superuser only, but the GET request is available to any authenticated user, regardless of his/her permissions." - see this comment in PR #15172: https://github.com/arangodb/arangodb/pull/15172.

Please correct the documentation accordingly for both methods. The same applies to the PRs for other versions:
https://github.com/arangodb/arangodb/pull/15251
https://github.com/arangodb/arangodb/pull/15252
https://github.com/arangodb/arangodb/pull/15253

**Review by ansoboleva — CHANGES_REQUESTED** [review]
@kapahimansi123 
1. As per https://arangodb.atlassian.net/browse/ES-1006 ticket, the documentation for the GET /_admin/server/mode incorrectly states that it does not require authentication. Why is not fixed in this PR?
2. For the GET /_admin/server/tls call (which you've actually changed here), not superuser rights, but authentication is required. "The corresponding POST request is superuser only, but the GET request is available to any authenticated user, regardless of his/her permissions." - see this comment in PR 15172: https://github.com/arangodb/arangodb/pull/15172.

Please correct the documentation accordingly for both methods. The same applies to the PRs for other versions:
https://github.com/arangodb/arangodb/pull/15251
https://github.com/arangodb/arangodb/pull/15252
https://github.com/arangodb/arangodb/pull/15253

**Comment by kapahimansi123** [comment]
> @kapahimansi123
> 
> 1. As per https://arangodb.atlassian.net/browse/ES-1006 ticket, the documentation for the GET /_admin/server/mode incorrectly states that it does not require authentication. Why is not fixed in this PR?
> 2. For the GET /_admin/server/tls call (which you've actually changed here), not superuser rights, but authentication is required. "The corresponding POST request is superuser only, but the GET request is available to any authenticated user, regardless of his/her permissions." - see this comment in PR 15172: #15172.
> 
> Please correct the documentation accordingly for both methods. The same applies to the PRs for other versions: #15251 #15252 #15253

@ansoboleva  Please check now.

**Comment by KVS85** [comment]
@kapahimansi123 please consider checking *all* comments from all reviewers:
- As per https://arangodb.atlassian.net/browse/ES-1006 ticket, the documentation for the GET /_admin/server/mode incorrectly states that it does **not** require authentication. Why is not fixed in this PR?
> This is *not* a public API so it requires authentication.
This sounds strange. How authentication requirement related to a publicity of API?

**Comment by kapahimansi123** [comment]
> #15172



> #15172

In the latest commit, I have reverted the changes i had originally made to GET /_admin/server/tls . 
The only change now that exists in these pull requests is for GET /_admin/server/mode.

Basically i am leaving the GET /_admin/server/tls unchanged. Any changes required to this can be done in a different pr.

**Comment by kapahimansi123** [comment]
> @kapahimansi123 please consider checking _all_ comments from all reviewers:
> 
> * As per https://arangodb.atlassian.net/browse/ES-1006 ticket, the documentation for the GET /_admin/server/mode incorrectly states that it does **not** require authentication. Why is not fixed in this PR?
> 
> > This is _not_ a public API so it requires authentication.
> 
> This sounds strange. How authentication requirement related to a publicity of API?

Do you mean the comment should be, "This API requires authentication"?

**Comment by KVS85** [comment]
> > @kapahimansi123 please consider checking _all_ comments from all reviewers:
> > 
> > * As per https://arangodb.atlassian.net/browse/ES-1006 ticket, the documentation for the GET /_admin/server/mode incorrectly states that it does **not** require authentication. Why is not fixed in this PR?
> > 
> > > This is _not_ a public API so it requires authentication.
> > 
> > 
> > This sounds strange. How authentication requirement related to a publicity of API?
> 
> Do you mean the comment should be, "This API requires authentication"?

I suppose yes. Although I don't know whether this API is public or not and how API publicity related to authentication here. I believe it's a matter of PR creator to figure out.

**Comment by ansoboleva** [comment]
> > #15172
> 
> > #15172
> 
> In the latest commit, I have reverted the changes i had originally made to GET /_admin/server/tls . The only change now that exists in these pull requests is for GET /_admin/server/mode.
> 
> Basically i am leaving the GET /_admin/server/tls unchanged. Any changes required to this can be done in a different pr.

Please create a new PR then with this information, because you know now that it needs to be changed.

**Comment by kapahimansi123** [comment]
will create a new pr.

**Comment by ansoboleva** [comment]
@kapahimansi123 Why did you close this PR with unmerged changes to the GET /_admin/server/mode documentation? It needs to be fixed according to https://arangodb.atlassian.net/browse/ES-1006.

**Comment by ansoboleva** [comment]
@kapahimansi123 As we discussed, please make the following changes in this PR and the related ones for other versions:

- to the get_admin_server_mode: This API requires authentication.
- to the get_admin_server_tls: This API requires authentication.

**Comment by kapahimansi123** [comment]
> @kapahimansi123 As we discussed, please make the following changes in this PR and the related ones for other versions:
> 
> * to the get_admin_server_mode: This API requires authentication.
> * to the get_admin_server_tls: This API requires authentication.

@ansoboleva In both the files, I have changed the respective lines to the ones mentioned in the comment above. 
However, if any further changes are required, kindly write the exact changes (and exact location) here in a comment.

**Review by ansoboleva — APPROVED** [review]
reviewed

**Pull request merged**
