### PR TITLE
Finalize documentation of --force flag for hotbackup.

### PR DESCRIPTION
**Pull request by neunhoef**
This now contains a stern warning hopefully convincing customers
not to use this option.

### CODE REVIEW

**Comment by neunhoef** [comment]
No jenkins run necessary, this is pure documentation.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7548/
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/478/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/479/

**Comment by KVS85** [comment]
Tests and examples blue.

**Pull request merged**
