### PR TITLE
change "term" from double to integer value

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Change serialized "term" value from double to integer value after persisting a compaction snapshot, so there is no truncation for larger term values.

For 3.7, this fix is included in https://github.com/arangodb/arangodb/pull/13200.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13156/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13407/

**Comment by KVS85** [comment]
Tests blue except known failure.

**Review by KVS85 — COMMENTED** [review]
LGTM.

**Pull request merged**
