### PR TITLE
rclone path normalization (port from devel to 3.5).

### PR DESCRIPTION
**Pull request by neunhoef**

### CODE REVIEW

**Comment by neunhoef** [comment]
Probably does not compile yet. Beware.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6546/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6547/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6548/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
