### PR TITLE
Bug fix 3.6/optimise react proxy

### PR DESCRIPTION
**Pull request by hkernbach**
Same as: https://github.com/arangodb/arangodb/pull/10919

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/8120/

**Comment by jsteemann** [comment]
Tests blue

**Comment by hkernbach** [comment]
Do **NOT** merge. There is one issue I need to solve first!

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/8133/

**Pull request merged**
