### PR TITLE
add helper pointer for stripped binaries into the locks

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3330/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3331/

**Comment by dothebart** [comment]
tests green.

**Comment by graetzer** [comment]
I don't get it, whats the benefit of having the pointer in the _temporary_ locker object ?

**Comment by dothebart** [comment]
in the usual shutdown hangers you only see <this optimized out> - this pointer will be accessible, since the lock structure doesn't get removed. Most probably this branch is never going to be merged.

**Comment by jsteemann** [comment]
Obsoleted by now

**Pull request closed without merging**
