### PR TITLE
Friendlier Foxx manifests

### PR DESCRIPTION
**Pull request by pluma**
This PR adjusts the export logic to support node-style exports (i.e. overwrite `module.exports` in your export file) and to allow exporting a single file directly.

E.g. previously you had to do this:

```json
{
  "exports": {
    "some-stupid-name": "my-exports-file.js"
  }
}
```

Now you can do this instead:

```json
{
  "exports": "my-exports-file.js"
}
```

Also you can now do this:

```js
// in my-exports-file.js
module.exports = function () {
  return "hi";
};
```

instead of this:

```js
// in my-exports-file.js
exports.someStupidName = function () {
  return "hi";
};
```

This change is backwards compatible. The "old style" manifest exports should still be supported for the time being. The use of `module.exports` instead of `exports` is entirely optional and both styles should be supported for the foreseeable future (as in Node.js).

If we want to deprecate "old style" manifest exports, the same behaviour can be easily replicated with `require`, e.g. before:

```json
{
  "exports": {
    "a": "a.js",
    "b": "b.js"
  }
}
```

after:

```json
{
  "exports": "exports.js"
}
```

With `exports.js` simply containing the following code:

```js
"use strict";
exports.a = require('./a');
exports.b = require('./b');
```

@mchacki, @fceller: could you please review this PR?

EDIT: While at it, I've also cleaned up the manifest validation a bit. Because we're using joi for validations everywhere else, the manifest is now also validated using a joi schema. Unknown attributes are still handled gracefully but also result in warnings if the manifest is invalid (which may help troubleshooting typos).

EDIT2: I've also adjusted the `controllers` attribute to support using a single file (with implied mount prefix "/"), which should simplify Foxx apps that only use a single controller.

i.e. before:

```json
{
  "controllers": {
    "/": "my-controllers.js"
  }
}
```

after:

```json
{
  "controllers": "my-controllers.js"
}
```

This change is also fully backwards-compatible and "old-style" controllers should be supported for the foreseeable future (unless we decide to allow nestable controllers).

EDIT3: I've also implemented @moonglum's suggestion to move `setup` and `teardown` into a `scripts` property. This behaviour is currently backwards compatible, but the old style will be deprecated in the next release but one (i.e. assuming this PR lands in 2.6, warn in 2.7, remove in 2.8).

### CODE REVIEW

**Comment by moonglum** [comment]
I like this idea (don't forget the docs :wink:). I would also vote for changing...

```json
{
  "setup": "bla.js",
  "teardown": "blubb.js"
}
```

to

```json
{
  "scripts": {
    "setup": "bla.js",
    "teardown": "blubb.js"
  }
}
```

Make this optional at first and deprecate it later. Why? Because this enables the following future feature: Custom scripts. Someone could add a "seed" script to fill up the database for example. Those scripts could then be executed via the script dropdown in the web interface.

**Comment by pluma** [comment]
+1 on the scripts. Should I add them to the PR?

**Comment by moonglum** [comment]
I vote for yes.

**Comment by pluma** [comment]
TODO: Documentation.

**Pull request merged**
