### PR TITLE
Fixed hotbackup upload and download with encryption at rest.

### PR DESCRIPTION
**Pull request by neunhoef**
The new encryption at rest key indirection was not up- and downloaded
alongside a hotbackup. This is a port from a fix in devel.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11032/

**Comment by neunhoef** [comment]
This is good to go.

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/11061/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
