### PR TITLE
detect duplicate testcase names in rspec tests and fix them.

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

*(Please describe the changes in this PR for reviewers)*

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [x] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [ ] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [ ] No backports required
- [x] Backports required for: all; mmfile related delete must not be backported.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11937/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11941/

**Comment by jsteemann** [comment]
Errors produced in the latest test run http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13599/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=(linux&&test)%7C%7Cgce/artifact/testfailures.txt:
````
* Test "http_replication"
    [FAILED]  tests/rb/HttpReplication/api-replication-global-spec.rb

      "test" failed: Failed to parse rspec results for: tests/rb/HttpReplication/api-replication-global-spec.rb - duplicate testcase name in fetches_the_available_tick_range {"id":"./tests/rb/HttpReplication/api-replication-global-spec.rb[1:1:2:3]","description":"fetches the available tick range","full_description":"ArangoDB dealing with the replication interface: dealing with wal access api fetches the available tick range","status":"passed","file_path":"./tests/rb/HttpReplication/api-replication-global-spec.rb","line_number":293,"run_time":0.0072124,"pending_message":null}

    [FAILED]  tests/rb/HttpReplication/api-replication-spec.rb

      "test" failed: Failed to parse rspec results for: tests/rb/HttpReplication/api-replication-spec.rb - duplicate testcase name in checks_the_state {"id":"./tests/rb/HttpReplication/api-replication-spec.rb[1:1:3:1]","description":"checks the state","full_description":"ArangoDB dealing with the replication interface: dealing with the logger checks the state","status":"passed","file_path":"./tests/rb/HttpReplication/api-replication-spec.rb","line_number":257,"run_time":0.003094116,"pending_message":null}

   Suites failed: 2 Tests Failed: 0
```

**Comment by dothebart** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11955/

**Comment by dothebart** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11966/ - green.

**Review by jsteemann — APPROVED** [review]

**Pull request merged**
