### PR TITLE
add more details to error messages

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Improve some log messages

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [ ] No backports required
- [x] Backports required for: *3.6, 3.7*

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12232/

### CODE REVIEW

**Review by joerg84 — APPROVED** [review]

**Review by fceller — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13841/

http://172.16.10.101:8080/job/arangodb-matrix-pr-linux-nonmaintainercompile/11522/

**Review by KVS85 — APPROVED** [review]

**Comment by KVS85** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13844/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
