### PR TITLE
Fix idiomatic Foxx testing reports

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This fixes the logic in the Foxx API so setting `idiomatic` to `false` actually opts out of idiomatic (string) formatting of test reports even if the `accept` header would allow it.

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [x] Added **Regression Tests** (Only for bug-fixes) 

### Documentation

- [x] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)

### CODE REVIEW

**Comment by pluma** [comment]
This will likely need to be backported, at least for 3.5, maybe 3.4.

If the request does not contain an "accept" header at all, currently the report will always be formatted "idiomatically" with no way to opt out. This breaks drivers and such that may not set this header explicitly.

This PR allows setting the flag explicitly to `false` to opt out. Changing the default behavior would be backwards-incompatible. In effect the flag is supposed to be ternary:

* if `false`, don't send an idiomatic response
* if `true`, always send an idiomatic response if possible
* otherwise, only send an idiomatic response of the `accept` header prefers it (default)

**Comment by pluma** [comment]
@mchacki can you backport this?

**Comment by mchacki** [comment]
@pluma ok will do.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10253/

**Comment by pluma** [comment]
Apparently `request.post` no longer works with relative paths in arangosh. The existing tests had been changed to use `arango.POST` instead. I've adjusted the new tests accordingly.

http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/11998/

**Comment by pluma** [comment]
The `arango.POST` API seems to be more limited. Didn't notice that.

http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/11999/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10258/

**Comment by pluma** [comment]
Local build has finally completed, the tests are now green locally and should be on Jenkins this time.

http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/12006/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10267/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10268/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
