### PR TITLE
Feature: Analyzer REST-API Tests

### PR DESCRIPTION
**Pull request by ObiWahn**
adds test
related ticket: https://github.com/arangodb/backlog/issues/583

latest CI runs:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4781/ - 2019-06-06 07:30
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4828/ - 2019-06-10 13:00

### CODE REVIEW

**Comment by ObiWahn** [comment]
adding permission tests: https://github.com/arangodb/backlog/issues/580

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4654/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/6276/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4727/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4750/

I am not able to reproduce the failures in `shell-view-arangosearch.js` cluster (mmfiles/rocksdb) locally.

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4828/

**Comment by Dronplane** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4989/

**Pull request merged**
