### PR TITLE
Refactor statistics

### PR DESCRIPTION
**Pull request by mpoeter**
### Scope & Purpose

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9716/

**Comment by dothebart** [comment]
it seems that there are unrelated hangers.

**Comment by dothebart** [comment]
Pulled devel, restarted: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9726/

**Comment by jsteemann** [comment]
Test failure here:
``` 
0000007c`345feb30 00007ff7`3897bd47 arangod!abort(void)+0x35 [minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 77]
0000007c`345feb60 00007ff7`3897c095 arangod!arangodb::statistics::Distribution::add(struct arangodb::statistics::Distribution * other = 0x00007ff7`3bdec8e0)+0x177 [D:\hw15-windows\oskar\work\ArangoDB\arangod\Statistics\figures.h @ 111]
0000007c`345febc0 00007ff7`38984d3c arangod!arangodb::RequestStatistics::getSnapshot(struct arangodb::RequestStatistics::Snapshot * snapshot = 0x0000007c`345ff190, arangodb::stats::RequestStatisticsSource source = ALL (0n2))+0xd5 [D:\hw15-windows\oskar\work\ArangoDB\arangod\Statistics\RequestStatistics.cpp @ 209]
0000007c`345fec10 00007ff7`389886b8 arangod!arangodb::StatisticsWorker::generateRawStatistics(class arangodb::velocypack::Builder * builder = 0x00000241`9fbab960, double * now = 0x0000007c`345ff8c8)+0x15c [D:\hw15-windows\oskar\work\ArangoDB\arangod\Statistics\StatisticsWorker.cpp @ 1061]
0000007c`345ff720 00007ff7`389892d3 arangod!arangodb::StatisticsWorker::historian(void)+0x98 [D:\hw15-windows\oskar\work\ArangoDB\arangod\Statistics\StatisticsWorker.cpp @ 207]
0000007c`345ff8b0 00007ff7`39cb4794 arangod!arangodb::StatisticsWorker::run(void)+0x133 [D:\hw15-windows\oskar\work\ArangoDB\arangod\Statistics\StatisticsWorker.cpp @ 1286]
0000007c`345ffa70 00007ff7`39cb5599 arangod!arangodb::Thread::runMe(void)+0x34 [D:\hw15-windows\oskar\work\ArangoDB\lib\Basics\Thread.cpp @ 319]
0000007c`345ffbe0 00007ff7`39d6a930 arangod!arangodb::Thread::startThread(void * arg = 0x00000241`9fbab780)+0xd9 [D:\hw15-windows\oskar\work\ArangoDB\lib\Basics\Thread.cpp @ 99]
0000007c`345ffd80 00007fff`0c007974 arangod!ThreadStarter(void * data = 0x00000241`9fa83c90)+0x20 [D:\hw15-windows\oskar\work\ArangoDB\lib\Basics\threads-win32.cpp @ 56]
0000007c`345ffdb0 00007fff`0eaea261 kernel32!BaseThreadInitThunk+0x14
0000007c`345ffde0 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by graetzer** [comment]
are there integration tests for the statistics? We need to make sure this works otherwise oasis billing will be off

**Comment by mpoeter** [comment]
@jsteemann the callstack refers to the assertion in this code:
https://github.com/arangodb/arangodb/blob/f4f866b4a85b23770c3a75ec01fe62951ff549f5/arangod/Statistics/figures.h#L110-L112
I am not sure why it fails though since I am not aware of any changes that would alter the behavior. On my Linux workstation the shell_server tests ran successfully several times. I am currently trying to build on Windows to see if I can reproduce this issue there (at least the failed build was on Windows).

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9778/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9784/

**Comment by dothebart** [comment]
all blue!

**Comment by Simran-B** [comment]
Example generation also blue
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/622/
https://github.com/arangodb/docs/pull/432

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9886/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9896/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9900/

**Comment by mpoeter** [comment]
Commit bd92c25af66150191c0196ba7e4b76ba95218851 contains a fix for VST request statistics that should probably me backported. HTTP2 request statistics are still broken - for these requests no statistics are gathered at all. I will investigate further and create a separate PR with a fix.

**Comment by jsteemann** [comment]
Thanks @mpoeter ! This is awesome!

**Pull request merged**
