### PR TITLE
Fix AQL cost estimate for spliced subqueries

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

SubqueryEndNode previously re-used the estimate for the number of rows at the end of the subquery, rather than the number of rows at the start, leading to overestimations, that were also clearly visible in explain output.

- [X] :hankey: Bugfix (requires CHANGELOG entry)
- [X] :book: CHANGELOG entry made

#### Backports:

- [X] Backport required for **3.7**: #13121
- [X] Backport required for **3.6**: #13122

### Testing & Verification

- [X] The behavior in this PR was *manually tested*
- [X] This PR adds tests that were used to verify all changes:
  - [X] Added new **integration tests** (e.g. in shell_server / shell_server_aql)

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12928/

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12937/

**Review by mchacki — APPROVED** [review]
LGTM, this has been very confusing I agree.

**Review by maierlars — APPROVED** [review]

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13060/

**Pull request merged**
