### PR TITLE
Bug fix/refactor find emplace

### PR DESCRIPTION
**Pull request by jsteemann**
This is an import of @mpoeter 's PR https://github.com/arangodb/arangodb/pull/7123 into our repository for testing.

### CODE REVIEW

**Comment by mpoeter** [comment]
Sorry, I forgot that your internal build system can't handle PRs from forked repositories.

**Comment by jsteemann** [comment]
@mpoeter : no worries. I will make sure your PR gets through!

**Comment by mpoeter** [comment]
Alright, on my system I have 6.4 - I hope that is close enough.

**Comment by jsteemann** [comment]
Seems good enough!

**Pull request merged**
