### PR TITLE
allow using `returnOld` and `returnNew` attributes in HTTP REST APIs …

### PR DESCRIPTION
**Pull request by jsteemann**
…for graph modifications

### CODE REVIEW

**Comment by jsteemann** [comment]
@mchacki : I think we cannot support `returnOld` for the HTTP DELETE verbs, because these APIs currently only return a boolean value. Returning the old documents in case of `returnOld=true` would change this API.
In case you're happy with the PR, I will add the missing documentation for it. Just let me know.

**Comment by ewoutp** [comment]
In this PR the `new` & `old` objects are returned under the `edge` key.
The go-driver expects them at the root. Which one do we want to be correct?

**Comment by jsteemann** [comment]
@ewoutp : I now moved `old` and `new` attibutes to the top-level of the response.

**Comment by jsteemann** [comment]
@mchacki : please check if you think the API responses can be changed like I did.

**Comment by ewoutp** [comment]
I've run the single-server go-driver tests on this.
Result:
- Remove single edge test with `ReturnOld` still fails (as expected, we should probably decide to just not support that)
- Single edge tests (create/replace/update) with `ReturnOld` & `ReturnNew` now pass
-Multi edge tests all fail. Since this is using the single-edge HTTP API this is a problem in the go-driver itself. I'll investigate that further

**Comment by jsteemann** [comment]
@ewoutp : thanks for checking

> Remove single edge test with ReturnOld still fails (as expected, we should probably decide to just not support that)

Yes, that is the current state. We have to check with @mchacki whether we want to support `returnOld` for delete as well.

> Multi edge tests all fail. Since this is using the single-edge HTTP API this is a problem in the go-driver itself. I'll investigate that further

Probably. At least I think the /_api/gharial APIs don't support multi edge operations at all

**Comment by ewoutp** [comment]
With go-driver PR https://github.com/arangodb/go-driver/pull/92 all tests are passing.

**Pull request merged**
