### PR TITLE
Some cleanup for scalability improvements.

### PR DESCRIPTION
**Pull request by neunhoef**
This PR fixes a few things which were found in the 3.7 version when
I ported the last round of scalability changes to devel and 3.6.
The `_log_size` one is an actual bug, the others are more for prettiness
and consistency between the branches.

- Please compiler.
- Fix _log_size in agency State.
- Typo.
- Correct error messagesCorrect error messages.
- Small performance tuning.
- Tiny performance improvement.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12407/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12414/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12448/

**Review by kvahed — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12555/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/6171/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
