### PR TITLE
Cherry picked bug-fix for GharialAPI to return name in LIST

### PR DESCRIPTION
**Pull request by mchacki**
*GET _api/gharial* did not return the `name` property of the graphs, as it is described in documentation, and as is done in all other gharial API parts that return graphs.
The name is identical with _key so one could still work with the original API, it is just inconsistent and inconvenient.

Also added tests for all GraphAPIs to make sure they return identical format.

- [*] Bug-Fix for *3.4* and onwards
- [*] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a *JIRA Ticket number* (In case a customer was affected / involved): DEVSUP-501

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [x] Added **Regression Tests** (Only for bug-fixes) 
- [x] Added new **integration tests** (i.e. in shell_server / shell_server_aql)

Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7386/

### Documentation

Adapted code to documentation, no change required there.

- [x] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)

### CODE REVIEW

**Comment by mchacki** [comment]
Jenkins again:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/7394/
The last run suffered from issues with GE machines

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1373/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1393/

**Comment by KVS85** [comment]
Windows PR tests (restarted) also blue.

**Pull request merged**
