### PR TITLE
naively implement timeout for waitpid

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Implement waitpid with timeout on Linux & MacOS, to make it compatible with what we do on Windows.
Requested by @kvs85

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6117/

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6796/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8492/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7972/

**Comment by jsteemann** [comment]
@kvs85: is this PR still needed?

**Comment by KVS85** [comment]
Yes.

**Pull request merged**
