### PR TITLE
always create the statistics collections

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

unconditionally create statistics collections when the database is created
it is not advisable to not create them when the statistics are turned off, because the server may later be restarted with statistics turn on. and then the collections will be missing

- [ ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7598/

### CODE REVIEW

**Comment by KVS85** [comment]
Tests blue.

**Comment by graetzer** [comment]
I swear I have seen this exact fix before by @hkernbach

**Comment by hkernbach** [comment]
https://github.com/arangodb/arangodb/pull/9967

Think it was part of that PR. Maybe those other changes there are missing as well.

**Comment by jsteemann** [comment]
That PR was for the 3.5 branch. We should make sure the changes were made in devel as well.

**Comment by joerg84** [comment]
@hkernbach Could you check whether other parts are missing as well (and if yes, which ones are RC blockers)

**Comment by hkernbach** [comment]
Added one commit to @jsteemann 's pr.

**Pull request merged**
