### PR TITLE
Fixed illegal optimizer rule on multiple consecutive SORTs (3.9)

### PR DESCRIPTION
**Pull request by hkernbach**
Backport of: https://github.com/arangodb/arangodb/pull/16718
Please see all notes there.

### CODE REVIEW

**Review by mchacki — APPROVED** [review]
The code looks good to me, but the Jenkins failed with JSLINT so unclear if there is a hidden merge conflict.
If Jenkins comes back green I approve to merge

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by hkernbach** [comment]
Jenkins green except unrelated windows failure ...

**Comment by KVS85** [comment]
Only unrelated known failure on Windows in Jenkins.

**Pull request merged**
