### PR TITLE
Documentation/actions examples to text

### PR DESCRIPTION
**Pull request by Simran-B**
Should fix devel docu build errors.

http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/127/

For reviewers: is the content of the warning box alright? If so, then it should be fine to merge.
http://web01.arangodb.biz/documentation/actions-examples-to-text/Manual/Appendix/Deprecated/Actions/

### CODE REVIEW

**Comment by dothebart** [comment]
I'm strictly against this change, since these were one of the areas where only the documentation proved that things were broken or not.

**Comment by dothebart** [comment]
Please rather add the .js code creating the missing collections in the setup of the test-server here: https://github.com/arangodb/arangodb/blob/devel/utils/generateExamples.py#L102

**Comment by Simran-B** [comment]
@dothebart Can we create system collections from user land (`_routing` and `_modules`)?
`db._create("_underscoreAnything")` throws `ArangoError: illegal name` for me.

The chapter is about Actions, deprecated since v3.0.0. Do we really care if it's broken or not? The reason why I put the example outputs in is because the feature is not removed yet, but we don't have the required collections anymore on new installations.

Alternatively, we could remove the entire chapter and if anyone needs it again, we can point him/her to the 3.3 docs.

**Comment by dothebart** [comment]
either remove or fix. but not hard code.

**Comment by Simran-B** [comment]
Removed most of it, except this:
http://web01.arangodb.biz/documentation/actions-examples-to-text/Manual/Appendix/Deprecated/

Test build passed:
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/128/

FYI: Only devel (so upcoming 3.5.0) does not create the two system collections anymore, 3.4 still does.

@sleto-it Are you okay with this?

**Pull request merged**
