### PR TITLE
[3.6] supervision maintenance unttled

### PR DESCRIPTION
**Pull request by kvahed**
image

### CODE REVIEW

**Comment by joerg84** [comment]
@kvahed is this ready to merge?

**Comment by jsteemann** [comment]
Status update, according to @kvahed :
this is not ready to merge yet, and needs a proper review.

**Comment by kvahed** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8218/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8357/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux-nonmaintainercompile/8107/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
