### PR TITLE
Bug fix 3.4/scheduler empty

### PR DESCRIPTION
**Pull request by fceller**

### CODE REVIEW

**Comment by matthewvon** [comment]
insert is 953 seconds compared to 3.3 baseline of 1085 seconds.  good.  update and replace tests still running.

**Comment by fceller** [comment]
@matthewvon strangly Jenkins does not like this PR. It fails in all runs. I need to investigate.

**Comment by fceller** [comment]
@matthewvon something is still amiss. The Jenkins runs are red.

**Comment by matthewvon** [comment]
I have retested this branch against the shipping 3.4.0 and one potential update that fixes Jenkins (there are alternate updates).  I did NOT spend time controlling all the server variables, such as flushing the Linux page cache.  I did NOT run each branch multiple times to get an average ... blah, blah, blah.  The numbers are all within 10% of each other.  Given my lack of test control, I say the differences are statistically insignificant.  And since we are looking for a 30% or better improvement, I believe this PR is not on the path.

<table>
  <tr><th></th><th colspan=3>Document<br>vary branches/changes</th></tr>
  <tr><th>branch</th><th>insert</th><th>update</th><th>replace</th></tr>
   <tr>
    <td> 3.4.0 </td>
    <td> 850s </td>
    <td> 1077s </td>
    <td> 1055s </td>
  </tr>
<tr>
    <td> add this PR</td>
    <td> 853s </td>
    <td> 988s </td>
    <td> 1009s </td>
  </tr>
 <tr>
    <td> add strand mgmt</td>
    <td> 877s </td>
    <td> 1032s </td>
    <td> 1043s </td>
  </tr>
</table>

**Comment by matthewvon** [comment]
Adding arangobench test results from my server for comparison to @jsteemann's tests:

<table>
 <tr><th>branch</th><th>single db</th><th>cluster</th></tr>
 <tr><td> 3.3 12/11 </td><td>1450</td><td>385</td></tr>
 <tr><td> v3.4.0 </td><td>1460</td><td>497</td></tr>
 <tr><td> add this PR </td><td>1346</td><td>609</td></tr>
 <tr><td> add strand mgmt </td><td>1336</td><td>637</td></tr>
</table>

**Comment by matthewvon** [comment]
java-benchmark execution:

<table>
  <tr><th></th><th colspan=3>Document<br>vary threads</th></tr>
  <tr><th>threads</th><th>insert</th><th>update</th><th>replace</th></tr>
  <tr>
    <td> 1 </td>
    <td> 1327s </td>
    <td> 1454s </td>
    <td> 1437s </td>
  </tr>
  <tr>
    <td> 8 </td>
    <td> 760s </td>
    <td> 884s </td>
    <td> 861s </td>
  </tr>
  <tr>
    <td> 32 </td>
    <td> 1675s </td>
    <td> 1817s </td>
    <td> 1830s </td>
  </tr>
  <tr>
    <td> 64 </td>
    <td> 3511s </td>
    <td> 4058s </td>
    <td> 4253s </td>
  </tr>
</table>
<table>
  <tr><th></th><th colspan=3>Document<br>vary shards</th></tr>
  <tr><th>shards</th><th>insert</th><th>update</th><th>replace</th></tr>
  <tr>
    <td> 3 </td>
    <td> 1675s </td>
    <td> 1817s </td>
    <td> 1830s </td>
  </tr>
  <tr>
    <td> 9 </td>
    <td> 1895s </td>
    <td> 2185s </td>
    <td> 2173s </td>
  </tr>
  <tr>
    <td> 27 </td>
    <td> 1852s </td>
    <td> 2085s </td>
    <td> 2108s </td>
  </tr>
  <tr>
    <td> 80 </td>
    <td> 1901s </td>
    <td> 2068s </td>
    <td> 2060s </td>
  </tr>
</table>
<table>
  <tr><th></th><th colspan=3>AQL<br>vary threads</th></tr>
  <tr><th>threads</th><th>insert</th><th>get</th><th>replace</th></tr>
  <tr>
    <td> 1 </td>
    <td> 1672s </td>
    <td> 2812s </td>
    <td> 1792s </td>
  </tr>
  <tr>
    <td> 8 </td>
    <td> 1008s </td>
    <td> 1673s </td>
    <td> 1153s </td>
  </tr>
  <tr>
    <td> 32 </td>
    <td> 1957s </td>
    <td> 2743s </td>
    <td> 2258s </td>
  </tr>
  <tr>
    <td> 64 </td>
    <td> 3979s </td>
    <td> 4284s </td>
    <td> 4575s </td>
  </tr>
</table>
<table>
  <tr><th></th><th colspan=3>AQL<br>vary shards</th></tr>
  <tr><th>threads</th><th>insert</th><th>get</th><th>replace</th></tr>
  <tr>
    <td> 3 </td>
    <td> 1957s </td>
    <td> 2743s </td>
    <td> 2258s </td>
  </tr>
  <tr>
    <td> 9 </td>
    <td> 2070s </td>
    <td> 2741s </td>
    <td> 2345s </td>
  </tr>
  <tr>
    <td> 27 </td>
    <td> 2089s </td>
    <td> 2763s </td>
    <td> 2262s </td>
  </tr>
  <tr>
    <td> 80 </td>
    <td> 2137s </td>
    <td> 2915s </td>
    <td> 2306s </td>
  </tr>
</table>

Various comparison times are here:  https://github.com/arangodb/release-3.4/issues/16

**Comment by matthewvon** [comment]
Previous commit c4688e1 was successful with clearing Jenkins shutdown problem.  Leaving it.

**Pull request closed without merging**
