### PR TITLE
Discard unused Foxx config when saving config in production

### LINKED ISSUE #12543: Unused Foxx service config can not be discarded
## My Environment

* __ArangoDB Version__:        3.6.5
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Windows Server 2016

## Component, Query & Data

__Affected feature__:
When upgrading a Foxx service, old service manifest values are not removed from the application configuration.

## Steps to reproduce

1. Install a Foxx service with some service configuration values set in the service manifest
2. Upgrade that Foxx service to a newer version, but remove one of the configuration values
3. ArangoDB will not remove the unreferenced configuration value, and will throw errors that you have an unsupported configuration value.

__Problem__:
There are two problems here:
1. Upgrading a Foxx Service does not remove any service configuration items from the relevant `_apps` document for the service.
2. Installing a Foxx Service does not automatically save default configuration values to the relevant `_apps` document, but that is a secondary issue.

__Expected result__:
Here is the `_apps` document for a service after it's installed for the first time:
~~~
{
  "id": "/myservice",
  "mount": "/myservice",
  "options": {
    "development": false,
    "configuration": {
      "blue_key": "github1",
      "orange_key": "github2",
      "purple_key": "github3"
    },
    "dependencies": {}
  }
}
~~~
Note that it has a value called `blue_key` which will be removed in the next version of the Foxx Service.

This is what the Service Manifest (configuration section) looks like in the next Foxx Service version:
~~~
    "configuration": {
        "orange_key": {
            "description": "orange_key",
            "default": "hello_github",
            "type": "string"
        },
        "purple_key": {
            "description": "purple_key",
            "default": "hello_github",
            "type": "string"
        },
        "green_key": {
            "description": "green_key",
            "default": "hello_github",
            "type": "string"
        }
    }
~~~

After upgrading the Foxx Service to the new version (and having to click the 'Apply' button to persist the configuration settings, the `_apps` document now looks like this:
~~~
{
  "id": "/myservice",
  "mount": "/myservice",
  "options": {
    "development": false,
    "configuration": {
      "blue_key": "github1",
      "orange_key": "github2",
      "purple_key": "github3"
      "green_key": "github4"
    },
    "dependencies": {}
  }
}
~~~

Notice how the `blue_key` is still sitting there, even though it was not defined as a valid configuration setting.

ArangoDB now starts to throw this error internally in the Logs:
~~~
[ebe22] Values for unknown options will be discarded if you save the configuration in production mode using the web interface.
[ebe22] is not allowed
[ebe22] Stored configuration for service "/myservice" has errors:
~~~

The only way to fix this is to manually open the system collection `_apps` and modify the document to remove the reference to `blue_key`:
~~~
{
  "id": "/myservice",
  "mount": "/myservice",
  "options": {
    "development": false,
    "configuration": {
      "orange_key": "github2",
      "purple_key": "github3"
      "green_key": "github4"
    },
    "dependencies": {}
  }
}
~~~

I would have expected a few different behaviours:
1. When installing a Foxx service, the default configuration parameters should save to the `_apps` collection immediately.
2. When upgrading a Foxx service, the new default configuration parameters should save to the `_apps` collection immediately.
3. When upgrading a Foxx service, any configuration parameters in the `_apps` collection that are not defined in the new serivce manifest.json should be removed from the `_apps` collection immediately.

Because of this issue, the upgrade process of a Foxx service becomes more cumbersome than it should be, as we have to:
1. After upgrading the service we have to remote into the server
2. Then we have to open the service and click 'Apply' to persist new default configuration settings
3. Then we have to open the `_apps` collection and open the document for this service
4. Then we have to modify the document for the service, manually removing the unreferenced keys.

Note:
When upgrading a service there is a setting there to reset the configuration of a service, but this isn't a feature we want to enable. The main reason is that installations of a service may have saved configuration settings for that service installation, and we don't want to reset everything back to default. Rather we want to remove unreferenced settings, keep retained settings, and set default values for new settings.

We don't want to reset everything.

Thanks for considering this issue.

### PR DESCRIPTION
**Pull request by pluma**
Fixes #12543.

### Scope & Purpose

This fixes the behavior of Foxx that was supposed to discard unused stored configuration options when options are renamed or removed after a service has been upgraded. These will result in warnings until discarded.

Additionally the warnings now indicate which configuration options they refer to, making them more meaningful to users.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions)*

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket number: #12543
- [ ] Design document: 

### Testing & Verification

The changes to tests in this PR overlap with #12694 but should merge cleanly.

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added **Regression Tests**
  - [ ] Added new C++ **Unit Tests**
  - [x] Added new **integration tests** (i.e. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)

Additionally:

- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

*(Include link to Jenkins run etc)*

### Documentation

> All new Features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the changelog so that
> developers and users have a concise overview. 

- [x] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)
- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### CODE REVIEW

**Review by dothebart — APPROVED** [review]

**Comment by pluma** [comment]
@joerg84 Can we get this merged plz too?

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13174/

**Review by joerg84 — APPROVED** [review]

**Comment by pluma** [comment]
@jsteemann can this be merged?

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13814/

**Pull request merged**
