### PR TITLE
typo

### PR DESCRIPTION
**Pull request by baslr**

### CODE REVIEW

**Comment by hkernbach** [comment]
Should be fine, but please use correct branch names as discussed.

**Comment by jsteemann** [comment]
If this PR refers to the wrong branch, is it still needed, or can we close it?

**Comment by hkernbach** [comment]
I just mean our branch name conventions.

**Comment by jsteemann** [comment]
@manuel: the branch should have been named "bug-fix/fix-typo" (or so) and not "typo-fixo-devel".

**Comment by jsteemann** [comment]
Merging now anyway.

**Comment by baslr** [comment]
@jsteemann I think its typo-fix/ldap-test. If I consult https://github.com/arangodb/documents/blob/master/ProcessDocuments/Branch-Naming-November-21-2017.pdf its  {what}-fix-{branch if not devel}/{description}

**Comment by jsteemann** [comment]
@baslr : no, according to this document it is bug-fix/typo-fix-ldap-test.
It was also announced like this when the convention was presented to us (via Zoom meeting).
Please have a look at the branch names that there are on Github and you will also notice.

**Pull request merged**
