### PR TITLE
Port minichaos agency restart fix to 3.6

### PR DESCRIPTION
**Pull request by neunhoef**
This ports the fixes for the minu chaos agency restarts from 3.7
to devel.

Background:

Before the fix there is a time when a compaction snapshot is received
from the leader, such that if the agent crashes at the wrong time, it
can not longer restart, since there is a mismatch between the latest
compaction snapshot and the rest of the log entries.

This PR fixes this problem by altering the restart procedure and erasing
the complete local Raft log when this is detected at restart. The
thinking behind is that if this happens, all we have from the Raft log
is anyway seriously outdated.
Scope & Purpose

(Please describe the changes in this PR for reviewers - mandatory)

    [*] hankey Bugfix (requires CHANGELOG entry)

Testing & Verification

    [*] The behavior in this PR was manually tested
    [*] This fixes mini chaos tests, which sometimes expose the problem

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13426/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13428/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13430/ after fixing a warning.

**Comment by neunhoef** [comment]
The failure in Jenkins seems to be known and has nothing to do with this PR. This now awaits Kaveh's review next week.

**Review by kvahed — APPROVED** [review]
LGTM

**Pull request merged**
