### PR TITLE
auto-adjust count values during the getting-in-sync protocol

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

If there's a checksum mismatch, we can currently get stuck in an endless loop since the checksum is currently just a collection count, and it may not get corrected if all documents are actually present and the cached count is simply wrong. This PR triggers a recount first on the  follower, then the leader if necessary, using a new non-blocking method to recalculate the count.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [ ] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] Backports required for: *3.6*

### Testing & Verification

- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added **Regression Tests**
  - [ ] Added new C++ **Unit Tests**
  - [x] Added new **integration tests** (i.e. in shell_client)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12259/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12276/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12281/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12293/

**Review by kvahed — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
