### PR TITLE
[3.5] Bug fix/smart bfs stack size

### PR DESCRIPTION
**Pull request by goedderz**
Backport of #10577.

The enterprise part is in https://github.com/arangodb/enterprise/pull/371.

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7657/

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7668/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7825/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
