### PR TITLE
replace jemalloc with mimalloc

### PR DESCRIPTION
**Pull request by ObiWahn**
devel only

http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4951/

Use the following commands to check that it is working as expected.
```
export MIMALLOC_VERBOSE=1
export MIMALLOC_STATS=1
```

### CODE REVIEW

**Comment by graetzer** [comment]
did you do performance measurements yet ?

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8064/

**Comment by ObiWahn** [comment]
retry -- build works locally -- jenkins complained about jemalloc

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8103/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8108/

**Comment by ObiWahn** [comment]
Test Marix Result:

- Linux ok/ok
- Mac ok/fail
- Windows fail/fail (`fatal error C1189: #error:  "It is only possible to override "malloc" on Windows when building as a DLL (and linking the C runtime as a DLL)"`)

Probably not worth the trouble for now. Retry in a year.

**Pull request closed without merging**
