### PR TITLE
issue 380.5: move all transaction status callback logic to Methods

### PR DESCRIPTION
**Pull request by vasiliy-arangodb**

### CODE REVIEW

**Comment by vasiliy-arangodb** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-pr/

**Comment by jsteemann** [comment]
@vasiliy-arangodb : it seemed that the catch tests failed for this PR:
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/818/
Can you have a look?

**Comment by gnusi** [comment]
@jsteemann it fails for us in https://github.com/arangodb/arangodb/pull/5610, too. I'm on it

**Comment by vasiliy-arangodb** [comment]
replaced with https://github.com/arangodb/arangodb/pull/5610

**Pull request closed without merging**
