### PR TITLE
Bug fix 3.5/fix console log

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix `console.log(...)` in arangosh.
It didn't log anything when invoked in arangosh. Curiously, `require("console").log(...)` still worked.

- [ ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8448/

### CODE REVIEW

**Comment by pluma** [comment]
This looks like it would not just affect arangosh but also the server. Could you check whether the console object is also weird in server-side code (i.e. in Foxx but also in `POST /_admin/execute` or other non-Foxx code)?

**Comment by jsteemann** [comment]
@pluma : I think `console` is not made available automatically in the server, same as `db`. It needs to be explicitly required IMHO. And if such, it should just work. But I will check it.

**Comment by jsteemann** [comment]
@pluma: works from within the server. However, `console` is not available by default and needs to be required first. That fixes the problem anyway.

**Comment by pluma** [comment]
I guess Foxx is explicitly loading in console by default, then. Fine by me. No idea where the client console comes from.

**Comment by Simran-B** [comment]
I also noticed that an old example didn't print anything in console anymore using `arangosh --javascript.execute file.js` and `console.warn()` etc. inside the file https://github.com/arangodb/arangodb/issues/7111#issuecomment-434252693.

No such problem with print().

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
