### PR TITLE
upgrade RocksDB

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Test branch for testing the upgrade to latest RocksDB (6.8)

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *(please describe tests)*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9102/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9103/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9105/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9106/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9109/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux-nonmaintainercompile/8783/

```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: _ZN7rocksdb10perf_levelE: TLS definition in ../bin/librocksdb.a(perf_level.cc.o) section .tdata mismatches non-TLS reference in /tmp/arangod.DElkOp.ltrans26.ltrans.o
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/arangod.DElkOp.ltrans26.ltrans.o: error adding symbols: bad value
```

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9131/

**Comment by jsteemann** [comment]
Tests blue

**Comment by ObiWahn** [comment]
This adds files deleted in https://github.com/arangodb/arangodb/pull/11320

**Comment by jsteemann** [comment]
> This adds files deleted in #11320

@ObiWahn : this is not true.

**Pull request merged**
