### PR TITLE
Feature/upgrade rocksdb

### PR DESCRIPTION
**Pull request by dothebart**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/597/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/668/

**Comment by jsteemann** [comment]
As usual I am lost, but why does this PR upgrade RocksDB to 5.9.2 (from Dec 2017) instead of to 5.14 (from May 2018)?

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/679/ - testing with disabled rocksdb throtteling integration - the used interface is gone.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/695/ next try with fixed snappy integration

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/727/

**Comment by matthewvon** [comment]
A 5 hour import of 303 million JSON records (~360 bytes each) experienced several rocksdb stalls.  The longest stalls were 4 minutes long.  This is with a single db server.  

I am currently executing the test again against devel to verify throttle fixes the problem with older rocksdb version.  

Obvious next step will be to look for the auto tuning feature @dothebart noted in the rocksdb CHANGELOG and/or see about restoring the rocksdb compaction callback we need.

Have guests this weekend.  Follow-up will be slow.

**Comment by matthewvon** [comment]
Import with same parameters using devel had no stalls of 10 seconds or more.  10 seconds is the current reporting granularity.  Guess we are going to have to look at restoring code removed from rocksdb and/or changing out throttle mechanism.

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/95/

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/101/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/177/
Windows compile problems fixed.

**Comment by dothebart** [comment]
Success - except for one build where it couldn't resolve the host name on git clone.

**Pull request merged**
