### PR TITLE
[3.5] clean up your crap, dbservers. alright, i'll do it.

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by kvahed** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5712/

**Comment by joerg84** [comment]
Can we fix the name of this PR and get some review @neunhoef ?

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5788/

**Comment by neunhoef** [comment]
Unfortunately, the API is published, so we cannot leave out the changed entries, please revert.

**Comment by kvahed** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5818/

**Comment by KVS85** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5828/

**Comment by KVS85** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux/7488/

**Pull request merged**
