### PR TITLE
remove several outdated error codes

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Remove several error codes that were defined but not used anymore by ArangoDB

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] The behaviour change can only be verified via automatic tests

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

Additional test plan:
```
grep -r "ERROR_ARANGO_VALIDATION_FAILED" js tests arangod arangosh lib enterprise
grep -r "ERROR_ARANGO_ENDPOINT_NOT_FOUND" js tests arangod arangosh lib enterprise
grep -r "ERROR_ARANGO_INDEX_DOCUMENT_ATTRIBUTE_MISSING" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_NO_AGENCY" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_NO_COORDINATOR_HEADER" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_COULD_NOT_LOCK_PLAN" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_COULD_NOT_READ_CURRENT_VERSION" js tests arangod arangosh lib enterprise
grep -r "ERROR_ARANGO_DOCUMENT_NOT_FOUND_OR_SHARDING_ATTRIBUTES_CHANGED" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_COULD_NOT_DETERMINE_ID" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_UNKNOWN_CALLBACK_ENDPOINT" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_AGENCY_STRUCTURE_INVALID" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_REPLICATION_FACTOR" js tests arangod arangosh lib enterprise
grep -r "ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_NUMBER_OF_SHARDS" js tests arangod arangosh lib enterprise
grep -r "ERROR_QUERY_IN_USE" js tests arangod arangosh lib enterprise
grep -r "ERROR_USER_INVALID_PASSWORD" js tests arangod arangosh lib enterprise
grep -r "ERROR_SERVICE_INVALID_NAME" js tests arangod arangosh lib enterprise
grep -r "ERROR_SERVICE_INVALID_MOUNT" js tests arangod arangosh lib enterprise
grep -r "ERROR_AGENCY_INQUIRY_SYNTAX" js tests arangod arangosh lib enterprise
grep -r "ERROR_AGENCY_INQUIRE_CLIENT_ID_MUST_BE_STRING" js tests arangod arangosh lib enterprise
grep -r "ERROR_DISPATCHER_IS_STOPPING" js tests arangod arangosh lib enterprise
grep -r "ERROR_QUEUE_UNKNOWN" js tests arangod arangosh lib enterprise
grep -r "ERROR_ACTION_ALREADY_REGISTERED" js tests arangod arangosh lib enterprise
grep -r "ERROR_ACTION_UNFINISHED" js tests arangod arangosh lib enterprise
grep -r "ERROR_NO_SUCH_ACTION" js tests arangod arangosh lib enterprise
```

https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5058/

### CODE REVIEW

**Comment by dothebart** [comment]
should we keep the numbers around, so they don't get re-used by accident?

**Comment by jsteemann** [comment]
@dothebart : from my point of view we can reuse the numbers for other purposes. I will not do any harm, as the numbers were not in use for 3.4 neither.

**Comment by dothebart** [comment]
but if you have a driver that spans several version and takes action upon them?

**Comment by jsteemann** [comment]
Why should a driver act upon unused error codes?

**Comment by dothebart** [comment]
if it works with older arangodb versions too? Imho re-using is an incompatible api-change.

**Comment by jsteemann** [comment]
None of these error codes is actively used in 3.4.
2 of the error codes are used in 3.3, but only for startup errors or internally. That means drivers will not see these errors.
And older versions are already out of support.
So?

**Comment by dothebart** [comment]
ok, the arangodb starter doesn't handle exit codes yet, so its not a problem.

**Pull request merged**
