### PR TITLE
delete libarangoserver.a

### PR DESCRIPTION
**Pull request by m0ppers**

### CODE REVIEW

**Comment by jsteemann** [comment]
We could even get rid of about 500MB more library files:
```
1,3G	build/arangod/libarangoserver.a
7,9M	build/3rdParty/curl/curl-7.50.3/lib/libcurl.a
2,5M	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/src/libv8_base.a
4,0K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/src/libv8_nosnapshot.a
16K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/src/libv8_libbase.a
4,0K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/src/libv8_external_snapshot.a
4,0K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/src/libv8_libsampler.a
12K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/src/libv8_libplatform.a
472K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/third_party/icu/libicui18n.a
196K	build/3rdParty/V8/v5.7.492.77/x64.release/obj.target/third_party/icu/libicuuc.a
5,6M	build/3rdParty/rocksdb/v5.6.X/third-party/gtest-1.7.0/fused-src/gtest/libgtest.a
355M	build/3rdParty/rocksdb/v5.6.X/librocksdb.a
608K	build/3rdParty/zlib/zlib-1.2.11/libz.a
308K	build/3rdParty/boost/libboost_system.a
17M	build/3rdParty/jemalloc/v5.0.1/lib/libjemalloc.a
17M	build/3rdParty/jemalloc/v5.0.1/lib/libjemalloc_pic.a
17M	build/3rdParty/jemalloc/lib/libjemalloc.a
672K	build/3rdParty/snappy/google-snappy-d53de18/libsnappystatic.a
134M	build/lib/libarango.a
12M	build/lib/libarango_v8.a
```
And then the build directory also contains lots of useless ".o" files, which are about 2.2GB in size in the devel that I have checked out locally.
Maybe worth deleting those as well?

**Comment by m0ppers** [comment]
These .o files as well as the a files are NOT useless. They will be reused if jenkins chooses to schedule a new build. The libarangoserver.a is just the biggest one and is likely to be rebuilt anyway as something is possibly changing. I would leave the rest. This hack is just a notloesung because we are having disk space issues.

**Comment by jsteemann** [comment]
Alright.

**Comment by dothebart** [comment]
if you delete the .a's for v8 than you will have to invoke the V8 build again
You rather can remove all v8 .o's and keep the .a's.

**Comment by jsteemann** [comment]
Let's go ahead with mop's original commit. It just deletes the libarangoserver.a, which is a quick benefit that won't hurt us.

**Pull request merged**
