### PR TITLE
added extra assertions and checks for MMFiles index consistency

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Added assertions and checks for MMFiles index consistency. These changes will have effect in maintainer mode only.
Additionally, add log messages in case MMFiles index operations go wrong.

### Testing & Verification

This change is already covered by existing tests, such as *(please describe tests)*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8431/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8433/

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8457/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux-nonmaintainercompile/8198/

**Comment by KVS85** [comment]
Tests blue.

**Pull request closed without merging**
