### PR TITLE
Update OpenSSL to 1.1.1h (3.7)

### PR DESCRIPTION
**Pull request by KVS85**
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12837/

### CODE REVIEW

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12841/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/6408/

**Comment by KVS85** [comment]
Tests blue.

**Review by fceller — APPROVED** [review]
LGTM

**Pull request merged**
