### PR TITLE
Improved observability

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Forward port of the changes introduced in 3.6 via https://github.com/arangodb/arangodb/pull/13035.
The forward port is smaller than the referenced 3.6 PR because several metrics added by that PR already existed in 3.7.
This PR just adds the new things that were originally added by that 3.6 PR.

This is a PR to add more observability.

**Metrics**:

* Added new metric `arangodb_network_forwarded_requests` to track the number of requests forwarded from one coordinator to another in a load-balancing context.
* Added new metric `arangodb_replication_cluster_inventory_requests` to track the number of requests received for cluster inventories. The cluster inventory API is called at the beginning of a dump process or by arangosync.
* Added new metric `arangodb_aql_all_query` to track the total number of AQL queries.
* Added new metric `arangodb_aql_total_query_time_msec` to track the combined runtime of AQL queries (slow queries and non-slow queries).
* Added more scheduler metrics:
  * `arangodb_scheduler_jobs_done`: Total number of scheduler queue jobs done
  * `arangodb_scheduler_jobs_submitted`: Total number of jobs submitted to the scheduler queue
  * `arangodb_scheduler_jobs_dequeued`: Total number of jobs dequeued from the scheduler queue
  * `arangodb_scheduler_num_working_threads`: Number of currently working scheduler threads

**Availability API**:
Added startup option `--server.unavailability-queue-fill-grade`. 
This option has a consequence for the `/_admin/server/availability` API only, which is often called by load-balancers and other availability probing systems. 

The `/_admin/server/availability` API will now return HTTP 200 if the fill grade of the scheduler's queue is below the configured value, or HTTP 503 if  the fill grade is above it. This can be used to flag a server as unavailable in case it is already highly loaded.

The default value for this option is `1`, which will mean that the availability API will start returning HTTP 503 responses in case the scheduler queue is completely full. This is mostly compatible with previous versions of ArangoDB. 
Previously the availability API still returned HTTP 200 in this situation, but this can be considered a bug, because the server was effectively totally overloaded.
To restore 100% compatible behavior with previous version, it is possible to set the option to a value of `0`, which is a special value indicating that the queue fill grade will not be honored. 
  
To prevent sending more traffic to an already overloaded server, it can be sensible to reduce the default value to `0.75` or even `0.5`. This would mean that instances with a queue longer than 75% (or 50%, resp.) of their maximum queue capacity would return HTTP 503 instead of HTTP 200 when their availability API is probed. 

Docs PR: https://github.com/arangodb/docs/pull/580

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] 3.6: https://github.com/arangodb/arangodb/pull/13035

### Testing & Verification

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12754/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12757/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12760/

**Comment by jsteemann** [comment]
Tests blue

**Review by fceller — APPROVED** [review]

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
