### PR TITLE
don't perform unnecessary document lookups in incremental sync

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Don't perform unnecessary document lookups on the follower during the incremental sync protocol when the RocksDB storage engine is used.

- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *replication_sync*.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9331/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9344/

**Comment by jsteemann** [comment]
Tests blue

**Comment by graetzer** [comment]
is there a devel fix ??

**Comment by jsteemann** [comment]
@graetzer: yes, there is a devel fix. But it was not in a separate PR but part of another big PR:
https://github.com/arangodb/arangodb/pull/11379/files#diff-7131a071361633fcf52ec0769aad2b0dR746

**Pull request merged**
