### PR TITLE
Feature/add distinct aggregator

### PR DESCRIPTION
**Pull request by jsteemann**

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/

**Comment by brendanwheble** [comment]
Any ideas which release this will be in?

**Comment by dothebart** [comment]
heh, mergend in 2018 - so its probably in all supported versions.

**Comment by brendanwheble** [comment]
LOL. Good news for me then. Many thanks

**Pull request merged**
