### PR TITLE
fix assertion failure when database is specified with no URL path

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix assertion failure when database is specified without URL path (e.g. `/_db/system`). In this case, in maintainer mode an assertion failure was triggered, but it didn't have any effect in non-maintainer
mode.

This is a forward port of https://github.com/arangodb/arangodb/pull/13162

- [x] :hankey: Bugfix (requires CHANGELOG entry)

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13075/

### CODE REVIEW

**Review by dothebart — APPROVED** [review]

**Review by neunhoef — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13239/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13242/

**Review by fceller — APPROVED** [review]

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
