### PR TITLE
Fix vst network traffic accounting.

### PR DESCRIPTION
**Pull request by neunhoef**

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6924/

**Comment by neunhoef** [comment]
These changes are good enough to make the go-driver tests pass.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7088/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7089/

**Comment by neunhoef** [comment]
Waiting for final tests.

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7090/

**Comment by KVS85** [comment]
Tests blue except known issues.

**Pull request merged**
