### PR TITLE
Bug fix/fix msvc2019 build

### PR DESCRIPTION
**Pull request by Dronplane**
Fixes building and running on MSVC2019

### CODE REVIEW

**Comment by Simran-B** [comment]
@Dronplane Will this allow to compile full ArangoDB with MSVC2019, or just IResearch?

**Comment by Dronplane** [comment]
Full ArangoDB. IResearch itself already has msvc2019 support

**Comment by Simran-B** [comment]
Awesome, thanks!

**Comment by goedderz** [comment]
Jenkins runs into this assertion:
```
2020-02-08T18:47:34Z [12132] FATAL assertion failed in C:\vm03-windows\oskar\work\ArangoDB\arangod\Aql/SharedAqlItemBlockPtr.h:124: this != &other
```
with this backtrace:
```
0000003c`705fd460 00007ff7`827f361b arangod!abort(void)+0x35 [minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 77]
(Inline Function) --------`-------- arangod!arangodb::aql::SharedAqlItemBlockPtr::operator=+0x77 [C:\vm02-windows\oskar\work\ArangoDB\arangod\Aql\SharedAqlItemBlockPtr.h @ 124]
0000003c`705fd490 00007ff7`827f3fd5 arangod!std::_Move_unchecked<arangodb::aql::SharedAqlItemBlockPtr *,arangodb::aql::SharedAqlItemBlockPtr *>(class arangodb::aql::SharedAqlItemBlockPtr * _First = 0x000001d1`222f7f20, class arangodb::aql::SharedAqlItemBlockPtr * _Last = 0x000001d1`222f7f28, class arangodb::aql::SharedAqlItemBlockPtr * _Dest = 0x000001d1`222f7f20)+0x9b [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility @ 3632]
(Inline Function) --------`-------- arangod!std::vector<arangodb::aql::SharedAqlItemBlockPtr,std::allocator<arangodb::aql::SharedAqlItemBlockPtr> >::erase+0x8 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vector @ 1377]
0000003c`705fd4c0 00007ff7`827de905 arangod!arangodb::aql::AqlItemMatrix::popShadowRow(void)+0x1a5 [C:\vm02-windows\oskar\work\ArangoDB\arangod\Aql\AqlItemMatrix.cpp @ 199]
[...]
```

This is due to the following bug in the MSVC STL. It leads to self-move-assignments on an empty erase range, which in general leaves the elements in an undefined state.
https://developercommunity.visualstudio.com/content/problem/776568/vc-move-assigns-the-vector-to-itself-if-erase-is-c.html

I'll provide a patch for this case, but we should upgrade MSVC when a fixed version is available.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8476/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8478/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/2462/

**Comment by KVS85** [comment]
This will wait for VS 2019 16.5.0.

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9211/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9220/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9226/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/10940/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-mac-onlycatch/6988/

**Comment by KVS85** [comment]
Tests blue!

**Pull request merged**
