### PR TITLE
Feature/satellite graphs 2 default values overhaul

### PR DESCRIPTION
**Pull request by hkernbach**
Do not use custom/random defaults, but use server-wide defaults for gharial API instead.

### CODE REVIEW

**Comment by hkernbach** [comment]
https://github.com/arangodb/enterprise/pull/426

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/PR/job/arangodb-matrix-pr/9302/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9339/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9340/

**Comment by markuspf** [comment]
Need to merge devel into `satellite-graphs-2` before this is merged

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9348/

**Pull request merged**
