### PR TITLE
Add load balancing support to cursor API in 3.3

### PR DESCRIPTION
**Pull request by danielhlarkin**

### CODE REVIEW

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/233/

**Comment by danielhlarkin** [comment]
@jsteemann No, not yet. We need to use one of the drivers for that, right? Or do we have a way to do that with arangosh?

**Comment by jsteemann** [comment]
@danielhlarkin : arangosh does not yet support VelocyStream. So yes, either the Java or golang driver.
Both may have cluster tests already, and maybe they already test with multiple coordinators? This could be at least true for the golang driver tests.

**Comment by ewoutp** [comment]
@danielhlarkin go-driver uses multiple coordinators in its cluster tests (both http&vst).
However the go-driver has built-in stickyness for cursor follow-up calls.
So the best way to test this is to put an actual (roundrobin/random) load-balancer in front of the coordinators.
Suggest to setup such a test in kube-arangodb. Will be fairly easy todo there.

**Comment by danielhlarkin** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/396/

**Pull request merged**
