### PR TITLE
Reinstate loadPlan multiple execution protection.

### PR DESCRIPTION
**Pull request by neunhoef**
This addresses an issue that sometimes `loadPlan` is actually executed
way too often.

### CODE REVIEW

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11142/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11258/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11259/

**Comment by neunhoef** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11273/

**Comment by neunhoef** [comment]
I have tested this with the `arangosync` test both in a single cluster and Vadim's load and with `arangosync` in two local clusters. It improves performance dramatically. I have not found any further problems.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
