### PR TITLE
Fix VST / HTTP2 idle connection keep alive behaviour (#12549)

### PR DESCRIPTION
**Pull request by graetzer**
### Scope & Purpose

Make VST and HTTP2 connection have the same keep-alive behaviour as a HTTP 1 connection. Namely only truely cancel an IDLE connection

backport of #12549

- [x] :hankey: Bugfix 

#### Backports:

- [x] Backports required for: 3.7

Should be more or less covered by existing tests
http://172.16.10.101:8080/job/arangodb-matrix-pr/11722/

### CODE REVIEW

**Comment by graetzer** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/11722/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/job/arangodb-matrix-pr/11729/

**Review by jsteemann — APPROVED** [review]
LGTM

**Review by fceller — APPROVED** [review]
LGTM

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11766/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-go/55/

**Comment by KVS85** [comment]
Tests blue except known or false positives.

**Pull request merged**
