### PR TITLE
Replace ansi-html with ansi-html-community

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This replaces ansi-html with ansi-html-community as ansi-html is no longer maintained.

This is an internal, undocumented dependency and the replacement is a fully API-compatible fork.

- [x] :hammer: Refactoring/simplification

### Checklist

- [x] :book: CHANGELOG entry made
- [x] Backports
  - [x] Backport for 3.9: https://github.com/arangodb/arangodb/pull/15656

#### Related Information

- [x] Jira ticket: BTS-730

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by pluma** [comment]
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/19799/

**Comment by pluma** [comment]
Jenkins is green.

**Comment by Zyqsempai** [comment]
@KVS85 At least devel PR could be merged, right?

**Comment by KVS85** [comment]
@Zyqsempai yes.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Review by ajurdak — APPROVED** [review]
LGTM.

**Pull request merged**
