### PR TITLE
Converted rest handler for explain from JS to C++.

### PR DESCRIPTION
**Pull request by danielhlarkin**

### CODE REVIEW

**Comment by fceller** [comment]
@danielhlarkin Jenkins failed: http://c1.triagens-gmbh.zz:8080/job/arangodb-ci/job/PR-2907/2/artifact/FAILED_test_cluster_community_mmfiles_linux_shell_client.log

**Comment by danielhlarkin** [comment]
@fceller I think the tests are failing for reasons unrelated to the changes now. The tests which fail on Jenkins pass locally. One is due to cluster timeout and the other is because a collection truncate fails (I would guess also related to cluster traffic). Could you let me know if anything looks suspicious and, if not, re-run?

**Comment by fceller** [comment]
@danielhlarkin agreed

**Comment by fceller** [comment]
LGTM

**Pull request merged**
