### PR TITLE
3.4 -- DEVSUP-492 (fix upsert with empty objects)

### PR DESCRIPTION
**Pull request by ObiWahn**
backport

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7124/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7833/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1810/

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/1813/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
