### PR TITLE
Added .insert part for document insertion

### PR DESCRIPTION
**Pull request by lservini**
For Document Methods, **.insert** (alias of **.save**) was not mentioned in Manual 

Preview:
- http://web01.arangodb.biz/documentation/save_insert/Manual/DataModeling/Documents/DocumentMethods.html

### CODE REVIEW

**Comment by Simran-B** [comment]
I believe this is also missing somewhere else... Can you check the appendix about the JS API?

I'm actually in favor of using `.save()` as default, but no strong opinion on that.

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/291/

**Comment by lservini** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/293/

**Comment by lservini** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/294/

**Pull request merged**
