### PR TITLE
Bug fix/windows open ui in default browser

### PR DESCRIPTION
**Pull request by Simran-B**
Please build the installer for testing.

Also improves wording and fixes some typos in `NSIS.template.in`

### CODE REVIEW

**Comment by dothebart** [comment]
The configured browser is `chrome` and now no browser is opened at all.

**Comment by Simran-B** [comment]
@dothebart `{ }` were missing. Tried the corrected `ExecShell` command with a local NSI testing script and it worked fine with this fix.

**Comment by dothebart** [comment]
[x] Ok, working now.

**Comment by dothebart** [comment]
LGTM

**Pull request merged**
