### PR TITLE
fix forwarding of coordinator requests via /_api/job

### PR DESCRIPTION
**Pull request by jsteemann**
This needs backporting because the web interface is heavily using the `/_api/job` API for running queries, creating indexes etc.

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2465/

**Comment by jsteemann** [comment]
@danielhlarkin : yes, it was done in that PR, but not for 3.3.

**Comment by danielhlarkin** [comment]
@jsteemann Oh, didn't realize we were in 3.3 here. Got it. All good.

**Comment by jsteemann** [comment]
Yes, that was the whole problem. For 3.3 we only adjusted the cursor API which I thought would be sufficient. However, the web interface is using the job API a lot, so even with the cursor API properly forwarding, it didn't work from within the web interface.

**Pull request merged**
