### PR TITLE
Documentation/training material links

### PR DESCRIPTION
**Pull request by Simran-B**
Combined the patches, reviewed and improved the changes.

Weren't there plans to add even more links? If so, we can do it in this PR too.

### CODE REVIEW

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/101/

**Comment by Simran-B** [comment]
Merged all PRs by Jana except #6835 into this one, improved the formatting and wording.
Fixed a few other issues, especially on the Pregel page (needs a test build because internal links were involved).

**Comment by Simran-B** [comment]
Successful build after updating the jenkins host machine with the latest doc image:
http://web01.arangodb.biz/documentation/training-material-links/Manual/Graphs/Pregel/

**Comment by Simran-B** [comment]
Checked with Jana and added a few more links. We have enough of them in now IMO.
Waiting for Jenkins, can be squash-merged if it's green. I'll then cherry-pick it for 3.4.

For 3.3 and older, we will likely have to port the links manually, if there are even corresponding pages. Will continue to cooperate with Jana on this, after 3.4 GA.

**Pull request merged**
