### PR TITLE
enable cpp17 and new boost

### PR DESCRIPTION
**Pull request by ObiWahn**
This branch was not fully merged into devel.

### CODE REVIEW

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2544/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2655/

**Comment by ObiWahn** [comment]
relevant stackoverflow links:
https://stackoverflow.com/questions/52413643/why-does-boost-string-give-an-error-with-clang-and-c17
https://stackoverflow.com/questions/50710781/compatibility-of-c17-of-apple-clang-that-xcode-10-beta-bundle

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2769/

**Comment by jsteemann** [comment]
Doesn't compile on MacOS:
```
lib/V8/v8-json.cpp:753:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
lib/V8/v8-json.cpp:754:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp, *yy_bp;
        ^~~~~~~~~
lib/V8/v8-json.cpp:754:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp, *yy_bp;
        ^~~~~~~~~
lib/V8/v8-json.cpp:755:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int yy_act;
        ^~~~~~~~~
lib/V8/v8-json.cpp:804:4: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
                        register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
                        ^~~~~~~~~
lib/V8/v8-json.cpp:1087:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1088:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *source = yyg->yytext_ptr;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1089:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int number_to_move, i;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1089:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int number_to_move, i;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1221:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1222:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1229:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
                register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
                ^~~~~~~~~
lib/V8/v8-json.cpp:1254:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int yy_is_jam;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1256:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp = yyg->yy_c_buf_p;
        ^~~~~~~~~
lib/V8/v8-json.cpp:1258:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register YY_CHAR yy_c = 1;
        ^~~~~~~~~
15 errors generated.
make[2]: *** [lib/CMakeFiles/arango_v8.dir/V8/v8-json.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by ObiWahn** [comment]
broken on mac with:

```
[  8%] Building CXX object 3rdParty/boost/CMakeFiles/boost_thread.dir/1.69.0/libs/thread/src/pthread/thread.cpp.o
In file included from /Users/jenkins/arangodb/3rdParty/boost/1.69.0/libs/thread/src/pthread/thread.cpp:17:
In file included from /Users/jenkins/arangodb/3rdParty/boost/1.69.0/boost/thread/once.hpp:26:
/Users/jenkins/arangodb/3rdParty/boost/1.69.0/boost/thread/pthread/once_atomic.hpp:128:25: error: no matching function for call to 'decay_copy'
                        thread_detail::decay_copy(boost::forward<Function>(f)),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jenkins/arangodb/3rdParty/boost/1.69.0/libs/thread/src/pthread/thread.cpp:158:20: note: in instantiation of function template specialization 'boost::call_once<void (&)()>' requested here
            boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                   ^
/Users/jenkins/arangodb/3rdParty/boost/1.69.0/boost/thread/detail/move.hpp:355:3: note: candidate template ignored: substitution failure [with T = void (&)()]: function cannot return function type 'typename decay<void (&)()>::type' (aka 'void ()')
  decay_copy(T&& t)
  ^
1 error generated.
make[2]: *** [3rdParty/boost/CMakeFiles/boost_thread.dir/1.69.0/libs/thread/src/pthread/thread.cpp.o] Error 1
make[1]: *** [3rdParty/boost/CMakeFiles/boost_thread.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4241/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5643/

**Pull request closed without merging**
