### PR TITLE
Bug fix/restart follower no leader set

### PR DESCRIPTION
**Pull request by maierlars**
### Scope & Purpose

Devel port of https://github.com/arangodb/arangodb/pull/11669 instead of https://github.com/arangodb/arangodb/pull/11667. This code ensures that a restarting server will properly update the follower info for all shards (as those are only in memory).

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [x] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This change is already covered by existing tests, such as *(please describe tests)*.

### CODE REVIEW

**Comment by maierlars** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/10059/

**Comment by maierlars** [comment]
https://jenkins.arangodb.biz/job/arangodb-ANY-check-guidelines/6951/

**Comment by maierlars** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/10061/

**Comment by maierlars** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/11824/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10115/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
