### PR TITLE
make superuser ExecContext const

### PR DESCRIPTION
**Pull request by ObiWahn**
make `ExecContext` instance for superuser const, as it is shared among multiple threads, and they better do not modify it.

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10418/

**Comment by jsteemann** [comment]
Actual test memleak has been fixed here: https://github.com/arangodb/arangodb/pull/11851
The constness of the ExecContext also is a good thing.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10421/

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
