### PR TITLE
Endless loop on create database rollback

### PR DESCRIPTION
**Pull request by neunhoef**
This fixes the following problem:

If a coordinator wants to roll back a create database operation and the
database has - for whatever reason - already been removed from the
agency, then the corresponding retry loop runs endlessly, always running
into 412 precondition failed. This endless loop is broken by the changes
in this PR.

## Acceptance Checklist

*The below list is not exhaustive, think thoroughly whether the provided information is sufficient.*
*Remove options that do not apply*

### Scope & Purpose

*(Can you describe what functional change your PR is trying to effect?)*

- [ ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [*] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [ ] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [*] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [ ] The behavior change can be verified via automatic tests

### Testing & Verification

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13081/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13085/

**Comment by neunhoef** [comment]
This seems to be good to go. I will now port to 3.7 and devel.

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13404/

**Comment by KVS85** [comment]
Tests blue but more tests are required prior to merge (as well as in forward-ported PRs).

**Comment by neunhoef** [comment]
I would think that this is ready.

**Comment by KVS85** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13429/

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — COMMENTED** [review]
LGTM.

**Pull request merged**
