### PR TITLE
Small refactoring, clarifying intent

### PR DESCRIPTION
**Pull request by ignacionr**
### Scope & Purpose

Improves GeneralServer by leveraging <algorithm> for the intention of getting the least-clients context, and improves legibility on the stopWorking() timeout implementation.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as ApplicationServerTest.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Comment by goedderz** [comment]
Hi @ignacionr,

thank you for your contribution!

Please note that for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). You can find it here: https://www.arangodb.com/documents/cla.pdf

You can send a signed scan to cla@arangodb.com, or via fax +49-221-2722999-88. The instructions can also be found at https://www.arangodb.com/community/.

Best,

Tobias

**Review by jsteemann — APPROVED** [review]
Thanks, looks good!

**Comment by ignacionr** [comment]
> Thanks, looks good!

Thank you! I will get the required document signed.

**Comment by joerg84** [comment]
> > Thanks, looks good!
> 
> Thank you! I will get the required document signed.

Thanks, CLA receipt confirmed. 
Excited about your first contribution!

**Comment by jsteemann** [comment]
Created PR https://github.com/arangodb/arangodb/pull/13534 for running our Jenkins tests on it...

**Pull request merged**
