### PR TITLE
Reimplement coordshort request handler.

### PR DESCRIPTION
**Pull request by mpoeter**
Backport of #13112

The old implementation sent `statistcs/short` requests to all coordinators (including itself). The `statistics/short` handler is also implemented in JS and runs two DB queries. So for a cluster with 3 coordinators, the old implementation issued 3 network requests, which triggered a total of 6 DB queries and required 4 V8 contexts (one for the initial coordshort request, and one for each statistic/short request).

The new implementation only runs two DB queries without any additional requests to other coordinators, resulting in reduced load on the cluster.

In addition this reimplementation fixes the way statistics samples of coordinators are merged. Previously we simply took the timestamps from the samples of one coordinator and simply merged all samples based on their index. However, coordinators don't necessarily write their statistics sample at the same time, and it is also not guaranteed that all coordinators have the same number of samples.

### Scope & Purpose

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [x] Added new **integration tests** in shell_server
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12926/

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]

**Comment by jsteemann** [comment]
Restarted Jenkins after potentially unrelated failures:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12943/

**Comment by jsteemann** [comment]
Yet another Jenkins run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12954/

**Comment by KVS85** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13232/

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
Tests blue.

**Pull request merged**
