### PR TITLE
Doc - Sync-external-repo-2018-12-25

### PR DESCRIPTION
**Pull request by OmarAyo**

### CODE REVIEW

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/210/

**Comment by sleto-it** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/212/

**Comment by Simran-B** [comment]
esp. http://web01.arangodb.biz/documentation/sync-2018-12-25/Drivers/JS/Reference/

**Comment by sleto-it** [comment]
the backport is here https://github.com/arangodb/arangodb/pull/7859

**Pull request merged**
