### PR TITLE
Fix smart BFS stack

### PR DESCRIPTION
**Pull request by goedderz**
### Scope & Purpose

Fix a problem with path uniqueness in smart graph bfs, which could theoretically lead to duplicate edges or vertices in a path. As far as I can tell, it can only occur under a very rare condition.

Note that the actual fix is, of course, in the corresponding enterprise branch: https://github.com/arangodb/enterprise/pull/365

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [ ] Bug-Fix for a *released version* **TODO**
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

This was noticed by (undeterministic and seldom) the following test & assertion:

```
2019-11-12T18:29:49.765Z [     PASSED ] testCompleteGraphBfsUniqueEdgesPathD2_completeGraph_Graph_2shards_s0-ACE_s1-BD (setUp: 0ms, test: 9ms, tearDown: 0ms)
2019-11-12T18:29:49.765Z [ RUN        ] testCompleteGraphBfsUniqueEdgesPathD2_completeGraph_Graph_5shards_s0-A_s1-B_s2-C_s3-D_s4-E
2019-11-12T18:29:49Z [5959] C FATAL [36a91] assertion failed in /home/jsteemann/ArangoNoAsan/enterprise/Enterprise/Cluster/SmartBreadthFirstPathEnumerator.cpp:477: d <= _edgesOnPathStack.size()
Tue Nov 12 2019 19:29:51 GMT+0100 (Central European Standard Time) request timeout reached (Connection closed by remote), aborting test execution
oops! Skipping remaining tests, server is gone.
```

### Testing & Verification

This change is already covered by existing tests, such as `aql-smart-graph-traversal-generic-cluster.js`.

### Documentation

- [x] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)

### CODE REVIEW

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7467/

**Comment by goedderz** [comment]
Jenkins is blue.

**Comment by goedderz** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7484/

**Comment by joerg84** [comment]
We need to remember the EE part

**Pull request merged**
