### PR TITLE
more granular error reporting in Maintenance

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Add more granular error reporting to `reportInCurrent` maintenance function, and add lots of assertions.
This is not a bugfix, but a vehicle to simplify debugging and bug hunts.

This is a backport of https://github.com/arangodb/arangodb/pull/13342

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13508/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Review by neunhoef — APPROVED** [review]
LGTM

**Review by kvahed — APPROVED** [review]
LGTM

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
