### PR TITLE
Don't define incorrect ssize_t on Windows

### PR DESCRIPTION
**Pull request by MBkkt**
### Scope & Purpose

Correct `ssize_t` include looks like
```C++
#ifdef _MSC_VER
  #include <BaseTsd.h>
  using ssize_t = SSIZE_T;
#else
  #include <unistd.h>
#endif
```

Or better don't use `ssize_t`, because we have `ptrdiff_t`

Now we use int on Windows, it's incorrect but I don't want to change it.
So just remove using and replace to auto/int/ptrdiff_t

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by jsteemann — APPROVED** [review]
LGTM!

**Comment by markuspf** [comment]
Would you mind changing the title and the description of the PR to reflect what it does, and why?

**Review by gnusi — APPROVED** [review]

**Comment by markuspf** [comment]
Why was this merged? None of our team has approved it yet.

I do not understand why these changes were made in the way they were made.

**Comment by MBkkt** [comment]
@markuspf 
Sorry, but I don't think we should discuss it here.

Also your team responsible for few files, in which it's just safe replace ssize_t to ptrdiff_t

> I do not understand why these changes were made in the way they were made.

What don't you like? Before this changes on windows we use 4 byte ssize_t, it was incorrect.
Also we define our incorrect ssize_t in common header. That doesn't allow us to use library header with correct size_t

Now we use ptrdiff_t/auto.

For nghttp2 created special patch, to make it same way as they did (long instead of ssize_t)

**Pull request merged**
