### PR TITLE
upgrade rocksdb to V5.18.X

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2551/

**Comment by jsteemann** [comment]
Looks like Snappy include directories are not found after the change, at least on Windows.

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2561/

**Comment by dothebart** [comment]
Tests green.

**Pull request merged**
