### PR TITLE
Move ResultT.h from arangod/Cluster to lib/Basics

### PR DESCRIPTION
**Pull request by markuspf**
This is the correct home for this code.

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10432/

**Comment by maierlars** [comment]
:tada:

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10444/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10446/

**Comment by markuspf** [comment]
Now with passing jenkins.

**Pull request merged**
