### PR TITLE
feature-3.11/FE-255: add validation for collection, document, graph, view and database names

### PR DESCRIPTION
**Pull request by palashkaria**
### Scope & Purpose

Backport for https://github.com/arangodb/arangodb/pull/18797

### CODE REVIEW

**Comment by KVS85** [comment]
- [ ] https://jenkins01.arangodb.biz/job/arangodb-ANY-jslint/28868/

**Review by ajurdak — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
- [ ] https://jenkins01.arangodb.biz/job/arangodb-ANY-jslint/28924/

**Review by jsteemann — APPROVED** [review]
LGTM

**Pull request merged**
