### PR TITLE
fix shutdown deadlock

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix a potential deadlock during AgencyCache shutdown.
The bugfix was merged to devel as part of 2a204455d64c851344e5b5fcd4cbd9b87cfd35f4.
It is not required to backport this to 3.6.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (e.g. in shell_client)

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13570/

### CODE REVIEW

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13588/

**Review by kvahed — APPROVED** [review]
LGTM

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13595/

**Comment by jsteemann** [comment]
Tests blue

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13610/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13615/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13668/

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13669/

**Comment by jsteemann** [comment]
Tests blue

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
