### PR TITLE
[3.9] Replace xmldom with @xmldom/xmldom

### PR DESCRIPTION
**Pull request by pluma**
### Scope & Purpose

This is a backport of #15659 for 3.9. For upgrade compatibility reasons it includes an alias module re-exporting @xmldom/xmldom as xmldom.

- [x] :hammer: Refactoring/simplification

### Checklist

- [x] :book: CHANGELOG entry made

#### Related Information

- [x] Jira ticket: BTS-730

### CODE REVIEW

**Comment by pluma** [comment]
FYI I've manually tested the module alias.

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by Zyqsempai** [comment]
@KVS85 And this one.

**Review by ajurdak — APPROVED** [review]
LGTM.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Pull request merged**
