### PR TITLE
add metrics for V8 contexts usage

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Added metrics for V8 contexts usage:

* `arangodb_v8_context_alive`: number of V8 contexts currently alive.
* `arangodb_v8_context_busy`: number of V8 contexts currently busy. 
* `arangodb_v8_context_dirty`: number of V8 contexts currently dirty.
* `arangodb_v8_context_free`: number of V8 contexts currently free. 
* `arangodb_v8_context_max`: maximum number of concurrent V8 contexts.
* `arangodb_v8_context_min`: minimum number of concurrent V8 contexts.

Docs PR: https://github.com/arangodb/docs/pull/538

- [ ] :hankey: Bugfix 
- [x] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [ ] No backports required
- [x] Backports required for: 3.7

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11688/

### CODE REVIEW

**Comment by jsteemann** [comment]
Tests blue

**Review by dothebart — APPROVED** [review]
LGTM

**Comment by dothebart** [comment]
should
https://github.com/arangodb/arangodb/blob/devel/Documentation/DocuBlocks/Rest/Administration/get_admin_statistics_description.md
and 
https://github.com/arangodb/arangodb/blob/devel/Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md be changed too?

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11694/

**Comment by jsteemann** [comment]
@dothebart : other places for statistics have now been adjusted as well. good catch!

**Review by dothebart — APPROVED** [review]

**Comment by jsteemann** [comment]
Tests blue

**Pull request merged**
