### PR TITLE
fix for BTS-84

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Allow restoring arangodumps from ArangoDB 3.3 and before, taken with MMFiles, into a current version of ArangoDB.
Related ticket: https://arangodb.atlassian.net/browse/BTS-84 

This PR supersedes https://github.com/arangodb/arangodb/pull/11787

- [x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [ ] Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

#### Related Information

- [x] There is a *JIRA Ticket number* (In case a customer was affected / involved): https://arangodb.atlassian.net/browse/BTS-84

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [x] Added new **integration tests** (i.e. in shell_client)

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10409/

### CODE REVIEW

**Comment by jsteemann** [comment]
@maxkernbach : I think there is still a server-side issue triggered by my PR. Have to understand and fix it first. Until then, this PR should not be merged.

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10461/

**Comment by jsteemann** [comment]
Works for me now. May be related to my latest changes in the branch.
@maxkernbach : can you recheck?

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10470/

**Comment by KVS85** [comment]
Tests blue except unrelated failures.

**Pull request merged**
