### PR TITLE
ASAN fixes

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by jsteemann** [comment]
Can you check if fix this is also necessary in the original snowball Github repo and open a PR there if yes? 
https://github.com/snowballstem/snowball

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10346/

**Comment by ObiWahn** [comment]
https://github.com/arangodb/arangodb/pull/11801/files#diff-0259808b98fd367e65f72944f27f0ba7R144 -- argv element will be freed . -- fix follows

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10353/

**Comment by jsteemann** [comment]
tests blue

**Pull request merged**
