### PR TITLE
bulk test, don't use graph module

### PR DESCRIPTION
**Pull request by dothebart**
### Scope & Purpose

bulk inserts of test setup to save computing bandwith.

- [x] :hankey: Bugfix

### CODE REVIEW

**Comment by dothebart** [comment]
testrun green except unrelated errors.

**Review by jsteemann — APPROVED** [review]
LGTM

**Comment by markuspf** [comment]
Why was this merged with failing tests?

**Comment by dothebart** [comment]
because of the failing replication2-tests weren't altered by this PR.

**Pull request merged**
