### PR TITLE
avoid recursive locking in agency

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

when loading configuration with an AQL query (which acquires the collection's status lock) and then starting a transaction on the same collection (acquires the status lock once more) while the query object is still in scope. this leads to the same thread locking the same rw lock in read mode twice, which can be dangerous if a writer is queued for the lock. then the two threads will deadlock.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [x] Backport for 3.11: https://github.com/arangodb/arangodb/pull/19448
  - [x] Backport for 3.10: https://github.com/arangodb/arangodb/pull/19447
  - [ ] Backport for 3.9: -

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

### CODE REVIEW

**Review by MBkkt — COMMENTED** [review]
What about 3.11?

**Review by mchacki — APPROVED** [review]
LGTM

**Review by mchacki — CHANGES_REQUESTED** [review]
CHANGELOG entry missing.

Code LGTM

**Review by mchacki — APPROVED** [review]
LGTM

**Pull request merged**
