### PR TITLE
Fix display of "unique" column in indexes overview of collections.

### PR DESCRIPTION
**Pull request by jsteemann**
### Scope & Purpose

Fix display of "unique" column in indexes overview of collections.
https://arangodb.atlassian.net/browse/FE-393?focusedCommentId=103553
Does not apply to devel.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [x] Backport for 3.11: -
  - [ ] Backport for 3.10: -

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/FE-393
- [ ] Design document:

### CODE REVIEW

**Review by neunhoef — APPROVED** [review]
LGTM

**Review by palashkaria — CHANGES_REQUESTED** [review]
Please add build files

**Comment by jsteemann** [comment]
@palashkaria : Aren't build files auto-generated upon every release anyway?

**Comment by KVS85** [comment]
> Please add build files

@palashkaria it's not obligatory to @jsteemann to make this. Is this PR good from the source prospective?

**Comment by KVS85** [comment]
> @palashkaria : Aren't build files auto-generated upon every release anyway?

They are. And for this particular PR it's being done right before merge.

**Review by palashkaria — APPROVED** [review]
LGTM

**Pull request merged**
