### PR TITLE
Feature/new agency checks for preconditions

### PR DESCRIPTION
**Pull request by kvahed**

### CODE REVIEW

**Comment by fceller** [comment]
@kvahed 

```
arangodbtests: /tmp/fb0d7aadbf05f6f9634d5b416d4247f7/3rdParty/catch/catch.hpp:9443: virtual void Catch::CumulativeReporterBase::testCaseEnded(const Catch::TestCaseStats&): Assertion `m_sectionStack.size() == 0' failed.
```

**Comment by kvahed** [comment]
Cannot reproduce the error on Linux or Mac Enterprise Debug builds.

**Comment by jsteemann** [comment]
Just produced a crash in the branch:
```
/home/steemann/ArangoDevel/3rdParty/fakeit/fakeit.hpp:18399:13: runtime error: member call on null pointer of type 'struct FakeitContext'
ASAN:DEADLYSIGNAL
=================================================================
==26574==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55c0abaa9e4e bp 0x7ffdcaf7c9c0 sp 0x7ffdcaf7c7e0 T0)
==26574==The signal is caused by a READ memory access.
==26574==Hint: address points to the zero page.
    #0 0x55c0abaa9e4d in fakeit::MockImpl<arangodb::consensus::AgentInterface>::unmocked() /home/steemann/ArangoDevel/3rdParty/fakeit/fakeit.hpp:18399
    #1 0x55c0aca0d9b7 in arangodb::consensus::singleWriteTransaction(arangodb::consensus::AgentInterface*, arangodb::velocypack::Builder const&, bool) /home/steemann/ArangoDevel/arangod/Agency/Job.h:217
    #2 0x55c0acaa8473 in arangodb::consensus::Job::finish(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<arangodb::velocypack::Builder>) /home/steemann/ArangoDevel/arangod/Agency/Job.cpp:110
    #3 0x55c0aca08f51 in arangodb::consensus::Job::runHelper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/steemann/ArangoDevel/arangod/Agency/Job.h:96
    #4 0x55c0aca5a95c in arangodb::consensus::FailedLeader::run() /home/steemann/ArangoDevel/arangod/Agency/FailedLeader.cpp:73
    #5 0x55c0abce0ced in ____C_A_T_C_H____T_E_S_T____108 /home/steemann/ArangoDevel/tests/Agency/FailedLeaderTest.cpp:769
    #6 0x55c0ac8d9a27 in Catch::FreeFunctionTestCase::invoke() const /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:7142
    #7 0x55c0ac8d9a27 in Catch::TestCase::invoke() const /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:8086
    #8 0x55c0ac8d9a27 in Catch::RunContext::invokeActiveTestCase() /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:6723
    #9 0x55c0ac8d9a27 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:6691
    #10 0x55c0ac8d9a27 in Catch::RunContext::runTest(Catch::TestCase const&) /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:6517
    #11 0x55c0ac8d9a27 in Catch::runTests(Catch::Ptr<Catch::Config> const&) /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:6862
    #12 0x55c0ac9cac33 in Catch::Session::run() /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:6970
    #13 0x55c0ab3a7922 in Catch::Session::run(int, char const* const*) /home/steemann/ArangoDevel/3rdParty/catch/catch.hpp:6949
    #14 0x55c0ab3a7922 in main /home/steemann/ArangoDevel/tests/main.cpp:20
    #15 0x7f83de7bf1c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)
    #16 0x55c0aba00ea9 in _start (/home/steemann/ArangoDevel/build/tests/arangodbtests+0xd87cea9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/steemann/ArangoDevel/3rdParty/fakeit/fakeit.hpp:18399 in fakeit::MockImpl<arangodb::consensus::AgentInterface>::unmocked()
==26574==ABORTING
```

**Comment by kvahed** [comment]
Works with g++7 / ASAN now.

**Pull request merged**
