### PR TITLE
Ported ResignLeadership to 3.5

### PR DESCRIPTION
**Pull request by maierlars**

### CODE REVIEW

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5591/

**Comment by KVS85** [comment]
@maierlars please address Jenkins failures.

**Comment by maierlars** [comment]
@KVS85 looks like shutdown bugs and unrelated to this PR

**Comment by maierlars** [comment]
But maybe its not ... looking into it.

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5634/

**Comment by maierlars** [comment]
```
(gdb) info threads                                                                                                                                                                                                                                                             
  Id   Target Id         Frame                                                                                                                                                                                                                                                 
* 1    LWP 14544         0x00007f5d2aef46cc in __deregister_frame_info_bases (begin=0x7f5d2b25a690) at /home/buildozer/aports/main/gcc/src/gcc-8.3.0/libgcc/unwind-dw2-fde.c:214                                                                                               
(gdb) bt                                                                                                                                                                                                                                                                       
#0  0x00007f5d2aef46cc in __deregister_frame_info_bases (begin=0x7f5d2b25a690) at /home/buildozer/aports/main/gcc/src/gcc-8.3.0/libgcc/unwind-dw2-fde.c:214                                                                                                                    
#1  __deregister_frame_info_bases (begin=0x7f5d2b25a690) at /home/buildozer/aports/main/gcc/src/gcc-8.3.0/libgcc/unwind-dw2-fde.c:201                                                                                                                                          
#2  0x00007f5d28ac0fbe in __do_global_dtors_aux ()                                                                                                                                                                                                                             
#3  0x0000000000000025 in ?? ()                                                                                                                                                                                                                                                
#4  0x00007f5d28a5e830 in ?? () at /work/ArangoDB/arangod/RestServer/arangod.cpp:267                                                                                                                                                                                           
#5  0x00007ffdaec010d8 in ?? ()                                                                                                                                                                                                                                                
#6  0x00007f5d2af0edac in _fini ()
#7  0x0000000000000000 in ?? ()
```
This is a shutdown hanger unrelated to this PR.

**Comment by maierlars** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5639/

**Pull request merged**
