### PR TITLE
fix timeout issue next try: no subquery nodes on dbservers

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by jsteemann** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/487/

**Comment by jsteemann** [comment]
Please add a CHANGELOG entry and a test.

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/501/

**Comment by ObiWahn** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/503/

**Pull request merged**
